### ISSUE TITLE
SugarCRM-Mautic: 'Push contact to integration' not working. 

### ISSUE THREAD

**Issue by evgu** [mautic/mautic#10024]
We use the SugarCRM-Mautic integration plugin and SuiteCRM (community edition). Most part of the integration work fine. 

We have "Push contacts and/or companies to this integration" on the Mautic-SugarCRM plugin unticked. When trying to use the 'Push contact to integration' action in a Campaign it is not working. 

| Q   | A
| --- | ---
| Mautic version | 3.3.3
| SuiteCRM version | 7.10.30 (not SugarCRM)
| PHP version | 7.3.28
| Browser | Safari, Chrome latest 

### Steps to reproduce
1. Mautic-SugarCRM plugin: "Push contacts and/or companies to this integration" -> not-ticked
<img width="571" alt="Screenshot 2021-05-14 at 13 56 31" src="https://user-images.githubusercontent.com/18371928/118270160-e5acea80-b4bf-11eb-86bc-325ec2848281.png">

2. Create a Mautic campaign with a 'Push contact to integration' Action. 
3. Create a new Contact in Mautic and add to this campaign. Wait for relevant cronjobs to run. 
4. Error shows in notification area. Mautic Contact is not pushed to create a new SuiteCRM Lead. No errors logged in Mautic and SuiteCRM logs. 
<img width="326" alt="image" src="https://user-images.githubusercontent.com/18371928/118270269-17be4c80-b4c0-11eb-8927-5fd71d46b827.png">

**Comment by evgu** [comment]
@canal-web @npracht, grateful for your suggestions :)

**Comment by npracht** [comment]
To you have data in all mandatory fields ?

**Comment by npracht** [comment]
No feedback i close the issue.

**Comment by evgu** [comment]
@npracht Norman, apologies for delay. Yes all mandatory fields on SuiteCRM are aready completed in Mautic. Still same issue.

**Comment by evgu** [comment]
@npracht @RCheesley pls let me know how I should debug this issue so I can provide more detail here? I just retested it, still the same issue and not getting any errors in the SuiteCRM log, none in the Mautic logs, none in the apache logs. Only the error message in the Mautic notification area. Perhaps I need to increase log verbosity somehow?

**Comment by RCheesley** [comment]
@evgu are you testing in developer mode (using index_dev.php on the end of your Mautic instance)?

**Comment by RCheesley** [comment]
Also, if you have 'push to this integration' unchecked, would you expect a campaign action which pushes to the integration to work? 

I would have thought that it should fail in that case because you have not allowed the integration to push, only to pull.

**Comment by pstevens71** [comment]
I can tell you that Mautic definitely pushes the contact to SuiteCRM with the "synccontacts" and by checking the box in the setting to push contacts.  It will push all contacts.   However, it will not push a contact by itself if you have that unchecked and try to do it by a campaign workflow or a form action.  This has been an issue for many releases.

So unless I'm misunderstanding how it's supposed to work....

Checked - Pushes all contacts immediately.  That's what it does no problem
Unchecked - Does not push all automatically but I would expect it push one by one either by form action or campaign action "push contact to integration" otherwise why would you need this action if all get pushed with  it checked.  It's been a while since this worked but I do remember that' s how it worked.

Other issues with SuiteCRM/Mautic integration is that it will not push fields data to SuiteCRM either.  Not with the blank fields override checked or if you specifically make Mautic the the field of record in the plugin settings AND have push to integration checked. Seems the sync is only one way SuiteCRM -> Mautic.

**Comment by pstevens71** [comment]
I did some more testing this morning just to rule out a couple of things.  I tested both mautic:integration:synccontacs and mautic:integration:fetchleads  and sync is only one way. SuiteCRM -> Mautic only. (even with the arrow pointed to SuiteCRM from Mautic in the plugin settings).

**Comment by pstevens71** [comment]
This is still relevant!  I'm on 4.0.2 and still a problem.

OK did some more testing.

IF you update a contact on SuiteCRM side, Mautic WILL update the fields in SuiteCRM where Mautic is the primary field of record.

(SO IT DOES IN FACT GO MATUIC-> SUITECRM TO UPDATE SUITECRM FIELDS)

HOWEVER....

IF only a field changes on the Mautic side (even if it's tagged as the primary field of record in the direction of sync) Mautic does not update the record on the SuiteCRM side.

So the problem is the trigger that detects a field has changed in Mautic that needs to be updated to SuiteCRM.

So I would suspect that the trigger in Mautic that determines when a record was last updated and needs to be sync'd with SuiteCRM is the issue.

**Comment by alexhammerschmied** [comment]
I ran into a different error. When I try to run the cronjob mautic:integrations:fetchleads  or mautic:integrations:synccontacts it gives me this error:

> In FetchLeadsCommand.php line 103:Attempted to call an undefined method named "isConfigured" of class "MauticPlugin\GrapesJsBuilderBundle\Integration\GrapesJsBuilderIntegration  
  ".

**Comment by TonyBogdanov** [comment]
@alexhammerschmied For me this happens when you mismatch the name of the integration when passing it to the command.
This is OK: `./console mautic:integrations:fetchleads -i Hubspot`.
This gives error: `./console mautic:integrations:fetchleads -i HubSpot`.

**Comment by pstevens71** [comment]
Yes this is still relevant. I'm on 4.1.1 I'll upgrade to the latest version next week and check that too.  Issue still remains that SuiteCRM -> Mautic works great.  A new record in Mautic -> SuiteCRM works great.  HOWEVER, a change on the Mautic side does not sync with SuiteCRM even when the field is selected that Mautic is the master.  If however a change occures on the SuiteCRM side, the field then syncs with Mautic.  I'm thinking the problem is with triggering the sync when a record changes on the Mautic side.

**Comment by pstevens71** [comment]
So on 4.2.1 I've tested and the sync seems to be working both ways.  Haven't had a chance to test the "push" because I automatically add all leads that are in Mautic to SutieCRM so there is no need to "push".  However, the following now works for me:
1) New leads in SuiteCRM are added to Mautic
2)New leads in Mautic are added to SuiteCRM
3)Changes in Mautic reflect in SuiteCRM (if the Mautic field is selected as the primary)
4)Changes in SuiteCRM are reflected in Mautic

Here is the EXACT command I'm using:

php bin/console mautic:integration:fetchleads --integration="Sugarcrm" --time-interval="1 days"

**Comment by privateidaho** [comment]
@pstevens71 Which version of Suite are you running?

**Comment by pstevens71** [comment]
I'm on 7.12.5 and PHP 7.4

I used to use the synccontacts command vs.  the fetchleads, not sure if that made the difference or just the upgrade I recently did for Mautic.  I also slightly changed my command from "1 day" to "1 days" don't know if that makes a difference either.  I do know the above config works and I finally have 2 way sync!
