### ISSUE TITLE
Mautic not recognising positive result on Form Field Value campaign conditions with checkbox fields

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#10020]
## Bug Description
Possibly related to the closed issue #5833
Came across this when building out the campaigns for the Mautic Community GDPR / newsletter signup options:

We have a form with a checkbox list, which allows people to select what information they receive from us.

We have a campaign which uses the 'form field value' option to push them into the correct segments based on what is set in the checkbox (a yes value for the field equalling the relevant option:

![screenshot-community eu mautic net-2021 05 13-16_24_06 (1)](https://user-images.githubusercontent.com/2930593/118150615-a96b8280-b40a-11eb-9649-34dbf48b938b.png)

The form submissions are working, but they are not making their way into the correct segments.

In another place I am using a radio button yes/no for GDPR consent, and that part is working correctly - they have a tag applied if they select yes, receive an email, and are unsubscribed/removed if they set no.

![screenshot-community eu mautic net-2021 05 13-16_24_52 (1)](https://user-images.githubusercontent.com/2930593/118150650-b12b2700-b40a-11eb-80be-9dd096b6a234.png)

Perhaps this is an issue with how checkbox or multi-select options are being managed/processed by the form field value option in the campaign workflow?

| Q   | A
| --- | ---
| Mautic version | 3.?
| PHP version | 7.4
| Browser | Chrome

### Steps to reproduce
1. Create a form with a multiselect option field
2. Create a campaign which has conditions based on the value of those fields
3. Add actions on the yes/no for them, so you can check if they are executed (eg change segment or add tag)
4. Fill form, check if the path has been followed

**Comment by RCheesley** [comment]
I have been looking into this in a bit more detail - both multi-select fields and checkbox fields are affected, in that the user never goes down the 'yes' path.

This is a blocker for us getting the community Mautic instance up and running so I will try to find a workaround!

**Comment by RCheesley** [comment]
Workaround: Radio rather than checkbox

**Comment by jos0405** [comment]
@RCheesley , I kinda remember testing something from @kuzmany couple of month ago, that fixed this. I tested in 4.2.2 and it works as expected, the bug is not happening. Can we close it?

Multiselect field:
![image](https://user-images.githubusercontent.com/4246909/168888726-c13440f6-6cf5-4283-bc90-aaa0ce1fe416.png)

Campaign step:
![image](https://user-images.githubusercontent.com/4246909/168888828-7917d498-bbfb-4a78-bac5-6ad7d4916a25.png)

Decision:
![image](https://user-images.githubusercontent.com/4246909/168888861-684e2669-13df-4862-a392-f88c58ac2859.png)

Outcome: (YES BRANCH):
![image](https://user-images.githubusercontent.com/4246909/168889064-65f8d3fe-c346-441a-aeac-aea72f6fb922.png)

**Comment by jos0405** [comment]
Also:
What about this PR? Would it be obsolete?
https://github.com/mautic/mautic/pull/9658

**Comment by patrykgruszka** [comment]
I can confirm, that this issue still exist. @jos0405 your case works because you are using `Contact field value` instead of `Form field value`. PR #9658 does not affect this issue, it just adds option to select multiple values in `Contact field value` condition, like contact country is from Norway or Poland or Czech Republic.
