### ISSUE TITLE
Mautic 4: Email reported as being sent twice in contact log

### ISSUE THREAD

**Issue by Christophe9880** [mautic/mautic#10110]
Issue: When a campaign has send email / email open / send email in the workflow, the email sent activity log entry is being duplicated for the first two emails in the chain.

Have made a short vid about it: https://youtu.be/hOpjIoJfk88

### Instructions to reproduce

1. Create three emails, email 1, 2 and 3
2. Create a campaign from a form or segment (is not relevant)
2. Add 'Send email' and select Email 1
3. Add 'Opens Email' after this and on the Yes path, add 'Send email' and select the second email
4. Add 'Opens Email' after this and on the Yes path, add 'Send email' and select the third email

### Expected behaviour
When the email is opened (if using Mailhog make sure you are opening Mailhog in a separate incognito window and then opening the mail) we expect to see one entry in the activity log for email sent (highlighted in red, and one for email read

![screenshot-christopherutsaert be-2021 06 24-20_00_49 (1)](https://user-images.githubusercontent.com/2930593/123320376-91b70c00-d529-11eb-81a7-242b61f02d54.png)

### Actual behaviour
The Email Sent entry in the activity log is being duplicated - note the entry above the one highlighted in red, suggesting that a second email was sent (it was not).

### Observations
With the third and final email/open the duplication did not happen - only with the first and second.

![screenshot-christopherutsaert be-2021 06 24-20_00_26 (1)](https://user-images.githubusercontent.com/2930593/123320524-c88d2200-d529-11eb-83f3-4f5ff2ef7c68.png)

When one email is sent and nothing is chained after the duplication is not seen (see the latest entries in the activity log)

![screenshot-christopherutsaert be-2021 06 24-20_07_34 (1)](https://user-images.githubusercontent.com/2930593/123320621-e9557780-d529-11eb-9997-3d0eedb5ae8b.png)

**Comment by RCheesley** [comment]
Splitting these out into two separate issues for clarity.

**Comment by RCheesley** [comment]
Hey there,

I did a bunch of testing on this but I am not able to reproduce the issue. I tried with a form based campaign the same as yours, and with a segment based campaign.

I also tried with just one email, then added all the additional things in one at a time and am still not getting duplicated emails in the contact log after opening them (in Mailhog which is in an incognito window).

Is there any other way email 1 could be getting sent twice (maybe two active campaigns?)

**Comment by Christophe9880** [comment]
@RCheesley Hi Ruth, thx for your reply.
If you want, you can test on my installation as well, just let me know and I grant you access

**Comment by RCheesley** [comment]
Drop me a message on Slack and let's see if we can get to the bottom of it!

**Comment by Christophe9880** [comment]
@RCheesley done, see Slack

**Comment by RCheesley** [comment]
OK so I managed to track down the cause of this and replicate it.

1. Create three emails, email 1, 2 and 3
2. Create a campaign from a form or segment (is not relevant)
2. Add 'Send email' and select Email 1
3. Add 'Opens Email' after this and on the Yes path, add 'Send email' and select the second email
4. Add 'Opens Email' after this and on the Yes path, add 'Send email' and select the third email

Expected behaviour:
When the email is opened (if using Mailhog make sure you are opening Mailhog in a separate incognito window and then opening the mail) we expect to see one entry in the activity log for email sent (highlighted in red, and one for email read

![screenshot-christopherutsaert be-2021 06 24-20_00_49 (1)](https://user-images.githubusercontent.com/2930593/123320376-91b70c00-d529-11eb-81a7-242b61f02d54.png)

Actual behaviour:
The Email Sent entry in the activity log is being duplicated - note the entry above the one highlighted in red, suggesting that a second email was sent (it was not).

Observations:
With the third and final email/open the duplication did not happen - only with the first and second.

![screenshot-christopherutsaert be-2021 06 24-20_00_26 (1)](https://user-images.githubusercontent.com/2930593/123320524-c88d2200-d529-11eb-83f3-4f5ff2ef7c68.png)

When one email is sent and nothing is chained after the duplication is not seen (see the latest entries in the activity log)

![screenshot-christopherutsaert be-2021 06 24-20_07_34 (1)](https://user-images.githubusercontent.com/2930593/123320621-e9557780-d529-11eb-9997-3d0eedb5ae8b.png)
 
Will add this to the issue description.
