### ISSUE TITLE
Remove duplicate assets

### ISSUE THREAD

**Issue by nickveenhof** [mautic/mautic#10146]
Right now we have media/images with the country flags but also app/assets/images. We should make sure to remove files in media & replace the path in mautic codebase to point to app/assets/images

**Comment by shinde-rahul** [comment]
@nickveenhof with the #10153, I had to add the empty `images` directory into `media` just to pass the `Mautic tests and validations / PHPUnit 7.4 mariadb (pull_request)` pipeline. This is because, on the same repo, the scaffolding is not done. (The `media/images` directory is not present. [FileController::uploadAction](https://github.com/mautic/mautic/blob/features/app/bundles/CoreBundle/Controller/FileController.php#L47))
