### ISSUE TITLE
dates in mau_lead_donotcontact using UTC despite congis set otherwise

### ISSUE THREAD

**Issue by starchild** [mautic/mautic#10157]
## Bug Description
Dates in mau_lead_donotcontact are using UTC timezone dewspite config and server set to Australia/Sydney time

| Q   | A
| --- | ---
| Mautic version |  3.3.3
| PHP version | 7.3
| Browser | n/a

### Steps to reproduce
1. Checking time stamps in v against actual timing
2. 
 
### Log errors
none

**Comment by npracht** [comment]
Hi @starchild ! Thanks a lot for your message. Nevertheless it misses a bit of information.
When you say "Dates in mau_lead_donotcontact", you talk about the place where it is saved in DB ? Because the date in DB should not be done accordingly the date configuration of the app. We should save in DB timestamp and display it in the UI depending on the configuration. This timezone config is just for UI.

Let me know
