### ISSUE TITLE
I install the first version of mautic 1.0

### ISSUE THREAD

**Issue by miguelpascual** [mautic/mautic#1019]
and launch the update process and everytime I get one error:

![image](https://cloud.githubusercontent.com/assets/10166840/10581429/e6ed4bf0-7682-11e5-9f47-bea9091b1288.png)

There is nothing in the log

**Comment by miguelpascual** [comment]
New try.
I created a lead and a smart list for initialization process of ddbb (could be unnecessary but...)

![image](https://cloud.githubusercontent.com/assets/10166840/10582196/f8d7b734-7686-11e5-9ddb-7c2087e7c08e.png)

I get the same result
![image](https://cloud.githubusercontent.com/assets/10166840/10582269/50cc9720-7687-11e5-9476-ad0de9d9323e.png)

**Comment by escopecz** [comment]
The error message says: "Check log form more details". So what's in the logs?

The question as you put it seems like you intentionally installed fresh Mautic 1.0.0 and try to update it to the latest version. If that's the case, why don't you just install the latest version?

**Comment by miguelpascual** [comment]
"There is nothing in the log"

When I try to install the last versión it don't works :/ 

but until this moment install the version 1.0.1 and update work correct

**Comment by alanhartless** [comment]
This one is going to be tricky to track down considering the update from a very old version.  I am going to bet that there is a migration issue where a migration is using ORM before a newer field has been created and thus it is encountering a Doctrine exception.  

I'm betting it's the render_style. I updated #1007 to account for this.  Testing is going to be tricky since it won't be packaged in an update package.  Can probably test once we release 1.2.1.

**Comment by miguelpascual** [comment]
I reported this for your information.
:D

**Comment by alanhartless** [comment]
Should be fixed with 1.2.1.

**Comment by alanhartless** [comment]
Well shoot. The PR didn't get merged. Will be fixed in 1.2.2
