### ISSUE TITLE
Contact email reply not showing under contact history

### ISSUE THREAD

**Issue by elsaadj** [mautic/mautic#10203]
My Mautic version is: 3.3.3
My PHP version is: 7.3.27
My Database type and version is: mysql Ver 15.1 Distrib 10.2.36-MariaDB

After sending email to a contact from Mautic and replying to the email from outside Mautic, the contact history shows Email Read Event, but the contact reply email doesn’t show up in contact history?

mautic:email:fetch
1 email processed for {…} INBOX with a criteria of UNSEEN

**Comment by elsaadj** [comment]
How you turn on debug trace for email contact reply fetch?

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)  

If it turns out to be a bug after getting support from the community please post a detailed bug report so that we can assist you further.
