### ISSUE TITLE
Dynamic Content block for landing pages is missing on GrapesJS

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#10241]
### Bug Description
There is not currently a block for dynamic content when using landing pages in the GrapesJS builder as the feature has not been implemented yet.

Dynamic Content is created under Components > Dynamic Content and can be campaign-based or filter-based.

The block needs to allow you to select the appropriate DWC item and then drop the correct token into the page at the appropriate location.

**Comment by npracht** [comment]
Still an issue

**Comment by stevedrobinson** [comment]
This issue description isn't quite complete/accurate. Currently, even if you key in the token/shortcode (e.g. `{dwc=myslot}`) in for dynamic content, the dynamic content does not render. It's also not possible to put in dynamic content html (e.g. `<div data-slot="dwc" data-param-slot-name="myslot">`) in and get the dynamic content to render. 

From what I can tell, there is no workaround to getting any dynamic content working in landing pages once you make the leap to GrapesJS.

@RCheesley I would recommend splitting this into two issues:

1. Bug: dynamic content shortcode/token does not work in GrapesJS landing pages
2. Enhancement: Add dynamic content to the GrapesJS builder

My understanding is that number 1 is more of a back-end issue, while number 2 is more of a front-end/javascript/GrapesJS issue. Since resources for GrapesJS are scarce, at least getting the tokens/shortcodes working would allow those waiting on dynamic content support to upgrade/migrate to GrapesJS the ability to do so (and also allow them to upgrade to Mautic 5). 

It would also be a huge help to anyone in my boat that migrated to GrapesJS only to find out later that not even the token or html work when keyed or pasted into the editor.

**Comment by stevedrobinson** [comment]
Anyone have any thoughts on my note above? Without the shortcodes at least working, I worry this will hold people back from upgrading in the future.
