### ISSUE TITLE
[BUG] Switches don't switch on Integrations screen

### ISSUE THREAD

**Issue by pbwebdev** [mautic/mautic#103]
Appears there are some JS errors on activating an integration.

http://pasteboard.co/1sWPFppp.jpg

The integration is active when clicking the switches but they don't go green (indicating on) unless a full screen refresh is done.

**Comment by alanhartless** [comment]
Whatever is causing #104 is likely causing this as well. If you just upgraded from beta4 to RC, then clearing your browsers cache should take care of it.  If you didn't just upgrade, getting us the JS error may help figure out what the issue could be.

For the addons, toggling the publish button should trigger an automatic page refresh because we have to wipe out Symfony's cache and a page refresh is required to ensure the cache is rebuilt correctly with the enabled/disabled addon changes. This is done by javascript which is why I think it ties into #104  which is also a JS related issue.

Thanks!
Alan

**Comment by pbwebdev** [comment]
Confirmed related, just debugging now.

Thanks Alan
