### ISSUE TITLE
Mjml to html conversion needs the beautify option which is depreciated in browser mode

### ISSUE THREAD

**Issue by adiux** [mautic/mautic#10331]
We are currently using the browser mode to convert mjml to HTML. 

Html needs to be `beautified` for the click tracking to work. Therefore, we can not use the built-in command: `mjml-get-code` in order convert mjml to HTML. But we have to use `mjml2html` directly with the `beautified` option tuned on. This option is depreciated.

> `beautify` option is deprecated in mjml-core and only available in mjml cli.

Related: https://github.com/mautic/mautic/issues/10323

**Comment by LordRembo** [comment]
@adiux Has there been any ideas about what to do when `beautify` finally gets removed instead of just deprecated?
I'm currently looking at the possibility that we may have to change the logic in the `mjml2html` because something in the retrieval of MJML (perhaps the `getHtml` function) is causing classes and id's in the html to be lost. In that case, there isn't a way to set `beautify`.
