### ISSUE TITLE
Queued mailing won't work ("swiftmailer.transport.real" service or alias has been removed)

### ISSUE THREAD

**Issue by rafalsk** [mautic/mautic#10392]
### Mautic Version

4.0.x series

### PHP version

7.4.19

### What browsers are you seeing the problem on?

Chrome

### What happened?

A bug happened!
![image](https://user-images.githubusercontent.com/9338163/131502410-cd63a513-f417-4a60-a732-62a51ad1d961.png)

### How can we reproduce this issue?

Step 1: as seen above

The Cron Job is invoked as seen below:

`C:\Users\Administrator\Documents>php C:\inetpub\wwwroot\project\mautic\bin\console mautic:emails:send

`

### Relevant log output

```shell
In Container.php line 275:

  The "swiftmailer.transport.real" service or alias has been removed or inlined when the container was compiled. You
  should either make it public, or stop using the container directly and use dependency injection instead.
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by rafalsk** [comment]
Boys boys.. what's up with this project...
We seem to have gottena round the issue by invoking directly
php C:\inetpub\wwwroot\project\mautic\bin\console swiftmailer:spool:send --message-limit=300 --env=prod

Still guess what no e-mail are being sent.

Update: the ones invoked manually to specific contacts are delivered 
![image](https://user-images.githubusercontent.com/9338163/131503938-86d7bcf8-0d7e-4d16-98b6-5be10774d858.png)

Still.. remember? Only after the above work-around. Still no luck with everything else...

![image](https://user-images.githubusercontent.com/9338163/131504361-9b1499b2-ed9e-4292-b76b-cd99d9f1986a.png)

It's stuck at 0 emails being sent. For some reason it's stuck with everything else. Can't see any Cron tasks omited.

Folks look at the below.. it's gettin' ridiculous..
![image](https://user-images.githubusercontent.com/9338163/131507227-82b604a2-37c7-4850-af4e-15208a3f54e9.png)

**Comment by rafalsk** [comment]
We got it to work on Windows Server 2019 IIS for CAMPAIGNS with the following cron settings invoked by Task Scheuduler:
`php C:\inetpub\wwwroot\project.org\mautic\bin\console mautic:segments:update --env=prod
php C:\inetpub\wwwroot\project.org\mautic\bin\console mautic:campaigns:update --env=prod
php C:\inetpub\wwwroot\project.org\mautic\bin\console mautic:campaigns:trigger --env=prod
php C:\inetpub\wwwroot\project.org\mautic\bin\console  mautic:messages:send
php C:\inetpub\wwwroot\project.org\mautic\bin\console swiftmailer:spool:send --message-limit=300 --env=prod
php C:\inetpub\wwwroot\project.org\mautic\bin\console mautic:email:fetch
php C:\inetpub\wwwroot\project.org\mautic\bin\console mautic:social:monitoring
php C:\inetpub\wwwroot\project.org\mautic\bin\console mautic:import

.. :-)

**Comment by RCheesley** [comment]
Hey there, firstly thanks for raising your 8 issues over the past day. It's great to see you're testing Mautic and helpful that you've taken the time to report bugs when you found them.

This bug (or at least something similar) was fixed in the 4.0.0 release with this PR: https://github.com/mautic/mautic/pull/10352. Are you running 4.0 or an earlier release? We will update the issue form to make it a bit more granular now we're into general release.

I would ask that you please refresh your memory by reviewing our [Code of Conduct](https://contribute.mautic.org/policies/code-of-conduct#4-expected-behavior) and remember that the folks who have worked extremely hard to get this release out, are doing so on the whole as volunteers. Some of your comments are getting quite close to the line as being unkind and offensive, so please be more mindful going forward of how this comes across to our volunteers.

Please be courteous and polite in your feedback on issues, and respect the fact that they may not be available to immediately respond to your issues.

Perhaps next time you will be able to dedicate as much time as you have here, to testing the Release Candidate and earlier releases. 

We would very much appreciate more help with testing, and this is the number one reason why the releases have been delayed (and why there may be bugs we have not identified).  

Perhaps think about whether you can allocate an hour a week or something like that, to help the project. Every single person we have poking about with pre-releases and picking up bugs helps immensely!

**Comment by RCheesley** [comment]
Also as an aside, 

> Boys boys.. what's up with this project...

Some of us aren't boys. Let's try to use gender neutral terms eh, thanks! :)

**Comment by rafalsk** [comment]
> Hey there, firstly thanks for raising your 8 issues over the past day. It's great to see you're testing Mautic and helpful that you've taken the time to report bugs when you found them.
> 
Happy to help.

> This bug (or at least something similar) was fixed in the 4.0.0 release with this PR: #10352. Are you running 4.0 or an earlier release? We will update the issue form to make it a bit more granular now we're into general release.
Seems like you've released version 4.0.. 48 hours ago. We're still on the 'candidate' version. Will give the final thing a go in a sec.
> I would ask that you please refresh your memory by reviewing our [Code of Conduct](https://contribute.mautic.org/policies/code-of-conduct#4-expected-behavior) and remember that the folks who have worked extremely hard to get this release out, are doing so on the whole as volunteers. Some of your comments are getting quite close to the line as being unkind and offensive, so please be more mindful going forward of how this comes across to our volunteers.
> 
Relax Chesley, would you; trust me; I know something about 'this' line, of work.
> Please be courteous and polite in your feedback on issues, and respect the fact that they may not be available to immediately respond to your issues.
> 
Glad you respond so fast!
> Perhaps next time you will be able to dedicate as much time as you have here, to testing the Release Candidate and earlier releases.
> 
Doing my best Cheesley!
> We would very much appreciate more help with testing, and this is the number one reason why the releases have been delayed (and why there may be bugs we have not identified).
> 
Curious, how the release plays our here for us, will upgrade in a sec!
> Perhaps think about whether you can allocate an hour a week or something like that, to help the project. Every single person we have poking about with pre-releases and picking up bugs helps immensely!

We would be more than happy to help Chesley!


Update: we're now on 4.0 Release (after fixing the update-certificate-thing) , still got to clear the cache and see how things roll.

**Comment by RCheesley** [comment]
Hi there, thanks and good to hear that you're getting things sorted.

Generally speaking, please post initially on the forums at https://forum.mautic.org/c/support if you have an issue and you are not sure if it is server related or a bug with Mautic. The community will then help to troubleshoot and will then direct you over to GitHub if it is definitely a bug with Mautic.

Otherwise, our issue queue gets full with things which may not be bugs.

Please don't address me by my surname, you're fine to use @RCheesley if you wish to address me by name. There is no need to be rude or condescending either in your replies.

**Comment by rafalsk** [comment]
We triple checked it's all configured to your documentation so this or that looks like a bug doesn't it? Glad to hear your community sounding helpful but we would rather be on the front line after being certain everything is done by the book so to speak and seeing it stuck. 

@RCheesley as you might see most of the things (if not all) I report turn out to be confirmed bugs indeed. It costs us a lot of time to being stuck with ascertaining what would one presume as basic functionality and another middle-men wouldn't make things easier and/or faster as deliberately all the stuff I/we report turn out to be bugs indeed.. saw the SQL report/log? Clearly your app didn't handle data right way, hasn't done value-length/table-cell length validation.. things went wild :-)

I'm not about being cheeky. I want to have this working and fixed and thus trying to be helpful. Wasted a lot of time on this already(days) which was sort of unexpected. Some (1-2)things were due to misconfiguration (I found in matters of hours and closed the tickets) others are serious bugs and were it not for some serious IT expertise typical user would have long run away.

Once I'll be having questions in regard to functionalities/ wondering how to get things done I'll be more than glad to reach our to the community of yours. But seeing the software throwing away in my face X times a day.. naah that's a devs talk.

Also @RCheesley :

- the website of yours says to use the 'download page' for user-builds. The recent 'relase-build' available there is 2.X+
- thus the only way to proceed as far as I can tell is downloading the Zip from github. And getting it all set-up might be considered as 'hell-of-a-work' form a typical user's perspective (I suppose, especially on Windows where a couple of commands the packager invokes simply do not exist). maybe you rely on the auto-update functionality I have no idea. Just letting you know that it seems there wasn't an update to the release-packages since long.

**Comment by RCheesley** [comment]
> * the website of yours says to use the 'download page' for user-builds. The recent 'relase-build' available there is 2.X+

I have just downloaded the latest release from mautic.org/download and it downloads 4.0, please share where you found a link to the 2.x version?

**Comment by shurco** [comment]
Don't work function 'Contact Replies'
After cron check IMAP I see - 
**0 emails processed for {imap.yandex.com:993/imap/ssl}INBOX with a criteria of UID 3489:1000003489**
