### ISSUE TITLE
Argument 1 passed to Swift_Transport-AbstractTransport::send() must be an instance of Swift_Mime_SimpleMessage (..)

### ISSUE THREAD

**Issue by rafalsk** [mautic/mautic#10456]
### Mautic Version

4.0.0

### PHP version

7.4.19

### What browsers are you seeing the problem on?

Chrome

### What happened?

https://github.com/mautic/mautic/issues/10451
Closing this issue due per the guidance above.

(..) closing due to a guidance. (..) Management of this project seems ridiculous. Just if it was of concern to you, Ruth, the problem is exactly the same when invoking through "php /path/to/mautic/bin/console mautic:emails:send" you probably know better than me that it's just a wrapper for the previous function.

### How can we reproduce this issue?

Step 1: like in previous report.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by pwned555** [comment]
Was this closed because using mautic:emails:send is supposed to fix the issue?  We sometimes get the same error as above and we use mautic:emails:send, however I am unable to replicate consistently.  If so I'll try to spend some time finding a way to reliably replicate the issue.

It usually reports once for us and then doesn't report again the next time it runs.  I'm unsure if the email that caused the issue is never sent, never existed, or was sent the next run.

It's being generated by \vendor\swiftmailer\swiftmailer\lib\classes\Swift\FileSpool.php in the flushQueue function.
$message = unserialize(file_get_contents($file.'.sending'));
$count += $transport->send($message, $failedRecipients);

This calls 
vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\AbstractSmtpTransport.php send function
This is where it errors because $message is a bool and not a Swift_Mime_SimpleMessage.

So it looks like unserialize(file_get_contents($file.'.sending')) sometimes errors and returns a bool instead of Swift_Mime_SimpleMessage.  However I can't reliable replicate yet that's just some more information of the source of the issue, I might try updating it so that it only calls unlink($file.'.sending'); if there isn't an issue so I can view a sample of the file that caused the error.
