### ISSUE TITLE
Database failed to update during 4.0.1 update

### ISSUE THREAD

**Issue by starchild** [mautic/mautic#10484]
### Mautic Version

4.0.0

### PHP version

8

### What browsers are you seeing the problem on?

Chrome

### What happened?

Upon updating from 4.0.0 > 4.0.1 everything worked except for the database update.

Is there somewhere that I can get the SQL queries to do this manually?

FYI, the upgrade notice no longer is showing.

### How can we reproduce this issue?

Step 1: update via the on board upgrade tool

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Hi there,

Mautic does not yet support PHP 8 so there are likely to be issues. Before we step into troubleshooting, can you please check with PHP 7.4? Supported versions can be found at https://mautic.org/download/requirements.

**Comment by starchild** [comment]
so far, other than that part of the upgrade, everything else seems ok.

Can you tell me what the sql queries are to complete the upgrade please?  

(unfortunately I can't step down to php 7.4)

**Comment by dennisameling** [comment]
@starchild do you have access to a command line? If yes, you can run `php bin/console doctrine:migrations:migrate` so that it will execute the database migrations 👍🏼 

_Note to self:_ we might want to add a UI screen (under System Information for example) that shows if the database is up-to-date and allows the user to start migrations from the UI. That way, no CLI access is needed. For small installations this should work without problems, but for larger installations we might want to add a warning that folks could run into PHP execution  timeouts.

**Comment by starchild** [comment]
Thanks, I've run that but no message or anhything was shown on the command line.  How can I tell if it worked please?

**Comment by jos0405** [comment]
You supposed to see something like this:
`
Updating database schema...
77 queries were `executed
`
