### ISSUE TITLE
After activating API, need clear the cache to make APi working

### ISSUE THREAD

**Issue by joakimvivas** [mautic/mautic#10568]
### Mautic Version

4.0.0

### PHP version

7.4.25

### What browsers are you seeing the problem on?

Firefox

### What happened?

It is not possible to connect to the API "Code 404, Requested URL not found: /api/contacts/"

### How can we reproduce this issue?

Step 1: Activated the API on config
Step 2: Created the credentials and validated the connectivity
Step 3: Launched first API call to /api/contacts (and another case)
Step 4: Cleared the cache

Constantly I have the error:

{
  "errors": [
    {
      "message": "Requested URL not found: /api/contacts",
      "code": 404,
      "type": null
    }
  ]
}

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by npracht** [comment]
I think i can reproduce. But we might be doing something wrong, i cannot believe API is not working since 4.0 and none said nothing.
<img width="624" alt="Capture d’écran 2021-11-09 à 16 04 27" src="https://user-images.githubusercontent.com/14075239/140949139-38ab37b0-7bdd-43f8-a761-8afeecb448e1.png">

@dennisameling @mohit-rocks @kuzmany @alanhartless can someone give a look at this ?

**Comment by dennisameling** [comment]
@npracht IIRC you have to delete the cache after enabling the API. Then it should work. Not an ideal user experience, so let's keep this issue open so we can improve that at some point 👍🏼

**Comment by npracht** [comment]
Okay, not that bad.
After doing in SSH console: 
```shell
rm -rf var/cache/*
```

It works properly.
<img width="577" alt="Capture d’écran 2021-11-09 à 16 46 49" src="https://user-images.githubusercontent.com/14075239/140956860-639abd53-b020-48ba-b391-38788279368d.png">


Yes we have to follow this, this is a bit dirty but it works.

**Comment by jos0405** [comment]
This issue is generating a LOTS of questions in Mautic forums. Everyone thinks, there is something wrong with the API calls they make, as the calls return "not found". As next step poor vicims try to look for the /api/ folder and get nowhere, since it's not a real folder, just a virtual path. The next step is they try to install an api extension or something. Really annoying.

Can we maybe add text to Config/Api settings?
![image](https://user-images.githubusercontent.com/4246909/143557565-e51c1fc5-dd52-403e-8f18-dfa1f416b71b.png)

**Comment by jvkroeger** [comment]
I can confirm that deleting the cache helped. I had the same problem.

**Comment by dakur** [comment]
Encountered this as well right now. And I've already encountered it some years ago, this is quite long-standing bug, even it was reported 7 months ago.
