### ISSUE TITLE
[feature] ignore 404 as a lead

### ISSUE THREAD

**Issue by tiagomreis** [mautic/mautic#1060]
If someone access to a file or content on mautic url, do not process as a lead, only if the content exist.

Create a option on settings that can change the rules type to exclude error 404 access as a lead.

After some hours with software online, several access from china and india, generate on software "fake leads" based on url's like "domain.com/header.asp", "domain.com/header.png". This 404 are being converted to leads and counting to statistics on reports.

**Comment by tiagomreis** [comment]
![screen shot 2015-10-27 at 10 26 51](https://cloud.githubusercontent.com/assets/921743/10755381/563b771c-7c95-11e5-8b28-20fdc88add36.png)
![screen shot 2015-10-27 at 10 26 32](https://cloud.githubusercontent.com/assets/921743/10755385/5e3b2ca0-7c95-11e5-91af-5bc59afd5b75.png)

After a clean installation, 4 hours later..fake leads

**Comment by ChuckRenner** [comment]
+1
I was very surprised to see 404s create new contact records.

**Comment by moyashidaisuke** [comment]
Why Mautic create 404 as contact ??

**Comment by escopecz** [comment]
404 is a page. And Mautic tracks page hits so you'd know what the contact did. I personally think that knowing that the contact ended up on the 404 page is valuable information.

**Comment by moyashidaisuke** [comment]
thanks reply.

> I personally think that knowing that the contact ended up on the 404 page is a valuable information.

Yes, the information  of  the user who visit LP or our tracking website is valuable.
But, mautic url 404 is not valuable.

for example, 
"mymautic.com/phpmyadmin"

It is a bot attack. 

Tracking bot attack will be  obstacle to report, and  database server load will increase.

**Comment by aspiers** [comment]
I am also experiencing significant spam in one of my segments due to this.  Since this issue is closed, and my scenario is slightly different to the one described here, I have submitted #7565.

@escopecz I can see how tracking 404s reached by existing contacts is useful as a mechanism for spotting broken links or other breakage in the navigation process, but I can't see how it would be justified to create a new contact when 404s arrive out of the blue.  @moyashidaisuke is correct that it is pointless to gather noise in the database as a result of countless bots constantly scanning the internet for vulnerable servers.

Also @dbhurley please forgive me if this is a newbie question, but I'm not sure why this issue was closed without any obvious resolution.  If it was moved elsewhere for tracking in a different tool, please could we have a link to that?

How can we move this forward?  Would it be reasonable and possible to only track 404s reached by existing contacts, whilst avoiding creating new contacts when random bots attempt attacks?
