### ISSUE TITLE
Can't edit Tags on Mautic 4.2 

### ISSUE THREAD

**Issue by andresagui** [mautic/mautic#10927]
### Mautic Version

4.2.x series

### PHP version

7.4

### What browsers are you seeing the problem on?

Chrome

### What happened?

After updating from 4.1.2 to 4.2 can't edit Tags.

I can not edit the Tag Name, only the description. I don't know if that's a bug or if that's the new way (only editing description)

### How can we reproduce this issue?

Step 1: Go to tags, choose one, click edit, unable to change the name

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Confirmed this behaviour - the tag name was not editable. 

![Edit tag_ test _ Mautic](https://user-images.githubusercontent.com/2930593/156819279-9ef9102a-f231-46d6-a41d-61da66f88b3e.png)

According to the PR which introduced the description field (#10799)

> Note: We are now able to edit tag only the first time we open the form. If we want to rename the tag we have to create a new one, this however is not true for summary and description, we can update those two fields as much as we want.

@mzagmajster as the author of that PR, could you share the reasoning and also let's make it clear in the documentation that this is the expected behaviour going forward.

**Comment by mzagmajster** [comment]
Hi, @RCheesley @andresagui

It has to do with identifying the correct record. I added this because without this logic description was not properly updated (edited). Before PR in question editing worked because tag name was the only thing on the form and that changed with description field.

Initially I thought that editing tag name is not something that should be done very often anyway (please correct me if I am wrong).

I suggest we leave tag name read only as you can still delete the tag and create new one, allowing editing the tag name would require to update the controller code and if I remember correctly also transformer and form.

If on the other hand you want to introduce tag name editing, I can make an effort to allow that.

**Comment by ghost** [comment]
@mzagmajster  It is very common for me to make a typo when creating a new tag. Therefore, I would rather edit existing tags than add new ones. Especially that mass adding a new tag to existing contacts requires creating a campaign. I can't select them manually and do bulk add.

**Comment by mzagmajster** [comment]
@RCheesley If I go into implementation of enabling editing the tag names, will this get merged?

**Comment by RCheesley** [comment]
@mzagmajster I don't see any reason why not if the code is reviewed and folks test the PR, I'd make it clear in the PR description that it's a bug fix (then we can merge it in a patch release) to re-enable the ability to edit a tag name.

**Comment by leoborlot** [comment]
Hi folks. The problem persist:
https://forum.mautic.org/t/cannot-edit-tags-name-in-4-4-3/25564

**Comment by RCheesley** [comment]
@leonardoborlot this was by design - see the comment here: https://github.com/mautic/mautic/issues/10927#issuecomment-1059460766

If you want to change the behaviour we would need a PR that takes into account the points raised as to why editing existing tags was blocked in the first place.
