### ISSUE TITLE
Running deduplicate on 260k contacts freezes and hangs in the processes

### ISSUE THREAD

**Issue by russkiimike** [mautic/mautic#10941]
### Mautic Version

4.1.x series

### PHP version

7.4.27

### What browsers are you seeing the problem on?

Not relevant

### What happened?

Mautic Version
4.1.x series

PHP version
7.4.27

What browsers are you seeing the problem on?
Not relevant

What happened?
Resiurces: 8 vCPUs
16GB / 80GB Disk

My problem is: Running deduplicate on 260k contacts freezes at around 100k contacts mark and just hangs in the processes!

These errors are showing in the log: N/A

Steps I have tried to fix the problem: Tried installing the custom deduplicate plugin but there's a compatibility issue with 4.1

Is there a way to fix this? Increasing batch limit like with the segments updates? It slows down to the point of freezing.

I also posted this issue on the forum and nobody looked.

Relevant log output
No response

### How can we reproduce this issue?

How can we reproduce this issue?
Step 1: Install Mautic with 281k contacts
Step 2: Run deduplciate

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by russkiimike** [comment]
Previous issue but it actually freezes now, and no replies on the forum https://github.com/mautic/mautic/issues/10867

**Comment by RCheesley** [comment]
@russkiimike this is most likely due to a server resourcing issue than a bug with Mautic. Please do not keep raising issues here, the proper place for that discussion is in the forums, and having no answer there does not entitle you to spam the bug tracker issue queue. 

If you are unable to address the issue yourself, please consider hiring a specialist to help you dig into what the problem is and find a resolution.
