### ISSUE TITLE
Editor is generating 'p' tags in page's html

### ISSUE THREAD

**Issue by thinkbigger** [mautic/mautic#1106]
I'm building a customized theme and the editor automatically generates `<p>` tags even on text elements.
As an example, on my *page.html.php* I have
```html
<?php if ($view['slots']->hasContent('s1Titulo')): ?>
            <h1 class="header text-center"><?php $view['slots']->output('s1Titulo'); ?></h1>
<?php endif; //?>
```
but the returned result will be
```html
<h1 class="header text-center"><p>sdfsdf</p></h1>
```
On *config.php* page, this slot is configured as text
```php
    "slots"       => array(
        "page" => array(
            "s1Titulo"    => array('type' => 'text'),
```
If I open the editor and try to edit the source code of the slot, the `<p>`tag is always there. If I delete it on the editor, it reapers after saving.
By the way, I'm using V1.2.2

Thanks for your help.

**Comment by escopecz** [comment]
I wrote a fix for this (https://github.com/mautic/mautic/pull/1096). Would be great if you could test it and comment on that PR.

**Comment by thinkbigger** [comment]
Sorry. It doesn't work.
It still add the `<p>`tag on the text.

**Comment by escopecz** [comment]
It generates classic `<input type="text"/>` fields without HTML editor for text slots. If you create a new theme, it will not create a `<p/>` tags there. Because they are generated by the HTML editor. The `<p/>` tags will remain for older templates, but the tags are visible in the input.

**Comment by thinkbigger** [comment]
Hi,
It happens with a new theme.

**THEME NAME:** tbHome
**themes/tbHome/config.php**
```php
    "slots"       => array(
        "page" => array(
            "s1Titulo"    => array('type' => 'text'),
```
**themes/tbHome/page.html.php**
```html
<?php if ($view['slots']->hasContent('s1Titulo')): ?>
            <h1 class="header text-center"><?php $view['slots']->output('s1Titulo'); ?></h1>
<?php endif; //?>
```
**Results on http://mydomain.com/mautic/landingpage/ (source code)**
```html
<h1 class="header text-center"><p>sdfsdf</p></h1>
```

**Comment by vln104** [comment]
Hi guys,  can you confirm the issue here is that CKEditor encloses everything in a <p> tag and if this has been fixed? If not I think I know what might be causing it so would @thinkbigger be willing to try out a fix for me please? 

The fix might have wider consequences outside of the page builder so will need to be discussed and reviewed carefully

**Comment by TomRoethlisberger** [comment]
This is a ckeditor configuration issue. I'll created a pull request to change from the enter_p mode to enter_br mode. To be discussed if we should enhance the enter and shift enter behaviour otherwise. But for e-mails (not for pages) the p tag is really bad since the styling of the p can't be defined and gmail is ignoring all the styles except the inline styles.

**Comment by escopecz** [comment]
The CK editor and the Email Builder were changed in 2.0.0 so I'll close this issue.
