### ISSUE TITLE
Multisite Cabability?

### ISSUE THREAD

**Issue by phillipwilhelm** [mautic/mautic#1113]
Is it possible to make mautic multisite capable for clients etc?

**Comment by that0n3guy** [comment]
Nope, not really.  You may be able to do something w/ permissions depending your needs.  Otherwise, you might be better off creating a quick app that allows you to manage multiple installs (via direct DB access or api) and deploy with docker.

**Comment by escopecz** [comment]
@phillipwilhelm could you describe "multisite capable" in more detail? It can mean many things.

**Comment by phillipwilhelm** [comment]
To allow multiple tenants on one install. Instead of re-installing for every organization it would be easiest to have them all share same base code, and access different db tables for their account. Is this possible?

**Comment by that0n3guy** [comment]
@phillipwilhelm If you use docker, you could have the have the containers built from the same code base.  Also, because of the way docker handles images, all the different containers wouldn't take up more space (example: IF 1 mautic container was 1GB, 100 mautic containers would still only take up 1GB).

So this isn't a drupal "share the same code base" solution, but the container code base will be consistent and space is still saved.

**Comment by phillipwilhelm** [comment]
Any documentation on this approach?

**Comment by that0n3guy** [comment]
Probably not, its doesn't really have anything to do w/ mautic.  Its a server thing at that point.  Look into docker.com

**Comment by alanhartless** [comment]
Yea, it would take a unique Mautic installation per client to keep all data completely separate. 

Thanks,
Alan

**Comment by ravikannankr** [comment]
Found this on Github. 
https://github.com/vmeretail/multi-tenancy-bundle 

Will this work with Mautic? Has anyone used this?

**Comment by 3Maestros** [comment]
@pwilhelm949 wondering if the solution with docker worked for you as a multi-tenant solution?
