### ISSUE TITLE
Do not handle emoji in importing contacts

### ISSUE THREAD

**Issue by esmaeili0101** [mautic/mautic#11151]
### Mautic Version

4.2.x series

### PHP version

7.2

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### What happened?

When uploading the contact list, if there is an emoji in a line, it does not give any error, but the import is not done. That is, it remains in upload mode without incident.

### How can we reproduce this issue?

Step 1: Make a list of email and name columns
Step 2: In one of the lines, use an emoji (for example, a flower emoji) as a name.
Step 3: Upload the list.

### Relevant log output

```shell
nothing
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by jos0405** [comment]
Hi, before excalating this further, can you plz confirm, that your database is for the table "leads"

 'charset' = 'utf8mb4';
'collation' = 'utf8mb4_unicode_ci'

Looks like this:
![image](https://user-images.githubusercontent.com/4246909/166878979-2ae55ac7-f3f0-440e-8f82-6854ed84e672.png)

**Comment by RCheesley** [comment]
Hi @esmaeili0101 can you please report back regarding the request above? Otherwise we will close this issue down. Thanks in advance!

**Comment by trianity** [comment]
@esmaeili0101 @RCheesley 
I can confirm that if the MySQL code collation and settings are correct, Mautic will handle the emoji characters correctly in any table.
I have just fixed a Mautic instance existing from an older installation (it was originally Mautic v2.x - now Mautic v4.3.1) that didn't save emoji characters for emails. In this instance the database collation was somehow utf8mb3_unicode_ci (it is possible that due to an incorrect database installation)

Provided with
```
'charset' = 'utf8mb4';
'collation' = 'utf8mb4_unicode_ci'
```
settings for all related tables, the problem is resolved.
