### ISSUE TITLE
Feature request: Decisions Links Clicked

### ISSUE THREAD

**Issue by kuunda** [mautic/mautic#1126]
Not sure if this has been brought up but have you busy chaps at Mautic considered having an 'Decisions' that does linked clicked yet?

**Comment by that0n3guy** [comment]
Yup, been on here for a while, but I can see why you didn't find it since subject hard to tell: #124

**Comment by alanhartless** [comment]
It depends on what you're end goal is.  If you want to track a specific link click, you could use a query parameter to ID the specific link. Then use that URL in the "visits a page" campaign hit (you can use a * wildcard for URL matching).  That would in essence have the same effect.

**Comment by that0n3guy** [comment]
> How would you envision the campaign UI for configuring such a feature?

This is how activecampaign does it: 
![image](https://cloud.githubusercontent.com/assets/113870/11879593/f026dd36-a4c1-11e5-82c4-ba7f6b26f4e6.png)

It allows you to choose any link sent from any email in the system.   I think it works well but is a little cumbersome.

For our UI, if decisionA is after a "send email" action, then decisionA's form would autofill with the email located pre-selected that was before decisionA on the builder.  This would make it easy to simply select a specific link (or multiple links) from that email.

Some wants:
* ability to select emails from within current Campaign, and list emails.  Selecting from emails that are in other campaigns might be confusing and I can't think of a use case.
* ability to select more than one email
* ability to say "all emails to X list".  This would only work for "list emails".
* Ability to choose one, many, or all of links from email(s)/List(s)

Is that what you were asking?

**Comment by that0n3guy** [comment]
Also, if you wanted to start out simple... you could just make it so the user can only select emails that are before the decision in that specific campaign's builder.

**Comment by amagdy3** [comment]
I'm also interested in having this feature. Are there any plans to produce it in the future?

**Comment by that0n3guy** [comment]
This is also useful for deliverability.   A good practice is to move contacts to a different, less used, list if they are not engaged in the last 30-90 days.  

We do this in Activecampaign using workflows that ad tags, or remove tags when people click or open emails.   See the "recency of engagement tagging" here: http://www.activecampaign.com/blog/automations-to-track-and-engage-your-contacts/
In their system it requires 2 campaigns/automations because tags don't have a date associated with it.

**Comment by ipso** [comment]
This is something I would be interested in as well, but it seems like it could be really simple to implement and work out even better. Rather than making a fancy UI that pulls out each link from the email to place in a dropdown box and such, just use the existing logic for matching URLs on page visits.

In the campaign builder, copy the exact "Visits a Page" decision logic to "Clicks a Link", then just define the URL you want to match, ie: "www.facebook.com/mypage". or "*facebook*"

Mautic already wraps all links in emails for tracking purposes, so on redirect, just pass the *destination* URL into the "Clicks a Link" logic the same way the tracking pixel passes the URL into the "Visits a Page" logic. 

That should make this still quite simple to use and a easy feature to implement rather than quite difficult. 

It also has the added benefit of not having to setup the link clicking logic for *every* link in *every* email a campaign has. We have a campaign that goes through about 25 emails over the course of a year, and each one has our "facebook" link at the bottom. Given the above method we can just specify the logic once for all emails.

**Comment by that0n3guy** [comment]
@ipso   Ooooo, yes.  I like that.    This could make it crazy flexible.  You could do it based on google tracking UTM's (if you don't know what that is, see here: https://ga-dev-tools.appspot.com/campaign-url-builder/)  per marketing campaign, or traffic source

**Comment by kuzmany** [comment]
I am starting  work on click condition.  
Community can speed up developement  on https://mautic-fund.kuzmany.biz/ 
Show your love to Mautic 
👍

**Comment by escopecz** [comment]
I just did. Thanks!

**Comment by daniloalba** [comment]
i am having the same problem, i am not able to track links in the emails sent in campaigns.
i have checked a few forum answers but dont seem to have found any solution.
any body can help?

**Comment by MFriedbergNZ** [comment]
Hi - was the feature added?  I have just started using (3.01) But cant find this feature as part of Campaign Building Action item list.  Thanks
