### ISSUE TITLE
File Manager error to upload files

### ISSUE THREAD

**Issue by pedrinholula** [mautic/mautic#1127]
I have an error when upload a file using File Manager (FM). 

I've tried to upload an image in email section using FM and get the error:

```
[2015-11-04 20:46:26] mautic.ERROR: Uncaught PHP Exception
Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "Requested URL not found:
/app/bundles/CoreBundle/Assets/js/libraries/ckeditor/filemanager/scripts/languages/pt-br.js" at /opt/bitnami/apps/mautic/htdocs/app/bundles/CoreBundle/Controller/CommonController.php line 352
{"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): Requested URL not found:
/app/bundles/CoreBundle/Assets/js/libraries/ckeditor/filemanager/scripts/languages/pt-br.js at /opt/bitnami/apps/mautic/htdocs/app/bundles/CoreBundle/Controller/CommonController.php:352)"} []
```

**Comment by alanhartless** [comment]
@pedrinholula That file definitely doesn't exist and I'm not sure how it's deciding to look for `pt-br` since I don't think we're setting the locale for filemanager or ckeditor.  It looks like it pulls it out of the config file `/app/bundles/CoreBundle/Assets/js/libraries/ckeditor/filemanager/scripts/filemanager.config.js` (culture) or if it's passed in the URL as a query parameter `langCode`.  Are you able to see if langCode is in the URL when the filemanager opens? Or did you by chance modify the default filemanager config file?

Thanks,
Alan

**Comment by escopecz** [comment]
Closing for lack of feedback. Feel free to comment on this issue any time and I will re-open it again.

**Comment by Surmont** [comment]
Hi 

Was wondering if a solution has been found? I have the same error and can't find a way to fix it.
I haven't modified the filemanger config file, only the user.config.php to make the filemanager work. (It didn't load properly)

Thanks!
