### ISSUE TITLE
Mautic messes up email source code

### ISSUE THREAD

**Issue by Verbat** [mautic/mautic#1128]
I just noticed there are some problems with editing tags or source code by creating an email. I'm running the latest Mautic version and do not use an existing template.

If i copy my working email template via the source code button into mautic it removes or edit some code after using save and close. I know it's not strict HTML but it is necessary to fix outlook DPI scalling issues.

##Namespace##
The following
```
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">
```
becomes
```
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:o="urn:schemas-microsoft-com??office" xmlns:v="urn:schemas-microsoft-com:vml">
```
## Conditional comment##
The following 
```
  <!-- Outlook DPI Scaling Fix -->
  <!--[if gte mso 9]><xml>
  <o:OfficeDocumentSettings>
  <o:AllowPNG/>
  <o:PixelsPerInch>96</o:PixelsPerInch>
  </o:OfficeDocumentSettings>
  </xml><![endif]-->
```
becomes
```
	<!-- Outlook DPI Scaling Fix -->
	<!--[if gte mso 9]>
  96
  <![endif]-->
```
Full Email template can be viewed here:
http://pastebin.com/gq4LqaAS

I also noticed that it adds < tbody > after each table. If you have a very long template with a lot of tables these additional tags which are not realy necessary might just push you over the 100kb file size limit (spam filters) especially if you are inlining all css styles.

**Comment by bdentino** [comment]
Tracked this down to sanitization code here: https://github.com/mautic/mautic/blob/11e412c649418368b0d3230b8e4b076077b87312/app/bundles/CoreBundle/Helper/InputHelper.php#L337-L367

Got the conditional comments to pass through unscathed by commenting these lines out. I'll admit it's only been about 20 minutes since i saw my first line of php or set foot in the mautic codebase so I have no idea what the root cause _actually_ is or how to properly address it without breaking other assumptions. I can dig in deeper when I have some more time, but in the meantime maybe this will point someone with a little more experience in the right direction...

**Comment by siparker** [comment]
This is still a current bug

adds [if (gte mso 9)|(IE)]> into emails

**Comment by escopecz** [comment]
@siparker please create a new issue with full description of your issue. That means steps to recreate, what HTML content does your email have and where this code appears.

**Comment by siparker** [comment]
@escopecz after some further digging it seems to be flagged in #2370 as a Froala issue.

Ill wait for the update to come out.

shame i didnt dig further first.
