### ISSUE TITLE
Missing mautic:assets:generate step in the composer update process

### ISSUE THREAD

**Issue by trianity** [mautic/mautic#11380]
### Mautic Version

4.4.x series

### PHP version

8.0.18

### What browsers are you seeing the problem on?

Chrome

### What happened?

The Mautic embed form looks for the https://mautic-url.test/media/js/mautic-form.js file, while /media/js/ folder contains file with name mautic-form-src.js 

The issue cause Error 404 in the javascript console. 

### How can we reproduce this issue?

Step 1: Composer update from 4.4.0 to 4.4.1 version
Step 2: Embed any Mautic form into Mautic landing page with {form=x} code, or embed Mautic form with javascript embed method into an external webpage.
Step 3: Load the webpage (with embed form) and open the javascript console in the browser to see the log, and error. 

![Képernyőkép ekkor: 2022-08-04 21-06-13](https://user-images.githubusercontent.com/6353141/182933232-f10af7b2-b8ff-45dc-a40e-e089f316b7f3.png)

I try to handle with renaming  /media/js/mautic-form-src.js to /media/js/mautic-form.js and this solution only works while the session was active. The renamed mautic-form-src.js causes error 500 in the dashboard after login.

The issue related with https://github.com/mautic/mautic/issues/10408 too same error message.
and with https://github.com/mautic/mautic/issues/9951 

In the last mentioned case ( #9951 ) both name of the file is exists: mautic-form-src.js and mautic-form.js also.

I have found a that the /docroot/media/js folder content was not updated with the general update process via composer.
Copied the content of /docroot/app/assets/js to the /docroot/media/js folder, but the issue was not resolved.

![Képernyőkép ekkor: 2022-08-04 21-18-28](https://user-images.githubusercontent.com/6353141/182937212-8719d6b4-542c-4b9e-914b-a794dc5ddce3.png)

But running the `bin/console mautic:assets:generate` command the issue finally resolved.

So, it would be willing if the update process run fully and the assets also would be updated.

### Relevant log output

```shell
n/a
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by saschafoerster** [comment]
I can confirm the solution, as I had the same issue.

**Comment by saschafoerster** [comment]
Look, stalebot, a rabbit! 🐰

**Comment by mabumusa1** [comment]
I implemented a PR on 5.x, so this issue is solved in the next version of Mautic

**Comment by HrbzxcDev** [comment]
its look the same in mautic 5.x in using compose installer 

![image](https://github.com/mautic/mautic/assets/56247062/6475f540-937c-4159-8555-0b01bf3535c6)

**Comment by GrandM1961** [comment]
@HrbzxcDev

I had the same error with composer install, so I went looking what caused this.
So I took a look around in the composer.json and changed 1 line:

Line 143: "generate-assets": "bin/console mautic:assets:generate"

and I changed it into:
"generate-assets": "php bin/console mautic:assets:generate"

and I did a composer install again and now I got it all installed and working.

**Comment by makeasnek** [comment]
> Want to back this issue? **[Post a bounty on it!](https://app.bountysource.com/issues/121828452-missing-mautic-assets-generate-step-in-the-composer-update-process?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://app.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github).

     

Please do not use bountysource. Many devs have had trouble getting paid there. You can check out this lemmy community as an alternative https://lemmy.ml/c/bugbounties

For statements from devs who have been unable to cash out from bountysource see:
https://github.com/bountysource/core/issues

**Comment by RCheesley** [comment]
Thanks for the suggestion @makeasnek - it's an area where we know we need to find another provider as we've also had no end of issues (including that it simply doesn't work properly with the GitHub integration so we haven't actively used it in a long while, this is a very old issue - I have posted on their GitHub queue and also sent numerous issues and basically gave up). 

I'd thought about using Open Collective and having a general fund that could be paid into where we create a tier for each task/project to be addressed or a project which is just for bug bounties, see https://opencollective.com/mautic/projects/rfp-general-fund which we used as a proof of concept. It's kinda clunky and there's no real automation though, we were intending to use it for larger issues where we'd create an RFP (see https://contribute.mautic.org/product-team/request-for-proposals-rfp-process).

We had in the past looked at moving to Rysolv.com but they seem to have pivoted away from focusing on bug bounties and toward recruitment, their offering was nice because the open source project had actually got a % of the fee for each issue resolved.

I've been looking at https://algora.io recently after having an approach from their team as an alternative but am not happy with the steep fees that they charge. https://www.boss.dev could also be an option, perhaps, but I've only recently discovered it.

Happy to chat with you on Slack if you'd like to help us review similar tools which allow people to post bounties on GitHub issues!

**Comment by Fred-DTV** [comment]
> @HrbzxcDev
> 
> I had the same error with composer install, so I went looking what caused this. So I took a look around in the composer.json and changed 1 line:
> 
> Line 143: "generate-assets": "bin/console mautic:assets:generate"
> 
> and I changed it into: "generate-assets": "php bin/console mautic:assets:generate"
> 
> and I did a composer install again and now I got it all installed and working.

@GrandM1961 I had the same issue and was very happy to find your fix, unfortunately on my machine adding the php just resultet in a different error:
```
PHP Fatal error:  Uncaught Symfony\Component\Dotenv\Exception\PathException: Unable to read the "/var/www/html/.env" environment file. in /var/www/html/vendor/symfony/dotenv/Dotenv.php:567

Script php bin/console mautic:assets:generate handling the generate-assets event returned with error code 255
Script @generate-assets was called via post-install-cmd
```

Do you maybe have an idea what this could be?

EDIT: Nevermind I found the issue. My file transfer client didn't transfer the .env file

**Comment by RCheesley** [comment]
Closing this issue, as far as I know it's been resolved in later releases but feel free to request a re-open if not. Thanks!
