### ISSUE TITLE
PHPUnit can't test functional test the second time w/o removing fresh_db.sql

### ISSUE THREAD

**Issue by biozshock** [mautic/mautic#11402]
### Mautic Version

4.4.x series

### PHP version

7.4.26

### What happened?

After merging #11196 i'm no longer able to run tests multiple times, because the `fresh_db.sql` file used here https://github.com/mautic/mautic/blob/5.x/app/bundles/CoreBundle/Test/MauticMysqlTestCase.php#L186 already contains prefix and thus can not use the database tables restored from the SQL file.

### How can we reproduce this issue?

Step 1: Run any functional test that uses mysql database
Step 2: Run any functional test that uses mysql database (second run)

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by escopecz** [comment]
I'm having the same issue. I continued discussing it in https://github.com/mautic/mautic/pull/11196#issuecomment-1231415330 with @mollux

**Comment by mollux** [comment]
@biozshock @escopecz 

I understand the issue, could reproduce it, and want to discuss the options.

The problem is 2 fold:
* the logic in `MauticMysqlTestCase` doesn't check if the prefix corresponds with the one form the test run
*  the prefix is cached in the Symfony container cache.

I personally always start with a clean slate before running tests
This means deleting the `var/cache/test` folder before every run.
This is slower, but ensures a reproducible test environment (well, not completely, as the prefix changes).
This is why I didn't see the issue in the first place.

I see 2 options:
* a fixed prefix instead of random if there is no prefix defined
* an alternative `bootstrap` file (currently `autoload.php`) that deletes `var/cache/test`
```php
<?php
use Symfony\Component\Filesystem\Filesystem;

require dirname(__DIR__).'/vendor/autoload.php';

(new Filesystem())->remove([__DIR__ . '/../var/cache/test']);
```

I'm not sure yet what option I prefer, so any ideas from your side?

**Comment by escopecz** [comment]
@fedys I wonder what are your thoughts on this

**Comment by fedys** [comment]
I don't like the idea of building cache every time I run a test as it will slow down my and others velocity a lot. I am for making the prefix fixed then.

**Comment by escopecz** [comment]
Please review https://github.com/mautic/mautic/pull/11476 which fixes this issue.

**Comment by mollux** [comment]
@escopecz can we split up that fix separately from #11476? 
AFAICT the fixed prefix is not crucial in getting the tests in  #11476, and this fix is also needed anyhow on 4.x to improve DX?

**Comment by escopecz** [comment]
@mollux what commits would you split or removed from the PR?

**Comment by mollux** [comment]
@escopecz o wow, I looked at #11438, my bad, looking at it now
