### ISSUE TITLE
System Adding Multiple Database Lines For The Same Tag "Name"

### ISSUE THREAD

**Issue by edutj** [mautic/mautic#1154]
I found an issue regarding the Tags system. Mautic is adding multiple lines for the same Tag "Name". 
The problematic Tags are added through Campaign Actions.
For example: 
Ideal Situation: Tag 1 that should have only ID 1.
Current Situation: Tag 1 has ID: 1->76.

Consequences identified so far: Lists that are based on tags do not gather all leads with that tag, since these leads have tags (with the same name but) with different IDs.

**Comment by escopecz** [comment]
I can confirm I have also multiple tags in my DB with the same name.

**Comment by edutj** [comment]
Hi. Are there any solutions for this one?

**Comment by escopecz** [comment]
Hi @edutj, since you are asking, could you help with fixing this one? If you're not a developer and you don't have one in your team, you could help the core team with some other tasks they have to do instead of fixing bugs and implementing feature requests like:

- Writing the documentation
- Answering forum questions
- Testing pull requests
- Promoting Mautic

I'd really love to fix more bugs in a day, but I spent most of my time doing tasks described above.

**Comment by alanhartless** [comment]
I think this might be because Mautic "cleans up" tags that do not have any leads associated. I can see where that can cause a problem for IDs saved in places.

https://github.com/mautic/mautic/blob/7099c652d2700d10f7ff9da9e4557780af1378ec/app/bundles/LeadBundle/Controller/AjaxController.php#L490-L490

https://github.com/mautic/mautic/blob/f60706f36436486f348b1a4da97a5392af6dfe24/app/bundles/LeadBundle/Model/LeadModel.php#L1037-L1037

We probably need to prevent that and give some sort of UI to manually delete tags if desired.

**Comment by alanhartless** [comment]
I just realized I totally mis-read the original issue.  I read it as the tags weren't keeping consistent IDs not that there were duplicates. :blush: 

But I can't reproduce this.  I've tried with campaigns, manually, and other means but the tags are never duplicated.  Are there steps I can follow to force this to happen?

**Comment by edutj** [comment]
Alan,
Yes, each duplicate Tag has its own ID. This happens when the system applies (through a campaign) a tag to multiple users at once.
