### ISSUE TITLE
Field based on selected value (feature) makes the order of questions wrong

### ISSUE THREAD

**Issue by gloriateodoro** [mautic/mautic#11558]
### Mautic Version

5.0.x series

### PHP version

7.4.30

### What happened?

A bug happened! 
When adding fields based on a selected value, questions within another question, after saving the form, most of the time the questions are in the wrong order.

### How can we reproduce this issue?

Step 1: create a form
Step 2: create a select field with "yes" or "no" (example)
Step 3: create multiple questions based on a selected value from the field above
Step 4: note that the order of questions will not be the same as the order you defined

### Relevant log output

```shell
Bug screenshot:
https://docs.google.com/document/d/1hAkLJsRa6wT4wMbYjewyLhe9sZA9NG_osRZB2ZWRMk4/edit?usp=sharing
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by mabumusa1** [comment]
Keep opened

**Comment by jos0405** [comment]
The field order is pulled from form_fields.field_order. But wrongly it takes the field order from the "parent question" instead of having a field order that corresponds the creation order of the fields. So you end up having all the subquestions having the same fields order as the parent. Would be even better if the SUB-fields could be drag and drop, but they are not.

**Comment by jos0405** [comment]
BTW - this is also for Mautic 4.4.5
