### ISSUE TITLE
Maxmind GEOiP broken

### ISSUE THREAD

**Issue by quadcom** [mautic/mautic#11680]
### Mautic Version

4.4.x series

### PHP version

8.0

### What browsers are you seeing the problem on?

Chrome

### What happened?

Reconfiguring new 4.4.4 server and Maxmind does not DL GEOiP data files. I've tried all versions from Maxmind and none of them work.

### How can we reproduce this issue?

Step 1: Configure a Maxmind account and create a key. Add that key to the Mautic config and click fetch data. Nothing gets downloaded and there is no message or error returned.

### Relevant log output

```shell
No messages in the log.
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by bartoszpijet** [comment]
Can confirm, it does however work properly by CLI  
`php bin/console mautic:iplookup:download`

**Comment by zeretrelle** [comment]
Confirm.

1) Pressing Update IP Lookup is broken

2) Cronjob doesn't seem to work either. 

I can't even find it in the logs. All other cron jobs are working fine.

3) Running a CLI command php bin/console mautic:iplookup:download  updates the database.

**Comment by kreativekrise** [comment]
Can also confirm, that it does not work when pressing the button.
But the CLI command `php bin/console mautic:iplookup:download` is working.

**Comment by bleg** [comment]
For me on a fresh install

1. Pressing update IP lookup doesn't work
2. Cron doesn't work
3. CLI command php bin/console mautic:iplookup:download 
gives error:
In AbstractLocalDataLookup.php line 100:
Error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 36864 bytes)

**Comment by jos0405** [comment]
Hi, the maxmind does work in recent versions.
@bleg I think you have an envirnmental issue here. Is it a 2GB+ install?
If it still doesn't work feel free to reopen.

**Comment by bleg** [comment]
> Hi, the maxmind does work in recent versions. @bleg I think you have an envirnmental issue here. Is it a 2GB+ install? If it still doesn't work feel free to reopen.

Yes, you are absolutely right. I finally got it to work correctly. For others with similar issues about allowed memory
 on Cpanel:
cPanel -> Select PHP Version -> Options -> Memory Limit. and increase the limit

**Comment by PierreAmmeloot** [comment]
Last e-mail from Maxmind

Subject : We're transitioning to R2 presigned URLs

Hello,

As of Wednesday, May 1, 2024, we will use R2 presigned URLs for all database downloads in order to increase the security and reliability of our services.

This is a potential breaking change. Please ensure that your servers can make HTTPS connections to the following hostname: URL

We recommend confirming the above as early as possible. 

The permalinks from the [download page](#) in your account portal (login required) will not be changing. You will be redirected from those permalinks to the R2 presigned URLs.


For more information, please [review our documentation on directly downloading databases](https://dev.maxmind.com/geoip/updating-databases).

If you download databases manually through the account portal and encounter an error, we recommend checking your firewall and browser security settings before trying again.

**Comment by PierreAmmeloot** [comment]
@RCheesley can you reopen ?
