### ISSUE TITLE
Autowiring should allow us to make services private.

### ISSUE THREAD

**Issue by biozshock** [mautic/mautic#11707]
### Mautic Version

5.0.x series

### PHP version

8.0.x

### What browsers are you seeing the problem on?

Not relevant

### What happened?

After merging #11587 the system should be able to hide it's services.

### How can we reproduce this issue?

Step 1: Change code.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by escopecz** [comment]
All services were set as public since that option was introduced in Symofny 3. See

https://github.com/mautic/mautic/pull/11587/files#diff-608c3bdd0a0d55716c015a6462cd7795239c3f0908cfc57112fad8575af4daefL107

Each bundle can now decide whether the services will be private or public. See for example

https://github.com/mautic/mautic/pull/11587/files#diff-fd1c26c007f60144a2c179150f017c31dc0e68d788f26acc7b25e1821354f805R13

So if you write a plugin, you can write it the right way finally 🎉 

Right now the mentioned PR sets them as public by default because there are still many places where the services are loaded directly from the container instead of using DI. Especially controllers. It is on my todo list to refactor controllers to use DI and then we can set services as private by default in some future major release. It is work for long winter evenings though.

I'm not sure if we need an issue for this. If so, we should create a project for it and create an issue for each bundle to divide into manageable chunks. But all that makes sense only if we'll have developers working on it. Otherwise such issue will just sit here and eventually get closed by our stale bot.

**Comment by biozshock** [comment]
@escopecz I agree that this is a much bigger task. And if you can create a task+subtasks in jira and pin that to the board it would be cool to have it there instead of here.

**Comment by RCheesley** [comment]
@biozshock would you mind creating the issue in Jira? The best place for it is the TPROD project (Product Team). I would recommend that we create a project (it's an issue type) to do with autowiring (or something else if there's a better high level overview title) within the [Mautic 5 initiative](https://mautic.atlassian.net/browse/TPROD-244), and then an epic within which relates to this task. That way you can create tasks and sub-tasks within the Epic.

Use the field 'select parent link' to link up to the relevant initiative or project, and the field 'Epic link' to connect issues with an Epic.

Shout if you get stuck with any of the above!

**Comment by mabumusa1** [comment]
Keep open
