### ISSUE TITLE
smart list problem

### ISSUE THREAD

**Issue by miguelpascual** [mautic/mautic#1173]
I made smart list that work: 
![image](https://cloud.githubusercontent.com/assets/10166840/11206266/2a5d4a2e-8d0e-11e5-8154-91dab714d618.png)
these list get the correct number of leads.

But I create another smart list very similar that dont get any lead 

![image](https://cloud.githubusercontent.com/assets/10166840/11206296/55fcf6e8-8d0e-11e5-89e2-cd71b69f7fdb.png)

**Comment by miguelpascual** [comment]
any idea for made this run?

**Comment by miguelpascual** [comment]
If I do it step by step it seen that works. 
1º all not empty
2º when the list is full add the filter not in these list
but is not very usefull :S

**Comment by RegisScaggiante** [comment]
I have the similar problem.
![screenshot 2015-11-27 21 38 21](https://cloud.githubusercontent.com/assets/15522366/11560448/b579239e-99a7-11e5-8d8d-938426f5ed2f.png)

![screenshot 2015-11-27 21 38 46](https://cloud.githubusercontent.com/assets/15522366/11560459/cdffb2fc-99a7-11e5-94a3-45dfc4857da7.png)

The filter of my smart list is not working. I select the filter that I desire, but when saved, a message appears saying that a value is required. Outa attempt I did was use the "including" instead of "equals". In this way the filter is created, but not adequately filters the leads. They appear only 6 leads the list, and I know it has a lot more leads that match this filtering option.

**Comment by alanhartless** [comment]
@miguelpascual I'm not sure I'm understanding what this means:
```
If I do it step by step it seen that works. 
1º all not empty
2º when the list is full add the filter: not in these list
but is not very usefull :S```

Could you reword that for me? I'm also curious if https://github.com/mautic/mautic/pull/1193 will fix whatever the issue may be?

@RegisScaggiante I think that is a cosmetic issue that happens when you have include/exclude then change it to equals. As a temporary workaround, when you get that message could you set the value again and save? Does it go through?

**Comment by miguelpascual** [comment]
Sorry for my english I'm working on it but....

"If I do it step by step" I edit the list and add one only condition (the one less restrictive) when the list have the correct amount of leads I add another condition and that seen that applies correctly both conditions. 

The list when I tested have 50.000 leads

**Comment by RegisScaggiante** [comment]
He thought most appropriate solution to the problem I had was the development of the suggestions proposed in this issue.
https://github.com/mautic/mautic/issues/1268

For a simpler solution for now, I got the following alternative:
I linked the checkbox form field to a "text" type core field instead of using a "select" type core field.
![1](https://cloud.githubusercontent.com/assets/15522366/11956273/201752d2-a8a0-11e5-8775-af917aefc14b.png)

In the filter of the Smart List I used the "like" and I wrote exactly the checkbox option form.
![2](https://cloud.githubusercontent.com/assets/15522366/11956297/4f72bf3a-a8a0-11e5-8583-bf20df32cc90.png)

![5](https://cloud.githubusercontent.com/assets/15522366/11956315/71497ac2-a8a0-11e5-86d7-a95d02f05eb3.png)

It worked perfectly so far.

**Comment by miguelpascual** [comment]
One Question...

If the user changes the selection and now he doesn't want "Grupos". When the user removes the checkbox the smart list is not affected, is it?

If this is the case, we can execute one remove from lists just when the user sends the form. 

I'll try it.
Miguel
