### ISSUE TITLE
REPORTING | Only leads with points are shown

### ISSUE THREAD

**Issue by vexersa** [mautic/mautic#1175]
When attempting to view leads in the reports section, only leads with points assigned to them are displayed. 

Specific use scenario: 
I am attempting to migrate from one Mautic instance to another. I have a "bulk" amount of leads which need to be exported but have no points assigned to them as they were imported from another provider's CSV file. When attempting to "find" these leads to export in the Report section there is currently no mechanism to do so, and so no way of exporting these leads. 

It would be great if there was a way to view ALL leads within the Mautic instance regardless of whether they had any qualifying criteria, if anything for the purpose of exporting those leads.

**Comment by npracht** [comment]
Hi,

You should go on *Leads --> Manage Leads*, here you see all your leads. You can select them but you don't have any export button.
![capture d ecran 2015-11-18 a 12 33 10](https://cloud.githubusercontent.com/assets/14075239/11240144/9ed3ad84-8df0-11e5-9a4b-7cb7999a9b51.png)

* It would be very efficient to have here an **Export (or download) button** close the **Import button**
* I don't know if you select the page or all the contact (filtered or not, not matter). I've open a topic for that issue here: [#1172](https://github.com/mautic/mautic/issues/1172)

N.

**Comment by alanhartless** [comment]
Import and export is planned for 1.3.  #1259.

Thanks,
Alan

**Comment by escopecz** [comment]
I'll reopen this issue as the original issue was 

> Only leads with points are shown

which I can reproduce and consider it a bug.

**Comment by escopecz** [comment]
Ok, I looked at the code so I could fix the issue. From the code I found out that there are 2 possible "contexts" for the lead bundle:

- *lead points*
- *leads*

Lead points will show only points (and lead info) and this is shown by default. The leads context can be selected if you edit the "Leads and Points" report (or create a new one). This context will show you all leads.
