### ISSUE TITLE
Convert Amazon SES transport to use the HTTP API protocol instead of SMTP

### ISSUE THREAD

**Issue by gpassarelli** [mautic/mautic#1178]
Hey guys, so me and ehiller1  were talking about the integration between Mautic and Amazon SES, and we think the perfomance is not the best. 

So we were wondering if this slow performance is only with Amazon SES, or with other third party emails sender as well. Right now, the number I’ve got it: Mautic can send **~250 emails per minute.** with Amazon SES, is this the expected perfomance for other services as well or it is being this slow only with Amazon SES? 

We were thinking about improving the integration with Amazon SES by API, instead of SMTP, this way the perfomance should increase. Right?

**Comment by alanhartless** [comment]
Each email sent through SES is making a SMTP connection so that will slow things down.  Using the API will likely see speed increase for email list sends since you can batch tokenized emails to Amazon (if they support it and which is what the Mandrill transport does right now).  (Tokenized emails are not supported when Mautic is configured to queue email to the filesystem due to the way Swiftmailer/Symfony writes each message to the filesystem). If you are using the queue to filesystem setting, the other thing to ensure that you aren't configuring the throttle settings inappropriately which can slow things down.  

Campaigns are currently designed to handle one action at a time since any given lead can be at any given point in the campaign.  So batching for campaigns gets tricky and would only make sense for kicking off campaigns. But some ground work would have to be done to get Mautic to support campaign event batching.

**Comment by ptcc** [comment]
:+1:

**Comment by maxitromer** [comment]
Hi!

I'm a new user here in Mautic.

I have installed a new copy of this system in my hosting and I integrate it with Amazon SES.

I need to start working with a 55k email list of suscribers.

My situation is that Mautic has a very slow speed on sending emails. (1 per second aprox) for a total of 15 hours to send 1 email to this list.

And seen a video from Amazon I think that this (the HTTP API Protocol) will be the solution for this problem.

This is the video where the Amazon people explain how to scale (and speed up) your sendings with this:

https://www.youtube.com/watch?v=BpuqLT1UGVM

I need to know if this feature is already added to Mautic or if you plan to do it ?

I'm not an experimented coder (I just code small and simple things) but maybe I can work with someone and help to make this work.

**Comment by wittwerch** [comment]
Please see my comment in #1740

**Comment by alanhartless** [comment]
Merging this into #1740
