### ISSUE TITLE
Contact field is using Yesterday even when a date has been entered in the field

### ISSUE THREAD

**Issue by theodorusvlads** [mautic/mautic#11962]
### Mautic Version

4.3.x series

### PHP version

7.4

### What happened?

problem with contact fields value
![campaign](https://user-images.githubusercontent.com/102359795/218365603-f60189eb-be6f-4ffb-91da-d97b9342455a.png)

### How can we reproduce this issue?

I have a problem with the contact field value, where it continues even though I have replaced the variable with the previous date. and it will always send dwc to users who are on the segment. my cronjob is till run normaly

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by jos0405** [comment]
Could you plz change the name of this bugreport?

**Comment by RCheesley** [comment]
Hi @theodorusvlads I think what you are seeing is actually the expected behaviour. If you have 'yesterday' in that field, I believe the date will be set to yesterday.

Maybe it would be better to instead set the date dynamically (eg with a campaign?) when the action takes place - for example when they hit the post-login page use that as a page hit action and then have the campaign set the contact field date to today?
