### ISSUE TITLE
Check for unique identifier conflicts when creating/updating leads via tracking pixel (same as form submission behavior)

### ISSUE THREAD

**Issue by ptcc** [mautic/mautic#1199]
I'm having an issue when I use the tracking pixel with the email in the query:
If the user already has a tracking cookie, and then someone else uses the same browser with a diferent email, both leads will be merged.
I think that if emails do not match then a new lead should be created. (it seems to be just a priority issue, where the cookie is taking precedence over the email to tell if it is a new lead or the same lead...)

**Comment by alanhartless** [comment]
We've had the exact opposite request that if a user is tracked by cookie, their email should be updated with something different because it's assumed they are the same lead.  I'm with you though that if an email is in conflict, it should be recorded as a different lead which is the current behavior for forms. Forms will create a new lead if a "unique identifier" field is in conflict with the currently tracked lead. I think the tracking pixel should have the same behavior. 

Do you have experience with other MA products? What did they do for this scenario?

**Comment by ptcc** [comment]
I don't know how others are doing it... still i think we should do it at least in a coherent way... having the same behavior with forms and with tracking pixel.

**Comment by alanhartless** [comment]
This should now be the case in the latest versions of Mautic.
