### ISSUE TITLE
Customize contact list columns

### ISSUE THREAD

**Issue by lance-spurgeon** [mautic/mautic#120]
It would be nice if I could change what i see in my Leads List as a default view i.e.: if I wanted to see first name, phone, email, score, double optin, twitter I could change to my default view

**Comment by skynet** [comment]
Is this in work, somehow?

**Comment by cougar2009** [comment]
Came here looking for the same.

**Comment by Eckin0x** [comment]
+1, this feature would be great

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._

**Comment by npracht** [comment]
hi @lance-spurgeon @skynet @cougar2009 @Eckin0x !
Feature is there, please give a test !

https://github.com/mautic/mautic/pull/7511

**Comment by sellpahomefast** [comment]
> hi @lance-spurgeon @skynet @cougar2009 @Eckin0x !
> Feature is there, please give a test !
> 
> #7511

Hello.  I'm not sure where to post this, but since this request is nearly identical to PR #7511, I'm adding here.  Under Channels->Emails, it would be great if we could "Customize the Emails List Columns" so we could the Subject line.  It's difficult to keep track of various emails in a drip sequence.

**Comment by RCheesley** [comment]
We are pending the Travis issues being addressed in #7511 after which it will require two tests to be considered for merging - if we want to get it merged into 3.1 this needs to be done by 16th August 2020.

**Comment by christopheg** [comment]
is there any chance to add a column with the applied 'tags'?
