### ISSUE TITLE
Full installation import/backup

### ISSUE THREAD

**Issue by alanhartless** [mautic/mautic#1259]
Feature to create a complete export of data to be imported into another Mautic.

**Comment by bloodlynx** [comment]
This would be a really nice feature! Can this be expected to be in an release any time soon?

**Comment by sujaypawar** [comment]
+1

A plugin for automatic scheduled backups is really very essential.

**Comment by vanko69** [comment]
+1

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
