### ISSUE TITLE
Form email field label class not represented in HTML

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#12625]
### Mautic Version

5.0.x series

### PHP version

8

### What browsers are you seeing the problem on?

Not relevant

### What happened?

When I add classes on the Email field, these are not being pulled through into the form when it's previewed:

![screenshot-8080-mautic-mautic-73cmi7ovu7v ws-eu102 gitpod io-2023 08 04-15_24_13](https://github.com/mautic/mautic/assets/2930593/61377f5c-6185-46eb-a708-0d9949ad4f6d)

![screenshot-nimbusweb me-2023 08 04-15_25_17](https://github.com/mautic/mautic/assets/2930593/77077351-a25d-4724-99a6-bdd209d04504)

### How can we reproduce this issue?

Step 1: Create a form
Step 2: Add a field of type Email
Step 3: Add class names in the Attributes tab
Step 4: Check the rendered form and inspect the classes being used for the relevant element

### Relevant log output

```shell
N/A
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
So, this is new in Mautic 5, however I am not convinced that we are doing it right in Mautic 4 - maybe my CSS knowledge is hazy (most likely!).

I would have thought that the class should be within the class in the format of `class="existingclass extraclassfromformfield"` but it seems we render it `extraclassfromformfield class="existingclass"` in the 4.4 branch 🤔 .

![screenshot-nimbusweb me-2023 08 04-15_47_56](https://github.com/mautic/mautic/assets/2930593/9e685d64-6a96-4c85-b5bc-a4e9ec2d7cc6)

I don't know what is the expected behaviour at this point and it's a long while since I have been in the weeds with CSS in the front end so I will leave this to the experts to decide what should be the correct behaviour!

**Comment by escopecz** [comment]
It is working correctly in M4. It's not adding just CSS classes. It can add any HTML attribute. So if you want to add a class you should input `class="the_class"`.

**Comment by mollux** [comment]
@RCheesley 

I don't see the issue here

as @escopecz mentioned, the attributes should contain the full atributes, and are not limited to classes.

See screenshots below where I add a background color with an inline style:

edit form
<img width="688" alt="Screenshot 2023-10-31 at 05 41 54" src="https://github.com/mautic/mautic/assets/3983285/c9033b8e-ce49-457f-9a44-a2e566833196">

overview of fields
<img width="953" alt="Screenshot 2023-10-31 at 05 42 04" src="https://github.com/mautic/mautic/assets/3983285/e03695f9-27c6-421f-ad20-4535afbe4289">

preview form
<img width="656" alt="Screenshot 2023-10-31 at 05 42 16" src="https://github.com/mautic/mautic/assets/3983285/37576cb9-4245-4c53-8a39-cff841b9afbe">
