### ISSUE TITLE
[bug] Mailchimp authorisation failing with error Authorization failed with the error message, 'SSL certificate problem: unable to get local issuer certificate'

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#1274]
I needed to re-authorise my Mailchimp application as it seemed to have dropped connection.  Initially clicking re-authorise gave me the error:

Authorization failed with the error message, 'SSL certificate problem: unable to get local issuer certificate'

Things I've tried to resolve this include:
- Checking settings in Mautic and Mailchimp
- Creating a new app in Mailchimp and updating details in Mautic

None of these seem to be working, I still can't get the Mailchimp integration to successfully connect.

**Comment by escopecz** [comment]
Hello Ruth, I don't think the SSL certificate problem is a Mautic issue. I googled around and found this:

http://redwebturtle.blogspot.nl/2013/09/mailchimp-api-v20-ssl-error-solution.html

Maybe give it a try.

Also, Mautic 1.2.3 will come with API authorization to Mailchimp instead of OAuth authorization (https://github.com/mautic/mautic/pull/1184) so it might fix the certificate problem as well. I'll close this issue. Feel free to re-open it if you think otherwise.

**Comment by escopecz** [comment]
This issue seems to be still there.

**Comment by RCheesley** [comment]
So far as I am aware this is not an issue any more.
