### ISSUE TITLE
Logfiles should be called .log instead of .php

### ISSUE THREAD

**Issue by Tie-fighter** [mautic/mautic#12872]
### Mautic Version

5.0.x series

### PHP version

8.0.30

### What happened?

Logfiles are called (mautic_)prod-YYYY-MM-DD.php

I feel like .log would be more appropriate.

### How can we reproduce this issue?

Step 1: Look at mautic/var/logs/

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by martoboto** [comment]
This is very true logs should not be executable, its dangerous and there is no reason for it.

**Comment by escopecz** [comment]
This was done for security reasons. It is way better to execute a PHP file with logs (text) as it fails right away due to a syntax error. It's way worse to have a log file content displayed to a hacker.

You can always configure it as you need. An example:
```php
// app/config/config_overrride.php

$definition =
     new \Symfony\Component\DependencyInjection\Definition(
           ...
     );
    $definition->addMethodCall('setFormatter', [new Reference('mautic.monolog.fulltrace.formatter')]);
    $container->setDefinition('monolog.custom.handler', $definition);
```
Monolog docs: https://github.com/Seldaek/monolog?tab=readme-ov-file#monolog---logging-for-php-

**Comment by martoboto** [comment]
Seems like it would be smarter to move the logs out of the public directory if we don't want them public rather than making them executable. By making them executable and public you are fixing a problem with a problem. Having executable logs on its own is a bad idea but then making it possible for anyone to execute those logs, double bad idea.

**Comment by escopecz** [comment]
With M5 we are suggesting to install Mautic via Composer which creates better structure and as far as I know it will have logs outside of the public dir. But Mautic 5 can still be installed the old way. Perhaps we can get rid of it in M6.

Storing logs in the filesystem is a bad idea no matter what format. They should be pushed to some system where you can easily filter them, build monitoring and reports. So this is just a poor man's implementation. I suggest to configure the logs exactly as you need them as I suggested in the previous comment.
