### ISSUE TITLE
Update lists with a click

### ISSUE THREAD

**Issue by ahansson89** [mautic/mautic#1291]

**Comment by alanhartless** [comment]
The tricky part with this is handling a potentially huge task via the web frontend.  For example, trying to build a list of 2 million leads via a batched ajax'ed process would take forever.  And it couldn't be done in a single web request since PHP would for sure timeout.

For this to work, we need a worker/task queue system where Mautic registers a task when a button is clicked in the.  Then a cron job scheduled at intervals handles the task outside the web request. Long term we'd like to see this but I'm not sure how quickly it'll happen unless someone from the community devotes resources to it.

**Comment by ahansson89** [comment]
That sounds like a good way to do it. Say we create a cron task every 10 minutes that will run scheduled tasks like the list that the user wants to update. For me it is just an annoyance factor that I need to go and do it with a command.

Alternatively I could just run the cron on update lists for every 10 minutes, but that would update all of my lists which I may not want.

**Comment by that0n3guy** [comment]
So maybe you just need the ability to update specific lists from cron?

**Comment by escopecz** [comment]
You can update specific segment with `app/console mautic:segments:update -i ID`. Replace `ID` with the ID number of the segment.
