### ISSUE TITLE
Marketplace search bar doesn't work

### ISSUE THREAD

**Issue by andersonjeccel** [mautic/mautic#13134]
null

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by mallezie** [comment]
Checked this, this is actually because the Marketplace is still in beta. While in the beta version there is a limited list of packages in the list, and that indeed does not take search into account. 
When the allowlist is gone, the search value is properly passed to the packagist query and filters it. 
I would say to not fix this, will be gone when marketplace is out of beta anyway.

**Comment by andersonjeccel** [comment]
@mallezie Should we close this issue?

**Comment by mallezie** [comment]
I would say yes.
