### ISSUE TITLE
Missing English translation: mautic.mauticSocial.permissions.tweets

### ISSUE THREAD

**Issue by matbcvo** [mautic/mautic#13286]
### Mautic Version

5.0.x series

### PHP version

8.1.27

### What browsers are you seeing the problem on?

Chrome

### What happened?

mautic.mauticSocial.permissions.tweets does not have English translation.

### How can we reproduce this issue?

Step 1: Settings
Step 2: Roles
Step 3: New role
Step 4: Permissions tab
Step 5: Social Permissions

### Relevant log output

![image](https://github.com/mautic/mautic/assets/1006437/baf53598-4bd3-4d13-8433-bb4412bb2b0b)

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by RCheesley** [comment]
Thanks for reporting this @matbcvo- would you be up for making a PR to address that?

I think that the issue is in this file: https://github.com/mautic/mautic/blob/bf3794331bf7c5d349de62c12d67df84f81a7ed0/plugins/MauticSocialBundle/Translations/en_US/messages.ini#L82 and it seems that the language string 'mautic.mauticSocial.permissions.tweet' doesn't match what the code is looking for - 'mautic.mauticSocial.permissions.tweets'. Personally I'd add the 's' to make it plural, and change the actual language string to 'Tweets - User has access to' at the same time as it reads better, in my opinion.

Please fix this in the 5.1 branch, let me know if you need any guidance with that.

**Comment by matbcvo** [comment]
Sure, I'll work on that.
