### ISSUE TITLE
Error opening/editing forms: Argument #4 ($properties) must be of type array, null given

### ISSUE THREAD

**Issue by pjrobertson** [mautic/mautic#13652]
### Mautic Version

5.0.x series

### Way of installing

I downloaded a release from https://www.mautic.org/mautic-releases

### PHP version

8.0.30

### What browsers are you seeing the problem on?

Not relevant

### What happened?

Upgraded from 4.x to 5.0.4. Tried to open up an existing form and also tried creating a new form. A 500 error occurred, with the following info in the console:

```
[2024-04-15T15:27:43.858030+00:00] mautic.CRITICAL: Uncaught PHP Exception TypeError:
 "Mautic\FormBundle\Crate\FieldCrate::__construct(): Argument #4 ($properties) must be of type array, null given, 
called in /mautic/public/app/bundles/LeadBundle/EventListener/FormSubscriber.php on line 133" at
 /mautic/public/app/bundles/FormBundle/Crate/FieldCrate.php line 14 {"exception":"[object] (TypeError(code: 0): 
Mautic\\FormBundle\\Crate\\FieldCrate::__construct(): Argument #4 ($properties) must be of type array, 
null given, called in /mautic/public/app/bundles/LeadBundle/EventListener/FormSubscriber.php on line 133 at
 /mautic/public/app/bundles/FormBundle/Crate/FieldCrate.php:14)"} {"hostname":"example.com","pid":802}
```

### How can we reproduce this issue?

Step 1: Upgrade to 5.0.4
Step 2: Open up an existing form OR create a new form then go to the 'fields' tab and try to add a new field (e.g. 'email)
Step 3: Note the 500 error in the console, go to the backend and see the logs as above.

NOTE: I managed to 'fix' this problem by modifying `public/app/bundles/LeadBundle/EventListener/FormSubscriber.php:L133` as follows:

```php
$field->getProperties() === null ? [] $field->getProperties()
```

I don't know if this is a 'good' way of fixing the issue.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by dsp76** [comment]
@pjrobertson it looks like the update and/or migration had an error. Forms editing works usually fine in 5.0.4. Could you please try to see in the Mautic forum, if other users had the same experience when updating? Please then also add details on how you upgraded in the forum post, e.g. with Mautic CLI commands or via composer... 

Please also try to do a "console mautic:assets:generate" and refresh the cache.

**Comment by pjrobertson** [comment]
1. Nothing in the forum/other GH issues regarding this, I previously checked but have just checked again.
I did have a problem during the update, which was the same as [this issue](https://forum.mautic.org/t/issues-with-migration-after-updating-from-4-4-to-5-0-2/30758/5) - I followed the steps there and ran the following SQL on my database: `update emails set headers='[]' where headers='';`  - but this table is completely unrelated to the forms

2. I updated using the CLI `console mautic:update:apply` and `console mautic:update:apply --finish` - when the error above ocurred I had to rerun the `--finish` command

3. Regenerating assets and clearing cache did nothing.

I suggest integrating my above fix, the worst case it takes another milisecond in script execution when editing a form. Best case is it fixes a bug. I agree that the right way to solve this would be to find the table in the DB where the `properties=null` and change to `properties=[]` but this fix is easier.

**Comment by RCheesley** [comment]
@pjrobertson in the upgrade process, did you run the database migrations at all?

**Comment by pjrobertson** [comment]
When I faced the issue above [see here](https://github.com/mautic/mautic/issues/13652#issuecomment-2067875126) I did try to run the migrations manually, which subsequently failed. I then fixed the issue manually as explained above with `update emails set headers='[]' where headers='';`

**Comment by RCheesley** [comment]
Closing this issue as it seems that there's an issue with the migration which can be resolved with a workaround. Thanks folks!

**Comment by alexanderjsluiter** [comment]
Sorry to hop in so late here, but this problem just surfaced on a large deployment of mine. This particular instance has been in deployment since around 2017 and has had several failed migrations throughout the years. Earlier this year, I pulled it offline and ran every change required to bring it up to a "vanilla" Mautic installation. It required pulling down almost every foreign key constraint and re-applying them after major table alters. The database is over 100GB...yes...of text...it took forever. The workaround provided above works, but you still have database schema issues. My users could not access the edit pages of any forms or manage fields. Symfony is expecting that properties never be NULL, but your database is returning NULL on at least one field's properties. This will only lead to problems upon every upgrade.

@pjrobertson Here's your path forward:
Find out which fields have NULL in their properties. If you use a database prefix, check the table name.
`SELECT properties `lead_fields` WHERE properties = 'N;'`
You should see at least one row returned where the properties are the PHP serialized version of NULL (N;).

The fix:
`UPDATE `lead_fields` SET properties = 'a:0:{}' WHERE properties = 'N;';`
"a:0:{}" is PHP serialized format for an empty array.
