### ISSUE TITLE
API mobile search does not work!

### ISSUE THREAD

**Issue by Aclavelar** [mautic/mautic#13653]
### Mautic Version

4.4.x series

### Way of installing

I downloaded a release from https://www.mautic.org/mautic-releases

### PHP version

8.20

### What browsers are you seeing the problem on?

Chrome

### What happened?

When I try to search a contact by a moblie number, I get empty result. The API search works for names, but not for mobile number. This is very important, specially for the ones that use Mautic integrated with Whatsapp.

### How can we reproduce this issue?

Step 1:  GET   https://mautic.domain.com/api/contacts?search=+123456789

### Relevant log output

```shell
[
{
"total": 
"0",
"contacts": 
{
}
}
]
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by dsp76** [comment]
Hi @Aclavelar ... I gave it a quick try and can confirm, that "search" doesn't return records for phone numbers. It works for some fields, but not all. Also "Adress line" or other manually added test fields will not be searched. Not sure if it ever worked, because then it would be a feature request to improve the "search" functionality.

Could I ask you to help finalizing the description? It would be helpful to add more or less complete list of fields that don't work to help developers.

Meanwhile I have a workaround: Use the "where" option. Its described in the dev documentation - see "Advanced filtering": https://developer.mautic.org/#list-contacts

Example: GET /contacts?where%5B0%5D%5Bcol%5D=mobile&where%5B0%5D%5Bexpr%5D=in&where%5B0%5D%5Bval%5D=%2B491234567890

Please continue the discussion in the forum to get others to join. Then this bug should be more detailed here.

**Comment by Aclavelar** [comment]
Hi Dirk,

Thanks for checking it. Having the Search option working for mobile numbers would be very helpful, specially for the fact that many people are using Mautic for doing WhatsApp campaign. When integrating a chat system like Chatwoot to Mautic, you need to make sure that the lead does not exist, before creating a new lead into Mautic. The best way to do so would be by checking the mobile number recorded in Mautic (once Mautic Id is not known by Chatwoot).

**Comment by dsp76** [comment]
OK, maybe open a feature request for that? As said, it would help if you could contribute more details. Please read my comment before.

**Comment by escopecz** [comment]
Yep, this never worked and never will. The search is already looking into too many fields and when you get 1M+ contacts it gets very slow because of it.

What can be implemented is the special phone search with the prefix. Like we have the `email:` prefix to search just in the email column without searching in names and companies and other fields. So there can be `phone:` search prefix for that. But it will work only for the default phone field. How about mobile? Or a custom phone field? It's better to just use the advanced conditions that @dsp76 mentioned above. It's the same API request, just different syntax and there is no need for additional feature requests.
