### ISSUE TITLE
Update from v4.4.11 to v4.4.12

### ISSUE THREAD

**Issue by acremonezi** [mautic/mautic#13762]
### Mautic Version

4.4.x series

### Way of installing

I'm using a Docker image from https://hub.docker.com/r/mautic/mautic

### PHP version

7.4.33

### What browsers are you seeing the problem on?

Chrome

### What happened?

From Mautic v4.4.11:

It does not give me the option to update from v4.4.11 to v4.4.12.

### How can we reproduce this issue?

From a Mautic v4.4.11 installation
after this command: `php bin/console mautic:update:find`
I received this message: `Version 5.0.4 is available to updated`
It suposed to offer me to update to v4.4.12 instead of v5.0.4

### Relevant log output

info: updating this way bellow works very well:
php bin/console mautic:update:apply --update-package=4.4.12-update.zip

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by matbcvo** [comment]
Can confirm, on 4.4.11 it offers 5.0.4 instead of 4.4.12

**Comment by RCheesley** [comment]
Hi folks, I've chatted about this with the core team. This is because it's looking for 'latest' and the PHP version requirement is the same at this time between 4.11.12 and 5.0.4 - so it's seeing that as the upgrade path you should take. 

It's not something at this time we can fix without some fairly major retooling, and it's only become a problem now because of the cross-over in PHP versions and the fact that when this happened in the past, the earlier version of Mautic did not use GitHub releases for checking availability and compatibility of releases.

Therefore, at this time I'd recommend you update by specifying the specific version, as provided in the workaround above (and hopefully plan to get up to 5.x soon, as you're missing a _lot_ of bug fixes and features!)

We will need to update the docs to advise people how to update when they do not want to go up to the latest stable release outside their current major branch. cc @favour-chibueze @fakela on this as it's something the education team will need to pick up. Might be a nice 'good first issue' if we can point people in the right direction - if anyone would like to get involved and contribute that update, the docs are at https://github.com/mautic/user-documentation.
