### ISSUE TITLE
Lead history getting mixed with logged user history

### ISSUE THREAD

**Issue by ptcc** [mautic/mautic#1395]
When I click on a sent email on the lead history to view it, my history gets merged into that lead's history.

**Comment by escopecz** [comment]
The question is if that is bad. If you send an email to a lead and click on a link in it, you think that Mautic shouldn't think that you (whether you are admin or not) are the lead who it send the email to? Because if the link goes to a website without Mautic tracking pixel, Mautic has no way how to recognize you as an admin.

**Comment by ptcc** [comment]
whats the point of having a lead history if i cannot view an email to check if was correctly sent then?
I did not click any link on the email itself, I clicked only on a link inside mautic's interface... 
i'm talking about something inside mautic: mauticURL/email/view/someID
Is it not possible to check if i'm a logged user and ignore the email pixel?

**Comment by escopecz** [comment]
I thought you were testing the email sends and clicked on a link in a sent email. It should work like you wrote. I tested it and my visit was also registered. I'll mark this as a bug.

**Comment by dongilbert** [comment]
I agree. If the admin user is logged in, and clicks the email link within the lead history to visit the web view page, the visit should not be logged into the user history. It dilutes the history.

**Comment by dongilbert** [comment]
@dbhurley Please confirm

**Comment by dongilbert** [comment]
@escopecz Please test #1445
