### ISSUE TITLE
Feature Request - grid alignment & copy item for campaign building

### ISSUE THREAD

**Issue by 750430** [mautic/mautic#1406]
Hi,

I'm building another campaign - it's a fair size and I've aligned it by eye, but it's not as neatly laid out as it could be.

I'd like to be able to print or export the view of the campaign so I can share with with my client / document it, if an option to export could be added, that'd be brilliant! (discussed with DH in the Slack #support channel)

Also, given the complexities of having campaign decisions or actions accept multiple inputs at any stage, would it be at all possible to be able to duplicate a campaign item - at present (mid campaign build) I have 28 items at the campaign flow end points which are exactly the same, so being able to select / group items for duplication within the campaign would be incredible!

thanks!

**Comment by JoshFialkoff** [comment]
This would be a great feature enhancement! Is there any news on this?

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
