### ISSUE TITLE
Anonymous contacts spam from exploit-crawlers & more

### ISSUE THREAD

**Issue by AlbertMN** [mautic/mautic#14074]
### Mautic Series

5.1.x series

### Mautic installed version

5.1.0

### Way of installing

I installed with composer using https://github.com/mautic/recommended-project

### PHP version

8.2

### What happened?

Somehow anonymous contacts are being created, possibly by crawlers, hitting random & non-existing endpoints, yet still getting a contact created, though they hit the **Mautic admin** URL. This happens without tracking script enabled, and with all tracking settings disabled in the settings.

This topic on the Mautic forum includes more in-depth details; https://forum.mautic.org/t/lots-of-anonymous-contacts-appearing/33100/1

### How can we reproduce this issue?

I believe all you have to do, is have a Mautic 5 site.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by RCheesley** [comment]
Hi there!

Mautic is by design set up to track anonymous contacts, read more about that in our docs [here](https://docs.mautic.org/en/5.x/contacts/contacts_overview.html#visitors-formerly-anonymous-leads).

Furthermore, there's an option to **not** track on 404 pages which you can turn **on**, find the PR which implemented that [here](https://github.com/mautic/mautic/pull/7614), and the documentation about it [here](https://docs.mautic.org/en/5.x/configuration/settings.html#mautic-tracking-settings).

> Do Not Track 404 error for anonymous Contacts - Select **Yes** to **not** track page hits on any 404 error page tracked by the tracking code. This option helps prevent filling your logs with hits from bots.

Note: You need to set that option to YES, to **not** track page hits which are coming from a page with a 404 response. cc @andersonjeccel as this is confusing for the user.
