### ISSUE TITLE
Padding changes after editing button text

### ISSUE THREAD

**Issue by Semantic8170** [mautic/mautic#14140]
### Mautic Series

5.1.x series

### Mautic installed version

5.1.1

### Way of installing

I'm using a Docker image from https://hub.docker.com/r/mautic/mautic

### PHP version

8.1.29

### What browsers are you seeing the problem on?

Firefox

### What happened?

Buttons change their padding after changing the text. I expect it to stay the same.
When editing emails, this only affects the editor. When editing landing pages, it also affects the end result.

Button without changes on the left, button with changed text on the right:
![grafik](https://github.com/user-attachments/assets/1a92fec7-6f25-443c-ba13-3f3d78f2c92e)

You can also find another screenshot here: https://forum.mautic.org/t/button-padding-in-the-editor-is-confusing/33059

### How can we reproduce this issue?

Step 1: Create a new landing page.
Step 2: Insert a button.
Step 3: Double click, change text and save.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by RCheesley** [comment]
Thanks for the bug report @Semantic8170 - hopefully a quick fix!

**Comment by LordRembo** [comment]
@Semantic8170 Both for the mailbuilder: in what theme are you experiencing this? Or if it is a custom one: is it built in MJML or HTML? I can't seem to be able to replicate your issue when trying it myself.

**Comment by LordRembo** [comment]
@Semantic8170 Okay, I found the cause and have a suggestion for a temporary fix.
Changing text is using CKE5, which automatically wraps text within `<p>`-tags and those have margins. That was not the case in CKE4 and I'm not sure this is behaviour that is easily turned off but it is worth investigating of course.
Some themes probably have a reset for p-tag padding, so in some emails that gets reset when saving the mail, but other themes (like the generic landing page one) don't have that, so it stays bigger when saved.

Until a proper fix is added to Mautic, I suggest you add a reset in your themes, for nested p-tags. Something like:
```
.button p { margin-bottom: 0; margin-top: 0; }
```

**Comment by LordRembo** [comment]
A note for whoever digs into this to fix, I'd suggest looking for a way to override CKE in the Button block type, and use a plain text input instead. While inline editing is [a thing CKE5 is trying to implement](https://github.com/ckeditor/ckeditor5/issues/762#issuecomment-1964458982), doesn't look like it's gonna happen anytime soon or not for use with inline tags like `<a>`.

**Comment by andersonjeccel** [comment]
@LordRembo @RCheesley 
My PR #14155 includes themes that have this issue fixed for the editor, preview and most email clients as result

But since the P tags are still wrapping the content, contacts receiving emails through Outlook for Windows will have all buttons buggy
The way to fix what people using Outlook for Windows receive is making CKEditor not add those tags, because adding styles only seem not to solve the issue or be enough

**Comment by LordRembo** [comment]
Yeah I know, that's what I said in the last comment. The problem is that CKE adds those p-tags when editing the button. You can't disable that. The fix would be an override for the button Block Type, in the grapesjs-mautic-preset submodule or override it in the GrapesJS plugin itself. [I did some investigation into it](https://github.com/GrapesJS/grapesjs/discussions/6179) but haven't had time to try it out yet. 
So anyone who wants to dig into GrapesJS, feel free to tackle that.

**Comment by andersonjeccel** [comment]
@LordRembo Edited my comment to make clear that I'm talking about how using theme styling seems to produce no results for the specific email client I was testing for, didn't meant to use what you said as new info, just answering how testing your suggestion went :)

**Comment by LordRembo** [comment]
I made a proof of concept for replacing the button modal with a custom input instead of the CKEditor. If anyone else takes this on, it might be of help as I don't know when I'll have time to do more. (mostly based on stellar work @abhisekmazumdar is doing):
[See this commit](https://github.com/mautic/mautic/commit/095dd1f1ca79b89a719d365b796bdd109f0982b4)

**Comment by patrykgruszka** [comment]
Nice work, @LordRembo. I was struggling with overriding the block config.

I'm also exploring the possibility of replacing the CKE plugin for GrapesJS with a custom initializer for Mautic. I will publish the PoC when it's ready.

**Comment by patrykgruszka** [comment]
Here is the draft of my concept - #14258. The button editing should now work properly, and the CKEditor initialization can be easily changed in the new class. I think there will be more cases we'll need to adjust in the future.

**Comment by patrykgruszka** [comment]
The fix is ready to test: https://github.com/mautic/mautic/pull/14258

**Comment by patrykgruszka** [comment]
We need one more test confirmation to get this fixed: #14258. Come on

**Comment by LordRembo** [comment]
This issue can be closed, as the related PR was merged
