### ISSUE TITLE
E2E test failure on 5.x branch

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#14174]
### Mautic Series

5.1.x series

### Mautic installed version

5.1

### Way of installing

I cloned the Mautic repo (not recommended or supported)

### PHP version

8

### What happened?

It looks like we have a test failure on the 5.x branch in the End to End Test Suite:

![screenshot-github_com-2024_10_06-13_03_14](https://github.com/user-attachments/assets/3c0a00df-15f9-4c18-9b13-128fd81e016b)

This is causing other PRs to be blocked, as they fail the test.

### How can we reproduce this issue?

Step 1: Check the 5.x branch GitHub Action runs e.g. https://github.com/mautic/mautic/actions/runs/11201214177/job/31135868513

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by andersonjeccel** [comment]
The issue is the way tests were created

They depend on acting like the user to click on things etc, so they're also dependant on waiting for things to load, for example

Many errors happen because the tests expect to run in a top-tier ultra fast hardware, but Mautic not always load like that

You can see it because retriggering the test sometimes make them pass
