### ISSUE TITLE
Bug - Email open condition does not work

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#1432]
Hi,

I noticed **since the 1.2.4 version** (i don't know if it was also inefficient before) that the "Open Email" condition does not work. We tested on a 1.2.4 mautic.org version.

## How to reproduce
* Select a lead list
* Send a first email
* Add a open email condition
* Send a 2nd email 15mn later (tested with more and more minutes)
![capture d ecran 2016-02-09 a 09 42 48](https://cloud.githubusercontent.com/assets/14075239/12972090/8e02b37a-d0a2-11e5-9555-e42e1f17ab12.png)

## Issue
* I open this email directly after receiving it, but i receive the 2nd email!
![capture d ecran 2016-02-09 a 09 42 40](https://cloud.githubusercontent.com/assets/14075239/12972091/8e03f244-d0a2-11e5-9482-afc269ff8f74.png)

_______
Anyhow i see that i'm well tracked (it's written on my profile).
![capture d ecran 2016-02-09 a 09 43 07 1](https://cloud.githubusercontent.com/assets/14075239/12972092/8e06e2a6-d0a2-11e5-8f71-9dbf23015daf.png)

**Comment by escopecz** [comment]
I tested your scenario with this campaign:
![mautic-campaign-test-email-open](https://cloud.githubusercontent.com/assets/1235442/13319450/fd2c0326-dbc1-11e5-9c5f-80c61c4e4e78.png)
The lead detail shows the right tag after I run this campaign and open the email:
![mautic-campaign-test-email-open-lead-detail](https://cloud.githubusercontent.com/assets/1235442/13319523/869964d2-dbc2-11e5-849f-48467470112c.png)

@npracht could you also test with the tag action? Maybe the issue is in the second send email action or elsewhere. The email open decision seems to work fine for me.

**Comment by npracht** [comment]
Hi @escopecz ,

Sorry for the delay of my answer. I've tested the same campaign as you with `tag` management.
It works well.

Could you test my configuration ?

N.
