### ISSUE TITLE
Feature request - Send example email to someone else

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#1447]
## Definition of the need

It would be great to be able to select to whom the Example email is send. In that way you could send a test to collaborators for a better test without the need to create a campaign.
## How it would look like

You would just have to write the email addresses of all the people you wanna send the test to.
Here is an example of how proceed competitors.

![capture d ecran 2016-02-18 a 09 49 36](https://cloud.githubusercontent.com/assets/14075239/13138018/fa6c3388-d624-11e5-8829-1889921eb9c0.png)

**Comment by 750430** [comment]
+1 from me - especially useful if all the tracking details would be included too...

**Comment by dongilbert** [comment]
So, in the email detail page, when you click "Send Example", it would open a modal where you can enter email address. I like that idea and I think it would help for sure.

One suggestion, and let me know what you think, but I don't think that we need the HTML checkbox, do we? The email should just send out to the same way it would when you click "Send Example" now, except with the ability to send to multiple.

Maybe in the same way we currently have the modal for creating a new email "New Template Email" or "New List Email", we can have two boxes, one that says "Send example to me" or "Send example to list", with either the ability to enter emails in a text area (one per line, rather than individual boxes), or select an existing list to send the example to (say, you've created a list of your collaborators).

**Comment by npracht** [comment]
Hi @dongilbert 

* No need for the checkbox (this software had previously the option to send HTML version AND/OR text brut version), the 100% equal version is a perfect answer to the **i wanna test** need.
* One per line, or coma separated is great.
* Select a list. It could be great, but i think it goes too far from the feature itself **email test**, when you select a list it must be for your campaign or for a real shoot.

Thanks a lot for caring about.

N.

**Comment by 750430** [comment]
I would say the email has to be sent with any leadfield data included in it - so if I am the user logged in and I sent my test email(s) ... that personalisation is included to, rather than some [some leadfield data] text.

**Comment by 4evermaat** [comment]
@dongilbert @npracht what if the user wants to see how both styles of emails turn out? (html vs plain text).  Without a checkbox, how would the sender see both versions how they look?

**Comment by ayrad** [comment]
+1 on this

The possibility to send test emails **to a segment** as @dongilbert suggested I think it's great idea, because sometimes the tests must be sent to the same people again and again (like 3 or 4 people), so there is no point to type in the same email addresses again and again

**Comment by ldrrp** [comment]
+1 

I have a ton of emails labeled TEST with a bunch of segments i created to send to specific people. It would be really nice to either type in an email or use a typeahead search to find it in the contacts.

**Comment by Skrypton** [comment]
+1

**Comment by nithinga** [comment]
We started looking in this PR

**Comment by sibben** [comment]
+1

**Comment by plenartech** [comment]
+1 This feature would be a great addition to this wonderful tool! A must have!

**Comment by escopecz** [comment]
Implemented in 2.5

**Comment by yashsaxena** [comment]
@escopecz just wondering is this feature implemented right at the place (email settings) where we check connection & send a test? or is it implemented & accessible from somewhere else?

**Comment by escopecz** [comment]
Ok, you found it 👍
