### ISSUE TITLE
Feature request - Score on specific lead field value

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#1465]
## Need of this Feature Request
- It would be great to be able to **score depending on a `value` in a `leadfield`**. eg: my target is big sized company, if `500` or more in `company_size` field --> +50pts
- Manage that in the **scoring section** as standard rules. I personally always prefer to add standard scoring rules (applied any time) than adding special rules into a campaign.
  That's better to have a global view of the scoring settings.
## Suggestion and user procedure

In the scoring section as explained.
1. Select the option `Specific field value`
2. It add a **dropdown list** with all my `leadfields`
3. It add an `input` where i select/write my `value`
4. Possibility to add _more than one value separated by a coma_, `more than`, `less than`, `contains`, `exclude`, `empty`, `not empty`, etc.
![capture d ecran 2016-02-24 a 11 38 25](https://cloud.githubusercontent.com/assets/14075239/13283131/9a0bfaa6-daec-11e5-9500-46680d26a844.png)

**Comment by npracht** [comment]
@dbhurley today the only way to do so is to:
1. Create a segment
2. Create a campaign
3. Add the action score

# Why this should be manageable in Point Action ?
1. Because you'll be able to manage all your Scoring Strategy from the same place.
2. Because point action allows to apply the points to all leads from now or previous leads
3. Because it probably use less resources than using 2 CRON jobs (segments + campaigns)

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
