### ISSUE TITLE
Bug - CAPTCHA Error Message not shown.

### ISSUE THREAD

**Issue by echh** [mautic/mautic#1467]
Reproduce, on version 1.2.4
Make a simple testfForm, add a captcha test field.

If the captcha is solved wrong custom error is shown,
the Servers postMessage answer seems to be ignored
on client side. 
If the captcha is solved right, the OK message works.
But users solving the captcha wrong dont get proper feedback 
(submit, please wait, submit)

The error occurs in preview mode, when embedding via js and in plain html mode.

**Comment by dongilbert** [comment]
Confirmed bug.

**Comment by williamconifer** [comment]
I can confirm that this bug exists in the current version of Mautic running at mautic.net as of July 20, 2016. Ver 2.x??

This bug will become a serious barrier in using Mautic in a real life environment. Spamming will become an issue and clients will just say NO to Mautic. All because the captcha doesn't tell you that you answered incorrectly. 

IOW this is a big deal. 

Thanks for all your help and we appreciate your effort.
