### ISSUE TITLE
[feature] Allow bulk remove from list/mautic

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#1474]
There might be a need to bulk-remove a list of users, either from a specific list or from Mautic as a whole.

Example use case: I accidentally added a bunch of people to the wrong list .. oops!  Some were existing users so I couldn't just remove them.

It would be handy to be able to upload in the same way you do an import, to remove people from specific lists.  I couldn't see how to do this but from a UX perspective I'd think:

Navigate to list
Click button (maybe bulk/batch process?)
Upload CSV file
Choose what to match on (probably email?)
Choose which lists to remove from 
Go

Ruth

**Comment by hansakoch** [comment]
+1

**Comment by kuzmany** [comment]
You should able to do it now, but in little more complicated way.
You can import your contacts to temporary lead list and start campaign from this list with remove action from another lists.

**Comment by alucmb** [comment]
Maybe could have an option in the campaings to remove from all lists too... (besides the one we selected to add)
I have several lists, and today I have to select one by one all that I want the lead to be removed, since I  am always increasing the number of lists and campaings it's becoming a little harsh.

It could be very helpfull :)

**Comment by alanhartless** [comment]
At some point, I forget when, bulk add/remove of segments/campaigns was added as a feature.
