### ISSUE TITLE
A/B testing not working in campaigns

### ISSUE THREAD

**Issue by ps92** [mautic/mautic#1520]
## Description
There is a issue in Mautic (v1.2..4 and v1.3.0) where I cannot send two variants of the emails in the campaigns. I can send it in List Emails. 

## Steps to reproduce
Prepare a email and add  a variant to the email. Create a campaign. Choose campaign builder and select the lead list as something (with 2 or more leads). Add send email to the list. Select the name of the A/B test email (only name of its parent is shown), and send the campaign out. 

##Expectation
I am expecting the recipients would receive the both categories of the email. 

##Reality
I am receiving only 1 variant in my inbox, for all emails. (I use {my_email}+x@{organization}.com with x being a number}

**Comment by vegami** [comment]
If you are using the command line, which is the only way of triggering the campaign emails now, you will not get varying emails in your inbox.

**Comment by vegami** [comment]
There isn't actually anything with related with variants while sending through Symfony CLI. 
Refer file: Symfony\app\bundles\CampaignBundle\Command\TriggerCampaignCommand.php

**Comment by FarhadF** [comment]
Hi , I noticed the same issue.

By the way, I was wondering about A/B Testing in mautic, and how it is supposed to work. if anyone can shine some light on this matter it would be awesome. So we know what should we expect.
On the other hand  take a look at this document : [http://mailchimp.com/features/ab-testing/](http://mailchimp.com/features/ab-testing/)
Mailchimp has a feature to distribute variants with weight, to a percentage of leads, then wait for some time (the user sets the time) and then sends the remaining leads the winning variant.
this feature is nice because when you are sending newsletters (one time only emails in general) you can send the winning variant to the majority of your recipients.

Thanks 
Farhad

**Comment by ps92** [comment]
It is not supposed to work with campaigns. That is not how campaign emails are triggered. Each email in campaign is sent with independent setting, irrespective of the other emails. Adding a global setting might help as potential fix.

**Comment by escopecz** [comment]
@FarhadF I created a new feature request for what you described not so long ago: https://github.com/mautic/mautic/issues/1752

**Comment by alanhartless** [comment]
Fixed in #2335

**Comment by ps92** [comment]
Thanks!
