### ISSUE TITLE
Update problem

### ISSUE THREAD

**Issue by richtera** [mautic/mautic#160]
When running trying to update after doing a pull it causes several manual questions about files within bundles having been modified. This makes it very problematic to upgrade using continuous integration. Alternatively you should support --yes to force all bundles to upgrade or make sure the files which are going to be modified in each of the bundles are not the ones checked into the git submodules.

**Comment by alanhartless** [comment]
Hi

Are you referring to doing an update after executing a pull from Git? If so, which update commands are you using that's requiring interaction?

Or are you referring to updating Mautic via the update cli command?

Thanks,
Alan

**Comment by richtera** [comment]
I tried git pull and composer upgrade, git pull and composer install, and the app/console update.
In most cases it showed me several prompts asking if I wanted to proceed upgrade because of modified files.
I didn't find a command line which would allow non-interactive update. We deploy all of our web-apps using jenkins.
But using mautic as a --recursive git module wasn't possible either since the base .gitmodules doesn't point to all the modules installed using composer install.
My base requirement is that I would like to have a jenkins job which can upgrade to the latest mautic or a specific branch of mautic.
Thanks
Andy

**Comment by mbabker** [comment]
Could you share a sample of the job you're using to deploy with?  Since there aren't any submodules in our git repo, it sounds like you may be hitting prompts from either git or Composer in your deploy script.

This is untested, but to update between release tags, this should work fine on a Jenkins server:

Job configuration:
- Check "This build is parameterized"
- Add a String Parameter to input the version
- Under the Source Code Management section, ensure you've added the Mautic git repo
- Add a build step to execute a shell script:

```sh
git checkout $version
composer install
```

- Add a build step to run a shell script on a remote server (this step should be executed after Jenkins has deployed the updated code to the production server)

```sh
cd /path/to/mautic
php app/console cache:clear
php app/console doctrine:migrations:migrate --no-interaction=true
```

Note that in updating this way, you'll also be deploying development dependencies and code, there are some files and folders you'll want to move.  At a minimum, I'd suggest removing the build folder, index_dev.php file, and upgrade.php file.  You can take a look at our [packaging script](https://github.com/mautic/mautic/blob/master/build/package_release.php) to get a general idea of how we build our production packages and exclude development dependencies.

**Comment by alanhartless** [comment]
Also, not sure if you are trying upgrade to the latest released tag or to the latest master source but we highly recommend that you stick with the released tags.  If running the latest source, you have to run the Doctrine `doctrine:schema:update` to update the database schema which is not recommended for production use and especially not in any automatic process.  The reason is that Doctrine sometimes makes assumptions that could cause catastrophic loss of data.  In released tags, we have included migration scripts that ensure the schema is updated safely.

Thanks,
Alan
