### ISSUE TITLE
mjml.io support

### ISSUE THREAD

**Issue by cmnstmntmn** [mautic/mautic#1616]
https://mjml.io/try-it-live

it would be great as a future feature to use mjml syntax in order to generate emails.

**Comment by qneyrat** [comment]
+1, I have modify mjml and add id to html div for mautic builder. It's pretty good for create template but in first time, i know it's better to create plugin mautic for mjml integration and compilation.

What do you think ?

cc @dongilbert 

example : 

![Imgur](http://i.imgur.com/a5jkp6s.jpg) 

# 

![Imgur](http://i.imgur.com/o8R8m0P.jpg)

**Comment by grebett** [comment]
Good idea! Mautic could rox with MJML (disclaimer, I contributed to it a little :) ).

**Comment by ngarnier** [comment]
Hey guys, I'm from the MJML team so I'm excited to see this request, would love to see MJML integrated in Mautic :-). 

I wanted to let you know that we're working on an API which is in beta, it might make the integration easier as you won't have to run MJML yourself. Feel free to [request access](https://mjml.typeform.com/to/tW2U6K) and I'll activate an account for you! 

If you have any question as well, just ask!

**Comment by qneyrat** [comment]
@ngarnier Plugin with this api can be cool yeah i can dev that :)

**Comment by qneyrat** [comment]
@ngarnier You could come on the mautic slack we discuss about this issue ?

**Comment by ngarnier** [comment]
@qneyrat Of course, I'll join the Slack right away!

**Comment by ngarnier** [comment]
After discussing with @qneyrat (thanks!), we've come to the conclusion that Mautic could leverage MJML in 2 ways, the drag an drop mode being the most ideal:
- **Code mode**: Mautic users can benefit from MJML as a code mode to easily generate the responsive HTML
- **Drag and drop mode**: the Mautic builder directly benefits from MJML as a layer of abstraction. Instead of using HTML attributes such as `data-*` to identify a UI block with a HTML block, UI blocks are associated to MJML components. The MJML file is then rendered to HTML in the preview DOM. This enables to easily handle and manipulate complex responsive HTML.

Basic example to illustrate:
- a UI button block as HTML:
```
                    <tr>
                      <td style="word-break:break-word;font-size:0px;padding:10px 25px;" align="center">
                        <table role="presentation" cellpadding="0" cellspacing="0" style="border-collapse:separate;" align="center" border="0">
                          <tbody>
                            <tr>
                              <td style="border:none;border-radius:3px;color:#ffffff;cursor:auto;padding:10px 25px;" align="center" valign="middle" bgcolor="#414141">
                                <p style="text-decoration:none;line-height:100%;background:#414141;color:#ffffff;font-family:Ubuntu, Helvetica, Arial, sans-serif;font-size:13px;font-weight:normal;text-transform:none;margin:0px;">Hello</p>
                              </td>
                            </tr>
                          </tbody>
                        </table>
                      </td>
                    </tr>
```
- a UI button block as MJML: 
```
          <mj-button>Hello</mj-button>
```

Better than that, MJML can also be used in JSON (that's how we do it in Mailjet's drag and drop interface), to make programmatic manipulation way easier. This leaves us with 3 steps:
1. Manipulate UI blocks to create the email
2. Generate the MJML JSON according to what is done with the UI blocks
3. Render MJML to HTML from the JSON

What do you guys think? If you're interested, we're definitely willing to help you and share our experience from using MJML the same way in Mailjet!

**Comment by justlevine** [comment]
@dbhurley why was this closed?

**Comment by dbhurley** [comment]
Sorry if I misunderstood. I shared some thinking in Slack about how we could clean up our GitHub issues list and one of the things to undertake was removing 3rd party integration feature requests. After that conversation I closed any issues tagged with that label. Help me understand if that label was misapplied to begin with and we can reopen the issue. 

Of course I would love to see a plugin for this created! Hope that makes things a bit more clear.

**Comment by Helmi** [comment]
Has there been any more work on that end. From my understanding MJML would be a huge step forward in easily creating/modifying template and at the same time having compatible code.

**Comment by digitall-it** [comment]
I think that `mjml` could be a huge step forward for Mautic. As I understand @dbhurley every third party integration issue will be closed automatically because it has not to be discussed in the main issue list, for maintenance purposes. Would it mean that a new repo should be created? 

Theoretically, can a module extend Mautic to obtain the proposed code mode and editor mode integration proposed by @ngarnier and @qneyrat ?

- If yes, a new repo can be created and work can be started.
- If not, a new issue can also be opened by requesting access to the missing features needed for both those two modes to operate.

**Comment by TornMarketing** [comment]
Has a plugin been built for MJML?

or is it every time a great idea is closed because it isnt in the scope of the platform at that given time it is lost to be forgotten as another 'idea'

MJML is critical to how businesses are now building new responsive email templates that are easy to transfer between email platforms.

**Comment by digitall-it** [comment]
Actually it is easy to use MJML as a compiler on the template developer's site, so as an afterthought, the main use case for it can be solved easily. Otherwise, why not support SASS or handlebars or any other template engine. That would make the @ngarnier proposed "code mode" a minor feature.

The other one, the "Drag and drop mode" may benefit more from it, but the editor could need a major reengineering to make it more useful for complex, nested use cases.

**Comment by npracht** [comment]
Hi guys, we are considering adding this as new feature in the mautic 3 series. You can follow the debate there : https://github.com/mautic/mautic/issues/7360
