### ISSUE TITLE
Feature request - SMS Providers support

### ISSUE THREAD

**Issue by ldrrp** [mautic/mautic#1731]
| Q | A |
| --- | --- |
| Bug report? | N |
| Feature request? | Y |
| Enhancement? | Y |
## Description:

Add new support for more sms providers, You can look at this system to see how they added so many.

http://www.phpservermonitor.org/

Nexmo – https://www.nexmo.com/
Clickatell – https://www.clickatell.com
Inetworx – http://www.inetworx.ch
Mollie – http://www.mollie.nl
Mosms – http://www.mosms.com
Smsglobal – http://www.smsglobal.com
SMSit – http://www.smsit.dk
Spryng – http://www.spryng.nl
Textmarketer – http://www.textmarketer.co.uk

I would prefer NEXMO because it is what i use.

**Comment by ldrrp** [comment]
I am willing to run tests for nexmo and provide some support on this.

**Comment by scottybo** [comment]
Rather than trying to integrate with the hundreds of providers out there, why not add an option to send a webhook request? I use 46elks for example, and all I'd need to do is send a POST request to their server.

I'm sure most of these services have the same functionality. This means the management of integration can be taken away from Mautic as they only need to add one feature.

**Comment by dalarworld** [comment]
Code I have Written need to be made generic & have configuration settings where we collect API URL & Other parameters.  Since i;m new to mautic this is best i could put together in 1 day and test it.

**Comment by PatrikNorrgard** [comment]
Hi, I would also suggest a more generic approach. Allow us to configure a generic request, GET or POST, and let us use placeholders in that request for the receiving number, and the message body.

For instance our company runs a SMS Gateway with customers in Northern Europe, and our gateway can run as a simple get-request.
