### ISSUE TITLE
Social plugins not working as they should after update

### ISSUE THREAD

**Issue by Harry5-5** [mautic/mautic#1742]
Just installed a new version of Mautic - must admit to being really impressed.

However, if I have a lead, when I click on Social in that lead, I get details of my Twitter account and nothing else. I have the correct @twittter handle as well as other web addresses for facebook, LinkedIn, G+ etc and although the apps are setup they are not working.

I have also cleared the cache out too.

## Steps to reproduce

- I updated to the new version through the link that came through on the Alerts icon with in Mautic

- Having updated initially the plugins link would not work so we cleared the cache this solved the problem accessing the plugins section.

- from that point on any contact that has twitter handle included in their profile started showing the twitter details from the authorized account from the plugin rather than the details on that contacts Twitter activity.

Please help Im losing my mind trying to find out whats happened.

**Comment by Danibz** [comment]
Have the same issue. Also have problem with emoji's on instagram. List and leads become unavailable.

**Comment by mqueme** [comment]
What should be appearing in the social cache area for each contact is their own profile data, but this needs to be authorised by the user.  So probably after this bug is fixed, the social cache won't show up anything on the contact until after he/she authorises this. ie: The social login buttons in the forms would update the contact's social cache.
