### ISSUE TITLE
Bug - Redirection 301 not working

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#1757]
## Description
There is a feature that allows to redirect to any URL from an Mautic landing page.
This feature is not working.

![capture d ecran 2016-05-18 a 15 51 28](https://cloud.githubusercontent.com/assets/14075239/15361085/6ae3df9e-1d10-11e6-8935-e6c303885bd1.png)

## Steps to reproduce
1. Create an empty landing page
2. Add the 301 redirection feature to anny URL
3. Save the page (published or unpublished)
4. Go on the generated link
5. Notice that you are not redirected

**Comment by ayrad** [comment]
Confirmed. The page throws Internal server error with following error:

```
mautic.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "The HTTP status code "0" is not valid."
```

This is happening because under `app/config/local.php` the parameter `redirect_list_types` is saved as a simple Array (which saves 0 and 1 values as redirection HTTP code which must be 301 and 302)

```php
'redirect_list_types' => array(
"mautic.page.form.redirecttype.permanent",
                "mautic.page.form.redirecttype.temporary"
        ),
```

Instead of the original config which should be:

```php
'redirect_list_types' => array(
            '301' => 'mautic.page.form.redirecttype.permanent',
            '302' => 'mautic.page.form.redirecttype.temporary'
        )
```
When I get some free time I will look at this more in depth (if someone already found a solution, just go for it!)

**Comment by ayrad** [comment]
It took me a lot of time since all was so strange, but finally managed to solve it. I will make a PR with the fix (small but useful yeaah :))

**Comment by npracht** [comment]
@escopecz merged in 1.4.1

**Comment by jeffiepriya** [comment]
http://www.seoindiarank.com/

**Comment by jordan8037310** [comment]
I had to update the config file manually to replace 0 and 1 with 301 and 302
