### ISSUE TITLE
Segments filters > Bounced, Unsubscribed not working

### ISSUE THREAD

**Issue by ayrad** [mautic/mautic#1767]
## Description
Segments filters called "Bounced" and "Unsubscribed" not working as exepected (not applying. No contacts are added/removed to/from the segment)

## Steps to reproduce
- Create a Segment with filter "Unsubscribed" => Yes
- Unsubscribe a Contact (manually or from email link)
- Update segment contacts `app/console mautic:leadlist:update`
- 0 Contacts added to the Segment

**Comment by BartKaminski** [comment]
Same problem with Bounced filter

**Comment by peteratnsight** [comment]
The issue is caused by 

LeadListRepository at line 772: $q->expr()->eq($alias . '.channel', $channel) with $channel defined as 'email' in line 758 => causing a select query as .channel = email ....

Quick fix - change 758 to  $channel = '"email"';

But the query expression definition certainly needs to be fixed for this.

**Comment by TiagoRodrigues** [comment]
+1 


Quick fix offered by @peteratnsight worked.

**Comment by alanhartless** [comment]
This is fixed by https://github.com/mautic/mautic/pull/1836.

**Comment by TiagoRodrigues** [comment]
Thanks @alanhartless
