### ISSUE TITLE
Segment For Created User Role Doesn't Contain "**** Own" Permissions

### ISSUE THREAD

**Issue by MxyzptlkFishStix** [mautic/mautic#1768]
![1](https://cloud.githubusercontent.com/assets/9151657/15426107/5ecb3608-1e5a-11e6-987f-de904b279409.png)

After logging in, as a user with the assigned user role, any attempt to create a segment results in the following error in the log.  There are no "View Own", "Edit Own", "Create", "Delete Own" or "Publish Own" permissions.

`mautic.ERROR: Fatal: Call to a member function getId() on null - in file /var/www/tools/mautic/app/bundles/EmailBundle/Entity/EmailRepository.php - at line 308`

**Comment by escopecz** [comment]
Segments have option in their edit page to either make them "Public Segment" (by default) or if set to "no" the segment will be accessible only for its author. So the *Own permissions are not needed.

Could you please write down the steps to recreate the error you reported? I don't think it's related to a segment since it's origin is in the EmailBundle and the segments are in LeadBundle.

**Comment by alanhartless** [comment]
This is correct. Segments purposively do not have own permissions - it's assumed if a user has access to contacts, they can build their own lists/segments to organize those contacts.

**Comment by dongilbert** [comment]
Fixed in #3627. Thanks @MxyzptlkFishStix!

**Comment by fonderco** [comment]
I have 2.8.2 and the segment button just returns a 500 error.  The user is on a custom role and has access to create, edit, delete their own contacts, but the segments button doesn't work.  I know it is stated that this is fixed in #3627 but it isn't.

**Comment by escopecz** [comment]
@fonderco please create a new issue with all the details. Especially the error message from the logs.

**Comment by fonderco** [comment]
Actually #3724 resolved the issue.
