### ISSUE TITLE
[Feature Request] Installation on Read-only systems

### ISSUE THREAD

**Issue by ErvalhouS** [mautic/mautic#1793]
## Description

Make a check on installation for read-only systems and change behavior to saving DB/config specs on Database, or even use cloud storage like AWS S3.

This would make the app compatible with Heroku and other platforms.

**Comment by squeral** [comment]
Assets will also have to be uploaded to cloud storage like S3.

**Comment by jmcarp** [comment]
This would be really useful! I'd be interested in helping, but I'm not very familiar with the mautic internals. Is there a list of mautic features that require local storage?

cc @mogul

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._

**Comment by mogul** [comment]
For those following along: I've restated this request/idea at https://www.mautic.org/topic/enable-mautic-in-heroku-and-cloud-foundry/
