### ISSUE TITLE
Error on Installer Creating Admin User

### ISSUE THREAD

**Issue by nickian** [mautic/mautic#1866]
I'm having an issue running the installer. It's giving me this error on the step where you create the admin user. Any idea what's going on here?

> An error occurred while attempting to create the admin user: A new entity was found through the relationship 'Mautic\UserBundle\Entity\User#role' that was not configured to cascade persist operations for entity: Mautic\UserBundle\Entity\Role with ID #1. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist this association in the mapping for example @ManyToOne(..,cascade={"persist"}).

**Comment by nickian** [comment]
The only way around this for me was go to install version 1.3.1 and update inside of Mautic. What happened to the installer?

**Comment by scyzoryck** [comment]
In the InstallController:performUserAddition there is used another entity manager than in the RoleModel. When I've changed Entity Manager to the default one (from container), than it works fine..

**Comment by staffcheck** [comment]
This is still a problem. I installed Mautic early last year without any problems and run into this exact problem now.
![by default 2017-02-12 at 17 23 35](https://cloud.githubusercontent.com/assets/14122429/22863889/246098b6-f148-11e6-8364-6cc1a665802b.png)

**Comment by staffcheck** [comment]
@dbhurley, I really tried to find out what the problem is. In the end I created an admin user manually in the table including creating a bcrypt hash and linked it to the admin role (which was created). I then commented out the admin user creating step and let the installer finish. This is a show stopper for many for sure. I made several attempts to fix as I wanted to submit a pull but no luck. Sorry. Anyway I am glad I am up and running

**Comment by NickStallman** [comment]
I've identified the issue in our setup using MySQL Replication. In our case, autoincrement rows may skip numbers (e.g. start at 2 instead of 1).

The Role is added with no ID specified meaning it gets the first ID for the DB server it is using.
But the installer uses setRole with a hard coded reference to Role 1.
If role 1 doesn't exist then the installer fails.

There are two possible solutions.
a) The installer when adding the role initially should hard code that the admin role is id 1. It's only unspecified ids that can be affected.
b) The installer should look up the id of the admin role.

**Comment by joltcan** [comment]
Just installed mautic with the latest version (https://www.mautic.org/download/latest), and this is still an issue. I'm running MariaDB galera cluster on Debian 9 (mariadb-server-10.1, 10.1.26-0+deb9u1)

**Comment by fcostantino** [comment]
**Solved** by inserting a new row in roles table with ID #1 . Mautic expect to find roles administrator with ID#1 but mine was #5 .
