### ISSUE TITLE
mautic conjobs for all tasks - crontab mautic:cron:all

### ISSUE THREAD

**Issue by manuelfink** [mautic/mautic#1870]
I'm still not having all crontabs installed and still stumble over once I have forgotten since not all are listed in the docs. eg. console mautic:leadlists:update (even though I don't even know what it does.
## One cronjob for all task

Thus I wanted to suggest to make one crontab to execute all cronjobs. 
- cron triggered minuteley or every 5mins
- defined execution order
- thread safe - only one tasks runs and starts
- execution safe - recontinues with the next start where it stops
- multi-thread or service option for heavy load enviroments 
## Configurations
- Verbose vs Error Mode: Make the crontab outputs configurable. That it is possible to send emails only on errors. Add an option like --onlyerrors or --verbose to be able to distinguish that the script returns or even better differentiate outputs in logs and error messages
- Recommendation dump log messages whilst errors are still send per mail with `> /dev/null` (see sample below)
- options for deactivating not needed tasks (run all tasks by default)
- worker/thread count --threads=2

```
# crontab sample:
MAILTO="mymailadress@example.com"
*/5 * * * * php /path/to/mautic/app/console mautic:cron:all > /dev/null
```

**Comment by tomgoldsmith** [comment]
I agree, I think this would be a great idea. One very handy addition would be being able to pass arguments to the script to turn off jobs that people don't want to run.

**Comment by manuelfink** [comment]
@tomgoldsmith good idea, added it to the description.

**Comment by jordan8037310** [comment]
I think an issue with this idea is that if your Mautic DB is large, each individual task needs to be separated so it doesn't exceed PHP max execution time during cron runs. 

It would make sense as a basic feature, but since you can't skip the work of creating the cron job in the first place, might as well create them all so you don't get frustrated when, after some growth of your DB, your single cron job starts timing out, emails stop sending, campaigns aren't updated, etc.

**Comment by magician7** [comment]
@jordan8037310 in some environment there is no problem with max execution time. For example on my host php (php cli) has no time limit. For me and other people with ability run php cron with no time limit it will be very useful - having cron job run all necessary task. AND of course left options to run task individually.

**Comment by manuelfink** [comment]
## Considerations:

@jordan8037310 @magician7: I'd even go one step further and would considering adding 3 modes

1. deamon (background worker of a que which finishes tasks as the come)
2. cronjob all
3. single cron jobs

Regarding all three the following challenges may be considered:

- overlapping shell scripts being executed parallelly resulting in concurrency issues must be avoided
- prioritizing tasks (e.g an campaign sending over 2 days shouldn't block the whole system)
- parallelizing tasks for faster execution
- error handling that a stuck task does not block the whole system

**Comment by robwent** [comment]
If it could work in a similar way to something like magento then it could be used for some new features.

EG. You have one cron set to run every minute (Or 5 or whatever), but all commands aren't run by default, the jobs are just added to a queue in the database.

Enabling features in the admin can add the needed crons to the queue and make sure that the new jobs are added as needed. Features that aren't enabled don't get added.

You could specify the intervals for each task in the admin area so they only get added to the queue as needed.

Then new plugins could add their own jobs to the queue without needing their own cron jobs to function.

Different campaigns could be set to update at different times rather than one cron trying to update everything at once.

Issues like this one https://github.com/mautic/mautic/issues/3450 where some campaigns only want to be sent on specific days, could be set up in the admin area without needing to set up specific crons for each campaign in the system.

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
