### ISSUE TITLE
release-2.0 - Send Email page is not rendered properly in Chrome v49 on Linux.

### ISSUE THREAD

**Issue by ipso** [mautic/mautic#1949]
## Description
The Send Email page is not rendered properly in Chrome v49 on Linux, but its fine on FireFox. The "Subject" input field is behind the "Body" textarea toolbar. 

See attached image.
![mautic_bug1](https://cloud.githubusercontent.com/assets/4147850/16570640/861f290e-41fe-11e6-9dc5-268738b5c525.png)

**Comment by wittwerch** [comment]
Had the same problem, regenerating the javascrip/css files solved it for me.

``php app/console mautic:assets:generate``

**Comment by ipso** [comment]
I can confirm that running the above mentioned command did in fact fix the issue on Chrome. Not sure what the root cause was, but clearly it has affected more than just me.

**Comment by alanhartless** [comment]
It's because you guys got ahold of a not-quite-ready release :-D. When you see a release-x.x.x branch, it means we are preparing for the official release so some production assets probably weren't generated and some last minute bug fixes may get squeezed in. When you see the official announcements along with an update to master is when we have finalized the release. You may need to manually update the source from master to catch the final 2.0.0 changes.

**Comment by ipso** [comment]
Good to know, I was basing it off the "Release" section on GitHub which did seem like it had an announcement for v2.0. Which GIT branch do you recommend using for production?

**Comment by escopecz** [comment]
For production it's recommended to use the [production ZIP package](https://www.mautic.org/download/). But Git has it's advantages so if you want to use, it use the master branch. But there are some things you have to care about yourself. Like:

- Do not use the update command nor the update UI, use git pull to update.
- Take care about composer yourself. Run `composer install` after pull.
- Generate the production assets from the sources with `app/console mautic:assets:generate`
- Update your DB schema with `app/console doctrine:migrations:migrate` command.

I hope I didn't forget something.

**Comment by ipso** [comment]
Thanks for that info, I will close this issue now.
