### ISSUE TITLE
Specify the date format before import

### ISSUE THREAD

**Issue by Mike-Benoit** [mautic/mautic#2038]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? | Y |
| Feature request? |  |
| Enhancement? |  |
## Description:

Its unclear when importing contacts what date/time format must be used for things like "Date Created", "Modified Date", etc.... 

I tried several different ones including the full date format specified in the settings, and the ISO YYYY-MM-DD format and none seemed to work. Though the other data imported fine.
## If a bug:

| Q | A |
| --- | --- |
| Mautic version | 2.0 |
| PHP version | 7.0 |

**Comment by ipso** [comment]
I finally managed to get the import of dates to work, in all cases the format must be: 
YYYY-MM-DD HH:MM:SS

Since the system I was importing from didn't have seconds, even this format was rejected: YYYY-MM-DD HH:MM or even: YYYY-MM-DD

It still would be nice to specify the required format right on the import screen to avoid any confusion for other users.

**Comment by guillaumegarcia13** [comment]
I work on 2.1.1 and had to use YYYY-MM-DD HH:MM as date format (no seconds) to make the import work
