### ISSUE TITLE
Clearing 'is read' dynamic filter in reports causes Error 500

### ISSUE THREAD

**Issue by pierreavizou** [mautic/mautic#2064]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
After creating a custom report with a dynamic filter on the 'is read' email property, when viewing the report, if you click on the 'clear' button for the 'is read' dynamic filter, an error 500 occurs.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.0.1
| PHP version | 5.6.23

### Steps to reproduce:
1. Create a custom report with emails sent as the source
2. Add a 'is read' dynamic filter
3. View the report
4. Click on the 'clear' button for the 'is read' dynamic filter
5. You should get an internal server error

### Log errors: 

`[2016-07-20 10:29:29] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\DBALException: "An exception occurred while executing 'SELECT COUNT(*) as count FROM email_stats es LEFT JOIN emails e ON e.id = es.email_id LEFT JOIN leads l ON l.id = es.lead_id LEFT JOIN ip_addresses i ON i.id = es.ip_id LEFT JOIN emails vp ON vp.id = e.variant_parent_id LEFT JOIN categories c ON c.id = e.category_id WHERE (es.date_sent BETWEEN :dateFrom AND :dateTo) AND ((es.is_read LIKE :esisread) AND (e.subject LIKE :esubject))' with params ["2016-06-19 22:00:00", "2016-07-20 10:29:29", "%Remboursement Rihanna%"]:  Value for :esisread not found in params array. Params array key should be "esisread"" at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php line 119 {"exception":"[object] (Doctrine\\DBAL\\DBALException(code: 0): An exception occurred while executing 'SELECT COUNT(*) as count FROM email_stats es LEFT JOIN emails e ON e.id = es.email_id LEFT JOIN leads l ON l.id = es.lead_id LEFT JOIN ip_addresses i ON i.id = es.ip_id LEFT JOIN emails vp ON vp.id = e.variant_parent_id LEFT JOIN categories c ON c.id = e.category_id WHERE (es.date_sent BETWEEN :dateFrom AND :dateTo) AND ((es.is_read LIKE :esisread) AND (e.subject LIKE :esubject))' with params [\"2016-06-19 22:00:00\", \"2016-07-20 10:29:29\", \"%Remboursement Rihanna%\"]:\n\nValue for :esisread not found in params array. Params array key should be \"esisread\" at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:119, Doctrine\\DBAL\\SQLParserUtilsException(code: 0): Value for :esisread not found in params array. Params array key should be \"esisread\" at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/SQLParserUtilsException.php:41)"} []`

**Comment by goangus** [comment]
This issue is the same with any report that has a dynamic filter with a 'clear' option.

I've tracked the problem down to the Report Builder Interface
`Mautic\ReportBundle\Builder\MauticReportBuilder`

When applying the dynamic filters, if the reset value of '2' is present, the parameter value is not set (/app/bundles/ReportBundle/Builder/MauticReportBuilder.php:298), so the filter is applied without a value (/app/bundles/ReportBundle/Builder/MauticReportBuilder.php:318).

2 possible options for a quick fix:

**Option 1**
Add '2' to the break on line 298. 
`if ((int) $filter['value'] > 1) {`
`         // Ignore the "reset" value of "2"`
`        break 2;`
`}`
This will cause the program to break out of both switch statements so that the filter is never applied but it does mean that the default value for the paramater will be used which means the 'clear' button is useless.

**Option 2**
Put a Mysql Wild card into the parameter value so that the query looks for any value.
`if ((int) $filter['value'] > 1) {`
`         // Ignore the "reset" value of "2"`
`        $queryBuilder->setParameter($paramName, '%', 'boolean');`
`        break 2;`
`}`
This clears the filter in the 2 reports that I have tried it on, but without knowing the Report Bundle very well, I'm not sure if this will break in other circumstances, i.e if the condition is 'eq' rather than 'like'.

**Comment by escopecz** [comment]
I don't see any 'clear' button. Could you share a screen shot?

**Comment by pierreavizou** [comment]
![capture d ecran 2016-07-29 a 14 22 47](https://cloud.githubusercontent.com/assets/7101583/17248059/fc726722-5597-11e6-9f92-a17572eff133.png)

@escopecz there you go ;)

**Comment by dongilbert** [comment]
Closing as the PR that fixed it has been merged.
