### ISSUE TITLE
Country/State codes instead of names.

### ISSUE THREAD

**Issue by Mike-Benoit** [mautic/mautic#2112]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? | N |
| Feature request? | N |
| Enhancement? | Y |
## Description:

It appears that Mautic while having a list of countries and states, it references them by name rather than ISO standard codes. This makes it virtually impossible to integrate with other software, since there are many ways to reference the following countries:

'Moldova, Republic of'
'Republic of Moldova'
'Moldova'

'Micronesia, Federated States of'
'Federated States of Micronesia'
'Micronesia'

In Canada, there are many ways to reference some of the provinces:
'Newfoundland and Labrador'
'Newfoundland & Labrador'
'Newfoundland'

'Prince Edward Island'
'PEI'
'P.E.I'

Of course US has similar issues:
'Washington DC'
'Washington D.C.'
'D.C.'
'DC'

If it used ISO standard codes instead, it would be much simpler and we wouldn't need to create custom country/state mappings to talk with Mautic. It would also cut down a duplicated data in the DB of course.

**Comment by ldrrp** [comment]
This would greatly improve sortings and stuff and clean up the leads

**Comment by escopecz** [comment]
@ipso would you mind describe the steps where to find the list of countries you are talking about? Or maybe a screenshot? I don't know if you have an issue with the select box in the contact edit page or the country stored in the IP addresses table or where?

**Comment by ipso** [comment]
When you edit a contact, and there is a Country dropdown box, the list of countries is there. However when adding new contacts from the API, it seemed to require the full company name and that is where I was running into the most problems due to the above variations.

I found the actual list of countries in this file: app/bundles/CoreBundle/Assets/json/countries.json.

**Comment by jordan8037310** [comment]
I would also like to point out here that the `leads.state` and `companies.companystate` fields differ in the database and are stored in the abbreviated and long format, respectively. e.g. CA and California. These should definitely match.

**Comment by jordan8037310** [comment]
This might be useful as a lib solution: https://github.com/commerceguys/addressing

**Comment by yyil** [comment]
Also, when sorting contacts by location, it should be in order:
country > state > city
rather than
city > state

If I'm sorting by location, I obviously want to group by geography. Sorting simply by city names provides no value.

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._

**Comment by nick-fullstack-dev** [comment]
> In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site.
> 
> We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic.
> 
> _More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._

If you don't listen to user requests,  then there is no point.

For 5 years, you haven't even provided an answer to users, except systematically closing discussions to prevent people from expressing themselves.

You don't provide an answer on the forum either. 

Really sad.

**Comment by escopecz** [comment]
@githubcom13 we (the open source community) do not close the comments. Just the issue. You can still add more details to this and we can always reopen it. It does not mean it will never be done. It just means that there is not many users of Mautic that experience this issue. We try to keep the open issue count small so we can see what are the issues that are really painful or recent so we can focus on those.

What question do you need answered?

_Please, consider investing your time answering comments here and/or on the forums if you wish to improve the experience for other users_
