### ISSUE TITLE
Text Messages Don't Support Contact Tokens

### ISSUE THREAD

**Issue by scottybo** [mautic/mautic#2135]
When sending an SMS message via Twilio we'd like to be able to include personalised text (their name, unique links, mentions of past purchases etc).

I've tried using the same format as in emails, but the text doesn't get replaced, eg.

`{contactfield=firstname}‍`

Just outputs that exact text in the SMS, rather than the persons first name.

**Comment by renegademarketer** [comment]
+1 for this request. One of the key benefits of marketing automation is the ability to personalize communications with your list. Being able to personalize text messages with contact fields including custom fields is essential.

**Comment by CarlVanderLaan** [comment]
+1 for this request too

**Comment by quippy** [comment]
Yup. Me too. Wild that this isn't done, yet. Seems like a pretty core expectation for messaging from an automated marketing platform to be able to reference the person by name.

**Comment by npracht** [comment]
@dongilbert maybe you can tell if it supports or not tokens? Some people says yes, some other no...
Thanks !

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._

**Comment by YosuCadilla** [comment]
Bumping this up.
As there are mixed reports where some people sya it works and others say it doesn't.
Is there any documentation or any information available for adding tokens to an SMS?
