### ISSUE TITLE
GoToWebinar (Citrix) integration

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#2156]
| Q | A |
| --- | --- |
| Bug report? |  |
| Feature request? | X |
| Enhancement? |  |
## Description:

Add the integration of a Webinar software (ie. GoToWebinar from Citrix). The different features would be the following:
- Subscription to a webinar from a mautic **form**
- Inject the list of upcoming webinars to a mautic **form** (dropdown input)
- **Segment** depending on different criteria related to the webinar activity (subscribed, attended, did not attend, to a specific webinar or to the entire list of webinar).
- Make a different **campaign** path depending on webinar activity.

@webmecanik has started working on it. It's today working on 1.4.1. We're now processing on the upgrade and we'll share the development to the community.

**Comment by autoize** [comment]
+1 for this feature request. Another item I'd add is:
Being able to include the unique GoToWebinar "join" link for the attendee, as an token in emails sent from Mautic. This way, we can send personalized confirmation and reminder emails for webinars.

**Comment by ronnieduke** [comment]
I'm curious what the approach would be to integration on this... Since Mautic doesn't run off of "Programs" with "Program Statuses" (Like Marketo), would the webinar activity integration just be dynamically assigning users to lists based on their status? i.e. "Webinar_10-12-16_Registered"

What might be cool is a "Webinar" activity log type (like webpage visit or email open) where it could hold the webinar name, date of activity, and status (registered, attended, no-show, etc). Then segments or campaigns can filter off the activity log event.

**Comment by npracht** [comment]
Hi @ronnieduke,

We store the activity depending on a Webinar name. Let me provide you some **screenshots**:
## Form settings
![capture d ecran 2016-10-13 a 08 34 23](https://cloud.githubusercontent.com/assets/14075239/19338906/4f78b8e0-9120-11e6-9b65-828208d364f9.png)
![capture d ecran 2016-10-13 a 08 34 40](https://cloud.githubusercontent.com/assets/14075239/19338907/4f7ecc1c-9120-11e6-8bd4-b67fd7879989.png)

## Segment filters
![capture d ecran 2016-10-13 a 08 34 58](https://cloud.githubusercontent.com/assets/14075239/19338911/549c8dba-9120-11e6-80c5-4a9496bde5df.png)
![capture d ecran 2016-10-13 a 08 35 22](https://cloud.githubusercontent.com/assets/14075239/19338910/5496b124-9120-11e6-901b-e9bf9c3534c2.png)

## campaign decisions
![capture d ecran 2016-10-13 a 08 35 38](https://cloud.githubusercontent.com/assets/14075239/19338918/58c13f76-9120-11e6-9279-6e11863a0a67.png)

**Comment by escopecz** [comment]
Added to 2.3
