### ISSUE TITLE
Script Branding

### ISSUE THREAD

**Issue by brandonecarr** [mautic/mautic#217]
I've changed the images inside the "media/files/" folder, but none of the images have changed. Is there somewhere inside the script something needs to be uploaded or changed? Thanks!

**Comment by alanhartless** [comment]
Hi Brandon,

What images are you trying to replace?

Thanks,
Alan

**Comment by brandonecarr** [comment]
@alanhartless All of the branding... Logos on the front pages, the login page, etc. Thanks!

**Comment by dbhurley** [comment]
Some graphics are SVG in order to take advantage of retina displays and increase load times. You will also need to modify those files to make those updates.

**Comment by alanhartless** [comment]
As David mentioned, some of the graphics are svg and thus not an image that can be easily replaced. So you'd have to override the views to do so. Refer to https://www.mautic.org/community/index.php/147-form-name-appearing-on-front-end#p622 which gives some guidance on that.  Note that since 1.0.2 you can also use themes/system instead of the default theme to override the views regardless of chosen default theme.

If you wouldn't mind, this type of support question should go in the forum. We are trying to use this more as bug reports and feature requests.

Thanks!
Alan
