### ISSUE TITLE
In campaigns, page hit decisions do not always trigger related actions

### ISSUE THREAD

**Issue by pierreavizou** [mautic/mautic#2188]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
I have several campaigns where I want to trigger a stage change based on the URLs a lead visits. 

I have created a segment that contains all my identified lead (they are added as soon as they are identified by their email address, this is managed by the segmentation engine). 

This segment is then used as the source for the campaigns that are supposed to trigger stage changes. 

These campaigns consist of three elements: 

- A contact source (my segment containing all my identified leads)
- A page hit decision filtering the relevant URL for the relevant stage
- A stage change action

The URL filter for the page hit decision is like this: `*index.php?controller=order-confirmation*` 

You can see a screenshot below

![capture d ecran 2016-08-05 a 10 20 22](https://cloud.githubusercontent.com/assets/7101583/17430737/5033dd4c-5af6-11e6-9d8f-fa25524402d2.png)

Something a bit strange is that even the contacts that do not get updated by the campaign are added to the campaign. The problem is that, even though they visited the pages that should trigger a stage change, nothing happens, the campaign action is not triggered. 

I execute the three needed cron jobs (segments update, campaign rebuild and campaign trigger) every 5 minutes in a bash script.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.0.1
| PHP version | 5.6.23

### Steps to reproduce:
1. Create a campaign that changes a lead's stage based on a page hit
2. Have some leads visit the relevant page
3. You should see some of them do not have their stage updated by the campaign
 
### Log errors: 
I can't see any related error logs.

**Comment by escopecz** [comment]
Isn't it a testing problem described in https://mautic.org/docs/en/pages/troubleshooting.html ?

**Comment by pierreavizou** [comment]
Hi,

Nope it isn't :) 

The pages are actually tracked correctly and appear in the contact's timeline. 
This is exactly what seems strange to me: The timeline clearly shows that the contact visited the order conf page, but the campaign did not trigger on this page hit.

**Comment by adborges** [comment]
i have the same problem
mautic 2.0.1
php 5.6.24

page hit shows in timeline
decision even with page hit in timeline, goes the RED(NO) decision

**Comment by escopecz** [comment]
@adborges could you share a screenshot of your campaign tree graph?

**Comment by adborges** [comment]
my crons are running *1 one minute gap (just to test, normally its 3)

**Comment by escopecz** [comment]
Ok, that's what I thought. You have to add some timeout to the negative path otherwise Mautic will always trigger the negative path first. The way you have it now, you basically don't give the contacts a chance to hit the page.

**Comment by adborges** [comment]
Sadly not, @escopecz 
This campaign is not "live" yet
In my tests, when the campaign reach the decision, the URL was previously hit, already in timeline as page hit. So normally would have to work
Mautic is bypassing this.... even with timers

**Comment by escopecz** [comment]
Yes, I believe the action must happen after the decision was triggered. Mautic doesn't search the contact history if they was on that page or not.

**Comment by adborges** [comment]
@pierreavizou give this a try, i think will solve your problem

Bingo! Thanks @escopecz 
Let me tell you something more:
It would be helpful user can concatenate 2 decisions in sequence... today i have to put some tag shananiggans between decisions to work... 

i.e:
Form > decision 
If yes: send email
If No: Another decision

**Comment by pierreavizou** [comment]
Alright guys so if I understand clearly what happens here, the problem is that the page hit needs to happen **after** the campaign decision is triggered by the cronjob, right?

**Comment by adborges** [comment]
Yep...Maybe someday mautic will take in account the lead history. This would be awesome to solve cross campaigns duplicate actions.
In some cases is mandatory to know if this lead already visite a page, because marketing campaigns are made simultaneously in other platforms like adwords, social, etc  and other campaign efforts may be already got the user there. EVEN when the user got there again, maybe to got some free ebook or something

But... lets wait....
bye guys

**Comment by pierreavizou** [comment]
Ok so I think we could consider this as a bug because, in the current state of things, if the contact visits a page before my cron job runs and adds them to the campaign, the page hit is ignored... 

Is there any workaround for this, while a potential fix is disussed ?

**Comment by pierreavizou** [comment]
@escopecz Why did you close this? 
It does not seem like this is quite solved :(

**Comment by escopecz** [comment]
@pierreavizou I thought my explanation shed some light into how it actually works and you confirmed it was the case.

If you want someone to develop the feature to also track the actions in the contact's history, please, open another issue.

**Comment by neosparx** [comment]
@escopecz  Thanks for the detailed explanation above there. 

I am facing the same issue, but here is a work around.

1. Create a blank dummy page in mautic corresponding to the external page you would like to track.
2. Add the dummy page link to your external page using a image tag like the one below.
<img src="https://marketingpages.co/mautic/mp-what-would-you-like-to-do" width="1" height="1" />
 So whenever the external page is loaded, your dummy page is called too.
3. Now use the dummy page in your campaign, thats it.

Now whenever someone calls the external page, the dummy page also is called inside the image tag, and since the dummy page is used in the campaign, the campaign works fine.

Thanks, Best Regards,
Santosh
