### ISSUE TITLE
Gmail - Monitored Inbox Settings

### ISSUE THREAD

**Issue by cerebrumbr** [mautic/mautic#2216]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
Monitored address - email
IMAP host - imap.gmail.com
IMAP username - email
Port - 993
Encryption - SSL
IMAP password - pass

When I clicked in button "Test connection and fetch folders"

Return this ...

Error communicating with the IMAP server: Can not authenticate to IMAP server: [ALERT] Please log in via your web browser: https://support.google.com/mail/acco

## If a bug:

| Q   | A
| --- | ---
| Mautic version |  2.0.1
| PHP version |  5.6

### Steps to reproduce:
Monitored address - email
IMAP host - imap.gmail.com
IMAP username - email
Port - 993
Encryption - SSL
IMAP password - pass

Clicked in button "Test connection and fetch folders"
 
### Image: 

![img](https://cloud.githubusercontent.com/assets/2263217/17519598/057b1b5a-5e23-11e6-9dae-87feafd7f81c.png)

**Comment by cerebrumbr** [comment]
Hi,

See image.

If change to encryption TLS

Return this ...

Error communicating with the IMAP server: [CLOSED] IMAP connection broken (server response)

![02](https://cloud.githubusercontent.com/assets/2263217/17520303/a4335c92-5e25-11e6-8ba0-aee3e865d3f3.png)

**Comment by cerebrumbr** [comment]
Hi,

See image.

The imap is enable in Gmail.

![imap](https://cloud.githubusercontent.com/assets/2263217/17520388/f225414a-5e25-11e6-948d-3b1b87b6a8e5.png)

**Comment by escopecz** [comment]
Go to https://www.google.com/settings/security/lesssecureapps and turn the access for less secure apps on. Does it solve your issue?

**Comment by cerebrumbr** [comment]
Hi @escopecz 

Work perfectly now.

Thank you so much.

Please closed this issue.

**Comment by PeteOliveira** [comment]
Instead of changing the "less secure apps" setting.
1 - setup 2 factor auth (needed prior to next step) https://myaccount.google.com/security/signinoptions/two-step-verification
2 - create an App password https://security.google.com/settings/security/apppasswords

**Comment by malayladu** [comment]
@escopecz I am still having this issue even after turn the access for less secure apps on.

What to do now?

**Comment by dirtroof** [comment]
I struggled with this for far too long.
Finally figured it out—hopefully helps others.
So for me, the problem was my email (gmail) being paid/pro gmail that comes with google suite ($5/mo single user plan). 
If logged in as the primary user, when I went to set "Enable less secure apps" feature, it told me the account admin had to set it. That's exactly where the problem was, I just didn't realize it. I went to the admin account and enabled less secure apps, still didn't work.
The fix was to login to admin.google.com as the admin, then go to Security —> Advanced Security Settings —> Enable Less Secure Apps and set it to "Allow users to manage their access to less secure apps." I think this was because initially I setup the account as a group or something is the reason it works this way. But once doing that, I was able to Enable Less Secure Apps via the account that I needed to and it worked.
