### ISSUE TITLE
Campaign page hit decisions should take page hit history into account

### ISSUE THREAD

**Issue by pierreavizou** [mautic/mautic#2234]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? | N |
| Feature request? | Y |
| Enhancement? | Y |
## Description:

This issue follows the discussion in #2188. 

The idea is that when we have a campaign that is supposed to trigger actions when a contact visits a specific URL, the past history should be taken into account. 

This would be useful because Mautic handles campaigns triggers via cron jobs, and if a contact already visited the relevant page when they're added to the campaign by the cron job (even just 10 seconds after), then the associated action in the campaign is not triggered because the browsing history is not taken into account. 

Concrete case: 

All my identified contacts are added to a segment that contains all my leads. This segment is used as the source of a campaign that changes the contact's stage if they visited the payment page. 

My cron jobs run every 5 minutes. 

If a contact registers and visits the payment page before my cron jobs are run, they are successfully added to the segment containing all my leads and to the campaign, **BUT**, the payment page hit is considered past history (because the page was visited before the contact was added to the campaign), so is does not trigger the stage change action in the campaign. 

This leads to rather random stage changes based on when the cronjobs were run during each lead's visit. 

A possible solution would be that campaign take into account a lead's past browsing history (which is already available in Mautic) in order to trigger actions associated with 'page hit' decisions in campaigns. 

Based on how complicated/ressource-intensive it would be to take into account all the past history, a configuration option could be added to tell Mautic to only look at the past X minutes of browsing history. 

I hope this can foster discussion around the way campaigns work with browing history in Mautic, and welcome feedback about my suggestions :)

**Comment by tstanczyk** [comment]
I would also like to see more discussion about this feature/bug #2188.
I do undestand that from the technical standpoint this is not a bug, but from our experience the attention span of the leads is very short.
The sequence:
send email > open email > page hit > form submit > asset download
very often takes 1-3 minutes. So even with cron fireing every 1 minute the campaign is not reliable.

**Comment by Experto-Hosting** [comment]
Hi,
Any workaround?
Thank you.

**Comment by neosparx** [comment]
@escopecz  Thanks for the detailed explanation above there. 

I am facing the same issue, but here is a work around.

1. Create a blank dummy page in mautic corresponding to the external page you would like to track.

2. Add the dummy page link to your external page using a image tag like the one below. So whenever the external page is loaded, your dummy page is called too.
`<img src="https://marketingpages.co/mautic/mp-what-would-you-like-to-do" width="1" height="1" />` 

3. Now use the dummy page in your campaign, thats it.

Now whenever someone calls the external page, the dummy page also is called inside the image tag, and since the dummy page is used in the campaign, the campaign works fine.

Thanks, Best Regards,
Santosh

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
