### ISSUE TITLE
BUG! The same bug that has been there since version 2.0.0 is still there in 2.1! WHY???

### ISSUE THREAD

**Issue by abooster** [mautic/mautic#2254]
Seriously, guys, WHAT IS THAT? 
Or rather: WHY IS THAT??? 
The same bug that has been there since version 2.0.0. is still there in 2.1! 

What do you need to get that fixed? 
Do you need me to open 10 issues on this bug every day? 
Or what is needed to get this fixed? 
Tell me and I'll do my best to help.

### Steps to reproduce:
Very simple: 
1. Update to the newest version of Mautic.
2. DONE! 

You will now get a "500 Internal Server Error" every time you try to use the "add new" button anywhere! 
Whether you try to add a new form, a new landing page, a new contact, a new campaign, a new ANYTHING! 
You will ALWAYS get that "500 Internal Server Error"! 

And why? 
Because some stupid-shit new paragonie vendor files were added in version 2.0.0 that break everything. 

Please tell me this: 
Why do I have to manually overwrite the contents of "/vendor/paragonie/" with the old (version 1.4.1) contents for that directory? 
WHY DO I HAVE TO DO THIS AFTER EVERY UPDATE? 

Don't you think this is a little bit of a bug? 
Yes, it's a BUG!!! 

Now, please tell me: 
What do I have to do to get your attention to this bug? 
Because obviously, normal reporting is not working. 
So, naturally, I wonder if it needs a rant like this one?
:-(

**Comment by escopecz** [comment]
I rather won't react. See https://github.com/mautic/mautic/issues/2034

**Comment by luizeof** [comment]
@abooster please, make your own zero/free bug software and share with community or buy another software that provides 24h support.

Also, you can share your bug fixes with an pull request.

**Comment by abooster** [comment]
@luizeof Are you a fool or are you just pretending to be one?

**Comment by luizeof** [comment]
@abooster none

mautic.com provides you premium support fot your issues and if mautic does not correspond with your expectations you are free to use another software. There is rssr

And you can help us with your bugfixes, please share your work with the /vendor/paragonie/ bug.

**Comment by dongilbert** [comment]
@abooster Please use respect when talking to other community members. I will be locking this conversation to prevent further outbursts.

**Comment by abooster** [comment]
@luizeof So, the summary of your comment is: You aren't pretending to be a fool, you ARE one. 
OK, thanks for clarifying. :)

**Comment by alanhartless** [comment]
@abooster To address this concern, we are of course based on the Symfony framework. Symfony's own security-bundle component requires their polyfill-php70 which in turn requires the dependency paragonie/random_compat. In their v1.3, paragonie decided to drop support for openssl because it has potential serious security concerns in and of itself; see https://github.com/paragonie/random_compat/issues/96. Instead they now rely on the unix system's /dev/urandom, see https://en.wikipedia.org/wiki//dev/random
, to generate secure hashes for encryption. Because in a Unix environment this is treated like a file location, PHP does not have access to it by default when open_basedir is in effect. There should be no security risk adding `/dev/urandom` to PHP's open_basedir although I'm definitely open to any article stating otherwise. The whole reason for these changes by these two vendors, leading to the issue you're experiencing, is to provide a more secure environment. Because we are allowing their defaults - Mautic is erring on the side of security as well.
