### ISSUE TITLE
Getting error 500 (Internal server error) while opening mautic

### ISSUE THREAD

**Issue by sushilcmd** [mautic/mautic#2262]
I upgraded mautic 1.2 to 2.0 latest version now getting an 500 internal server error while opening mautic.
You can see in the image.
![selection_020](https://cloud.githubusercontent.com/assets/10064480/17642189/45b1bff0-615a-11e6-9a46-450833abaad9.png)

**Comment by silviodelgado** [comment]
I have the same error.

**Comment by wlaurance** [comment]
I went from 2.0 to 2.1 and had to update the database schema. I was getting a 500 on some forms I created prior to updating.

I was playing with a new fresh install so I wasn't concerned about data loss.

But if I had any data, I would make a database backup, then follow the instructions https://github.com/mautic/mautic#database-schema

**Comment by escopecz** [comment]
Also check https://mautic.org/docs/en/tips/troubleshooting.html to see how to report an error so developers could fix it.

**Comment by ericgopak** [comment]
Got the same error while performing an update today. Here is what log says:
`[2016-08-15 19:11:51] mautic.ERROR: Deprecation: The alias option of the form.type_extension tag of service "fos_rest.form.extension.csrf_disable" is deprecated since version 2.8 and will be removed in 3.0. Use the extended_type option instead. - in file /var/www/myproject/vendor/symfony/framework-bundle/DependencyInjection/Compiler/FormPass.php - at line 67 [] []
[2016-08-15 19:11:52] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\UndefinedFunctionException: "Attempted to call function "curl_init" from namespace "Debril\RssAtomBundle\Driver"." at /var/www/myproject/vendor/debril/rss-atom-bundle/Debril/RssAtomBundle/Driver/HttpCurlDriver.php line 54 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\UndefinedFunctionException(code: 0): Attempted to call function \"curl_init\" from namespace \"Debril\\RssAtomBundle\\Driver\". at /var/www/myproject/vendor/debril/rss-atom-bundle/Debril/RssAtomBundle/Driver/HttpCurlDriver.php:54)"} []
`

**Comment by alanhartless** [comment]
@ericgopak Check to see if your server has cURL enabled for PHP

@sushilcmd  and @silviodelgado  - did the trouble shooting steps or http://johnlinhart.com/blog/uh-oh-mautic-upgrade-was-not-successful get you back in action?

**Comment by ericgopak** [comment]
@alanhartless Thanks!  Indeed, my PHP7 setup was missing cURL :)

**Comment by alanhartless** [comment]
Awesome! Closing this issue then. If upgrades to 2.1.1 have any issues, please open a new issue.

**Comment by leokovaski** [comment]
Hello friends. Was able to resolve by setting some folder permissions:

/mautic

find . -type d -exec chmod 755 {} \;
find . -type f -exec chmod 644 {} \;
chmod -R g+w app/cache/
chmod -R g+w app/logs/
chmod -R g+w app/config/
chmod -R g+w media/files/
chmod -R g+w media/images/
chmod -R g+w translations/
chown -R $USER:www-data
