### ISSUE TITLE
Security issue arising from paragonie and /dev/urandom

### ISSUE THREAD

**Issue by abooster** [mautic/mautic#2275]
**This is a reply to** @alanhartless who posted here: https://github.com/mautic/mautic/issues/2254#issuecomment-239879212 
Since that topic was closed I have to open a new one for this discussion and I wish all brainless individuals would ignore this thread. 

Alan, first of all: Thank you so much for posting some real information! 
**It is so refreshing to read a reply from someone with a brain!** 
And someone who cares enough to actually explain why the issue is there. 
Thanks again for contributing your reply! 

Now, this topic is far from finished and I'd like your response (or response from anyone else who has a brain) to the following statement that I got from one of my server technicians... 

For background: I have a VPS with a company that has an excellent reputation in regards to server security and the very job of their server technicians (as well as the reputation of the company) depends on keeping my server safe. So, those aren't some clueless people. **Their very job is and depends on keeping my server safe.** 

And by now, I had THREE of them look into this issue and all 3 of them draw the same conclusion in regards to this open_basedir /dev/urandom issue: 
What Mautic requires me to do (in regards to open_basedir /dev/urandom) 
is an **"ill-advised workaround"**. 

Thanks to your cordial reply, Alan, I now understand that this whole paragonie/random_compat issue is due to Mautic using the Symfony framework and paragonie coming baked into it. 
(thanks again for clarifying it to a clueless non-developer like me) 

So, I went ahead and pasted your entire reply, Alan, to my server technicians 
and I asked them: I'd like you to comment on this reply. What do you think? 

Here's what my third server technician replied to your post, Alan: 

> ## As Jessie mentions [Jessie was the second server technician who had looked into this], there are many mentions of it as an ill-advised route in PHP codes for various reasons, but ultimately the simple fact that OpenSSL uses /dev/urandom by default to seed it's RNG function makes this claim of dropped OpenSSL support by the developer confusing. You can see here for on source of this:
> ## https://wiki.openssl.org/index.php/Random_Numbers#Initialization
> 
> There are many builtins that use /dev/urandom through the code, libraries, and handler without needing to open up direct access to /dev/urandom. Directly accessing /dev/urandom can pose a few problems, but for direct reasons as to why, I'd recommend contacting a qualified security/cryptography focused developer as they will be able to provide you the most accurate and concise information regarding this case.

So, now I'm curious if you have anything to say to that, Alan?

**Comment by alanhartless** [comment]
Although I appreciate the compliments, to be completely honest, the means in which you phrase your replies is very demeaning and disrespectful. It saps just about all motivation to even reply which is why I believe you are getting the types of reactions leading up to this post. Things could be very different if you use a more respectable way to deliver your concerns. We seek not just to be a company that provides software, but a community that learns and grows from one another - such attitudes displayed in some of the posts I've read from you are completely opposite of that. We'd really like you to continue to be part of this community - but it will require some reflection and a little self control with your words. For example, simply eliminating sentences referring to "brainless individuals" from this reply would have completely changed it's tone and made it appropriate.

To address your server technician's response. The fact that OpenSSL uses /dev/urandom by default is not the reason it was dropped by paragonie. It was dropped for the reasons they list in https://github.com/paragonie/random_compat/issues/96. One of the more serious ones is the fact that OpenSSL uses MD5 as a CPRNG by default - which is stated in the same article your tech referenced (https://wiki.openssl.org/index.php/Random_Numbers#Generators). MD5 is no longer considered secure in cryptology - as any modern password hashing code will allude to. `/dev/urandom` is the highly recommended means of generating random, secure strings in a Unix environment and thus many PHP dependencies leverage it. 

We are taking this concern seriously and are evaluating the best means in which to deal with it.

**Comment by alanhartless** [comment]
Just giving a heads up that this is not addressed in 2.1.1 due out today - we still need to time to work this out with upstream vendors.  As a side note - I've tried to write to and delete /dev/urandom with PHP and am blocked by the OS on every action. However, that does not necessarily mean that  we are not considering alternatives.
