### ISSUE TITLE
Installing plugins requires clearing the cache.

### ISSUE THREAD

**Issue by CreaoticX** [mautic/mautic#2354]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
When adding a new plugin, the app/cache folder needs to be deleted before the plugin will appear after clicking the install/upgrade button on the plugins page.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.1.1
| PHP version | 5.6.24

### Steps to reproduce:
1. Upload a new plugin
2. Navigate to plugin page
3. Click Install/Upgrade -> The new plugin should fail to appear in the list.
4. Delete the app/cache folder
5. Click Install/Upgrade again -> The new plugin should now appear in the list.
 
### Log errors: 

None

**Comment by alanhartless** [comment]
Sorry. We should have this documented - now on the todo list. :-)

This is required and will remain required for now simply because plugins are currently basically Symfony bundles and we are married to Symfonys cache. So if a new plugin is added, you have to delete the cache so the bundle is recognized by Symfony then click the install button in Mautic to run the plugins installation processes (such as schema installation). Clearing the entire cache from the UI is not consistent or reliable when done through a web request so that why we don't do it.

**Comment by CreaoticX** [comment]
This is probably a stupid question, but is the todo list online somewhere that I should be referencing as well in my pull requests?
