### ISSUE TITLE
Snapshot Segment

### ISSUE THREAD

**Issue by paulofelixjunior** [mautic/mautic#2366]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? | N |
| Feature request? | N |
| Enhancement? | Y |
## Description:

Imagine the following situation: I create a segment based on some filters from my contact database and then I create a campaign to touch these contacts.

However, I do not want do have the segment updated. I want, for any business motivation, to have this segment closed only to the names that were eligible to the filter when the segment was created.

I'd call this a snapshot segment - which could be set as a parameter on segment creation setting if the segment will be (or will NOT be) updated after creation.

**Comment by ipso** [comment]
What about just "Manual" segments, that are only updated when manually triggered to be updated? 

The advantage to this I see is that if you create the segment, then a few days later decide to change the filter, you could just manually click a button to trigger the segment update, rather than have to create an entirely new segment.

**Comment by PatchRanger** [comment]
There is a workaround for this usecase:
- Create a segment with filter by some tag, for example "snapshot".
- Mark all of the needed contacts with such tag "snapshot".
That's it. The segment will remain the same all the time.
I guess it's not the best solution - though it should do the trick you need)
