### ISSUE TITLE
Add option to disable froala editor all together for text only input in emails/landing pages

### ISSUE THREAD

**Issue by blmedia** [mautic/mautic#2368]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? | Y |
| Feature request? | Y |
| Enhancement? | N |
## Description:

Integrate Text-Only Editor for all Contents like Email/Landingpage ...

I found different tickets for mautic belonging the froala Editor and the problem that it changes the HTML Content. I know, that there seems to be an solution for this in version 2.1.0.

But for me, and I generate the E-mails with Mailjet.com, the problem still exists. The solution for me would be to have "Text-Only" Fields without GUI Support.

I Tried to remove the Froala Editor and removed all "Clearing" Skripts, but the Content, that receives in the database is still manipulated/changed. The Content in the XHR Request is correct but in the editAction there musst be an function that removes some tags (like in the Screenshot).

![20160823_105750](https://cloud.githubusercontent.com/assets/9772106/17886151/d07a58e0-6920-11e6-88a0-2b2ec43bc3a7.png)

I hope there would be an solution for this, because mautic is one of the greatest pieces of software that I found this year in the www ;).

**Comment by escopecz** [comment]
There is another fix for that for Mautic 2.1.1: https://github.com/mautic/mautic/pull/2258

Could you please test (or wait for the release and test then)?

**Comment by blmedia** [comment]
How can I test the staging version? Do I need to build the app.js?

**Comment by escopecz** [comment]
see https://github.com/mautic/mautic#how-to-test-a-pull-request

**Comment by merlin0** [comment]
Just tested the pull request since we're facing a similar issue. Got a few tags in the theme for Outlook rendering.

![image](https://cloud.githubusercontent.com/assets/12198056/17893660/cd1bfbec-6946-11e6-8ea5-609b9925a745.png)

With the pull request active the tags still get removed. The code editor in Mautic shows the following snippet:

![image](https://cloud.githubusercontent.com/assets/12198056/17893756/2220b556-6947-11e6-868a-fded28bbd975.png)


As you can see only the `<center></center>` blocks survive the html cleanup by the editor.

**Comment by escopecz** [comment]
@merlin0 if your concern are the HTML comments, see https://github.com/mautic/mautic/issues/2370

Please, guys, don't use the screenshots with code, just copy-paste it to the issue. How can others test it this way?

**Comment by merlin0** [comment]
The none screenshot version


    
    <a href="/" class="cta" style="-webkit-text-size-adjust: none; background-color: #d9015c; border-radius: 25px; color: #ffffff; display: inline-block; font-family: 'tisaSansBold', 'Helvetica Light', arial, sans-serif; font-size: 20px; font-style: italic; font-weight: 600; line-height: 50px; text-align: center; text-decoration: none; width: 480px;">Mail: ..............</a>

**Comment by abooster** [comment]
YES! Thank you, Alan! 
This feature is very badly needed. 
Version 2.1.1 didn't fix anything in regards to Froala and trying to make it work with this 3rd-party software is a futile exercise. 

Naked HTML input boxes = instant and permanent pain relief! :+1:

**Comment by merlin0** [comment]
It would be great if this could be in the next milestone. We keep getting issues with the editor even in 2.1.1..

**Comment by blmedia** [comment]
It would be so great if this option would be available. Currently I find no way to use our extern Templates/Newsletter and I would like to use mautic in production!

**Comment by sethharris** [comment]
Totally agree with @merlin0.

Whatever is hacking up the html has made landing pages unusable for us. It's even breaking layout for native Mautic forms inserted into landing pages.

We're getting tons of unwanted 'nbsp;', '<br>', 'data-' attributes, and for whatever reason...all of our links are getting 'background-color: transparent;'. Not to mention breaking modals by moving code blocks around.

I've tried tweaking custom_html in the database but the system still overwrites my changes when rendering the page. So apparently the 'hack' function is getting called multiple times.

I would very much prefer the system simply renders the exact html I give it.

If someone could be so kind as to point out the code that's making the html changes, I'd be happy to rip it out of the system.

**Comment by blmedia** [comment]
Just for Info: I found out, that not only Froala ist making "problems". Additionaly https://github.com/mautic/mautic/blob/13436c9b10eab0533a8ee4524528f30af5026604/app/bundles/CoreBundle/Helper/InputHelper.php#L362 was part of the problem. 

I uncommented this line yet an everything works fine. I know that this is an security feature, but currently we work only with administrator accounts. 

After removing Froala and the InputValidation I'am able to send my campaign ;)!!

**Comment by abooster** [comment]
@blmedia 
Hmm... you said you "uncommented" that line.
Did you mean you **commented out** that line? (i.e. did you put 2 slashes in front of it?)

Also, you are saying "After removing Froala and the InputValidation"... 
but I'm lost here. 
Please explain: **How do I remove Froala and the InputValidation??**
Is commenting out that line the only thing you've done?

**Comment by abooster** [comment]
In order to use Progressive Profiling I need to embed a Mautic page via iframe on a WordPress page. 
That's OK. The problem is: 
I this case I also need to embed a JavaScript snippet on that Mautic landing page. 
And that brings us back to square one: 
This Froala editor is causing problems! (no surprise) 

I just barely managed to get the JavaScript snippet in and save it. 
But when I come back and try to edit that page everything goes dead i.e. the wheels are spinning forever with no effect! I can't even get into edit mode. 
So, the only way to "edit" a page like this is to delete it and to create a new one. 
Who doesn't love this kind of "editing"? :( 

Please, **Add option to disable Froala editor all together for text only input in emails/landing pages!** 
Everyone and their brother has already voted YES for this!

**Comment by escopecz** [comment]
Code Mode added to 2.3. Pages and emails can be created without Froala touching the code.
