### ISSUE TITLE
Campaign allowing to send unpublished emails

### ISSUE THREAD

**Issue by paulofelixjunior** [mautic/mautic#2375]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? | Y |
| Feature request? | N |
| Enhancement? | N |
## Description:

The decision tree is allowing to select unpublished emails in "Send email" action.
## If a bug:

| Q | A |
| --- | --- |
| Mautic version | Mautic.com |
| PHP version |  |
### Steps to reproduce:
1. create an e-mail, save it and publish it
2. unpublish the email
3. create a new campaign, define a contact source and the send email action
4. try to select the unpublished email in the "Email to send" field. It will be there.
### Log errors:

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by alanhartless** [comment]
They do show up but won't be sent. We can't hide them in the lists because it will break the campaign builder itself when emails are unpublished in the meantime. Or maybe you're in the campaign builder and want to select an unpublished email with the intent of coming back to the email to publish it before the campaign is executed. All our campaign entity select lists behave this way but I can see how it could cause some confusion. Maybe we can indicate somehow in the dropdown if the email is unpublished.
