### ISSUE TITLE
Thrive Leads not passing current session / cookie when form submit

### ISSUE THREAD

**Issue by julienbedard** [mautic/mautic#2404]
What type of report is this: Bug Report

## Description:
i'm not sure if it's realated to mautic itself or if related to thrive leads but I'm gonna post on both.
OK so I'm using a form on thrive leads that connect to the oauth2 of mautic to create new contact.
New lead is added but it doesn't merge with the anonymous lead I already have.

So here's the steps from a visitor:
1) go to the site, visit some web pages, mautic track every web page view flawlessly.
2) at one point the user enter their email and name into a form.
3) thrive connect to the oauth and create the contact with name and email.
4) so now there's two contact (one anonymous that continue tracking what user do) and another with email and name from current contact, this one is not tracking anything he do after.

My main concern is it should be able to merge those contact till it come from the exact same browser and user.

| Mautic version | 2.1.1
| PHP version | 5.6.25

### Steps to reproduce:
1) go to the site, visit some web pages, mautic track every web page view flawlessly.
2) at one point the user enter their email and name into a form.
3) thrive connect to the oauth and create the contact with name and email.
4) so now there's two contact (one anonymous that continue tracking what user do) and another with email and name from current contact, this one is not tracking anything he do after.
 

More informations:
I'm using Thrives lead, Oauth2, not logged as admin, using another browser, and clearing cookie before all operations are done.

Thanks
Julien Bedard

**Comment by alanhartless** [comment]
Unfortunately, there's nothing we can do about this - Thrive will have to address it. The reason is that Thrive is submitting the form "behind the scenes" outside of Mautic's control. This means that Mautic doesn't have access to set the needed cookies in the contact's browser to track the now identified contact. Thrive will need to use a fake cookie jar when it submits to Mautic to collect the cookies Mautic sets when the form is submitted then pass those cookies on to the contact's browser.
