### ISSUE TITLE
Lead Track (no just IP)

### ISSUE THREAD

**Issue by ninjoan** [mautic/mautic#2406]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? | N |
| Feature request? | Y |
| Enhancement? |  |
## Description:

Is possible to implement a new tracking method that is no just about the IP address in some countries the lead have dynamics IP, so when the lead has a new IP address Mautic lost the activity track with that contact.
## If a bug:

| Q | A |
| --- | --- |
| Mautic version |  |
| PHP version |  |
### Steps to reproduce:
1. 
2. 
### Log errors:

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by alanhartless** [comment]
Yes - if fingerprinting is legal in your country then add a custom contact
field with an alias of "fingerprint" then make it a unique identifier. Use
the mtc.js tracking instead of a pixel. The downside of this is that we do
not support multiple devices per contact yet.
https://mautic.org/docs/en/contacts/contact_monitoring.html

We are planning to improve this in a future version of Mautic.

**Comment by ninjoan** [comment]
and have to planning using cookies or something like that?

**Comment by kuzmany** [comment]
@ninjoan  we use this change https://github.com/mautic/mautic/pull/1030  and fingerprint also

**Comment by lukasleitsch** [comment]
I run into the same issue. Are there any news about this issue?

All people from the company, with the same public ip address, are identify as the same lead in Mautic. User A on computer A opens the page. Mautic creates a new anonymous lead. User B on computer B opens the same page. The activity from both merge into one lead. Mautic set on both computers the same `mtc_id`-cookie.

The suggestion with the fingerprint doesn't work. The fingerprint ist always overwritten from the last user who visited the page.

**Comment by manuelfink** [comment]
Copy from my original post:

Hi Everybody,

I'd like to pick up the cookie vs ip tracking topic once again, since I do have several questions regarding this and could not find any answers here on git nor the docs.
### Questions:
1. Does mautic use ip4, ip6, fingerprinting cookie by default?
2. Is anywhere an option to solely use cookies or switch between cookie/ip tracking?
   3a. How are cookies persisted? 
   3b. Solely cookie or any combination of cookie, localstorage and others? 
   3c. Is anything like evercookie used?
3. How does mautic behave in a cross domain tracking context? 
   4b. Is there any strategy for cross domain user tracking this?
### Opinion towards cookie vs ip

Situation in Germany, in reason of privacy issues we do have changing IPs in Germany. Meaning every 24h or on every reconnection the ip addresses is changed. Thus, **IP based tracking does not make any sense here!**

On other countries with static IPs this may be different. However it is possible that multiple users in an office may do share one ip address. In this case IP based tracking is not the best either

HOWEVER: Cookie based tracking may be not the best solution in case of any cross domain tracking, since cookies are not set on an foreign origin (if the user never visited the origin bevor) in reason of CORS policies. Thus in this case, depending on your location, IP may be preferred.

Cross device tracking, ... huge issue it self. The big players use single sign on. http://venturebeat.com/2014/10/06/the-cookie-is-dead-heres-how-facebook-google-and-apple-are-tracking-you-now/ 

Thus it should be possible to switch cookie vs ip tracking depending on the needs. And there should be a strategy for cross domain cookie tracking and cross device tracking.
### legal considerations

Fingerprinting may be not allowed in some countries

Cookies laws may differ in different countries. EU is currently working on privacy laws and it is a grey area for analytics. For now it seems an opt-out possibility is enough. 

Thus it may be necessary to implement adjustability of tracking strategies within the mautic script / server.
### Other related issues:
- Switch tracking to JS https://github.com/mautic/mautic/pull/1582 #1582
- Docs on contact monitoring https://mautic.org/docs/en/contacts/contact_monitoring.html

**Comment by manuelfink** [comment]
# Tracking is NOT working for a lot of mautic users!

@escopecz: I suggest adding labels **bug** and **urgent** to this issue!

 I think this is a **serious issue** and a lot of mautic users are not even aware of what this issue means. They are not that deep on internet infrastructure, dynamic ips, tracking and the legal situation. 

1. it is unclear to most users how mautic tracking works!
2. ip based tracking is inappropriate for most mautic users (except US, see explanation above)

**Comment by ralphkretzschmar** [comment]
is there any update to do account based marketing (iplookup) with a service? or which one do you recomend for europe/germany? im looking for MaxMind - GeoIP2 Precision.... is it possible with such tool to which company was on the regarding website? at the moment i only see ips from the visitors in the name field...
