### ISSUE TITLE
Image Height/Width attributes should not be added automatically on landing pages

### ISSUE THREAD

**Issue by stevegrant1983** [mautic/mautic#2421]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:

I have a custom theme for landing pages with CSS that displays an image across the entire width of the page, but when selecting the theme when creating the landing page and saving it, Mautic inserts specific height, width and style HTML attributes into the `<img>` element which completely screws up the intended design of the page.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.1.1-dev
| PHP version | 7.0.8

### Steps to reproduce:

1. Create new landing page
2. Select my custom theme
3. Either edit the page in the builder or save as-is
4. Open preview URL
 
### Log errors: 

None

**Comment by stevegrant1983** [comment]
Sorry, should also add - this is an issue with other "block" elements such as `<div>` as well.

**Comment by beefaaubee09** [comment]
Yeah I've faced the same situation. This isn't only happening in landing pages. It happens in creating new email from custom template as well. Adds width to image while already defined. But i noticed it doesn't harm height. As a temporary solution, I edit the html code written, change their width from inspecting element (Using Google Chrome, for Firefox you can use Firebug) & then save/close it. But if you click on edit again it will again add width to the images. Also along that, it adds up <br> tags. I think this issue is already on going with HTML editor.

**Comment by escopecz** [comment]
Fixed in https://github.com/mautic/mautic/pull/2459. Tests are welcome.
