### ISSUE TITLE
Add the global reply-to option

### ISSUE THREAD

**Issue by Arjoni** [mautic/mautic#2442]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? |  |
| Feature request? | x |
| Enhancement? |  |
## Description:

When i send emails, i want to add the reply-to header. 
For example, i am using sparkpost and i want all my users to be able to reply to the marketing emails. When a user replies, he/she gets the error that the email doesn't exist.

**Comment by escopecz** [comment]
Like this?:
![mautic-reply-to](https://cloud.githubusercontent.com/assets/1235442/18165549/25ff2d50-7046-11e6-8892-f14adab06ade.png)

**Comment by Arjoni** [comment]
It would be great to have a default setting for all emails at email
settings.

**Comment by escopecz** [comment]
Oh, is there a reason why don't you use the email address you want your contacts to "reply to" as the email address you send the emails from?

**Comment by Arjoni** [comment]
Well i am using external services to send emails and they don't have a
functional mailbox. They serve as a relay.

**Comment by escopecz** [comment]
Ah, OK. Thanks for the explanation. I'll mark it as feature request then.

**Comment by ArchetypeMkt** [comment]
I have exactly the same issue and am using Sparkpost as well and can't set up receiving so have to remember to change the "reply to" address everytime I do an email.  A global "reply to option" would be perfect.

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
