### ISSUE TITLE
Spurious bytes after contact email address inserted into email body

### ISSUE THREAD

**Issue by nickion** [mautic/mautic#2467]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? | Probably |
## Description:

An email with a contact's email inserted using `{contactfield=email}` in an email template has unexpected bytes after the inserted email address, e.g. view source of the email might contain
`blah blah mautictest@somedomain.com=E2=80=8D blah blah`
When editing the email template after saving, the invisible bytes appear as whitespace in the template, so it may be a facet of the editor.
## If a bug:

| Q | A |
| --- | --- |
| Mautic version | 2.1.0 |
| PHP version | 5.5.34 |
### Steps to reproduce:
1. Create a template with `{contactfield=email}` in the HTML body
2. Send the email to a contact
3. View the source of the received email

**Comment by escopecz** [comment]
I asked at https://github.com/ichord/At.js/issues/431 about this issue. Does it cause any problems?

**Comment by nickion** [comment]
Difficult to know as this will depend on the email client. I noticed it when a test email was received as spam, and spam assassin's summary included part of the text and this was displayed with latin-1 rather than unicode, so the bytes appeared as characters â and € after the email address. If a reader interprets as Unicode it likely isn't an issue.

**Comment by stevedrobinson** [comment]
This does cause problems if you put a merge field/token into a url. For example, we link alerts to CRM like this:

`<a href="https://my.crmsystem.com/person/{contactfield=crm_id}">`

This results in generating URLs like:

`<a href="https://my.crmsystem.com/person/1558=E2=80=8D">`

Which, when you click on it, becomes the URL:

`https://my.crmsystem.com/person/1558%E2%80%8D`

...because my email client replaces the "=" with a "%" to make the URL friendly

@escopecz @RCheesley This is in Mautic 3.2, but I was able to troubleshoot the problem down to something to do with the email editor. Would you like me to open a new issue? I know the email editor is slated to be replaced soon.

**Comment by RCheesley** [comment]
Yes please, create a new issue linking to this one as we may be able to get it fixed :)
