### ISSUE TITLE
[Feature] Mark/unmark contacts "do not email" via actions

### ISSUE THREAD

**Issue by that0n3guy** [mautic/mautic#2484]
What type of report is this:

| Feature request? | 
## Description:

I would be nice to be able to mark a contact as "do not email" via campaign actions and form actions.  Use-case: multiple custom unsubscribe forms, remove based disqualified lead

On the flip side, it would be nice to un-mark them as "do not email" if they fill out certain forms (to re-signup).

**Comment by zenzozen** [comment]
+1

I want to make a unsubscribe system in mautic  using own landing pages, because the default unsubscribe of mautic its a blank page with a phrase. Not so good for user experience / brand reputation. 

This "simple" action would provide much flexibility for mautic users make own unsubscribe methods. 

Cheers!

**Comment by kuzmany** [comment]
Fund this feature here https://mautic-fund.kuzmany.biz/campaign/5/campaign-do-not-contact-action

**Comment by gingerling** [comment]
I want to forcibly unsubscribe people who don't open an initial opt out email

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
