### ISSUE TITLE
Google captcha integration

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#2524]
| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | X

## Description:
The CAPTCHA version of mautic form is quite basic. As you may know, Google has developed an open source reCAPTCHA which is quite powerful.
![recaptacha](https://cms-assets.tutsplus.com/uploads/users/30/posts/23024/image/nocaptcha.gif)
It would be very nice that this feature is integrated instead (or furthermore) of the existing CAPTCHA.
I found a piece of doc there :-)
https://developers.google.com/recaptcha/old/docs/php

N.

**Comment by qneyrat** [comment]
+ 1 but with recaptcha v2 it's widget, 
I can start dev?

**Comment by Getron** [comment]
+1

**Comment by saint2016** [comment]
+1

**Comment by diegofcv** [comment]
+1

**Comment by jzba** [comment]
I've started implementing this based on #2986, as suggested by @qneyrat . 

I am almost done with it, but I ran into an unexpected trouble. It seems that Google`s grecaptcha is interacting with Mautic javascript on the front end.  I'll describe my approach and present the problem in the end.

I am using a late bind strategy to render grecaptcha on the form's submit button. I then set a callback method to run once the verification passed. This callback locates the form and calls `submit` on it. As a result, I get google's pop up asking me to click on images. On the back-end side I added a custom validation code that checks the received token against Google's API and through debugger I get to see that the process is working. Pretty neat, right? The problem is that somehow this messes up with the front end validation procedure. The problem is on the front end and it causes an annoying user experience in case the form validation fails. 

The normal form submit behavior looks like this: once the user clicks the submit button, Mautic's js will replaces the  'submit' message on the submit button by a "Please wait...." and then again to "submit". It will also clean up field forms in case the form was successfully validated. 

When adding my implementation of an Invisible Recaptcha field to the form, things change: once the user clicks 'submit', the message on the button changes to 'undefined' and never gets back to 'submit' again. Also, it won't clean up the form in case of a valid submission.

The only hypothesis I have is that rendering grecaptcha on submit button messes up the event handling logic managed by Mautic' javascript on the browser. No idea how to fix this, thought. 

I'd appreciate some help on this. If I get this working, I'm pretty sure I can submit a pull request to Mautic.

**Comment by Loanatik** [comment]
+1

**Comment by khaoua** [comment]
+1

**Comment by szsori** [comment]
+1

**Comment by KonstantinCodes** [comment]
@npracht I was also interested in recaptcha and wrote a plugin for mautic: https://github.com/KonstantinCodes/mautic-recaptcha

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._

**Comment by npracht** [comment]
@dbhurley & @KonstantinCodes couldn't we consider adding this plugin into mautic core ?
Because the existing Captcha does not catch anything and it seems much more serious to integrate Google tech here.
