### ISSUE TITLE
Introduce a concept of tracks and multiple stages - enhancement

### ISSUE THREAD

**Issue by nickion** [mautic/mautic#2531]
What type of report is this:

| Q  | A
| ---| ---
| Enhancement? | Yes

## Description:
Unless we missed something, there seems to be only a single possible stage for a lead, and this seems very limiting for anything other than a trivial use case. A lead might at different stages in any number of activities. Introducing the concept of "Tracks" (or "Activities" etc.), a lead being involved in any number of tracks, and having stage be a property of track would be very useful.

**Comment by ybombale** [comment]
+1

**Comment by zenzozen** [comment]
Yes, specially if you have multiple goals, services or products. 
Maybe an option is to input goals, and they inherit the stages. 

Lets say a company has Product X and Service Y, with a standard of 3 stages. 
A contact could be in both os goals stages:
- stage 1 of Product X
- stage 3 in Service Y

**Comment by trnelson** [comment]
New to Mautic, but definitely on board with this. Basically I'm looking for the ability to add a user to multiple funnels if need be. It seems like Stage would be the equivalent of a Funnel (in something like ConvertKit, Constant Contact, etc.) but please let me know if I'm off base here. Thanks!

**Comment by fcatanzaro** [comment]
This would be a game changer 100%.  Anyone who has more than one product would benefit greatly, the workarounds we have are unsustainable long term.

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
