### ISSUE TITLE
Forms - allow "Select" to use date as matching contact field

### ISSUE THREAD

**Issue by niklausmoser** [mautic/mautic#2533]
| Feature request? | 

## Description:
Currently it is not possible to use "Select" in a form and use a date field as matching contact field - I would like to offer the users of the form the possibility to choose from preselected dates (dropdown-like) and not simply show the calender which allows choosing a random date.

**Comment by wittwerch** [comment]
It's possible using a radio group. 

Form configuration
![screen shot 2016-09-14 at 10 45 02](https://cloud.githubusercontent.com/assets/1575445/18505621/5e858b16-7a68-11e6-80c0-28237143114b.png)

Form preview
![screen shot 2016-09-14 at 10 45 19](https://cloud.githubusercontent.com/assets/1575445/18505624/61f42f00-7a68-11e6-881c-db12414be377.png)

The only drawback is, that the dates are not shown in a non-localised manner. I think the dates should be shown using the format defined in the "System Defaults".

**Comment by escopecz** [comment]
You can match contact select field with forms select field. Since Mautic 2.2.0 the form select field options can be inherited form contact select field so you don't have to create the options twice.

**Comment by wittwerch** [comment]
Hi @escopecz,
This works perfectly in case you are dealing with text fields, but it does not work for date fields.
Let's say you offer three specific pickup dates from which the user can choose. First you add a custom field with the type "date". You then need a form where the user can select one of the offered pickup dates. 
The problem is, that you can use a select field and match it with your pickup field. But the values of the properties you add to that select fields need to be in the format yyyy-mm-dd. It would be nice if these dates would be displayed in a localised format according to the user's browser.
