### ISSUE TITLE
Progressive profiling improvement - could benefit from queued questions

### ISSUE THREAD

**Issue by wheresmylunch** [mautic/mautic#2545]
What type of report is this:

| Feature request? | 
## Description:

Progressive profiling feature on 2.1 is a great benefit on the forms completed by potential clients. However, an additional feature would be to be able to use queued questions as per hubspot. Means that forms could pick say 4 fields out of information that is either a) not already collated and b) required.

**Comment by npracht** [comment]
Hi, i think this is exactly what i've requested here: https://github.com/mautic/mautic/issues/2545

Indeed, the way progressive profiling is implemented in 2.1 is interesting for the "Do not show the filed" but to **display new fields**, this is not really flexible and would mean that a lead needs to submit twice the same form which seems being (marketingly) stupid.
______

# Objective
Qualify better leads by asking us information **we do not have yet** on the forms.

## What is Progressive Profiling?
Progressive Profiling allows your forms to only ask for information that’s not already known by the marketing automation software. This allows your forms to progressively uncover additional qualifying information as leads become more engaged with your content and your company.

On the forms, you'd have a feature to enable. For instance, Net Results does the same and it's a very powerful feature. https://www.net-results.com/progressive-profiling/

# How to proceed
1. On the form you enable the feature
2. **Then you choose how many fields should be displayed** --> missing feature
3. You sort fields the way you want (the way they'll appear on the website)
4. On each field you have the opportunity to **always display** the field
5. All known contact values make invisible the form input and replaced by the next in the form input list.

![capture d ecran 2016-06-08 a 10 12 16](https://cloud.githubusercontent.com/assets/14075239/15887245/84fd5728-2d61-11e6-9949-531253a61b31.png)

## Proposition
The missing feature is **Choose how many fields should be displayed** and queue the extra one in the form until that previous one are hidden because we have the value.
Then it adds the queued fields to the form instead of the hidden one with the limit of max field setup.

@escopecz & @matishaladiwala your opinion ?

**Comment by npracht** [comment]
@dbhurley !!!
This enhancement is core. Today it is not about progressive profiling but hiding known field.
A real progressive profiling as explain above proposes automatically new fields depending on contact known fields.

**Comment by npracht** [comment]
Screenshots from Hubspot for inspiration. @webmecanik is gonna work on it on coming days, we'll directly push it against M3 branch to be able to merge it in 3.x series minor version.

**Comment by npracht** [comment]
![image](https://user-images.githubusercontent.com/14075239/76075186-d87f9c00-5f9c-11ea-9cb3-8ad377cb7e06.png)
![image (1)](https://user-images.githubusercontent.com/14075239/76075181-d6b5d880-5f9c-11ea-8637-511fcac2e09c.png)

**Comment by RCheesley** [comment]
We are pending some fixes for Travis on the PR #8611 but once that is fixed we will need two tests before the 16th August in order to consider this for inclusion in 3.1.
