### ISSUE TITLE
Different Colour Tags

### ISSUE THREAD

**Issue by pcantellow** [mautic/mautic#2548]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | N
| Feature request? | Y
| Enhancement? | Y

## Description:

Just like you can set colour blocks to categories, it would be good if you could assign a different colour to a tag. 

For example, if you have multiple products, you can set the colours to correspond with the relevant product. This is great as you get more tags through use, and could possibly be implemented with the [tag manager feature request. ](https://github.com/mautic/mautic/issues/2308)

Rough edit using MS paint:
![untitled1](https://cloud.githubusercontent.com/assets/20662188/18592886/e403953e-7c30-11e6-8675-135a4ce9efdd.png)

**Comment by arthurlluiz** [comment]
+1

**Comment by pcantellow** [comment]
Is this going to be marked as a Feature Request? 👍

**Comment by merlin0** [comment]
+1

**Comment by benmautic** [comment]
+1 Tags are really too simple at the moment. They really need to be colour coded and grouped. For example you might break the tags into sections with a label for each. Really need this sort of organisation for segments, emails and campaigns etc also... folders!!!!

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
