### ISSUE TITLE
After contact identified, switch tracking from based on IP to based on cookie!

### ISSUE THREAD

**Issue by abooster** [mautic/mautic#2566]
Continuing to track a contact solely based on IP (after a contact has been identified) and completely disregarding any cookies associated with that contact (or not setting any cookies for that contact in the first place) 
is just plain **WRONG!** 

Please, at least give the Mautic user an option to opt out of this madness. 
Nowadays, cafes, airports, libraries, universities, convention centers, large companies etc. etc. have a large throughput of users all of which share the same IP. 
Who implements a tracking system today that is solely based on IP address??
Answer: **No one!** 
(except the current version of Mautic)

**Comment by mellsaid** [comment]
Agree, just faced this issue today. One contact at a university got a surge of points, apparently a link was forwarded on to may other people in the university... However sometimes it would be helpful to have it by IP. Because eventhough the surge was on that contact, that meant that the lead is becoming more interested with our product to a level that he sent it to other colleagues. If it was based only on cookies, that information wouldn't have been visible to us unless we were able to identify the company name based on IP as shown in request #1164

**Comment by escopecz** [comment]
This was implemented a while ago.
