### ISSUE TITLE
Public/Private Toggle for Email Public Previews

### ISSUE THREAD

**Issue by Kyle-Foley** [mautic/mautic#2578]
What type of report is this:

| Enhancement | 
## Description:

For the privacy of more discerning users, it would be great to have a toggle that allows Mautic users to publish/retract the public visibility of the email public previews. 

As it currently stands, any individual with an internet connection can scrape every email created by any Mautic user by incrementing the mautic/email/preview/## path.
### Steps to reproduce:
1. Go to any Mautic installation.
2. Add **/mautic/email/preview/1** to the end of the URL.
3. Increment the value at the end of the URL by 1

**Comment by Arjoni** [comment]
I think this is a security problem.

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
