### ISSUE TITLE
Relative date value enhancement

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#2607]
| Q | A |
| --- | --- |
| Bug report? |  |
| Feature request? |  |
| Enhancement? | X |
## Description:

In the PR https://github.com/mautic/mautic/pull/1587 and file https://github.com/mautic/mautic/blob/c44c1aba11947e5095c1c7b1063d77fd17461603/app/bundles/LeadBundle/Entity/LeadListRepository.php#L1218 it seems you can add relatives values.
Those relative values are given by transifex keys which means that the **value is different depending on the language**.

``` 'mautic.lead.list.month_last',
'mautic.lead.list.month_next',
'mautic.lead.list.month_this',
'mautic.lead.list.today',
'mautic.lead.list.tomorrow',
'mautic.lead.list.yesterday',
'mautic.lead.list.week_last',
'mautic.lead.list.week_next',
'mautic.lead.list.week_this',
'mautic.lead.list.year_last',
'mautic.lead.list.year_next',
'mautic.lead.list.year_this'
```

Moreover, those values **have to be written manually** in the date field where we "expect" to write in the date format.
## Suggestions

Add the translated relatives values in the dropdown operator. Then no risk that the user has to manage himself the text and by consequence insert error + generate error if mautic is used in different languages.
![capture d ecran 2016-09-29 a 12 03 25](https://cloud.githubusercontent.com/assets/14075239/18949957/df78b500-863d-11e6-817b-3aa411d1eb5b.png)

**Comment by npracht** [comment]
Hi,

I've just think about it cause it's a mess to manage when people are changing the language of the app or if they make a mistake in typing text which is different depending on the language.

### The best would be to have 2 new filters (green circle):
* `since`
* `in`

And that it automatically propose 2 new cells (instead of red):
* `number` (input to select the number of units)
* `timeframe`: hours, days, months, years

**Comment by npracht** [comment]
@dbhurley the way it is existing today is still a source of mistake and very weird way to manage:
- mistake when you write the text
- you need to know all values by heart
- it is using translated values that complicates even more the use (it depends on the instance language, what about if the user has another language ?)

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
