### ISSUE TITLE
Adding and detecting "Country Code" for Mobile Number field in Forms

### ISSUE THREAD

**Issue by amagdy3** [mautic/mautic#2660]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? |  |
| Feature request? | Yes |
| Enhancement? |  |
## Description:

While sending SMS campaigns, it's expected for mobile numbers to have the country code attached to it. While when users are inserting or updating their contact details, in our case, 80% didn't add country code. While means that we have to modify the mobile numbers manually in order to be able to send an SMS campaign.

If we are able to have a form field validation to get the user to choose their country, or automatically detect the country via IP and select it, it'll save lots of headache and would be more accurate in storing user's mobile numbers.

Example is how Trucaller do it: https://www.truecaller.com/
## If a bug:

| Q | A |
| --- | --- |
| Mautic version |  |
| PHP version |  |
### Steps to reproduce:
1. 
2. 
### Log errors:

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
Related to https://github.com/mautic/mautic/issues/1614

**Comment by martinstr** [comment]
+1

**Comment by Luisfmarkes** [comment]
+1

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
