### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by pautena** [mautic/mautic#2718]
Each time I submit a form that is inside a landing page I get a 403 Forbidden.

Failed to load resource: the server responded with a status of 403 (Forbidden)

Our mautic is installed in a digital ocean VPS (apache).
I've used the following line in htcaccess in an attempt to provide origin permissions:

Header set Access-Control-Allow-Origin "*"

The error remains there anyway. Can anyone provide any advice? Thank you.

**Comment by escopecz** [comment]
I'll close this issue because:
1. The issue template was removed. There is missing information about Mautic, PHP version.
2. It more seems like a server configuration error, not a Mautic bug. Please use [Mautic forum](https://www.mautic.org/community/) for your question and provide the link to the form so someone could check the headers.
