### ISSUE TITLE
Error with "Condition based on a form field select value" in Campaigns

### ISSUE THREAD

**Issue by insetic** [mautic/mautic#2725]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? | Yes |
| Feature request? |  |
| Enhancement? |  |
## Description:

In a Campaign, when you try to use a condition based in a contact field value and the field is State, there is an error with the values in the field States, it doesn't load the states names in the lists
## If a bug:

| Q | A |
| --- | --- |
| Mautic version | 2.2 |
| PHP version | 5.6.26 |
### Steps to reproduce:
1. Create a Campaign
2. Select a Contact Source
3. Add and connect a Decision (Request dynamic content)
4. Add and connect a Condition (Contact field value)
5. Select State as Contact field
6. Look at Value field, you'll see the problem

![image](https://cloud.githubusercontent.com/assets/20638806/19289540/85f80e04-900b-11e6-941c-95430864b846.png)
### Log errors:

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by Kyle-Foley** [comment]
This Bug also affects the Time Zone contact field.

**Comment by Ri100** [comment]
The issue seems to have been resolved in the case of Contact field values, however, it is still there with Form field value conditions (see screenshot).

**System Info:**
Mautic v.2.7.1
PHP 7.0.17-1~dotdeb+8.1
Apache/2.4.10 (Debian) 

![image](https://cloud.githubusercontent.com/assets/13216315/24109610/7b334c5a-0d91-11e7-8b1e-b455d6d732f0.png)

**Comment by escopecz** [comment]
This is fixed in 2.9.2. Just tested.
