### ISSUE TITLE
Promote DNC (Do Not Contact) to first class "citizen".

### ISSUE THREAD

**Issue by ipso** [mautic/mautic#2763]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | Y

## Description:
In my opinion, Do Not Contact seems to be one of the most important flags in Mautic. Its critical for ensuring people don't get emailed who don't want emails, and cleaning up lists and such. 

However from what I can tell there is no way to search Contacts based on this flag, nor a way to create a Segment based on filtering for this flag either. 

Additionally, there does not seem to be way to set this flag from a campaign action. For example I would like to create a re-engagement campaign, that if the user doesn't engage within X days, have them marked as Do Not Contact automatically. 

When viewing the segment list, it shows how many contacts are in each segment, this too would be nice to at least split it up by active/inactive contacts. Inactive being those that have bounced or are marked Do Not Contact. This would be really nice so you have a better idea of what to expect when you create a campaign from a old segment that has 10,000 contacts, but only 2000 get sent emails.

**Comment by escopecz** [comment]
Thanks for the suggestions!

There is a Segment Filter for unsubscribed contacts:
![mautic-segment-unsubscribed](https://cloud.githubusercontent.com/assets/1235442/19428667/9dbba2be-944b-11e6-9d12-d8ad21fac587.png)

There is already a feature request for unsubscribed actions: https://github.com/mautic/mautic/issues/2484

There is already a feature request to show count of unsubscribed contacts in a segment: https://github.com/mautic/mautic/issues/2568

So I guess the only feature you request is searching contacts that have unsubscribed?

**Comment by ipso** [comment]
There seems to be a difference between unsubscribed and "do not contact". I have a segment that filters on "Unsubscribed - Email" but it doesn't include the majority of the contacts that are actually marked as DNC... These contacts were imported with DNC though, but I don't quite understand the difference, or why the UI refers to what appears to be the same thing but with different names? unsubscribe and do not contact.

**Comment by escopecz** [comment]
This is how I understand it:
1. "Unsubscribed" means that the contact clicked the "Unsubscribe" link
2. "Bounced" means the message was not delivered to the contact for some reason.
3. "Do Not Contact" means 1. and 2. combined.

**Comment by ipso** [comment]
But the UI just shows Bounced and Do Not Contact of the edit contact screen. Either way it would be nice if you could filter segments and contacts on all of the above, as well as have campaigns set them as actions. Just using unsubscribed is definitely not sufficient when two other options exist.

**Comment by escopecz** [comment]
You are right and that discussion also already exists: https://github.com/mautic/mautic/issues/1970

So I'll close this issue as duplicate.

**Comment by ipso** [comment]
Searching contact list by unsubscribe/DNC would still be a valuable feature, would you prefer that I create a new feature request for just that?

**Comment by escopecz** [comment]
Yes, please. It'll save time in the future when the developer will search for what is this issue about.

**Comment by zenzozen** [comment]
+1 for "Do not contact" action

**Comment by gigcity** [comment]
+1 for "Do not contact" action

**Comment by precords** [comment]
+ for "Do not Contact" action

**Comment by gingerling** [comment]
+1 for do not contact action - especially as it can be used in list cleaning processes like:

We send email to contacts who didn't open last 10 emails (un-engaged) asking if they want to opt-OUT of the emails.
A) some open the email and unsubscribe
B) Some do not open the email
C) Some open the email and do NOT unsubscribe

Those in A are unsubscribe, those in B will be sent a follow up email saying they need to opt back in. Those in stage C will be put in a campaign designed to engage them more.

It seems to me that none of this is possible right now because you can't make actions based on  do not contact status?

**Comment by rmalla** [comment]
Hey, a question here. Do you know where I can edit the soft bounce email to go DNC on the first bounced email? 

I believe the default is after three soft bounces it is added to the DNC, I would like it to be one. 

Thanks, 

Ricardo Malla

**Comment by djmonzyk** [comment]
I agree - +1 for having a campaign action for Do Not Contact.  It's quite silly this isn't part of the core platform.

**Comment by wpon** [comment]
Same doubt of Ricardo Malla above, anyone know where we can edit soft bounces rules?

thanks

**Comment by Woolgoose** [comment]
Isn't there an natural hierarchical order. The most generic flag would be "Do Not Contact".
But there are quite a few completely different reasons WHY somebody should not get contacted.
- He has unsubscribed
- He soft bounced
- He hard bounced
- He never opened an email or visited my site (inactive)
- He is known as a hater (troll, spammer)
- I don't want him to know about my activities (competition)
and probably many other reasons ...

So I think it would be crucial to easily identify and segment these different types in order to treat them accordingly.
