### ISSUE TITLE
Move focus items JS into main mtc.js library

### ISSUE THREAD

**Issue by stevegrant1983** [mautic/mautic#2771]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? | N |
| Feature request? | Y |
| Enhancement? | Y |
## Description:

Rather than forcing users to embed a separate JS file every time a new Focus Item is created, move the functionality into the core mtc.js library. This means that a site only needs to load the core library in order to have full access to all of the Mautic functionality, and it leaves whoever has control of the Mautic system to determine when/where any Focus Items are displayed.

Most modern sites are created using a template system (Twig, etc) built on an MVC framework, so embedding varying JS files into article content isn't a sustainable long-term solution.

If the core library can determine whether the current page URL matches criteria set within Mautic, it can then initialise the JS functionality for any Focus Item that needs to be displayed on this page.

**Comment by lsoldado** [comment]
+1

**Comment by VinCardoso** [comment]
+1

**Comment by vizteck** [comment]
+1

**Comment by robwent** [comment]
The main library already includes video players and other things that aren't always needed on every page of a site.
I would rather nothing else get added and it was cut down in size. Possibly with some kind of module loader to just load the parts that are actually needed.

**Comment by YannickBiet** [comment]
+1

**Comment by wucherpfennig** [comment]
+1

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
