### ISSUE TITLE
Add support for Feedback-ID headers

### ISSUE THREAD

**Issue by Mike-Benoit** [mautic/mautic#2781]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? |  |
| Feature request? | Y |
| Enhancement? |  |
## Description:

Google uses Feedback-ID headers to aid in the feedback loop for complaint handling. It would nice if Mautic could make use of this too:

More information is here:
https://support.google.com/mail/answer/6254652?hl=en

**Comment by deepvoice** [comment]
I am extremely surprised that Mautic is seemingly completely ignoring requests for the ability to add X-Headers. I have seen several unanswered requests and questions in their forums for this.
This is a necessary and in many cases *required* feature to send email today (example: Gmail - Feedback-ID).
Other mailing systems require headers to know how to route email if there are several domains or IPs on the outgoing side.
Am I missing where this is in the documentation or in the software settings somewhere or are these requests/questions truly being ignored?

**Comment by amarjeetsharma** [comment]
I second this request

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
