### ISSUE TITLE
0 unique visits?

### ISSUE THREAD

**Issue by Nizzlay** [mautic/mautic#2801]
| Q | A |
| --- | --- |
| Bug report? | Y |
| Feature request? | N |
| Enhancement? | N |
## Description:

I just noticed that the visitors graph on the mautic dashboard tells me there are 0 unique visitors every single day. Even when there are about 700 visits.

According to Google Analytics and Clicky Analytics there should be around 500 uniques.

![dashboard screenshot](http://i66.tinypic.com/2qjgn50.png)

Installed the tracking pixel using the WordPress plugin (https://wordpress.org/plugins/wp-mautic/)

| Q | A |
| --- | --- |
| Mautic version | v2.2.1 |
| PHP version | 7.0.8-0ubuntu0.16.04.3 |
| WordPress version | 4.6.1 |
| Plugin version | 1.0.1 |
### Steps to reproduce:
1. Install WordPress plugin
2. Wait a few days
3. Look at stats on mautic dashboard

**Comment by DotPropertyGroup** [comment]
I have the same issue with the following setup:
Mautic v2.2.2
Self-hosted Mautic on one domain.
Javascript tracking code setup on 10 other domains.

**Comment by DotPropertyGroup** [comment]
After looking a bit more into it, I noticed the following query was made to generate the graph:

`SELECT DATE_FORMAT(t.date_hit, '%Y-%m-%d') AS date, COUNT(*) AS count FROM page_hits t WHERE t.date_hit BETWEEN '2016-11-01 00:00:00' AND '2016-11-11 23:59:59' GROUP BY t.lead_id, t.date_hit ORDER BY DATE_FORMAT(t.date_hit, '%Y-%m-%d') ASC LIMIT 11`

This returns something like this since the couple [lead_id, date_hit] is unique so the group by is not working:
2016-11-01 	1
2016-11-01 	1
2016-11-01 	1

Instead the following query seems to return the expected result:
`SELECT DATE_FORMAT(t.date_hit, '%Y-%m-%d') AS date, COUNT(DISTINCT t.lead_id) AS count FROM page_hits t WHERE t.date_hit BETWEEN '2016-11-01 00:00:00' AND '2016-11-11 23:59:59' GROUP BY date ORDER BY DATE_FORMAT(t.date_hit, '%Y-%m-%d') ASC LIMIT 11`

Not sure what code to edit though.

Similar issue for the unique vs returning pie chart, which doesn't work in the dashboard but works in the reports.

Hope that helps a bit.

**Comment by escopecz** [comment]
Should be fixed by https://github.com/mautic/mautic/pull/3782
