### ISSUE TITLE
Segments broken for non-admin users in 2.2.1

### ISSUE THREAD

**Issue by ToonGeneral** [mautic/mautic#2810]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? | Y |
| Feature request? |  |
| Enhancement? |  |
## Description:

Since upgrading to 2.2.1 our non-admin users cannot open the Manage Lists page. The browser indicates it's trying to open the link, but the page does not change. Ostensibly nothing happens.

No error code or visual feedback given, nor anything in any of the log locations that I know to check.

Possibly related to #2809, as all segments probably use owner as a filter.
## If a bug:

| Q | A |
| --- | --- |
| Mautic version | 2.2.1 |
| PHP version | 5.6.25 |
### Log errors:

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
While I was testing https://github.com/mautic/mautic/pull/3627, I could get to Masage Segments page. The "New Segment" was not working and that is fixed in the linked PR. Maybe it doesn't work for some role rule. If that's so, please provide use concrete steps to replicate and I'll re-open this issue.
