### ISSUE TITLE
Importing contact with companies fields details ?

### ISSUE THREAD

**Issue by YannickBiet** [mautic/mautic#2831]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? | Yes |
| Feature request? | Yes |
| Enhancement? | No |
## Description:

We can create custom fields for Companies
We can import Contacts
We can't import Companies
Nor we can import companies details with the contact import... we only access the company name field, not the company address fields, not companiy's custom fields.

Am I missing anything ?
## If a bug:

| Q | A |
| --- | --- |
| Mautic version | 2.2.1 |
| PHP version | 7.0.12 |

**Comment by MaxWebmecanik** [comment]
+1 This is a regular frustration points for users that see that they can now use companies in Mautic

**Comment by ronnieduke** [comment]
+1 - Is there any current workaround for this other than using the API? I'm trying to import a list with both Contact and Company data, and my options are either A) discard account data when importing (since there's no place to map it to) or B) re-create a bunch of account fields on the Contact object and just map it there which defeats the purpose of having a company object.

**Comment by tpilet** [comment]
I agree this point it's a bit frustated not to be able import and use full this information

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
