### ISSUE TITLE
Segment membership and Tags  in Email Dynamic Content

### ISSUE THREAD

**Issue by kuzmany** [mautic/mautic#2856]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | y
| Enhancement? | 

## Description:
Dynamic Email is great feature. Segment membership and tags filter will move it to next level ;)

**Comment by kuzmany** [comment]
Due performance issue is shifted to indefinitely 👍

**Comment by zenzozen** [comment]
+1. 

@kuzmany 
I create personas as Segmentations and Tags. 
This is exactly what i need to send different content to different personas.

I cant create a new custom field like "persona" because one person can fit as two or more personas. 

I could create one entire campaign per persona (if tag='persona-x') then do xyz, but the maintance here is not viable, as i would clone the campaign many times as i have many personas. 

Is there another workaround on this?

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._

**Comment by Shirkit** [comment]
@kuzmany why this is such a performance issue? Shouldn't it be just like any other check for the Dynamic Content?
