### ISSUE TITLE
Enhancement - Stream exports to avoid running out of memory with big data sets

### ISSUE THREAD

**Issue by MaxWebmecanik** [mautic/mautic#2920]
| Q  | A |
| --- | --- |
| Bug report? | |
| Feature request? | |
| Enhancement? | :white_check_mark:  |

## Description:

The report export feature has trouble scaling to high volumes.

Looking at the code, it seems to me that the data is queried and stored as a whole in the memory.

> https://github.com/mautic/mautic/blob/staging/app/bundles/ReportBundle/Controller/ReportController.php#L786

And finally, when all the results are fetched by the query, if there is not enough memory to store all of the soon-to-be-exported data, then the request goes 500 and no message is given to the user.

> https://github.com/mautic/mautic/blob/staging/app/bundles/ReportBundle/Model/ReportModel.php#L601

Would it be possible to stream the export file in chunks to the user, possibly line by line, thus avoiding the `fetchAll` which isn't very memory friendly and allowing arbitrarily large exports?

Do you guys have any idea or leads on how to achieve this in Symfony? Is [**this**](http://symfony.com/doc/current/components/http_foundation.html#streaming-a-response) what we would need?

## If a bug:

| Q   | A |
| --- | ---
| Mautic version | `2.2.1` |
| PHP version | `5.6.27` |

### Steps to reproduce:

1. Make a report with a substantial amount of data
2. Optionally reduce PHP's `memory_limit` to encounter the problem faster
3. Try to export the report
 
### Log errors: 

    [2016-11-09 10:10:26] mautic.ERROR: Error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 512 bytes) - in file path-to-mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php - at line 128 [] []

**Comment by npracht** [comment]
Hi @alanhartless @escopecz @matishaladiwala !

Our dev has been working on contact export optimization (https://github.com/mautic/mautic/pull/3819) and we can now go over 10 000 contacts export which is great.
We noticed that we anyway have issues because **the stream is too long and apache workers get killed** at a certain time.

### Where we need your opinion
We were thinking that we maybe should be working on a background export. And now that @escopecz is working on something similar for contact import (https://github.com/mautic/mautic/pull/4067), we think that the export feature should be inspired by your work Jan.

#### What do you think of

1. Select contacts to export
2. Click on Export
3. If under 10 000 contacts it goes for live download
4. If over 10 000 contacts it goes for background export
5. User will receive an email with zipped export on attachment

#### Let us know if

1. You agree
2. It should be included in your work Jan
3. Or worked aside (we could take the lead)

**Comment by escopecz** [comment]
Yes, I think that the background job is the only way around it. #4067 focus is on import.

**Comment by MaxWebmecanik** [comment]
Hi @escopecz,

After talking with @matishaladiwala, we agreed we would start working on exporting using a background process similarly to what you are doing in #4067.
Looking at that PR, it looks to me like you're now in the process of testing it out.
Do you think we can start working on top of your branch so as to make something that follows the same UX?
Do you have any word of advice before we start?

**Comment by escopecz** [comment]
I don't see any reason why to use #4067 as a base. But if you see there anything you could use, feel free to use it.

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
