### ISSUE TITLE
Add multiple email templates 

### ISSUE THREAD

**Issue by zhakid** [mautic/mautic#2923]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? |  Y
| Enhancement? | 

## Description:
Add multiple email templates (e.g. a transactional template and a newsletter-style template)

**Comment by RCheesley** [comment]
Maybe I can add a bit of clarification here :)

Often people will want to be able to use their MA system to send different types of emails.  Some might be short and sweet 'transactional' emails but others might be more in-depth 'newsletter' emails.

Currently the only way to provide this as a template is to provide two entirely separate themes, because it is only possible to include one email template per theme.

Clearly if you have multiple permutations of email templates this could quickly get a bit unwieldy!

The suggestion would be that you could have some way of providing multiple email templates (and indeed perhaps multiple landing page layouts) within a single theme.  This would allow greater flexibility and negate the need for entirely separate themes when adding different email templates.

From a user perspective I would expect that you could choose the theme you wish to use, but then a dropdown box shows you the available templates in that theme - so you choose the 'Amazing theme' via the usual UI, the button changes to 'Selected', and then a conditional field displays which allows you to specify which specific email (or landing page) template to choose for that particular email/landing page.

**Comment by phil-veloso** [comment]
I am currently encountering this issue, whereby we have 5+ email templates with various designs. Has anyone found a solution to this issue or must I use repeated themes?

**Comment by RCheesley** [comment]
@phil-veloso as far as I know you would currently require a separate theme for each one. Crazy huh!

**Comment by benfavre** [comment]
Could we explore this again ? @RCheesley

**Comment by RCheesley** [comment]
@benfavre absolutely - we would need a PR to add the functionality, but if you wanted to just discuss it as a feature request and don't have any code to accompany it yet, please open a thread at https://forum.mautic.org/c/ideas.
