### ISSUE TITLE
Reports - lead conversion path and stats

### ISSUE THREAD

**Issue by versadial** [mautic/mautic#294]
under reports, is there a way to see the path of a lead? example. Take all the form submissions, and run a report on what their typical path is. Index Page > Product Page > Pricing page > Form submission....and see based on lets say 50 leads, what was the optimal path they took (I know google kind of does this...but I never know how accurate that is).

Also, expand on that and have a trend report of Lead becoming Customer (I would think we need to add a Form field of status? maybe I am not seeing it, but a field that labels a person a lead and then a  customer) so you can see, 80% of people who become customers visit this page, this page, and then this page. This way, when putting together an automation strategy, you try and lead those prospects to those pages, so if a prospect fills out a form, but never visited two pages that typically convert a person into a customer, you can email them over time to go and visit those pages and try and encourage that optimal path.

**Comment by alanhartless** [comment]
We don't currently have such a report but beefing out the analytics of the system is definitely on the road map. 

Curious on what that report would visually look like? Since sessions are tracked, we could probably do a report that would show page hits and the percentage of leads that hit the pages up to the point of submitting the form. That would be easy enough and gives somewhat an idea of the path taken.  To get a typical path taken though may take some creative code, not only comparing percentages of hits but comparing sequential order as well.

We are working on a tags feature (not out yet) that could probably assist with the second type of report. You could tag the lead as a customer then we can use that in the reporting system.

**Comment by versadial** [comment]
Hi Alan

I agree...typical path in order (sequential) may be difficult (and maybe not necessary)...but I think you are on right track about providing at least the top pages that lead to prospects...and then with that tag integration you guys are thinking of adding, it could just back-track and provide the top pages that created customers. This will provide a rough idea as to what pages need to be enhanced, reviewed, maybe AB tested and also attempt to get in front of prospects through campaigns.
