### ISSUE TITLE
Error 500 on unsubscribe page

### ISSUE THREAD

**Issue by Nizzlay** [mautic/mautic#2951]
| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
I got a few complaints that people get an error 500 when they try to unsubscribe.

By the looks of it they are set to "do not contact", so not sure when it goes wrong.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | v2.2.1
| PHP version | 7.0.8-0ubuntu0.16.04.3

### Log errors: 
Server guy told me there's nothing in the nginx logs, while error 500 stuff should be there.

**Comment by escopecz** [comment]
Check Mautic logs https://mautic.org/docs/en/tips/troubleshooting.html

**Comment by escopecz** [comment]
I'll close this issue as the question hasn't been answered for a while. I'll re-open when it does.

**Comment by johbuch** [comment]
Hi @Nizzlay @escopecz 
in case I also have the issue. 500 error when i clicked on unsubscribe but I was as a do not contact in Mautic.
I found that in my client's template, it was missing 2 files on his template. 
The:
base.html.twig
message.html.twig

I added it into the theme and the problem was solved.

**Comment by vdavid** [comment]
Thanks a lot @johbuch 
I had the same issue, and your tip fixed my problem immediately.
I with at least there were some error messages about this in the log.
