### ISSUE TITLE
Allow bulk-change of category for resources & improve UX on individual changes

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#2983]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | x
| Enhancement? | 

## Description:
There is currently no way to bulk-change categories which makes it very time consuming.  I would suggest an ability to select with the check boxes and bulk-change resource categories.

Furthermore, it takes four clicks to change a category (using forms as an example) which is in my opinion a bit of overkill - can we make it possible to change categories more easily (maybe from within the form list, or from on the preview page?)

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
