### ISSUE TITLE
Add reply-to option for send form results action

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#2984]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | x
| Enhancement? | 

## Description:
As flagged in #2967 there doesn't seem to be a reply to option for when using 'send form results' and the customer's email is automatically used. For some use cases that would be fine, but we should offer the option to manually set the reply-to address if we can.

**Comment by wbuist** [comment]
In our workflow we use this email to share form data with the appropriate team member, the workflow should not be exposed to the person filling out the form as it includes internal activities. So we pass the data to the team but do not copy the person filling in the form with the toggle. Even though they don't get sent the email the mail to our team has a reply to address of the person.

If the team reply to an email rather than forwarding the reply is inadvertently exposed to the person filling in the form. If we toggle the 'send to contact' to 'No' then the reply to address should be the owner of the Mautic installation.
