### ISSUE TITLE
Sort campaign actions overview by (relative) date

### ISSUE THREAD

**Issue by Nizzlay** [mautic/mautic#2985]
| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | Y
| Enhancement? | 

## Description:
If you have a campaign, and take a look at the overview (non edit mode) you see all the actions for this campaign, and some statistics for those actions.

Currently (v2.2.1) this overview seems random.

![Screenshot](https://s16.postimg.org/6lkhbxowl/Screenshot_2016_11_21_14_20_25.png)

Would make a lot more sense if the overview was sorted by when those actions occur in the campaign

**Comment by gingerling** [comment]
+1

**Comment by gingerling** [comment]
Similar with https://github.com/mautic/mautic/issues/5490

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
