### ISSUE TITLE
Error when editing blank theme emails

### ISSUE THREAD

**Issue by marziovit** [mautic/mautic#3032]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:

After mautic 2.3 update I can't edit my old e-mails. I always used the blank theme and in the past I could edit the e-mails without the builder. Now, this option is gone and the builder don't let me edit the e-mails. Please restore the ability to write emails without the builder.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.3
| PHP version | 

### Steps to reproduce:
1. you should have a previously created email with blank theme
2. edit the email
3. select builder
3. there's no way to edit a previously created email
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by dotsi** [comment]
Note I am using the hosted version:
Since the 2.3 upgrade the usability of email editing has dramatically decreased.
I understand that in order for the Froala editor not to mess with custom html code it needs to be disabled. And that is fine for the emails that use the new Code mode option.
But why is there no editor for normal modes where you select a theme?
Within builder you can only edit the editable areas, but previously you could edit the whole html within the Content tab.
Since there is no way to delete sections in the Builder, the wysiwyg editor was the only option to delete/modify parts of the template while still keeping it editable. now this is not possible anymore.
Please restore the ability to write emails without the builder.

**Comment by Getron** [comment]
If i try to edit my Emails like in v2.2.1 (not only the blank theme, but all other themes and emails), and i go to Emails - Theme, select the theme, and the "Content" tab is not there, is not showing. It has just the text body, but not the editor.

I have tryed many times to update, manualy, and automaticaly, but no luck, updating works ok, no problems there, but the "Content" tab is not showing, and not able to editing with froala editor like in v2.2.1, just with the Builder, but, Builder give me not all the options like editing in "Content" tab in v2.2.1, for example, a code view switching, and back to WYSIWYG editor.

I know there is a new Code mode, but, this is not so great, because of missing editor there. It would be great, if Code mode would have the editor implemented on it, and able to use both, code mode manualy, and, if needed, editor to.

Why is this "Content" Tab disabled, or deleted on new version?

**Comment by alanpy** [comment]
I agree the Editor is very limited, and the code editor is not user friendly, simple tasks like copy/paste text, bold, break line, insert image, change links are now a headache. 

We use the hosted version (mautic.net) and there is not choise to use the previous version 2.2.1, or to upload new themes... we are limited to 5 specific themes that come with platform, it are not responsive and cannot delete sections.

Before the update we can simply duplicate an previous email we created and edit it using de "Content tab" by the WYSIWYG. 

Just some clics to create and send a new email to the list.

I wonder if there is a way to keep old funcionality and when choose the "code editor theme" hide the content tab?

Thanks

**Comment by escopecz** [comment]
@alanpy the suggested way is to create your company's theme and use that as a starting point for your emails and pages. You can upload your theme to the hosted version via the Theme manager. 

https://developer.mautic.org/#themes

**Comment by dotsi** [comment]
Is there some communication on an Issue or somewhere else that would help me understand the reasoning behind these changes?
The only thing I found is that some people had problems with the Froala editor stripping some html tags from the html they insert in the code view. So I guess this is why the "Code editor" option was created. 
But why was the wysiwyg editor removed from when you choose a template? Right now we would need to create several versions of the same template since there is no way to edit the html unless you convert it to Code editor.
Just imagine this simple use case: 
You have a long email template with several sections. Only a few of them get used when a single email is created. Since there is no option to delete sections in the Builder you now need as many themes as there are section combinations.

**Comment by escopecz** [comment]
@dotsi check https://github.com/mautic/mautic/pull/2653 (also see Slack discussion linked there) and https://github.com/mautic/mautic/issues?utf8=%E2%9C%93&q=is%3Aissue%20froala%20

There is no way we can let Froala edit the whole HTML document again. It is unstable and the issues created because of it would never stop coming. So we have to use Froala (or any other WYSIWYG editor) to only edit the content, not the whole layout. The layout must be composed in the builder. You are right it's lacking some features like adding / moving / removing sections, but it is coming.

**Comment by alanpy** [comment]
@escopecz I did not know I could send themes. I'll check it, thank you.

**Comment by Getron** [comment]
@escopecz Is this an warning, that we can't have any of WYSIWYG editor in next versions of mautic? Just the code editor, without almost any editor in it? If yes, this will be a terrible decision for almost all users of mautic.

**Comment by escopecz** [comment]
I'm not in a position to give any warnings :) I stated what the problem was, why the Content tab was removed. Let's discuss the solution.

There is the Builder where you can select a theme and drop the Text Slot and have an WYSIWYG editor in it.

Let's consider Mailchimp for example. It is a service which most of the marketers like for easy content editing. I can't find a full HTML document WYSIWYG editor option there. Does any other email or landing page service or tool have this option? I haven't seen it anywhere. 

Content tab was added in Mautic 2.0.0 and it caused troubles for many community members, so it was removed and the Code Mode was added for people who build their content elsewhere.

**Comment by Getron** [comment]
@escopecz but, why we can't hold both, content tab, and the code mode, and the users should decide, if they want content editor, or code mode?

**Comment by escopecz** [comment]
Maybe it would help if you'd read the previous discussions I linked to get the sense of why the two couldn't exist together. If there was a switch and one user would use the code mode for precise HTML and other would edit the same content the WYSIWYG editor, the editor would modify the HTML and the precise HTML which the first user needed would be gone. So we would still be dealing with the full HTML document WYSIWYG editor issues all the time and couldn't invest the time to other development instead. The full HTML document WYSIWYG editor was unmaintainable.

**Comment by marziovit** [comment]
@escopecz have you guys looked at how [this is done in sendy](https://sendy.co/demo/edit?i=2&c=37)? Why can't we have something like that? Tinyletter is another minimalistic app that uses both WYSIWYG editor and HTML editor.

**Comment by Rovel** [comment]
Hi, first thanks for the great tool, in my opinion the best open source automation by far, I'm kind of new in Mautic itself so I just need some help here to know if the only way to change the email's text font type is going to the source code since the builder don't have this option yet or I'm just missing it somewhere?

**Comment by onconcz** [comment]
I would also like to see the email editor soon.

**Comment by amarjeetsharma** [comment]
Email editor is an essential part for marketers like me

**Comment by R3SETInc** [comment]
Yes. I completely agree that this was a bs decision. Even creating an "advanced editor" option would have worked. 

The worst part of the change is that I can't edit my existing emails and as a result  of that this change has literally broken my ability to use the tool for an active funnel and tweak the copy. It's infuriating.

**Comment by R3SETInc** [comment]
This also broke the ability for me to center the text and images in my emails.....

**Comment by michaelbdana** [comment]
I can no longer clone my old emails and use it to make a new one. Can't edit the old and can't edit the new. Now I have only 2 options:

1. Learn how to create a new email template.
2. Replace Mautic all together.

**Comment by marziovit** [comment]
@escopez could you please let us know what you guys think? Are you going to do something about this issue or it will be code mode only from now on?

**Comment by patmifsud** [comment]
A warning to users pre upgrading that they will loose the ability to edit all existing emails in WYSIWYG may have been a good idea imo. Html knowledge isn't a requisite for most marketing automation tools, and setting up custom templates takes time that people may not have spare this week. So many people don't read change logs these days. A planned and informed update to 2.4 should be better for everyone, but if you don't know that you'll be locked out of properly editing all your existing emails, some of which are live in a campaign, that would come as a bit of a shock. Not to mention that this update, to be best of my understanding, is forced on hosted users? 

What is the quality control/ vetting process for Mautic currently?

**Comment by dotsi** [comment]
Like with many open source projects the problem seems to be that the people that make decisions and understand the reasoning behind them are developers. Even most of us complining here are not the people that use Mautic for marketing every day. This is boring stuff and people build routines to be able to focus on content and not play with marketing tools all day. In my opinion this is where Mautic falls short for now. 
I guess it is safe to say marketers spend much more time in the email or page builder then they do in the campaign builder. And still the campaign builder gets most of the attention. 
In my opinion it would be best to just copy working concepts from companies that have spent a lot of time perfecting it because they know what actual users want(not just technically savvy early adopters) and taught them what to expect. Probably nobody that posts issuses on Github is your average user, so most of the changes are implemented  for a small subset of users but they affect the average user much more. 
A few skilled users are happy that they can edit the source now without trouble but most of other users have to forget the workflow that they learned and go back and learn a much more complex one.

**Comment by quentinpain** [comment]
Mautic is primarily for me an email marketing platform. I have campaigns set up with multiple email sequences. I could tweak those emails before to optimise campaigns, but am I right in thinking that is no longer possible? Is there a way this can be done? or will it be allowed again - as Marziovit mentions at the top of this thread? I love Mautic, but this is a bit of a spanner in the works for me (I'm on the paid commercial version by the way so have no access to the code). Thank you all.

**Comment by appscaptain** [comment]
Why has this been closed? There's no solution. So if you have 30 mails you have to rebuild them all from scratch?

**Comment by escopecz** [comment]
@appscaptain This issue hasn't been closed.

**Comment by maxmeinberg** [comment]
Every time a edit a new email the builder gets these scripts errors:
Uncaught SyntaxError: Invalid or unexpected token
Uncaught ReferenceError: mauticLang is not defined
Uncaught ReferenceError: mauticAjaxUrl is not defined

I'm using English as the user language.

**Comment by recklessop** [comment]
I am having this issue as well. I created the email a while ago. I went to edit it today, but I am unable to do so.

**Comment by RCheesley** [comment]
Closing this issue as it hasn't had any recent activity
