### ISSUE TITLE
Replace cron-based rebuilding with event-based one

### ISSUE THREAD

**Issue by PatchRanger** [mautic/mautic#3058]
| Q  | A
| ---| ---
| Bug report? | n
| Feature request? | n
| Enhancement? | y

## Description:
I have not extremly large though quite big Mautic database - about 8 GB.
The problem is that my crons grab all of the hosting resources - and hoster by that reason sometimes cuts Mautic processes off.
I've mentioned already [here](https://github.com/mautic/mautic/issues/2449#issuecomment-264443918) that we already switched to archive pricing plan in order to satisfy (quickly growing) Mautic database CP hunger - but nevertheless the limits got exceeding again.
The hoster gave me slow queries log: it looks homogenous - it means that Mautic team have already optimized database load by creating indexes where they are needed.
So the problem is: database load is extremely high - but there is no non-cardinal way to optimize.

## Suggestion:
I suggest to replace cron-based rebuilding with event-based one: competely remove cron-jobs - having "subscriber-notifier" pattern implemented instead.
It means:
- Each time a contact is created/updated/deleted, it notifies segments. Segments (according to their own logic) decide whether to add this concrete contact to them or delete.
- Each time a segment adds/removes a contact, it notifies segment-based campaigns. Campaigns trigger their own set of actions - applying to that individual contact.
- Form-based campaigns get triggered after new form submission.

That's it.

Pros:
- Fixes #2870.
- **Much more cost-effective**: No more endless rebuilding, which consumes lots of CP even at idle.
- **"On-the-fly" reaction**: By the way, such approach would make it working immediately - not "in about 1-2-3 minutes" (waiting while required segments and campaigns get rebuilded) as it behaves now.
- **Push forward to State Machine**: See #1930.

Cons:
Can't see any.

**Comment by kuzmany** [comment]
👍

**Comment by zenzozen** [comment]
+1
It would be a huge improvement!

**Comment by zenzozen** [comment]
I am abandoning mautic because performance issues (300.000 contacts). 
Sadly. Mautic is a very good tool, but cant handle too many contacts with this cron-based rebuilding approach.  =(

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
