### ISSUE TITLE
Bulk import of Contact Notes

### ISSUE THREAD

**Issue by zenzozen** [mautic/mautic#3090]
| Q  | A
| ---| ---
| Bug report? | N
| Feature request? |  Y
| Enhancement? |  N

## Description:
As an user migrating to Mautic tool, it would be nice to bulk import NOTES of contacts. 
- UNIQUE field | Note text | datetime | type | owner (separated by pipe or another special char)

If one contact have several notes just make another rows with same unique identifier
- john@mail.com | I said Merry Christmas | 2016-12-25 10:00 | general | enzo
- john@mail.com | Contact to say Happy New Year | 2017-01-01 10:00 | email | enzo
- alice@mail.com | Called to say Happy New Year | 2017-01-01 15:00 | call | enzo

If possible, just make the unique, note text and date mandatory. If someone import like this below, system would recognize like "general" and no owner
- alice@mail.com | Called to say Happy New Year | 2017-01-01 15:00

**Comment by jordan8037310** [comment]
I wrote a script in Python that reads contact notes from a Google Spreadsheet Call Log and INSERTs them into Mautic DB. I can open source this if there is some general interest.

**Comment by qarlyblue** [comment]
I need your help @jordan8037310 
I want to import a lead from my DB to Mautic DB

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
