### ISSUE TITLE
Add Contact to segment When contact is created

### ISSUE THREAD

**Issue by kuzmany** [mautic/mautic#3105]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | n
| Feature request? | y
| Enhancement? | n

## Description:
New option to segments add contact to segment when is contact created
https://github.com/mautic/mautic/blob/afb4da4491ac2f12e8500d504906bd20f8ff47ee/app/bundles/LeadBundle/Model/LeadModel.php#L679

### Why we need this?
If we want use dynamic content we want work with contact after first visits.  
Campaign need 2 crons for execute that (mautic:segments:rebuild and mautic:campaign:update)
With this option we are able to work with contacts after first touch, because is activate onLeadListChange process https://github.com/mautic/mautic/blob/afb4da4491ac2f12e8500d504906bd20f8ff47ee/app/bundles/CampaignBundle/EventListener/LeadSubscriber.php#L123-L123

![add contact](https://cloud.githubusercontent.com/assets/462477/21221318/2dd98420-c2bd-11e6-8550-6e7e676d0472.PNG)

**Comment by alanhartless** [comment]
If memory serves me right, I believe we used to do this and backtracked because of performance. Every time a contact is created or updated, we have to loop over every (or configured in this case) segment and query to see if the filters apply to the contact. It's heavy - which becomes problematic if the contact is created during a web request such as a form submit or a page hit.

**Comment by kuzmany** [comment]
@alanhartless Yes, but contact is created just with first request (visits, form), maybe it's worth it.

**Comment by kuzmany** [comment]
@alanhartless and this option will be disabled by default.

**Comment by PatchRanger** [comment]
Looks related to #3058 . Defintely, it could be the first step in order to go forward to #3058.
