### ISSUE TITLE
Google Analytics UTM Codes for channels (email, web notification, dynamic content..)

### ISSUE THREAD

**Issue by kuzmany** [mautic/mautic#3106]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | n
| Feature request? | y
| Enhancement? | n

## Description:
Google Analytics for emails means add utm_source, utm_medium, utm_camapign emails.
The easiest way is add these parameters to links just for emails to redirectAction

https://github.com/mautic/mautic/blob/cd0b1cf466b1e0fee240f779cd83bf12545ee207/app/bundles/PageBundle/Controller/PublicController.php

To Configurations > Emails we should add  new fields for default values 

- utm_source = mautic
- utm_medium= email
- utm_campaign = category or name or alias of the email
- utm_content = name or alias of the email

**Comment by alanhartless** [comment]
I like the idea of this but I'm not sold on the global configuration idea. Each email will serve a different purpose and I'm betting that many will want the utm_campaign to be the name of the campaign the email is sent from.

So thoughts on this - instead of a global configuration; what if we add it to a section on the email's advanced tab? We'll need an array type utmTags (be sure the column is utm_tags) added to the email entity (with a migration for upgrades). You can still have a default section in the global configuration if you want but we'll need the ability to override per email to make this feature useful I think.

Then you'll want to update these two methods to accept a new parameter of array query params to append to the redirect URL. https://github.com/mautic/mautic/blob/afb4da4491ac2f12e8500d504906bd20f8ff47ee/app/bundles/EmailBundle/EventListener/BuilderSubscriber.php#L258
https://github.com/mautic/mautic/blob/afb4da4491ac2f12e8500d504906bd20f8ff47ee/app/bundles/EmailBundle/EventListener/BuilderSubscriber.php#L260

Thoughts?

**Comment by Getron** [comment]
@alanhartless This would be great to have.

+1

**Comment by kuzmany** [comment]
@alanhartless  yes, that's sound clearly. I will look on it.

**Comment by kuzmany** [comment]
Speed up developement: https://www.bountysource.com/issues/40092771-google-analytics-support-for-emails?show_profile_modal=1
