### ISSUE TITLE
Error about config.json on Importing a New Theme

### ISSUE THREAD

**Issue by nickian** [mautic/mautic#3178]
When I go to "Themes" and try to upload a theme I've created, I get this error: 

"The theme you tried to install doesn't have the config.json file in the root folder. The theme could not be installed."

But there IS a config.json file in the root folder. The themes work fine if I manually FTP the folder into the themes directory, but I can't seem to upload a zip file. I made sure php-zip was installed and the folder is writable for www-data, permissions set to 755.

This doesn't seem to be an issue with my theme structure. I tried downloading the "Goldstar" theme and renamed it to "Test," then tried to upload, but the same error occurs.

Am I missing something here?

Thanks.

**Comment by escopecz** [comment]
I tried to rename the Goldstar theme and it worked for me. Try it out:
[renamed-goldstar.zip](https://github.com/mautic/mautic/files/686642/renamed-goldstar.zip)

What I think is the problem is that in the zip root folder you have a folder and in that folder you have the config.json file. There shouldn't the the folder, but the theme files directly in the zip file in the root of the zip file.

**Comment by nickian** [comment]
No, I have the config.json in the root of the folder I'm zipping.

When I download your zip example, it imports fine, but if I unzip it, then (on Mac OS) compress the folder back into a zip and try to import, I get the same error. Is this something to do with how Macs zip files?

**Comment by nickian** [comment]
Ahh, ok, I figured it out. You're right, you can't just zip the folder itself. You have to select the individual files and compress them. I didn't realize it is essentially putting a folder inside of a folder when you zip a folder.
