### ISSUE TITLE
FR - API Get Company Events

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#3191]
| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | x
| Enhancement? | x

## Description:
It would be great to be able to export via API the events of all the contacts from a same company.
The same as https://developer.mautic.org/#get-contact-events but for companies.

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
