### ISSUE TITLE
Shortcode Email - First Name (First Word)

### ISSUE THREAD

**Issue by andersonojope** [mautic/mautic#3217]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | Yes
| Enhancement? | 

## Description:
In the forms I do not use the first and last name fields, only one field that I call the first name. (This is common here in Brazil)

It turns out that some people end up putting the first and last name or even the full name when filling in the field.

I would like to know if the shortcode that pulls the name of the lead when we send personalized emails has to pull only the first name, ie the first word registered.

Ex. For 'José Carlos' >> Pull only the 'José'.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by maxitromer** [comment]
mmm, Aweber has this feature.

When you use the 'name' var in an email they replace the complete sentence that the users put in the input of the form for that var like mautic do.

But if you use the 'first_name_fix' var in an email they put only the first word all in lower case but the first letter of that word in upper case.

Thats an interesting way to solve it because if you have the firstname and lastname works and if you have only the firstname will works too.

**Comment by ahfauth** [comment]
I would be interested in this feature as well @andersonojope 

How did you solve this in Mautic? I don't want to create a javascript on my website for this because it doesn't work for AMP pages.
