### ISSUE TITLE
Option to resubscribe lead from administration

### ISSUE THREAD

**Issue by ondraknezour** [mautic/mautic#323]
There should be user accessible way to reset do-not-contact flag for the lead. 

Consider following phone call between salesman and customer:
- We also send news and useful resources to our customers occasionally and over 80 % like it
- Sounds great, may you also add me to the list?
- Sure, wait a second... Eh, sorry, I see you was already subscribed and now you have do-not-contact flag and there is not any button to reset it. But you can of course call us weekly to ask if we have something useful for you :)

**Comment by alanhartless** [comment]
There is a link available, as /email/resubscribe/{idHash}, where {idHash} is the same as in the unsubscribe link.  It's displayed on the page when they first unsubscribe.  But you are right in that we need to make it a bit more easily accessible for the user.

**Comment by yyil** [comment]
UPVOTE

**Comment by marciomourao** [comment]
Please this function is very important, it would be so simple, so was the Lead enroll in a new form for the tag "no contact" be excluded automatically. This is the default behavior in most email marketing tools.

**Comment by gabrielwohlfart** [comment]
I miss this feature.
Of course it would be interesting the administrator can remove the tag does not contact but should also be made based on lead DECISION ON sending a new form for example.

Since this is the standard adopted by most popular automation systems market.

**Comment by zstephen** [comment]
Is it possible for a user who is flagged as Do not Contact to resubmit their email in a form and then receive a double opt in email confirming that they previously unsubscribed but are welcome to resubscribe? This would show concern for not spamming them, and also make it easy for them to go back on lists.

What happens if a lead wants to be removed from only one list, but they want to stay on others, they can click unsubscribe, but is this global or specific?

**Comment by quentinpain** [comment]
I've just had the same thing happen today. The customer forgot they unsubscribed and is now 'desperate' to get updates again. Is there a resubscribe link we can use to send them? Thank you.

**Comment by escopecz** [comment]
Resubscribe link is the same as unsubscribe link. If they are unsubscribed, Mautic allow them to subscribe again.

**Comment by marciomourao** [comment]
and why not through a form? Why not? All other email systems work well ...

**Comment by escopecz** [comment]
You are the first one to request such feature as far as I know. Please, create a new feature request for it. It could be done via a new standalone form action or campaign action, right?

**Comment by marciomourao** [comment]
guy does not believe I am the first person! yes standalone form action or campaing does not matter if the lead preecheu any form is because he wants to go back to correct the list, it's obvious!

**Comment by quentinpain** [comment]
Escopez - that worked - I told my customer to find the email they used to unsubscribe, click the option again and see if they can resubscribe - and it worked. This is just to let anyone else reading this know how to do this.

**Comment by ipso** [comment]
A separate re-subscribe link like @alanhartless mentioned (though when I tested I got an error, so I assume it may not exist?) would be really nice, especially for re-engagement campaigns.

**Comment by escopecz** [comment]
"Option to resubscribe lead from administration" is in Mautic for some time. Closing this issue.

**Comment by kgroveshok** [comment]
Just noticed in 2.7.1 that if I unsubscribe from the link in the email, I can't then use admin control (the preferences on the lead) as the check box for the preference seems to get lost on submission and has no effect. Using the changed unsubscribe link to resubscribe in the email does work as said above.

One further point I notice too that if I switch off a users preferences via admin it does show as a DNC and the same method can unset it back the same way which is contrary to what happens if the user clicks on the unsub link.

Can anyone confirm this please? Ta
