### ISSUE TITLE
Segment filter condition tag input: Add an option to change a way it joins them (AND (require all) or OR (require at least one))

### ISSUE THREAD

**Issue by PatchRanger** [mautic/mautic#3238]
| Q  | A
| ---| ---
| Bug report? | -
| Feature request? | -
| Enhancement? | +

## Description:
It's not clear what logical operator joins multiple tags listed in the same input of segment filter condition: does it means it requires to have ALL of the tags at the same time or just AT LEAST one of them?
I guess, it would be better to have an option to choose which behavior is used in each particular case having the one chosen by default: it will give the idea of how it works by default - together with an option to choose such behavior.

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
