### ISSUE TITLE
"Brackets" for prioritizing segment filter conditions order of execution

### ISSUE THREAD

**Issue by PatchRanger** [mautic/mautic#3239]
| Q  | A
| ---| ---
| Bug report? | -
| Feature request? | -
| Enhancement? | +

## Description:
It's not clear what is the current order of execution: are all the conditions executed one by one in the order they listed - or they respect the [operator precedence](http://php.net/manual/en/language.operators.precedence.php) (AND goes earlier than OR)?
It would be great to have a way to set explicit order of execution of segment conditions. It could be some kind of "brackets" or we could turn flat list of conditions into tree which could be edited just by drag'n'drop.

**Comment by dbhurley** [comment]
I really like this suggestion.

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
