### ISSUE TITLE
Invalid Login entry on mautic logs for integration with fail2ban

### ISSUE THREAD

**Issue by ikolubr** [mautic/mautic#3287]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | X
| Enhancement? | 

## Description:
Add an entry on the mauitc logs for invalid credentials with source IP so we can create a filter for fail2ban to ban the ip.

**Comment by luizeof** [comment]
+1

**Comment by luizeof** [comment]
@escopecz @alanhartless this is a critical feature for mautic security.

**Comment by migrivas** [comment]
+1

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
