### ISSUE TITLE
Is there any Advanced lead search in development? 

### ISSUE THREAD

**Issue by Fauvette** [mautic/mautic#3288]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | Feature request
| Enhancement? | 

## Description:
The more details the better...

When one is searching for a specific contact, you only get it by country, company or name. I'd like to have an advanced search with multiple filtering right on the contacts page.
## If a bug:

| Q   | A
| --- | ---
| Mautic version |  2.4.0
| PHP version | 5.6

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
Please update the issue description with more details about the feature you want. This is not a description anyone can implement because everyone will imagine different behaviour and look with "advanced search" and "multiple filtering".

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
