### ISSUE TITLE
Add segment filter: form submission

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#3293]
| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | x

## Description:
**Add the filter form submission:**
* any form
* +list of form

**Comment by npracht** [comment]
cc @kuzmany i think this topic is also very close to https://github.com/mautic/mautic/pull/2912

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
