### ISSUE TITLE
CSV Import of contact custom field structure

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#3299]
| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | X
| Enhancement? | 

## Description:
When you already have a CRM, it is sometimes a long time to create the structure of contact and companies.
It would be a great feature to import a CSV file structured to create all the custom fields at once (like the contact import page). With the following fields:
* Name
* Alias
* Type
* Default value
* Possibles values (for select type)
* etc.

# How to
1. Create file well structured
2. Import
3. be happy with all your created fields

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
