### ISSUE TITLE
Feature Request: Mautic integration with MS Dynamics CRM Online (2015)

### ISSUE THREAD

**Issue by jesseavtech** [mautic/mautic#331]
Hi Mautic Team

I love your product and I'm trying to get the best use out of it.  To do that I really want to be able to push leads into our CRM, MS Dynamics CRM Online (2015).  Microsoft Partners can get internal use licenses for this product without cost, whereas we can't afford Salesforce, which is quite expensive, as you know.  I wish everything was open-source.

It would be great to see some integration in the next release!  Thanks so much guys!
Jesse

**Comment by karo2204** [comment]
Like to have this integration too. My company uses MS Dynamics and it would be good if the generated leads and leads from Dynamics gets synced.

**Comment by drobotiks** [comment]
Was trying to pitch this product to my company and the first question they asked was, "Does it integrate with MS Dynamics?". Can you look into adding this feature? Thanks in advance.

**Comment by alirobe** [comment]
Dynamics CRM has a great little ODATA REST endpoint (organizationdata.svc) which should be fairly easy to write an integration against - https://msdn.microsoft.com/en-us/library/gg334767(v=crm.6).aspx

**Comment by jordan8037310** [comment]
A client of ours has requested we look into moving this integration forward. 

Did some research for PHP SDKs / examples with Microsoft Dynamics, and we can potentially leverage https://github.com/AlexaCRM/php-crm-toolkit in order to integrate this more easily. Adding here as reference, will comment again should we take up the work.

**Comment by Lyncros** [comment]
Hello, 
I'm looking for opportunities to get my team involved in Mautic as much as possible. If you're still looking for MsDynamics integration. I'd like to see if I can collaborate with my team to get it done and give it back to the community.

Regards,
Matías O'Keefe

**Comment by npracht** [comment]
Hi @Lyncros as far as i know, that is not planned yet and if you want to make your team working on it it would be great! I've prepared a standard brief for CRM integration. You can work on it if you like.

@mqueme what is you opinion about that? Knowing that you developed the first bi-directionnal plugin, you may have your word.
I think with all the following feature we cover everything that a marketer needs. It could be kinda "standard brief" for all native CRM integration.
________

# Features in mautic plugin
## “Push contact to integration”
Ability to push contacts from Mautic to MSD at the following events. This feature is existing in CRM bundle.
* Form action
* Trigger action
* Campaign action
That allow the user to choose when the contact should be synced to the CRM.

## “Full sync.” mode
Use a CRON to push all contacts created or modified since last CRON without any other condition.

## “Fetch from CRM”
Ability to fetch from multiple object in MSD. This should be manageable from the plugin config.
* Leads
* Contacts
* Companies
* Segments
It fetches all the items based on last modify date and date of last fetch CRON

### First fetch
For the first fetch, it should take all data in the CRM for the selected CRM objects.

## Contact field mapping
Contact field mapping to match leads/contacts fields from CRM to mautic contact fields.

### Writing rules
It would be great to add some rights on the data sync. to be able to choose **for each field**.
* Mautic erase in CRM (by default)
* Mautic erase only if empty
* Mautic never erase

## Company field mapping
Company field mapping to match company from CRM to mautic company fields.

### Writing rules
Same as contact.

## MSD plugin feature
Install on each contact a modal that displays the contact timeline from mautic.

**Comment by Lyncros** [comment]
Thank you very much Norman,
I already sent this to my dev team. Most of my prospects are using Ms
Dynamics.  As soon as I close a deal with them I should be able to move
forward or if someone else in the community has the same need, reach out to
me to see how can we get it moving faster.
Regards,



Matías O'Keefe
Director @ Lyncros
Ar: +5411 3221 3649
US:+1 317 353 3160

[image: Lyncros]




2017-02-02 6:26 GMT-03:00 Norman Pracht <notifications@github.com>:

**Comment by alirobe** [comment]
Don't have the bandwidth to work on this feature (or any knowledge of the product/language/etc) but +1 for the functionality. Would really appreciate this integration :)

**Comment by npracht** [comment]
Hi @Lyncros any news on that. If you need help for your brief or anything, just ping me and i'll do my best :)

**Comment by npracht** [comment]
@alanhartless you can assign that to @Lyncros !

**Comment by npracht** [comment]
Hi @Lyncros any news on that ?
Thanks for your feedback !

**Comment by mqueme** [comment]
Hi, really appreciate the brief @npracht, full sync mode has been now made available in the cron job, so for existing companies integration or new integrations this functionality can be added. Writing and updating rules have also been added,  I didn't think of using an update when empty rule, but I would note it as a feature request. 

Pls look at,   https://github.com/mautic/mautic/pull/3508 for these changes. Testing needed.

**Comment by npracht** [comment]
Hello all.

For those who are interested by Microsoft Dynamics CRM integration, please help by contributing a little bit ! Faster we get contribution, faster we work on it !
https://www.leetchi.com/c/mautic-dev-webmecanik

**Comment by wittwerch** [comment]
@Lyncros can you share the progress?
We have an internship starting in July that could work on that Microsoft Dynamics integration.
