### ISSUE TITLE
Notice: Array to string conversion in /vendor/symfony/translation/Translator.php on line 209

### ISSUE THREAD

**Issue by olimits7** [mautic/mautic#3339]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  Y
| Feature request? |  N
| Enhancement? |  N

## Description:
Under the **/contacts/view/** page when there are **Campaign action triggered** emails listed, when I click on the **Toggle details** button I see this error showing.

> Notice: Array to string conversion in /vendor/symfony/translation/Translator.php on line 209

## If a bug:

| Q   | A
| --- | ---
| Mautic version | v2.5.1
| PHP version | v5.6.29

### Steps to reproduce:
1. Add a contact to a campaign.
2. Run the **campaigns:trigger** cron job; so "**Upcoming Events**" section is populated with campaigns.
3. Next click on **Toggle details** under one of the **Campaign action triggered** rows.
4. Then you will see this issue; see screenshot image below for reference.

https://gyazo.com/576ed077529d5b1b4ec6b90ffe039a15

**Note:** You have to have a campaign with more than 1 email because I notice on my first email the error doesn't show but then on all the rest of them it does.
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by PatchRanger** [comment]
Could be related: I've triggered update of my translation following "How to update a language" section of Mautic Translation guide: https://www.mautic.org/docs/en/translations/index.html - and got stuck with semi-translated Mautic. I did try to restart the guide several times more, I cleared caches by command and manually deleting folders - nothing helped, it just appears to be semi-translated at the end. I am sure that there are translations in Transifex - because I've created them myself earlier)) It worked several months ago - I managed to get fully-translated Mautic. But now I had to force updating translation - and it refuses to get fully-translated.
I think it's related because I get lots of exactly the same translation-warnings into the logs. It looks the most likely reason of semi-translated situation.

**Comment by PatchRanger** [comment]
Additional logs that look related:
> [2017-02-10 07:51:47] mautic.ERROR: Deprecation: The Symfony\Component\Translation\Translator::getMessages method is deprecated since version 2.8 and will be removed in 3.0. Use TranslatorBagInterface::getCatalogue() method instead. - in file /vendor/symfony/translation/Translator.php - at line 275 [] []

> [2017-02-10 09:36:46] mautic.ERROR: Deprecation: Symfony\Component\DependencyInjection\Definition::setFactoryService(doctrine) is deprecated since version 2.6 and will be removed in 3.0. Use Definition::setFactory() instead. - in file /vendor/symfony/dependency-injection/Definition.php - at line 204 [] []

**Comment by LevryKurniawan** [comment]
Hi @escopecz, I found this error in log file when view contact details with upcoming events.

### Steps to reproduce bug:
1. Create a campaign with action to schedule send email in 3 days
2. Add a contact to the campaign
3. Run `app mautic:campaigns:trigger`
4. View contact details that have been added to the campaign.

**Comment by LevryKurniawan** [comment]
@npracht @alanhartless please check this.

**Comment by sensalot** [comment]
I have this same situation in mautic 2.15.0 php 5.6.40

[2019-03-27 13:40:35] mautic.NOTICE: PHP Notice - Array to string conversion - in file /var/www/html/mautic/vendor/symfony/translation/Translator.php - at line 209 [] []

**Comment by sensalot** [comment]
still present in 2.15.1
