### ISSUE TITLE
Date localization and default language

### ISSUE THREAD

**Issue by insetic** [mautic/mautic#3342]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? |  
| Enhancement? | Yes

## Description:

Since controls in System Configuration does not apply to Datepickers , Calendar and months/days translations when using languages different to English it will be great that it would be fixed

i.e. when you set your system to work in Spanish, the dates must be "5 ene 2017" instead of "Jan 5, 2017".

Also the months and day names must be translated in Calendar and other places, i.e. "Febrero" instead of "February" or "lunes" instead "Monday" and be able to set the first day of the week.

It will be great also that the Language selector for Emails, Contents, Forms, etc. use by default the System Language, now ever is English

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
