### ISSUE TITLE
Single Deep Page Hit Shows Double Hits & Homepage Hit

### ISSUE THREAD

**Issue by Paul979** [mautic/mautic#3343]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  V
| Feature request? | 
| Enhancement? | 

## Description:
A single page hit results in 3 registered page hits, one of which is the home page which was not visited.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.5.1
| PHP version | 7.0.15

### Steps to reproduce:
1. Click a link in an email from the domain you're tracking with Mautic (don't browse anywhere else after)
2. See the multiple page hits in that contact's history...

![mautic-page-hits](https://cloud.githubusercontent.com/assets/25543761/22619950/755b5fec-eb00-11e6-88ca-8a015a1cd02f.png)

 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by Paul979** [comment]
P.S. I'm using the WP Mautic plugin (https://nl.wordpress.org/plugins/wp-mautic/) and I see it was last updated 1 year ago.

**Comment by PeteOliveira** [comment]
Download the WP Mautic plugin from Github instead of installing it from
Wordpress plugins.
https://github.com/mautic/mautic-wordpress.git

The team is aware of it and will hopefully update it soon.


-- 
Pete Oliveira


From: Paul979 <notifications@github.com> <notifications@github.com>
Reply: mautic/mautic
<reply@reply.github.com>
<reply@reply.github.com>
Date: February 4, 2017 at 1:29:39 PM
To: mautic/mautic <mautic@noreply.github.com> <mautic@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
<subscribed@noreply.github.com>
Subject:  Re: [mautic/mautic] Single Deep Page Hit Shows Double Hits &
Homepage Hit (#3343)

P.S. I'm using the WP Mautic plugin (
https://nl.wordpress.org/plugins/wp-mautic/) and I see it was last updated
1 year ago.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/mautic/mautic/issues/3343#issuecomment-277474909>, or mute
the thread

**Comment by Paul979** [comment]
Ok thanks for pointing me there

**Comment by Paul979** [comment]
I just downloaded and installed the plugin from Github, but it's the same version as on Wordpress.org, version 1.01 also. So I suspect that's not going to fix anything.

**Comment by Paul979** [comment]
Just compared the pixel in Mautic > Landing Page Settings with the one from Wordpress that's in my page source ...

They're indentical. So unless I'm missing something, the double page load trackingdoesn't seem to be a Wordpress plugin issue, but an issue with the pixel in general.

**Comment by merlin0** [comment]
Did you remove the old plugin first? The new version on github uses the JS tracking instead of the old tracking pixel method.

**Comment by Paul979** [comment]
Yes I removed the old plugin first. And IC'm now using the new version from Github, which I tested after installing... And the problem is still the same.

**Comment by Paul979** [comment]
I just did another test and this time the page hit wasn't logged at all on the first click. Only the second click registered.

 And I'm using page hit tracking to double opt in my users, so not having this work reliably means that people who sign up sometimes will fall through the cracks and not get added to my list.
