### ISSUE TITLE
Feature Suggestion: A More Marketing Automation Focused Default Dashboard

### ISSUE THREAD

**Issue by Paul979** [mautic/mautic#3354]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | V
| Enhancement? | 

## Description:
Please see my post about it in the community forums here: https://www.mautic.org/community/index.php/6811-email-automation-optimized-dashboard-free-download/

I'm not suggesting to use my custom dashboard, but to take the general idea of...

"I found that Mautic's default dashboard focuses too much on website visitor analytics. I mean, we all already have a solution for website analytics, and we use mautic for contacting our leads and customers. So I felt the Mautic analytics dash should reflect that more prominently."

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by merlin0** [comment]
If you click on import, there are already a few build in alternatives.  It could be a good idea to add the best community made ones to every Mautic install.

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
