### ISSUE TITLE
Read Twilio Logs and Take Action

### ISSUE THREAD

**Issue by j-ki** [mautic/mautic#3359]
What type of report is this: Feature Request

## Description:
Twilio provides detailed logs about the SMS that are sent, replies, bounced, etc.

I'd like Mautic to read the logs and take certain actions:

* If a number is rejected or invalid, mark the mobile number as invalid and do not attempt to send SMS to that number again. (I guess that'll mean creating separate bounce flags, one for email address and one for mobile numbers.)

* If a user replies back with 'STOP' (or something similar), put them on the do-not-SMS list. (As above, this may require separate do-not-contact flags for both email addresses and mobile numbers.)

* Depending on the market, people may reply with different words to stop SMS. Please make the word list configurable so we can customize the SMS unsubscribe request to the particular market. Adding the ability for regex would definitely be helpful.

**Comment by eirua** [comment]
+1 for this. 

People are super sensitive to SMS marketing and with Canadian and US regulation, penalties are stiff for companies that fail to comply with unsubscribe requests.

I know Twilio will automatically DNC any contact that replies with a recognized unsubscribe word. Even if Mautic does attempt to send another SMS, Twilio will not send it (not sure if they consider this a sent SMS for billing though). 

Would be great for this to be passed back to Mautic so we can automatically stop workflow and mark them as DNC for other channels.

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
