### ISSUE TITLE
Enhancement | Add a date/time stamp option to the Update Contact campaign action. 

### ISSUE THREAD

**Issue by jasonolas** [mautic/mautic#3360]
Enhancement Suggestion:

A date/time stamp option within the Update Contact action.

I believe it would really improve the flexibility of the campaigns and segments if we could date/time stamp a field from within a campaign because then you can identify which contacts have taken certain actions recently and which ones have not.

Best,
Jason

**Comment by merlin0** [comment]
+1

**Comment by jasonolas** [comment]
Any movement on this feature?

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
