### ISSUE TITLE
Avatar URL broken after 2.6.0 update when Mautic is on a folder (not on root)

### ISSUE THREAD

**Issue by AlanRezende** [mautic/mautic#3382]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
The avatar URL has a broken URL after update to 2.6.0.

The url considers the name of the folder Mautic is installed 2 times so instead of 

http://i2.wp.com/**domain**/foldername/media/images/avatar.png

It shows

http://i2.wp.com/**domain**/foldername/foldername/media/images/avatar.png

I have found the same error with this user in Mautic forum [Upgrade 2.6 avatar path problems](https://www.mautic.org/community/index.php/6863-upgrade-2-6-avatar-path-problems)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.6.0
| PHP version | 5.6.26

### Steps to reproduce:
1. Install mautic 2.5.1 in a folder (not on root of domain)
2. Upgrade to 2.6.0
3. The default avatar has a broken URL

**Comment by gino1234** [comment]
This seems to resolve when the root folder of the domain is used rather than the installation directory in the root directory.

**Comment by escopecz** [comment]
@gino1234 where did you use the root directory?

**Comment by gino1234** [comment]
I simply have a domain www.mydomain.com which points to a httpdocs directly with a mautic installation under marketing

root / marketing / <all mautic files>
root / <other non mastic resources such as img, css etc for domain>

Under Configuration / System Settings / General Settings / Site URL I had:

https://www.mydomain.com/marketing

This was causing the extra value to be added to the path i.e. marketing/marketing

**Comment by gino1234** [comment]
Another aspect to this is that the URL for the tracking image in emails is modified by the Site URL and so not having the installation directory in the Site URL causes and incorrect path in the tracking image. Avatar.png is fixed when NOT using installation directory but tracking image is broken.

**Comment by AlanRezende** [comment]
The template's images of the emails have the doubled folder name too and don`t apear correctly.

**Comment by IADDIC** [comment]
same issue here!  

installed on https://www.mydomain.com/messages

avatar works for anonymous contacts but know contact avatar is broken.

other icons effected the same way (i,e logout)

**Comment by J-a-n-u-s** [comment]
Variation of the problem here.... hosting mautic myself on apache in /var/www/mautic/

'avatar.png' is just one of several related problems (I think) that I faced although I solved the other major one (see below). I have nothing wordpress related on my setup.

For the avatar and some other images from the dashboard, they are linking to

`http://i2.wp.com/**domain**/index.php/media/images/avatar.png`

instead of just 

`http://**domain**/media/images/avatar.png`

In General Settings the Relative path to images directory is set to

`media/images`

and my site URL is

`http://**domain**/index.php`

"Not sure if you got this fixed or not, but I was having the exact same problem when manually sending an email to a contact from the mautic web interface. I tried creating a new VM for it from scratch and then realized that if I was accessing the dashboard using the server's lan ip (e.g. 192.167.1.5), then that's the ip that showed up in the links in the emails that got sent out. However, if I accessed the dashboard using the hostname.domain, then the hostname.domain would show up in the links in the email. I'm not sure why mautic wouldn't use the base url that it's programmed to use in the dashboard." - http://stackoverflow.com/questions/38336645/issue-with-wrong-tracking-urls-in-mautic/42379129#42379129

**Comment by J-a-n-u-s** [comment]
Just found solution to this. Turns out the default file specified in the Site URL of General Settings needs to be removed (default: `http://domain.com/index.php` -> is now: `http://domain.com`). This was causing the wrong url to be used for the avatar.png and some other images.
[https://www.mautic.org/community/index.php/2753-avatar-cannot-edit-and-404/p1#p13157]

**Comment by jbmanos** [comment]
J-a-n-u-s,  I tried your solution -- I changed my site URL from https://domain.com/subfolder/ to https://domain.com/

It did fix the avatar, HOWEVER, this makes me nervous that it'll break whenever they fix the image problem in a later release.  all the way up to 2.6.0, the avatar loaded correctly, so something changed in the URL logic that broke it.

**Comment by abooster** [comment]
I just updated from 2.5.1 to 2.6.1 and this bug is still there! Very annoying. 
@J-a-n-u-s Your solution is not applicable here. My installation is in a subfolder (https://domain.com/subfolder/ ).

**Comment by abooster** [comment]
Hmm... after changing https://domain.com/subfolder to https://domain.com (under site URL in configuration) all the paths under 
`System Info > Folder & File Permissions `
are still shown correctly.
This is confusing as hell!

Does it mean Mautic auto detects the subfolder now and we only need to enter the root domain (or subdomain) under site URL in configuration? 
Or will changing https://domain.com/subfolder to https://domain.com (under site URL in configuration) break some functions?
HELP!!!

**Comment by abooster** [comment]
I just did a brand new install for testing (automated install via Softaculous) and the result is: 
In this brand new installation https://domain.com/subfolder remains https://domain.com/subfolder (under site URL in Configuration > General Settings) and there are no problems with the avatar in this new installation! 
This tells me that what I described in my previous post will probably break some functions. 
Or put it another way: **The update process from 2.5.1 to 2.6.1 has some kind of a bug that breaks something**.
Because a fresh install of the version 2.6.1 seems to work fine. (at least the things that I've tested so far seem to be working fine in a fresh install of 2.6.1)

**Comment by abooster** [comment]
UPDATE: The bug actually still exists even in a brand new installation of 2.6.1 (when installed in a subfolder).
The only exception is: When there is a gravatar image, then it appears fine. 
But without an existing gravatar image the same issue occurs as described in the first post.

Well, with an existing avatar image the encoding in the URL is also wrong but it still pulls the correct avatar image. This is what the URL of an existing avatar image loos like: 
`https://www.gravatar.com/avatar/8cb47585ae5e194c841c15904932e54e?s=50&d=https%3A%2F%2F****domain****%2F***foldername***%2F***foldername***%2Fmedia%2Fimages%2Favatar.png`

**Comment by escopecz** [comment]
Will be fixed in 2.7.1

**Comment by ralfhug** [comment]
I just did a test install with 2.7.1. as a subfolder domain.com/mautic and found that similar issue as for avatar image is happening with email and landing page theme images. domain.com/mautic/mautic/themes/sunday/img/logo.gif. 

If I replace the missing gif image und upload a different picture the folder seems Ok and it works. 

However, if I want to upload a theme, the issue of course persists with the folder path problem. Similar issue also with Landing pages. 

http://www.trajectorygroup.com/shifu/email/preview/2 Test URL with issue.

**Comment by escopecz** [comment]
@ralfhug please report this as a new issue so it won't get forgotten.
