### ISSUE TITLE
Add new Segment from segment selector

### ISSUE THREAD

**Issue by scottbuscemi** [mautic/mautic#3404]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | x
| Enhancement? | 

## Description:
On any dropdown that allows you to set a segment for a contact, typing in a new name in the dropdown should result in "Add new segment [[entered name]]" rather than "No matches found for [[entered name]]".

This functionality should extend to many other fields as well. The proper UX would be to allow for adding a new "x" if it doesn't exist, rather than stating no matches are found. An additional modal popover could appear for creating the segment, etc. Alternatively, a button for adding a new segment could appear whenever the segment selector is shown.

### Steps to reproduce:
1. View a contact 
2. Press the dropdown on the top right
3. Choose "Preferences" then click on the "Segments" tab
4. Type in a new segment name into the segments field
5. "No matches found" will appear rather than a prompt to add a new segment.

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
