### ISSUE TITLE
Add a "Form" slot type on the builder

### ISSUE THREAD

**Issue by scottbuscemi** [mautic/mautic#3406]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | x
| Enhancement? | 

## Description:
When creating a landing page using a theme, the builder does not allow for adding a form. Adding the iFrame or javascript code doesn't work, and there isn't a slot type for Form.

A recommendation would be to add a "Form" slot type on the builder, or to not strip out the iFrame code when it's added using the code view of a text slot.

### Steps to reproduce:
1. Create a new landing page
2. Choose the Skyline theme
3. Attempt to add a form using a Text slot (then choosing 'code view' to paste in the code)
4. Save the builder and save the landing page
5. The form code has been removed and does not appear

**Comment by escopecz** [comment]
Actually, forms as well as other tokens can be added when you type `{` and then start typing the form name. It's documented in https://mautic.org/docs/en/pages/manage_pages.html

**Comment by scottbuscemi** [comment]
Got it. I'll adjust the issue to request UX changes to make that more obvious for new users. Discoverability of functionality within the software rather than within documentation is important, IMO.

**Comment by scottbuscemi** [comment]
I also still think a Form slot type would be a more user-friendly approach for regular users.

**Comment by mryanb** [comment]
FWIW: I was taking a look at Mautic today for the first time. I was expecting to see a form slot.

**Comment by amit777** [comment]
also found this github issue after a bit of confusion.  I still can't seem to find a way to put the form in my custom theme landing page.  The drag and drop side doesn't have anything.  If I go into the code edit view of Customize Slot, and type curly brace, no auto complete options appear.  The mange_pages link above seems to have screen shots that don't match my mautic instance. I'm running latest 2.4.1.

**Comment by npracht** [comment]
Hi,

I agree, we should have a `Form slot` in the landing page builder. That way, we could also add additional settings of the form, directly in the landing page builder as:
* Customize URL redirection after submission --> Consequently you don't need to create a single form for each LP.
* Autofill: YES/NO
* etc

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
