### ISSUE TITLE
Code Mode landing page builder should have button to add forms

### ISSUE THREAD

**Issue by scottbuscemi** [mautic/mautic#3407]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | x
| Enhancement? | 

## Description:
The Code Mode builder currently has buttons for "Media Manager" and "Format Code". Beside these buttons, an additional button should be "Add Form". This would display a modal with a selector for all of the active forms and whether or not the code should be automatic or manual. This would insert the code wherever the cursor is currently placed in the code.

**Comment by escopecz** [comment]
Just so you know it is possible to easily add the form token if you press CTRL + SPACE BAR and search for the form title.

**Comment by mjrwhitehead** [comment]
Do you know - is that a key combination that works OK on a Mac - or is it mapped by default by macOS? Seems not to function for me?

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
