### ISSUE TITLE
Inserting lead fields into emails not initially intuitive

### ISSUE THREAD

**Issue by scottbuscemi** [mautic/mautic#3408]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? |
| Enhancement? | x

## Description:
Viewing all of the lead fields available in an email is simple - type **{** and all of the fields appear in a dropdown. However, this is not intuitive UX for users who have never used the Mautic builder before.

Personally, I looked for a button to add the lead fields in the WYSIWYG kitchen sink and couldn't find anything. It wasn't until I googled and found the blog post with the 'tip' until I knew how to do it.

A couple approaches for user discovery could be used for this:

- When the user customizes an email slot for the first time, display a popover tip telling them how to insert lead fields by typing **{**. However, this will assume that the user will remember that the next time 😄 
- A button could be added to the kitchen sink for lead fields. Pressing this would insert **{** into the text area and the dropdowns would appear. This is the recommended approach.

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
