### ISSUE TITLE
Suggestion to Future Releases

### ISSUE THREAD

**Issue by luizeof** [mautic/mautic#3428]
Hello Community,

Every Mautic update we see the same history: Bugs and more bugs and we have to deal with It.

Can we have Beta or Release Candidates of Mautic before Major or Minor updates? I believe this is very common on Open Source World.

With Beta ou RC we can test plugins, new features, enhancements on **real environments** before the final release. Today Mautic becomes part of our daily work (on some cases, with multiple clients and installations) and users need to known what expect from the platform.

Thanks for your great Work!

@alanhartless @escopecz @dbhurley @dongilbert @kuzmany @mqueme @MaxWebmecanik

**Comment by luizeof** [comment]
@escopecz @dongilbert @alanhartless  These options seems doesn't work .

![captura de tela 2017-02-15 00 22 36](https://cloud.githubusercontent.com/assets/257004/22958240/1576d7a6-f315-11e6-9be0-98659563028b.png)

**Comment by iadj** [comment]
+infinity
I'm running 2.6.0 with a bunch of Pull Requests  and code modifications in production which aren't implemented in 2.6.1. Out of fear of everything breaking I am no longer updating it. 

I'm also using the API, and it seems that with every update something about the API changes. This would cause me to have to re-implement the Mautic API into my project's production.

**Comment by RCheesley** [comment]
If you're not already in slack, join #dev - it's a good place to discuss stuff like API changes etc.

**Comment by pvasilion** [comment]
+infinity-and-beyond
We have held back updating Mautic for this reason but now have to upgrade to 2.6.1 so we are holding our breath that everything that could be reported has been since it went live. 

Give us a more graduated release cycle if that is what it will take to give us _some_ certainty that we can upgrade without fear of having to find workarounds. Until then we will diligently bite our nails and check the issue queue with a fine-toothed comb.
