### ISSUE TITLE
Add Ability multiple twitter accounts

### ISSUE THREAD

**Issue by IADDIC** [mautic/mautic#3458]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | No
| Feature request? | Yes
| Enhancement? | Yes

## Description:
Social media connections are limited to a single account.  It would be best to develop the ability to select one of the several social accounts.  For this, to work, the feature of adding multiple social accounts would be required.

For Example:

Once multiple Twitter accounts are connected, the campaign can be used to select which of the connected accounts is sending the message.  

Similar to how the "From Email Address" can be entered in the email segments. 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by marqpdx** [comment]
This would be extremely useful. Without it Twitter in Mautic is very limited even if you have only two such accounts.

Thanks,
m

**Comment by dbhurley** [comment]
Good suggestion. Adding to Backlog

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
