### ISSUE TITLE
Add class to data-slot for a better email styling

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#3459]
| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | v

## Description:
Google for instance, do not take account of data-slot. So the style given to it is not displayed in Gmail.
It would be great that fo each data-slot type, it adds to the `<div>` the class with the same name of the data-slot, then in the style of the theme, you can add the style to the data-slot + the class with the same name.

### Today
Here is a button for instance.
```
<div data-slot="button" data-param-background-color="" data-param-float="1" data-param-button-size="1" style="position: relative; left: 0px; top: 0px;" data-param-href="#" data-param-link-text="Le programme complet" data-param-color="#ffffff " align="center">
    <a href="#" target="_blank" style="font-size: 16px; color: rgb(255, 255, 255); text-decoration: none; border-radius: 3px; padding: 12px 18px; background-color: rgb(94, 10, 79); display: inline-block;">text</a>
    <div style="clear:both"></div>
</div>
```

### Improvement
Should add `class="data_slot_button"` to the div to apply same style.

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._

**Comment by pjoulot** [comment]
The forum issue has been closed. What was the reason?
I can't style emails because of this, that's pretty sad, is there a workaround?
