### ISSUE TITLE
Stats in report and in channels/email are not the same

### ISSUE THREAD

**Issue by v-akos** [mautic/mautic#3461]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | ?
| Feature request? | 
| Enhancement? | 

## Description:
I made an email report with all the stats of reading, clicking etc. Unfortunatelly the number of clicks in the report is not the same as that number of clicks when I check them at the page of the specific email. Checked with several emails, result is the same.

Stats that do not match: read count, clicks, unique clicks
Stats that do match: sent count, unsubscribed

Date ranges are the same.

Printscreens are attached from both of the screens.

![github-issue1](https://cloud.githubusercontent.com/assets/25770999/23071704/8392bf18-f52f-11e6-8f7e-6829bea10e6a.jpg)

![github-issue2](https://cloud.githubusercontent.com/assets/25770999/23071646/5c99a87c-f52f-11e6-9084-aca8656efc90.jpg)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.5.1
| PHP version | 5.6.24

### Steps to reproduce:
1. New report
2. Data Source: emails
3. Data: sent, read, unsub, clicks, unique clicks etc.
4. Compare the report to that one in channels/emails.

**Comment by v-akos** [comment]
@escopecz , do you maybe have any idea which stat can be real? I would appreciate to know, because there is no sense to send email camaigns without valid statistical data on them. Thanks in advance!

**Comment by npracht** [comment]
Related to https://github.com/mautic/mautic/issues/2846, you confirm @escopecz ?

**Comment by npracht** [comment]
I would add also issue in terms of clics sum in the graph (6) and in the table (18).
![capture d ecran 2017-02-28 a 18 25 40](https://cloud.githubusercontent.com/assets/14075239/23416524/7395d94e-fde3-11e6-89d6-57f6eb25fa95.png)

**Comment by Dcoutelle** [comment]
hello, I currently working on it.

**Comment by v-akos** [comment]
Awesome news, @Dcoutelle , thanks for your efforts!

**Comment by npracht** [comment]
@matishaladiwala could you please assign it to David to avoid that someone else work on it at the same time ?
Thanks,

N.

**Comment by npracht** [comment]
@alanhartless & @escopecz i'll need a bit of help here. We took time to check how calculations are done and... it's terrible.

# Stats in email overview
## Email graph
### Clicks
It was bugged. And we corrected it, but the data displayed is useless.

### What we propose
As marketing standard it should list the amount of CLICKERS and not of clicks. Otherwise you compare openers and clicks. **You should compare openers and clickers**.
Even if it is called clicks, they count clickers when they make stats like that:
![capture d ecran 2017-03-08 a 12 42 31](https://cloud.githubusercontent.com/assets/14075239/23702714/b852e01c-03fc-11e7-9b20-064df95c1202.png)


## Email click tab
* Total clics --> This is great
* Total unique clics --> This is great
It is not linked to contacts but only on activity on links which is a great standard.

# Stats in report
You have some ratio that are here that are not following email stats standards.
* Open ratio : amount of unique opens / amount email send --> This is great
* Unique click ratio : amount of unique clicks / (amount email send * amount of links)
* Click ratio : amount of clicks / (amount email send * amount of links)
## What we propose
As marketing standard it should list the ratio of CLICKERS and not of clicks. Otherwise you compare openers ratio and clicks ratio. **You should compare openers and clickers**.
Plus, the standards show the ratio of clickers on openers and not email sent.
The interesting ratio must be:
* Click ratio : amount of unique clickers / amount email opened

# Conclusion
### Problem here
We miss the amount of unique clickers for:
* the email overview graph
* in the report graph to make a new data `clickers` and `clickers ratio`

**The amount of unique clickers can be get in the `page_hits` table (source * source_id * lead_id).**

But as you may know to make it faster (in terms of data loading) you have created the table `channel_url_trackable` which is especially made for data stats. And we do not have here or anywhere else the already calculated date for **amount of unique clickers**.
We recommend to add it in the `emails` tab.

### How to proceed if you agree
Create the column in the tab
Create formula that stocks right value in the column
Insure script that will calculate all existing datas when you update your mautic --> Here we need help, we cannot work on it.

________
Your opinion guys ?
What can be the impact on other channels ?

**Comment by npracht** [comment]
@matishaladiwala i've been talking with John and he told me it's more about a discussion i should have with you cause here we talk about email "standard", not about "how to develop".

Could you give us a feedback GO/NOGO to know if we can start working on it ?
I've sum up in shot words
* Today we count clicks and we make rates on click.
* We should count **clicked emails** (clickers) and make a **clicked ratio** (clicker ratio) to be able to compare with **opened emails** which is today calculated.
* Moreover, the clicked email ratio should be calculated on emails opened, not on emails sent

Those are the standards we don't follow in Mautic.

I wait for your feedback.

N.

**Comment by matishaladiwala** [comment]
I agree we should have unique person clicks (or clickers) and click rate (clicker ratio) as metrics in addition to the total clicks metric. Most marketers and marketing automation tools calculate click rate as the ratio of unique person clicks to emails sent (or delivered). If you want to build the ability to calculate it based on emails opened, this could be made available in the reporting section.

**Comment by npracht** [comment]
Great @matishaladiwala, then you can assign it to @Dcoutelle he'll continue working it.
Thanks a lot for your feedback.

**Comment by escopecz** [comment]
@npracht GitHub will not allow to assign an issue to @Dcoutelle nor you. Just to let you know we are not ignoring you :)

**Comment by npracht** [comment]
What do you mean? Isn't a native feature of github to assign issues to devs?

**Comment by escopecz** [comment]
![screen shot 2017-03-10 at 20 03 20](https://cloud.githubusercontent.com/assets/1235442/23809120/ad126f34-05cc-11e7-97cc-619f6e329bb4.png)

**Comment by npracht** [comment]
Ha, a pity, we must be in Mautic team I guess.
Thanks for your message then :)
