### ISSUE TITLE
[Mautic Gmail Helper] after update to Mautic 2.6 not working

### ISSUE THREAD

**Issue by magician7** [mautic/mautic#3469]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | 
| Enhancement? | 

## Description:
After update Mautic to 2.6 Mautic Gmail Helper stop working. After click on icon to show window I got  "Uh oh! I think I broke it. If I do it again, please report me to the system administrator! 
500 Internal Server Error"

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.6 ; 2.6.1
| PHP version | 7

### Steps to reproduce:
1. Update Mautic to 2.6
2. Click on extension icon to show window
 
### Log errors: 
From Apache log this give 500: /s/plugin/Gmail/timeline?count=0&from=iframe
From Mautic log:  mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\DBALException: "LIMIT argument offset=-25 is not valid" at /home/dp/domains/qwerty.xyz/public_html/ma/vendor/doctrine/dbal/lib/Doctrine/DBAL/Platforms/AbstractPlatform.php line 3318 {"exception":"[object] (Doctrine\\DBAL\\DBALException(code: 0): LIMIT argument offset=-25 is not valid at /home/dp/domains/qwerty.xyz/public_html/ma/vendor/doctrine/dbal/lib/Doctrine/DBAL/Platforms/AbstractPlatform.php:3318)"} []

**Comment by IADDIC** [comment]
same issue

From Apache log this give 500: /s/plugin/Gmail/timeline?count=0&from=iframe

**Comment by RobertAlan** [comment]
Same here.

**Comment by jvenator** [comment]
Same here, although after uninstalling/reinstalling I also intermittently got the message below instead of the 500 error. I replaced our subdomain with "example". Also, this is on the official Mautic hosted solution.

The webpage at http://example.mautic.net/s/plugin/Gmail/timeline?count=0&from=iframe might be temporarily down or it may have moved permanently to a new web address

**Comment by magician7** [comment]
Works for me in Mautic 2.7
