### ISSUE TITLE
Email Read Date Display

### ISSUE THREAD

**Issue by nickian** [mautic/mautic#3478]
I was wondering what others thought of this. The way the email opened date is displayed doesn't seem optimal to me.

On the contacts page, I see that this contact was recently active today:

<img width="891" alt="screen shot 2017-02-20 at 11 45 57 am" src="https://cloud.githubusercontent.com/assets/590678/23138096/b8fde350-f762-11e6-933b-3807f1c161cd.png">

When viewing his profile, I see this as the most recent event:
 
<img width="556" alt="screen shot 2017-02-20 at 11 45 50 am" src="https://cloud.githubusercontent.com/assets/590678/23138132/d44c8328-f762-11e6-84d5-d7ce556e4ba1.png">

This is confusing since today is not January 24th; it's February 20th. When I click "toggle details," I see this (still not intuitive):

<img width="782" alt="screen shot 2017-02-20 at 11 48 43 am" src="https://cloud.githubusercontent.com/assets/590678/23138165/fc61fab4-f762-11e6-9eaa-92240fdd3264.png">

It's only after clicking the tiny "more" link that I finally determine he viewed the email today.

I think it would be more intuitive to display the **most recent** email opened date as the event timestamp on a contact's profile, not the original date they read the email. Also, it makes more sense to me to display their read date in descending order so the most recent actions are at the top. What do you think?

**Comment by stoykovstoyk** [comment]
I know this thread is a little bit old, but since I had the same experience I decided to share with you how I partially solved it as far as the problem with the **most recent** email opened date Event Timestamp column field goes.

I didn't solve the problem with the read date in descending order, but the solution still solves half of the problem that you mentioned here.

So my solution was to change

`<td class="timeline-timestamp"><?php echo $view['date']->toText($event['timestamp'], 'local', 'Y-m-d H:i:s', true); ?></td>`

in file **app/bundles/LeadBundle/Views/Timeline/list.html.php**

with this

`<td class="timeline-timestamp"><?php echo $view['date']->toText(reset(end($event['extra']['stat']['openDetails'])), '', 'Y-m-d H:i:s', true); ?></td>`

Now Event Timestamp shows the **most recent email opened date** instead of the original date they read the email.

I hope my solution will help others that are looking for this.

Best Regards,
Stoyko Stoykov
