### ISSUE TITLE
How to add Custom Fonts to Mautic Editors (Landing Pages, Emails...) ?

### ISSUE THREAD

**Issue by pitus** [mautic/mautic#348]
I've been trying to figure out how to add a Custom Font (`Open Sans` with variations for `Bold`, `Italics`, `BoldItalics` for example) to the `CKeditor` used by Mautic in the Builder.

I found info how to add fonts to the Font drop-down (`app/bundles/CoreBundle/Assets/js/libraries/ckeditor/config.js` adding `config.font_names = "my font/font ref;" + config.font_names;`) and that seems to work inserting `font-family: "open sans"` as style ... it seems I also need to add `font.css` file that defines `@font-face` for it with `src: ...` definitions pointing to font files...

As part of my investigation, I found that there's already an `@import url(https://fonts.googleapis.com/css?family=Open+Sans: ...` line at the top of `app/bundles/CoreBundle/Assets/css/app.css` but it doesn't seem to be referred anywhere by that name.

What puzzles me is the `app/bundles/CoreBundle/Assets/css/libraries/font-awesome/...` module which seems to define a custom Font in there ...

So I wonder, **what is the proper procedure to add a Custom Font or Fonts to the Mautic Builder?**

**Comment by alanhartless** [comment]
Hi Pitus,

Support is more geared for the forum rather than here; so if the following needs clarification, please move continue the conversation in the forum.

But to answer your question, core CSS and JS (app.js and app.css) and ckeditor source are not included in the public view for landing pages and/emails since you wouldn't want Mautic's UI affecting the UI of the landing page/email.  They are only included in the builder as some of the functions are utilized by the builder itself to construct the content.

To include custom fonts in CKeditor, you'd have to consult ckeditor docs.  To include the custom fonts in the public view/rendering, you would need to include the @font-face attribute in either the head of your custom HTML or edit the theme's base.html.php file and/or asset files to include the font. 

Thanks!
Alan
