### ISSUE TITLE
Have possibility to create installation package in different language

### ISSUE THREAD

**Issue by pavel-janicek** [mautic/mautic#3484]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | Y
| Enhancement? | 

## Description:
Default Mautic language is English and user has to go through installation process in English language. It would be great if there was a possibility to choose language during install or possibility to create at least installation package with preloaded texts of desired language.

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
