### ISSUE TITLE
mtc_id cookie not always '/' path

### ISSUE THREAD

**Issue by iadj** [mautic/mautic#3496]
The mtc_id cookies created by Mautic (2.6.0) are not always in the '/' path of my domain, but sometimes on a single local path. The Cookie Settings are set as:

Cookie Path: /
Remember me cookie path: /

Cookie domain and Remember me cookie domain are empty.

**Comment by isleshocky77** [comment]
I was looking for what I think was a similar issue and ran across your issue as well as the following forum

Just wanted to see if your problem was linked to what my solution ended up being.

> Are you working on a local installation? I also for the past year have been finding the mtc_id to be extremely unreliable; however, it's mostly while working on my local installation.
> 
> I just tracked down what looks like a change a year ago:
> https://github.com/mautic/mautic/commit/90b64034d09510d6f77fb9e790e91938bbadec9b#diff-680a217018ae349738fa38e34b7a19f8R152
> 
> Where 127.0.0.1 is always added to do not track. This means you'll get a mautic_session_id, but not a mtc_id.
> 
> Later on it was added so this functionality only happens in production:
> https://github.com/mautic/mautic/commit/78a64d35677b9c19fcbeacf3f1d4879e4522a208
> 
> However, I didn't realized this so I never thought to put my dev url into my local website tracker
> i.e. instead of tracking https://mautic.example.org/mtc.js use https://mautic.example.org/index_dev.php/mtc.js
> 
> That was my issue at least.

[Source](https://www.mautic.org/community/index.php/7392-mautic-cookies-mtc-id-mautic-session-id-mautic-session-name/0)
