### ISSUE TITLE
Grid for Campaign or Auto Organizer

### ISSUE THREAD

**Issue by moskoweb** [mautic/mautic#3502]
It would be interesting a grid to organize the construction of campaigns, because in the loose mode, can not always adjust for easy viewing the entire campaigns run. Especially when it involves big campaigns.

Or maybe an option of automatic organizer, would be nice too, could be a nice alternative.

Or maybe an option to use straight lines instead of loose curves, as in this example (https://jsplumbtoolkit.com/demos/toolkit/flowchart-builder/index.html)

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
