### ISSUE TITLE
Track user by unique identifier using JS tracking code

### ISSUE THREAD

**Issue by iadj** [mautic/mautic#3524]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | x
| Enhancement? | x

## Description:

```mt('send', 'pageview', {user_id: user.id});```
If `user_id` is a unique identifier in Mautic, and the user_id configured in the parameter is found, that session should now be identified.
This would make a lot of sense.

Currently there's a lot of workarounds and hacks into place to properly track users server-side using the API (i.e. overwriting the tracking cookie). It'd be much easier if unique identifiers set by the JS tracking code would make it so the user is identified by that parameter,.

**Comment by kuzmany** [comment]
Workround already exist.
Create Custom Field and enable options  "Is Unique Identifier" and "Publicly updatable"
Contacts will be merged by this value.

**Comment by vkathirvel** [comment]
Thanks. I do understand there is a work around. I am hoping that something like this could be introduced in the core, without making it a workaround.

**Comment by ullfindsmit** [comment]
With this approach, what will happen to contacts that DO NOT have this value

Example: in my case, i have users and then I have leads, leads dont have a username, but then at the same time, users may not have an email. I am having a hard time logging the user's page views because a user may not have email and if I make the username unique, i am afraid it will merge all my leads.
