### ISSUE TITLE
Manage form fields in a similar fashion as dashboard widgets

### ISSUE THREAD

**Issue by JohnConnell** [mautic/mautic#3528]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  N
| Feature request? | Y
| Enhancement? | Y 

## Description:

One of the first things new Mautic users do is create a form. If the form fields editor worked similarly to the dashboard widget editor I think it would be a huge usability improvement. Not having to edit .css (except in advanced use cases) would eliminate a barrier for many non-technical users and speed up form development for everyone.

The specific features of the dashboard widget editor that I think would be most useful:

Edit height and width of fields (px or by %)
Drag & drop fields
Ability to align multiple fields horizontally (3-4 columns max)

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
