### ISSUE TITLE
Support Markdown in email creation

### ISSUE THREAD

**Issue by gabeguz** [mautic/mautic#3529]
What type of report is this:

| Q  | A
| ---| ---
| Feature request? | YES

## Description:

It would be very handy to be able to enter markdown into the email creation tool and have that be rendered into an html message.  As a bonus, the plain markdown could be used as-is for the text only version of the email.

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
