### ISSUE TITLE
custom field encryption

### ISSUE THREAD

**Issue by nullsorcerer** [mautic/mautic#3540]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | No
| Feature request? | Yes
| Enhancement? | No

## Description:
I'd like custom fields to offer strong encryption as an option for storing sensitive information like birthdays. Ideally, you'd even be able to choose which roles were allowed to view which encrypted data, however, that's not necessary in my case. I just want Mautic to be able to collect said information in order to pass it on to another system further down the chain; as such, I'd be perfectly content if the data was entirely inaccessible from within Mautic.

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
