### ISSUE TITLE
Feature request - Importing Company data from CSV Files

### ISSUE THREAD

**Issue by kolinz** [mautic/mautic#3563]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | Y
| Enhancement? | 

## Description:
Importing Company data from CSV Files
Hello guys, I am having a difficult time at updating a lot of company data with Mautic's current feature.
I personally think that it is convenient to create and update all together by importing CSV Files.

Thank you very much for your understanding.
Regards,

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
