### ISSUE TITLE
Gmail Plugin - New Contacts Created by Gmail Plugin Should be Owned by Sender

### ISSUE THREAD

**Issue by jordan8037310** [mautic/mautic#3578]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | Yes
| Enhancement? | 

## Description:
When sending an email to a contact with the Mautic Gmail Plugin to track the correspondence with the user AND the user email is a new contact in the Mautic system, the `From` email address should be registered as the `Contact Owner` for the newly registered lead.

Example:
* jordan@mysite.com sends email to bob@mautic.com with Gmail mautic Plugin turned on.
* bob@mautic.com is added to jordan@mysite.com's mautic instance as a lead.
* When creating bob@mautic.com, a lookup is done for the user jordan@mysite.com, and if there is a match, that user is registered as contact owner.

**Comment by bhardin** [comment]
+1

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
