### ISSUE TITLE
issues with edit email template 

### ISSUE THREAD

**Issue by nesrine22** [mautic/mautic#3591]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | 

## Description:
The more details the better...

## If a bug:

| Q   | A
| --- | ---
| Mautic version | v2.7.0
| PHP version | 5.6.30-0+deb8u1

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
Please provide more information about the problem you are having and steps to replicate.

**Comment by nesrine22** [comment]
when i use the genrateur i cant change any thing with the barre at the right side so i must use the code to change it . nothing is work !

**Comment by escopecz** [comment]
It's working for me. What steps do I have to take to replicate the issue? Does it happen for every theme or only one? Does it happen in all browsers or only one?

**Comment by nesrine22** [comment]
it's not working for me. i use google-chrome also Mozilla and it's the same issue and it's happen for evry theme even i change the theme it's the same . so i 'm obliged to use the code for change texte.
(sorry for the explication i'm french user)

**Comment by escopecz** [comment]
Do you see some errors anywhere? Read https://mautic.org/docs/en/tips/troubleshooting.html to find the PHP errors in the log.

Open also the Chrome dev tools by pressing F12 on Windows or Unix machine or Option+Command+i on MacOS. Navigate to Console tab. Then try to create an email in the builder. Do you see some errors there?

**Comment by nesrine22** [comment]
i have this
![image](https://cloud.githubusercontent.com/assets/26248308/23659645/0d02db96-0347-11e7-8c59-223915a79730.png)

**Comment by escopecz** [comment]
Something is not right. For example the mauticLang error was fixed in 2.6.1. How did you install your Mautic? Did you use the official zip package at mautic.org/download? Or did you upgrade from some previous version somehow?

Anyway, if you can execute a command on your server, execute this in the Mautic root folder:
`app/console mautic:assets:generate`
It will re-generate production assets (JS and CSS). Then refresh the page, maybe even try to clear the cache in your browser.

**Comment by nesrine22** [comment]
i have execute this command now i have this 
![image](https://cloud.githubusercontent.com/assets/26248308/23660110/a56060f6-0348-11e7-918f-aa665b7d8720.png)

**Comment by nesrine22** [comment]
and now that what happen !!!
![image](https://cloud.githubusercontent.com/assets/26248308/23661538/54e85048-034d-11e7-8bd3-8af5240a02fa.png)

**Comment by escopecz** [comment]
There is something wrong with your environment were you host Mautic. Look at the link I posted in https://github.com/mautic/mautic/issues/3591#issuecomment-284727645 and check for the error in the log.

**Comment by escopecz** [comment]
If you switch to English, is the builder working? There is this bug report which points that direction: https://github.com/mautic/mautic/issues/3591

**Comment by ecoitsolutions** [comment]
Same problem here, running latest version i am unable to edit any existing template. Only the new blank template works.

**Comment by ecoitsolutions** [comment]
I have also tried switching back to english everywhere, cleaned browser and application cache without any luck.

**Comment by tnalias** [comment]
I had to set up the language in English (USA) to make the html editor working. Thanks for this great tool.

**Comment by escopecz** [comment]
The language issue should be fixed in 2.8.1. Let us know if it is after you upgrade, please.

**Comment by escopecz** [comment]
I'll close this issue as it seems it has been fixed already.

**Comment by EduLeonPavon** [comment]
Hello,
I have the same problem with spanish (v2.13.1)
Anyway, Mautic is amazing 👍

**Comment by Bellusterra** [comment]
I'm having a similar issue and can not figure it out. I have language set to English so that is not an issue. but when trying to open some templates i get a 404 on the html .jpg images and they are not showing. also opening the builder I cannot edit anything from the template. I decided to run the docker and everything works there, but that has other issues that I also can not solve like the avatar not showing and everything reverting to http.
