### ISSUE TITLE
Location specific Focus Items

### ISSUE THREAD

**Issue by jjdbrinker** [mautic/mautic#3593]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | N
| Feature request? | Y
| Enhancement? | Y

## Description:
It would be amazing to have an option make Focus Items location specific. You could select to include or exclude certain countries / regions, based on the IP geolocation. This would allow marketers to use Focus Items in a country specific way and tailor their messages accordingly.

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
