### ISSUE TITLE
Amazon SES Bounces vs Complaints vs Unsubscribe Requests

### ISSUE THREAD

**Issue by nickian** [mautic/mautic#3596]
I was hoping someone could clarify what the best Amazon SES setup should look like.

I noticed this page now shows a webhook for SES bounces/complaints: 
https://mautic.org/docs/en/emails/bounce_management.html#amazon-webhook

Is this a newer feature? I've been using a monitored inbox for bounces. If I set up the web hook, can I stop relying on  bounce IMAP accounts to handle all of this?

Also, can someone clarify what an "unsubscribe request" is? I don't understand what this feature is supposed to do. Is this something separate from SES? I don't see this documented anywhere.

I see this in the documentation, but it doesn't make much sense to me. Can someone describe an example scenario of an "unsubscribe request"? Thanks.

_Note that Mautic makes use of "append" email addresses. The return-path or the list-unsubscribe header will use something like youremail+bounce_abc123@your-domain.com. The bounce or unsubscribe let's Mautic note what type of email it is when it examines the inbox through IMAP._

**Comment by wittwerch** [comment]
> Is this a newer feature? I've been using a monitored inbox for bounces. If I set up the web hook, can I stop relying on bounce IMAP accounts to handle all of this?

The feature was added in Mautic 2.2 (see #2312).

> Also, can someone clarify what an "unsubscribe request" is? I don't understand what this feature is supposed to do. Is this something separate from SES? I don't see this documented anywhere.
> 
> I see this in the documentation, but it doesn't make much sense to me. Can someone describe an example scenario of an "unsubscribe request"? Thanks.

Not sure about what kind of "unsubscribe request" you are talking. But the Amazon webhook in Mautic only supports bounces and complaints. Both end in marking the contact as do-not-contact.

**Comment by pjrobertson** [comment]
Replying here as this ranks high on Google for "mautic amazon ses unsubscribe monitoring"

I believe what nickian is referring to is the unsubscribe email address mautic+unsubscribe_****

Currently, if you are using Amazon SES for sending emails and using the Amazon SES webhook system as described [here](https://docs.mautic.org/en/channels/emails/bounce-management#amazon-webhook) you will *still* need a monitored inbox for unsubscribes where people reply to the email mautic+unsubscribe_XXXX@domain.com. This is because the Amazon webhook does not support unsubscribe as mentioned above.
