### ISSUE TITLE
I just discovered the hidden secret

### ISSUE THREAD

**Issue by brianteeman** [mautic/mautic#36]
Wow  - the hamburger icon does something - it reveals the settings. How intuitive - not

And when you go to a mobile then you get two hamburger icons - confusion rocks

**Comment by MaxOnTheHill** [comment]
probably change to a gear icon, as that is generally what is used for settings/config area in UI.

Also checking in mobile view and fixing up .... going for my first pull-request on a public repo ... only used github on private repo before - this'll be a confidence booster to do more public contributions if I don't stuff it up :)

@brianteeman try enabling the chat add-on and then see what happens to the sidebar - TOTALLY break that right sidebar area ... but not sure the chat add-on is actually operational yet? @mbabker ??

**Comment by dbhurley** [comment]
No need for sarcasm @brianteeman - we appreciate constructive criticism (minus the bonus). :) Thanks for helping point out a UI confusing aspect, and thanks @MaxOnTheHill for the gear icon advice.  
I admit I missed this setting when reviewing the UI previously.

**Comment by MaxOnTheHill** [comment]
@dbhurley if it's OK I'll have a go at updating the icon and mobile nav and doing the pull request.

Nice to see you are using Bootstrap3 and Fontawesome ... my favourites :)

**Comment by dbhurley** [comment]
:+1: go for it! Much appreciated.

**Comment by alanhartless** [comment]
Hey @MaxOnTheHill ,

Can you create a new issue on what is totally broken in the right sidebar area?

Thanks,
Alan

**Comment by MaxOnTheHill** [comment]
ref: Chat Add-on Breaks Right Sidebar Display -> https://github.com/mautic/mautic/issues/37

**Comment by alanhartless** [comment]
@MaxOnTheHill Oh gotcha. Whew, so just a UI issue rather than a totally broken something something :-)  had me worried!

Anyway, so the right sidebar is designed to be somewhat customizable by addons, for example the chat addon.  The side bar has 3 canvases: left, main and right.  If an addon pushes something to the main canvas, the admin menu is moved to the left canvas.  A cogwheel appears in the main canvas header that will get you there.  The admin menu defaults to the main canvas if empty will of course only show up if the user has been granted access to some area listed. So there's a chance nothing will show up at all in which you'll be greeted by Mautibot.

So suggestions on what to do different with that in mind?  I don't really want to change the "hamburger" icon to a cogwheel because the sidebar's purpose isn't only configuration (via addons, it can be used for really anything that's appropriate for the space).  Looking at other templates on theme bucket for example, the "hamburger" icon is consistently used as the "button" to show/hide sidebars.

Thanks!
Alan

**Comment by brianteeman** [comment]
Sorry if my attempted humour was lost crossing the atlantic

![w0sj](https://cloud.githubusercontent.com/assets/1296369/5973709/6de0b654-a863-11e4-963c-d9fa2a3ac129.png)
The missing strings and colour made it impossible to see the three canvases or to move off the final canvas.

Personally I would not mix the settings and the chat integration. They dont have a logical place together. Its not intuitive to expect that.

I am with @MaxOnTheHill that a cog wheel is more normal icon for settings and you only need the extra two panels if chat is enabled (?) so why not dynamically add a chat icon next to the cog wheel when it is enabled.

That way it is much clearer. People dont like to go hunting around the page looking for things and dont like to be surprised by what they find.

There is a backlash against the hamburger icon but it is a convention now for a menu. So that is what people expect when they see it. The same would be true for the cogwheel. Conventions might be bad but they are known

**Comment by MaxOnTheHill** [comment]
@alanhartless @brianteeman .... yes, I think it is trying to load too much into the one area.
Normal State: 
- have gear icon to click to show settings
If Chat Enabled: 
- Have chat icon next to the settings gear icon

I see the image like what Brian attached ... was messy and confusing ... unless you think otherwise, will update to gear icon and chat icon when the chat plugin is enabled.
- Everyone OK with that?

**Comment by alanhartless** [comment]
I've changed the right "hamburger" to a double cog wheel.  And we are moving chat out of the right sidebar so it shouldn't be an issue.  The chat move won't happen for beta4 but will be part of the RC release.

Thanks!
Alan
