### ISSUE TITLE
Set dateModified on contact creation

### ISSUE THREAD

**Issue by LukaszMaslej** [mautic/mautic#3603]
What type of report is this:  **Feature request**

## Description:
New contacts after creation have null value on dateModified timestamp, that makes impossible to sort contacts with request like `curl -X GET -H "Authorization: Bearer secret" "https://{domain}.mautic.net/api/contacts?orderBy=dateModified&orderByDir=desc"` and get all new or updated contacts at the beginning of the list.

Can `dateModified` field store created at timestamp in case where contact hasn't been yet updated?

**Comment by LukaszMaslej** [comment]
I did review and it looks issue is still present. Is here any chance to fix it?

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
