### ISSUE TITLE
BUG | Line Breaks Do Not Work in Text Area Custom Fields

### ISSUE THREAD

**Issue by Kyle-Foley** [mautic/mautic#3607]
What type of report is this:

| Bug Report | 

## Description:

Currently, if you insert multiple lines (paragraph breaks) of text into a text area custom field, then use the custom field in an email, it will remove the breaks and insert the text as a single line.

The text area custom field should carry line breaks over into the email.

**Comment by mrerich** [comment]
+1 the same problem

**Comment by dbhurley** [comment]
Resolved in 2.12

**Comment by rafas** [comment]
> Resolvido em 2.12

Is there any additional command that needs to be inserted next to the token?
Because entering only the token is not working.
The line break appears in the source code of the message.
When using the {contactfield=field_name_textarea} token it would be necessary to convert the line breaks into <br>
Something similar to the function nl2br()

**Comment by galgamo** [comment]
> Resolved in 2.12

I am in the latest master version from git , as rafas said, only the token doesn't work.

I have tried look at the code, but it is far beyond my knowledge.

I don't know if I have to do an extra step for this to work.
