### ISSUE TITLE
Support both redirect and asset download for form submissions

### ISSUE THREAD

**Issue by natselection** [mautic/mautic#361]
When submitting a form that is set to redirect to a URL it fails to redirect on submit. Instead it just shows a page like "Your download should start within...."

Issue #272 fixed the 500 error that a form submit was causing but it ignores the form settings for what happens after submission.

**Comment by alanhartless** [comment]
Hi Matt,

The problem with the download option and the form redirect is that we can't both force a download and redirect at the same time as the browser will redirect without starting the download.  The only way we could get that to work is if Mautic had control of both the download and the page being redirected to so  we could redirect first, then initiate the download once we get there. But, since the redirect is often to a page outside Mautic's control, we couldn't really do that. 

Most "tuts" on the issue say that you have to redirect to your "thank you" or final page first then start the download.  But, I'm wondering if we could use some javascript magic to add a delay to the redirect to allow the download, then some seconds later, initiate the redirect. There are some browser security mechanisms that may prevent both a download and a redirect but would be willing to give it another shot.  I've fought this scenario a few times and each time ended up coming back to the "redirect first to final page then download" process.

Anyway, couple options for now.  

1) When configuring the download asset form submit action, add the link in the download message that the lead can manually click to return after the download starts.

2) Drop the downloads asset form submit action and create your own by redirecting to your own 3rd party page, then initiate the download from it using the Asset's public URL. 

Going to change the title and mark this as a feature request just for us to look at improving the form submit/asset download process.

Thanks!
Alan

**Comment by natselection** [comment]
Thanks Alan. Maybe some sort of indication of the limitation in the form settings would be a good addition as well.
