### ISSUE TITLE
Show API update calls in contact history

### ISSUE THREAD

**Issue by maxSupermoney** [mautic/mautic#3622]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | x

## Description:
When viewing the history in the contact details, updates made via API are not shown. 
Since the API call history is not displayed, it is difficult to positively identify what caused a field to change values.

Api updates could display similar to form submissions and show the values of the fields that were submitted.

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
