### ISSUE TITLE
Direct Contact Email Lightbox Client Name Suggestion

### ISSUE THREAD

**Issue by mikeamcbrien** [mautic/mautic#3658]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? |  X
| Enhancement? | X

## Description:
When sending a direct email to a single contact, it is titled "Send a custom email to xxxxgmail.com" - For clarity purposes, it would be helpful to also include the customers First and Last name if it exists.  Many of my clients don't necessarily have descriptive emails and the added clarity would be small, but helpful.

![sendto name](https://cloud.githubusercontent.com/assets/867651/23870445/d0daf5f8-07fc-11e7-800d-1f2a9beeeb10.png)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.7.1
| PHP version | 7.0.16

### Steps to reproduce:
1.   Contact Section, click arrow dropdown next to contact, select 'Send Email'
2.  Title in lightbox

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
