### ISSUE TITLE
Check history of events in email tracking from external source

### ISSUE THREAD

**Issue by martinduplex** [mautic/mautic#3663]
What type of report is this:
Feature / Process

| Bug report? | N
| Feature request? |  Y
| Enhancement? | Y

Hi all,

I am wondering whether it is possible for us to check the list of contacts who has opened or clicked any link built within the email templates created externally (not within Mautic system) that has the Mautic tracking script embedded in the source code? For instance, our email templates are built in the CRM (Customer Relationship Management) system which is Vtiger. The email template hosted in VTiger have the Mautic tracking pixel / script code embedded in the source code.

We want to know whether the history of read and clicks captured from those email templates are visible in the history events list in the contact page in Mautic? If so, how we could isolate / filter contacts who read email templates sent from CRM system (Vtiger) from other contacts that are populated in the Mautic database?

| Mautic version | 2.2.0
| PHP version |  5.6

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
