### ISSUE TITLE
Mautic Mapping IP locations Incorrectly

### ISSUE THREAD

**Issue by Rikk03** [mautic/mautic#3690]
What type of report is this:

| Bug report

## Description:
Mautic is detecting my IP address, but then in the contact view it tells me im in Utah!!

Im NOT in Utah US, but in Romania (according to my ip) so something is clearly fishy.
## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.7.1
| PHP version | 5.6 Fastcgi

### Steps to reproduce:
1. do a test contact creation via form
2.  Check your IP location in the contacts

**Comment by kuzmany** [comment]
Mautic don't provide geo location, but your geo location services in configuration. 

Step 3: Download the IP lookup service database

By default, Mautic installs set to use MaxMind's free GeoLite2 IP lookup database. Due to the licensing of the database, it cannot be included with Mautic's installation package and thus must be downloaded. Click on the cogwheel in the upper right hand of Mautic to view the Admin menu then click Configuration. On the System Settings tab, scroll down to find the IP lookup service option and click the "Fetch IP Lookup Data Store."

You could also choose another supported IP lookup service if you prefer.

https://mautic.org/docs/en/setup/getting_started.html
