### ISSUE TITLE
Upgrade Sets app/console To Non-Executable

### ISSUE THREAD

**Issue by j-ki** [mautic/mautic#3707]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
I used the web interface to upgrade Mautic from 2.6.1 to 2.7.1. I check the file permission of app/console and it's 644. Because the executable bit is not set, none of the cron jobs will work.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.7.1
| PHP version | 7.0

### Steps to reproduce:
1. Use the web interface to upgrade Mautic from 2.6.1 to 2.7.1.
2. Check file permission of app/console
 
### Log errors: 

N/A

**Comment by escopecz** [comment]
The file permission is still "Executable file" in the source code at GitHub:

https://github.com/mautic/mautic/blob/staging/app/console

We'll have to find on what stage the executable permission disappeared.

As a quick fix, use `php app/console ...` instead of just `app/console ...` to make the commands working.
