### ISSUE TITLE
2.7.1 install on subfolder with broken URL to images similar to avatar issue in 2.6

### ISSUE THREAD

**Issue by ralfhug** [mautic/mautic#3709]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
Broken URL to email/landing page theme images if version installed as subfolder. Related to avatar issue that was discovered in 2.6 #3382

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.7.1
| PHP version | 7.06

### Steps to reproduce:
1. Installed test version 2.7.1
2. Open Email Builder or Landing Page Builder with preinstalled themes or own theme
3. URL path to image folder is broken/duplicated:  domain.com/mautic/mautic/themes/sunday/img/logo.gif.
4. Replacing missing image with new image will work, however, if implementing new theme path to image folder remains broken
 
### Log errors: 
one error in log file: looks like unrelated to issue
2017-03-19 12:01:00] mautic.ERROR: SCHEMA ERROR: An exception occurred while executing 'SELECT f.alias, f.is_unique_identifer as is_unique, f.type, f.object FROM lead_fields f WHERE f.object = 'lead' ORDER BY f.field_order ASC':  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db498156_9.lead_fields' doesn't exist [] []

**Comment by GiovanniCst** [comment]
Same issue for me, asked for support here: https://www.mautic.org/community/index.php/7552-v-2-8-0-404-on-mautic-form-js

**Comment by GiovanniCst** [comment]
Resolved here: https://www.mautic.org/community/index.php/7552-v-2-8-0-404-on-mautic-form-js

**Comment by ralfhug** [comment]
Thanks @GiovanniCst for your update.

**Comment by GiovanniCst** [comment]
@ralfhug You're welcome - if you have installed mautic in a subfolder you **may** suffer the issues described here:

https://www.mautic.org/community/index.php/7571-2-8-0-tracking-pixel-link-in-emails/

and here

https://www.mautic.org/community/index.php/7359-mautic-2-7-1-campaign-email-links-not-working-is-it-a-known-bug/

Being quite dumb, it took me a couple of days to figure out a small hack to resolve them. I am linking them to you so that you can have a solution to keep things going.

Did't mean to bother you, I just wanted to help out, just in case,

ciao
Giovanni

**Comment by escopecz** [comment]
Fixed in https://github.com/mautic/mautic/pull/4148
