### ISSUE TITLE
Email Archive and Category Option - Feature Request

### ISSUE THREAD

**Issue by versadial** [mautic/mautic#371]
For emails, have the ability to Archive an email. So not delete it, but instead mark it as archive and have it move to an Archive folder. This allows emails in the view to be hidden and not clutter active  emails. 

Example....Can assign an email to archive and by default Archives are hidden. A checkbox can be clicked to display the archives. Emails in Archive folder are automatically made Unpublished.

Also, possibly a drop down selection next to the Search box, drop down is ALL (Categories that are manually created) and ARCHIVE in the list. This way you can flip between specific categories to view emails and search within a category, and also view only Archived emails.  Having the checkbox selected for archives however displays archives within the category you are in.

**Comment by RCheesley** [comment]
+1 from me - also useful when you have a huge volume of assets and some of which are no longer in use.  Don't want to lose the stats, perhaps, or want to use them a year later, but don't need them clogging up the view.

**Comment by zenzozen** [comment]
+1

**Comment by nithinga** [comment]
+1

**Comment by csaeum** [comment]
+1

**Comment by npracht** [comment]
+1 and it can be extended to any feature :-)

**Comment by dokime7** [comment]
+1

**Comment by ronnieduke** [comment]
+1, but extended to all objects such as emails, landing pages, campaigns, forms, etc.

**Comment by gingerling** [comment]
+1 - or just toggle unpublished emails. Part of the issue for me is that the statistics or opens etc only show on the email, so if I delete the email to tidy up I lose my stats :(

**Comment by gingerling** [comment]
This would help also: https://github.com/mautic/mautic/issues/5490

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
