### ISSUE TITLE
Report - add a tracked webpage report

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#3710]
| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | x
| Enhancement? | x

## Description:
Today, the page report gives data only on landing pages. it would be great to have the ability to make report depending on any tracked URL.

### Example
| URL  | Amount of contacts
| ---| ---
| test.com | 122
| test.com/id=1 | 14
| test.com/id=17 | 18

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
