### ISSUE TITLE
Show Weight column in Stages view

### ISSUE THREAD

**Issue by mingfang** [mautic/mautic#3714]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
N
| Feature request? | 
Y
| Enhancement? | 
Y

## Description:
Currently the Stages view can be sorted by ID.
I would like to sort Stages by weight.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
2.7.1
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
