### ISSUE TITLE
Track Progressive Profiling form via Cookie, URL Token, or login

### ISSUE THREAD

**Issue by Jo-Pitts** [mautic/mautic#3715]
| Feature request? | 

## Description:
Currently progressive forms get pre-loaded based on IP address.  This doesn't work well for shared PCs, PCs on networks, Mobile devices that may get different IPs on different wifi networks (or just from the mobile network).

A much needed feature is to correctly 'pre-load' a progressive profile form based on:
1. A cookie
2. A URL containing a token (i.e. one that might be embedded in an email)
3. A social or other login.

The token for cookie and email should be interchangeable.  This means that once a user clicks on a URL and the cookie is generated, then the form can be pre-loaded from the newly generated cookie.  If the user is on a PC they've used before, then the cookie can drive the pre-loading of already entered data.

Further - if a user logs in via social media, and has previously logged in on the same or any other PC, this should be used to pre-load their previously entered details into the progressive form.

Mautic admins should be given the option to turn off IP tracking.

**Comment by Jo-Pitts** [comment]
I see this didn't make it into 2.9.0.
This is really quite urgently needed to make progressive profiling work with any sense of usefulness.
Any thoughts on when this might make it into a sprint?

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
