### ISSUE TITLE
No View Own, Edit Own and Delete Options in Permissions for Segments and Campaigns

### ISSUE THREAD

**Issue by devadattas** [mautic/mautic#3716]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:

In role permissions there is no "View Own", "Edit Own" and "Delete Options" in Permissions for Segments and Campaigns

## If a bug:

| Q   | A
| --- | ---
| Mautic version | master
| PHP version | 5.6.3

### Steps to reproduce:
1. Go to /s/roles/edit/2
2. Click on "Permissions" >> "Campaign Permissions" and check the list
3. There are no "View Own", "Edit Own" and "Delete Options"  visible

**Comment by gingerling** [comment]
+1 the roles feature is 95% there for allowing one instance to be used for several businesses which is amazing! I run a web shop, a web design buisness and techie youth group, and I need mautic for all 3. Would be great to use the same instance! While all 3 are mine so it's okay for me to see my own campaigns, I worry about sending a campaign from the wrong account and also it's a bit frustrating having all my campaigns appear mixed up together even if I made them as different users. This feature would make my week!! 😁

**Comment by gingerling** [comment]
Actually, this won't solve the problem anyway, I have found.

If user with role B makes a form and contacts are created by filling out the form, a user with role a can wind up with those contacts in their segments and the campaigns very easily. 

I just did it by mistake, I made a new role and user for that role (B), and they couldn't see most of each others stuff (excluding those mentioned in this bug). User role B had a form, which user A couldn't see, but user A had a segment that was like "everyone excluding x y z" which was created before user B even excisted. All of user B's contacts from the form ended up in user A's segment because they were not excluded specifically, and then emails were sent to them from campaigns involving those segments. 

A total mess. My advise is don't use this system at all!

ps: if that is a bug, please make a report, I don't have time today. I suspect it's expected behaviour though (perhaps not forseen, but stilll)...

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._

**Comment by cloudpotions** [comment]
Hello all. Until this is fixed under Mautic Roles - The best solution I have found for this is to use [Leads Bridge](https://leadsbridge.com/) - This is a sync service similar to Zapier but it allows you to sync a Segment. From here you can sync over a segment based on a trigger... You can also update data as well (such as points, etc). Either pop it in an excel spreadsheet via google sheets or to any of the supported CRM's, etc.
