### ISSUE TITLE
Encrypt mtc_id cookie

### ISSUE THREAD

**Issue by iadj** [mautic/mautic#3718]
| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | x

## Description:
Currently, the `mtc_id` cookie value is saved in plain text i.e. `mtc_id : 3039`.
This could be exploited by changing the cookie value to overwrite or track the wrong user. If the value is encrypted with a secret key, and unencrypted on Mautic's side, the tracking experience would be more secure.

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
