### ISSUE TITLE
SAML Logout Landing Page

### ISSUE THREAD

**Issue by ChuckRenner** [mautic/mautic#3744]
| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | X

## Description:
SAML logout returns to the /s/login page.  This is confusing to end-users.  Can a SAML-enabled site instead go to a page with a 'click to login again' button?

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
