### ISSUE TITLE
Segment filters - drag and drop

### ISSUE THREAD

**Issue by igisho** [mautic/mautic#3751]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | yes
| Enhancement? | 

## Description:
It would be nice if you could make segment filters drag and dropable.

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
