### ISSUE TITLE
Gated video autoplay

### ISSUE THREAD

**Issue by giampyart** [mautic/mautic#3769]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | N
| Feature request? | Y
| Enhancement? | N

## Description:
Could be very useful to insert YouTube gated video into Mautic landing page and set it on autoplay.
Now the video URL gets corrupted with ?rel=0&autoplay=1
Embedding a video it works, but not with gated form of Mautic.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
