### ISSUE TITLE
REST API GET/contacts produces incorrect JSON

### ISSUE THREAD

**Issue by thomeudt** [mautic/mautic#3778]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
When making a GET/contacts call via the REST API, the result is a JSON string that is not structured as documented. Instead of returning a JSON array as documented, like this:

```
{
    "total": "1",
    "contacts": [
        {
            "id": 47,
            "isPublished": true,
```

it returns a list of nested JSON objects that looks like this

```
{
    "total": "87",    
    "contacts": 
    {        
              "183": {            
              "isPublished": true,  
```

This makes parsing incredibly more difficult in my case, as I want to write contact by contact into a database (through a java application). You have to mess around with Regex stuff and that can cause a high risk of error.

I suggest the JSON output is fixed to comply with what is documented. Alternatively, as a workaround, a simple rest call returning just a the contact IDs would be OK to, so that one can then iterate through and make GET/contact/id rest calls to retrieve the required contact details. 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.7.1
| PHP version | PHP Version 7.0.15-0ubuntu0.16.04.4

### Steps to reproduce:
1. make a GET/contacts call to the restful API 
2. compare returned json string to documentation
 
### Log errors: 
 n/a

**Comment by escopecz** [comment]
This is a problem in the documentation part. We cannot change the API output format as it would be a BC break. Please report it to https://github.com/mautic/developer-documentation or even fix the format there if you have a few minutes to invest into it.

The output is still a valid JSON object. Since JS doesn't have associative arrays, it stores it as an object. But every programming language should have methods to decode JSON and iterate on object properties.

**Comment by glebret** [comment]
Hi escopecz, the format returned by Mautic is useless as is. 
I can only retrieve the ID and then I have to make a new API call with the ID to retrieve the contact information.
Have you a method to get the contacts information directly from the get contact list response ?
