### ISSUE TITLE
extending social monitoring

### ISSUE THREAD

**Issue by BembelGmbH** [mautic/mautic#3788]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | N
| Feature request? | Y

## Description:
It would be grate to extend the social monitoring in 2 ways. 
1. When monitoring a social network, one wants to know how often & where (and also by whom, but not the way it is implemented in mautic) people are mentioning me or my company. I don't need all the people that mentioned me, stored as contacts in mautic - what I need is just a list of conversions that concern me. And this would also help not to spam my contact table. 

2. I would like to build my own plugin to monitor an other social network, but there seems to be no mentioning about how it can be done in the documentaion.

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
