### ISSUE TITLE
Browse server never resolves in landing page builder

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#379]
When using the image upload feature in the editor, and browsing the server to find an image, the spinning circle of death shows and the directories never display - however it is possible to create folders etc using the buttons, but you can't see them!

**Comment by alanhartless** [comment]
Hey Ruth,

I'm not able to reproduce this in chrome, FF, or safari on a mac.  If you view the browser's developer console, do you see any JS errors? 

Thanks!
Alan

**Comment by alanhartless** [comment]
Copied Ruth's response from #387.

```
No errors, but if I view the file it's trying to access if I switch between grid/list view I get this:

File accessed: http://mauticurl.com/app/bundles/CoreBundle/Assets/js/libraries/ckeditor/filemanager/connectors/php/filemanager.php?path=%2F&mode=getfolder&showThumbs=true&time=980&type=Images

I see a bunch of these errors being shown:

Warning: date(): It is not safe to rely on the system's timezone settings. You are required to use the date.timezone setting or the date_default_timezone_set() function. In case you used any
of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /mauticpath/app/bundles/CoreBundle/Assets/js/libraries/ckeditor/filemanager
/connectors/php/filemanager.class.php on line 247
```

**Comment by alanhartless** [comment]
It's possible the warnings could be affecting the ajax responses.  Could you check the server's php.ini to see if it has date.timezone uncommented and set?

**Comment by RCheesley** [comment]
Pretty sure it won't even allow me to install Mautic without it being set,
think it throws a red warning.  I believe I set this in the php.INI to
allow me to install. Will check tomorrow.

Ruth
On 12 May 2015 6:20 pm, "Alan Hartless" <notifications@github.com> wrote:

> It's possible the warnings could be affecting the ajax responses. Could
> you check the server's php.ini to see if it has date.timezone uncommented
> and set?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mautic/mautic/issues/379#issuecomment-101356777>.
>

-- 
Be like me, be Carbon free - don't print this and save a tree
IMPORTANT: The contents of this email and any attachments are confidential. 
They are intended for the named recipient(s) only. If you have received 
this email by mistake, please notify the sender immediately and do not 
disclose the contents to anyone or make copies thereof.

**Comment by CyberZen53** [comment]
I am having the same issue on a fresh install of 1.2.1 - the spinning circle of death while directories and files won't display.  Reproduced on 3 different browsers (Chrome, Safari, FF) while trying to load images into email . htaccess looks for the images subdirectory looks ok. Could it be a permissions issue I wonder? 

The workaround is to copy local images into mautic's root directory and bypass the File Manager window. 

Did Chrome Inspect Element on URL: /app/bundles/CoreBundle/Assets/js/libraries/ckeditor/filemanager/index.html?type=Images&CKEditor=emailform_customHtml&CKEditorFuncNum=1&langCode=en

Shows the following warning error:

Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.

chrome-extension://fnphbafmnfhfpndcjdnjmkmikgladall/on_content_end.js:54 on_content_end ==>response to loadPagePattern, 
href=http://bohmautic.laxden.com/app/bundles/CoreBundle/Assets/js/libraries/cked…ml?type=Images&CKEditor=emailform_customHtml&CKEditorFuncNum=1&langCode=en, pattern.id=undefined
chrome-extension://fnphbafmnfhfpndcjdnjmkmikgladall/on_content_end.js:80 before call TMExt.initTooltip
chrome-extension://fnphbafmnfhfpndcjdnjmkmikgladall/on_content_end.js:85 after call TMExt.initTooltip

**Comment by wderuijter** [comment]
I've got the same problem after upgrading to 1.3.. Trying to browse for an image results in the spinner of death. Chrome dev tools says:

```
https://mautic.example.com/app/bundles/CoreBundle/Assets/js/libraries/ckedi…lemanager.php?path=%2F&mode=getfolder&showThumbs=true&time=307&type=Images 
Failed to load resource: the server responded with a status of 500 (OK)

https://mautic.example.com/app/bundles/CoreBundle/Assets/js/libraries/ckedi…lemanager.php?path=%2F&mode=getfolder&showThumbs=true&time=323&type=Images 
Failed to load resource: the server responded with a status of 500 (OK)

https://mautic.example.com/app/bundles/CoreBundle/Assets/js/libraries/ckedi…lemanager.php?path=%2F&mode=getfolder&showThumbs=true&time=290&type=Images 
Failed to load resource: the server responded with a status of 500 (OK)

https://mautic.example.com/app/bundles/CoreBundle/Assets/js/libraries/ckedi…lemanager.php?path=%2F&mode=getfolder&showThumbs=true&time=760&type=Images 
Failed to load resource: the server responded with a status of 500 (OK)
```
