### ISSUE TITLE
Automatically select contact segment when import is clicked from segment search

### ISSUE THREAD

**Issue by gingerling** [mautic/mautic#3791]
What type of report is this:

| Q  | A
| ---| ---
| Enhancement? | Y

## Description:
If I want to add subscribers to a segment manually and in bulk I go

Segment > view x contacts in segment and click import. I then choose my file and click upload. I then have to again select the segment I want to add too.

It would be great if the "contact segment" dropdown would be automatically set to the segment I am adding too, rather than me having to choose it, it took me a few goes to understand why the contacts where not being added to the segment as expected.

**Comment by gingerling** [comment]
just spent a load more time trying to import to segment today, assuming that this would work, which of course it doesn't. Part of the issue is that when you go to segment, view members, it's hard to understand that you are actually just getting a search of contacts, not a dedicated page. I really don't think the current functionality is very nice for users.

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
