### ISSUE TITLE
Deleted lead ID reused by MySQL Innodb which leads to timeline error due to assumed missing template

### ISSUE THREAD

**Issue by synologic** [mautic/mautic#382]
After installation of 1.0.5 thru the web interface, the following error occurs when trying to view a lead:

[2015-05-09 10:14:20] mautic.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "The template "MauticLeadBundle:SubscribedEvents/Timeline:delete.html.php" does not exist." at /www/marketing/app/cache/prod/classes.php line 1093 {"exception":"[object] (InvalidArgumentException(code: 0): The template \"MauticLeadBundle:SubscribedEvents/Timeline:delete.html.php\" does not exist. at /www/marketing/app/cache/prod/classes.php:1093)"} []

After creating the empty file called delete.html.php in app/bundles/LeadBundle/Views/SubscribedEvents/Timeline everything seems to be working, however i'm not sure what delete.html.php ought to contain.

**Comment by alanhartless** [comment]
Hi,

The delete template should not be showing as once a lead is deleted, it should be viewable. 

Curious, did you by chance delete a lead right before this happened? If you look in your audit_log table and search object_id equals the lead id of the lead causing the error.  Does it show history of another lead that was deleted?

Thanks,
Alan

**Comment by synologic** [comment]
Hey,

looks like the object_id of the current lead was reused and indeed the old lead with the same id was deleted.

Still, the delete template was missing, shouldn't it exist ?

**Comment by alanhartless** [comment]
Hi!

So here is what I think happened.  It's come to our attention that innodb will reuse an auto-incremented ID if the last ID is deleted then the server is restarted for whatever reason.  (https://dev.mysql.com/doc/refman/5.1/en/innodb-auto-increment-handling.html). So, that kind of makes things awkward when an ID that assumed will never be reused gets reused.  I'm not totally for sure what we are going to do with this yet as it either means we have to manually manage the incrementing IDs, move away from innodb or find a way to compensate for it.

So I think the lead ID was assigned, was deleted, then reassigned by MySQL which lead to the mixed timeline data.  The delete template is missing because a deletion entry should never be displayed in a leads timeline (as it's assumed the lead no longer exists).  

For now, we can definitely add a check when pulling audit log data to ensure that it doesn't pull data for a previously deleted issue (by comparing lead created date to the entry dates in the log). I'm going to change the title of this and mark it as a bug for us to investigate further.

Thanks!
Alan
