### ISSUE TITLE
Allow adding multiple email services and choosing which one to use for actions / emails

### ISSUE THREAD

**Issue by isleshocky77** [mautic/mautic#3827]
What type of report is this:

| Q  | A
| ---| ---
| Feature request? | Y
| Enhancement? | Y

## Description:

Currently you can only configure one email service (i.e. Sendgrid, Mandrill, SES). It would be nice to be able to specify different email gateways to use for different purposes. (e.g. Transaction Email vs Marketing Email)

**Comment by JohnConnell** [comment]
I've been kicking around a similar idea on the Slack channel this week and was going to submit a feature request tonight, but I'm going to piggyback here instead with some details on why I think this feature is important.

When sending broadcast emails to large (50k+) lists, transactional and test messages are effectively taking a number and waiting in line depending on how far along the broadcast is. While Mautic moves these messages to the front of it's own queue, there's no way for the mail server to distinguish them from the flood of broadcast emails in order to move them to the front of the "real" queue.

In my case we have an ~80k list and cron 3k emails to Postfix every 3 minutes, but we can only deliver ~20k/hour so the queue builds rapidly. Transactional emails from campaigns and test emails Mautic users send themselves can be delayed for hours as a result. While delivery speed can vary widely between services and hardware, list sizes also vary widely between users. Mautic provides all the tools needed to build a big list currently, but without this feature it's hard to market to a big list without using a separate installation or other software to send broadcasts.

**Comment by mingfang** [comment]
+1

I would like three emails settings.
1-for campaign emails. I would use something like SES for those and may use "noreply" return address.
2-transactional emails. I can still use SES but will valid return address.
3-user emails. Currently Mautic does not support sending emails to users at all, but it should.  I will user internal email server for those.

**Comment by w3update** [comment]
Yes there should be support for multiple email delivery channel for marketing or transaction or specific to campaign or email.
![image](https://cloud.githubusercontent.com/assets/4979654/24994248/9bd79b32-2047-11e7-85d1-9baf84cac233.png)

**Comment by heathdutton** [comment]
This feature would make Mautic capable of providing service to larger organizations or marketing groups (at least in regard to email). Is there any movement on this front?

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._

**Comment by sgregori** [comment]
Excuse me, i'm interested in this feature, but the ideas forum, has disabled registrations and we can't post.

Thanks,

**Comment by brendansmallco** [comment]
+1 Bump! Need to be able to use seperate emails for marketing delivery and internal user prompts.

**Comment by felixvarghese** [comment]
This feature is available for discussion on the ideas forum at https://forum.mautic.org/t/ability-to-specify-different-email-gateways-to-use-for-different-purposes/10620
