### ISSUE TITLE
Segments - make it traditional way

### ISSUE THREAD

**Issue by naveedpeerzade** [mautic/mautic#3838]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? |  Y
| Enhancement? | 

## Description:
I have been using Aweber and couple of other autoresponder service provider for over a decade and as a marketer and UI/UX designer myself... one of the feature what really makes it super easy to use is "Lists"

I know that you Mautic call it Segments. But I have been testing it for couple of days and it's a lot of manual work to make use of it. So here are my suggestions.

1. When we create a Segments (list), we should be able to have "From email" and "From: Name" and even be able to assign mailing server, which gets associated with this particular list... This way, we don't have to enter "from name" and "from email" for every email. And can have LIST A to send emails from Amazon, while LIST B will send from Sendgrid.

2. Associate campaigns and emails to "Segments"... this way, if we are talking about 100s of emails, things do not get cluttered... So if we select any specific "List" we are working on emails or creating the one only for that "List/Segments" ... It will also be easy to create followup campaign for each "Segment / List"

3. Be able to have same subscriber associated with multiple Segments. So x@y.com can have duplicate entries. This is because it makes it easy to see subscribers for specific lists... (I understand there would be a workaround to filer by keeping single entry)

4. Custom fields, should also be associated with the "Segments" ... the reason is... when we have multiple list for multiple products/domains/services... they will have separate custom fields and we dont have to create so many fields globally. Also these fields would not clash with others.. 

eg. I have custom fields "username", "password" I use that for all my different products I sell on different domains and each of them have its own members area. So if we have only 1 entry of a buyer, we will have to create several fields for the same. like "username_for_productA", "username_for_productB" etc..

Aweber does absolutely great job associating everything to Lists.

**Comment by escopecz** [comment]
1. The "From email" and "From name" can be configured for every email. Since Mautic isn't only email autoresponder, each communication channel must have its configuration at the channel. There is another feature request for different mailing server configurations.

2. There are global categories which can be used to group emails and campaigns together.

3. Not sure I understand. A contact can be part of multiple segments.

4. I don't see why there should be more custom fields for each segments. It'd make everything much more complicated. But if you feel there is need for that, please create a special feature request for that.

It's hard to keep the feature requests up to date if it is list of independents features, so please, create a new issue for each feature. And check first with documentation if Mautic already doesn't have that and search the issues here if it wasn't already reported.
