### ISSUE TITLE
Add import html button in code mode

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#3849]
| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | x

## Description:
As does some emailing tools (Mailchimp) it's be great to have an **import html button** in the code mode. That way you could select a zip containing the HTML file + images in a folder called media.
In consequence, the user would not need to import each image manually and change link.

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
