### ISSUE TITLE
Directly send transactional Mails, Queue Mailing E-Mails

### ISSUE THREAD

**Issue by mburamorde** [mautic/mautic#3860]
Hello,

I'am running Mautic 2.7.1 and loving the product ;)! We build via campaigns an Double Opt In Workflow and would like to send the "Optin-E-Mail" direct without waiting for the cronjobs!?

Is there a way to act like this? If someone wants to subscribe he should receive the email DIRECT without any delay.

Thanks,
Michael

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
