### ISSUE TITLE
Make custom field of type `url` clickable in the details view

### ISSUE THREAD

**Issue by moltar** [mautic/mautic#3864]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | n
| Feature request? | n
| Enhancement? | y

## Description:
Make custom field of type `url` clickable in the contact view.

Ideally, should be redirected in a way that it strips referral string in order not to expose the Mautic install to the visiting website.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. Add custom field of type URL
2. Update contact and add the URL to the new custom field
3. Save contact
4. Look at contact view screen
5. Unfold "Details" section
6. Look in the appropriate group tab (where you added the new custom field)
7. The URL is listed but is not clickable.
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
