### ISSUE TITLE
Upcoming Emails count unpublished e-mails

### ISSUE THREAD

**Issue by tuliobbs** [mautic/mautic#3872]
I have an e-mail that I tried to send to X people, but had some internet issues and could send only to 70%. Because the promotion has ended, there is no need to send to the rest of the people.

In the dashboard, I cant see the upcoming e-mails, because it is filled with this specific segment e-mails that has not been 100% sent.

<img width="1038" alt="screen shot 2017-04-18 at 19 09 30" src="https://cloud.githubusercontent.com/assets/27643901/25155344/f02634ce-246a-11e7-97a4-3d62e4013823.png">
<img width="1280" alt="screen shot 2017-04-18 at 19 08 19" src="https://cloud.githubusercontent.com/assets/27643901/25155347/f716b1fa-246a-11e7-96c8-84a395a9e739.png">

**Comment by escopecz** [comment]
What is your suggestion?

**Comment by tuliobbs** [comment]
That when an e-mail is unpublished the upcoming e-mails from it do not show on the upcoming e-mails.

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
