### ISSUE TITLE
A/B Test - Drip campaign does not consider the variant email and no triggers next action

### ISSUE THREAD

**Issue by giampyart** [mautic/mautic#3898]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
Variant email in a campaign is not considered and does not trigger actions.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.7.1
| PHP version | 5.6.30

### Steps to reproduce:
1.   Create email A and an A/B test email B (50% split)
2.   Create a campaign:
         - starting from a segment
         - send email to more then 2 contacts
         - if open action add +2 points if yes

Only if contacts that open email A will receive points and action will be trigged into the campaign.
No action for all contacts that open email B

**Comment by npracht** [comment]
+1 !

**Comment by npracht** [comment]
I've checked that and i can explain it:
The decision is looking for the previous email sent action ID. The variant has another ID. Consequently then matching for a variant never happens because the contact did not open the email with the native ID (not the variant ID).

![capture d ecran 2017-07-12 a 12 33 37](https://user-images.githubusercontent.com/14075239/28115628-fe2fc782-6705-11e7-90d2-69ba321d2e0d.png)
![capture d ecran 2017-07-12 a 12 53 13](https://user-images.githubusercontent.com/14075239/28115629-fe300b7a-6705-11e7-8bd0-26eb0caa72d6.png)
![capture d ecran 2017-07-12 a 12 33 58](https://user-images.githubusercontent.com/14075239/28115627-fe2f3754-6705-11e7-86a8-200635ddffd1.png)

**Comment by npracht** [comment]
Hi @alanhartless & @escopecz we spent a day on that to try to fix it, but it is in the mystical part of the campaign event manager. I think that can be only hold by **Sir Alan Hartless** 😈 .

**Comment by giampyart** [comment]
@alanhartless we need your power!

**Comment by npracht** [comment]
Still critic... A/B testing on campaign email is broken...

**Comment by wuillaume** [comment]
Hi,
Is that issue being solved?

**Comment by npracht** [comment]
@amsolucionesweb & @wuillaume would you try again in 2.14.0 with the campaign refactoring ?

**Comment by kuzmany** [comment]
Let's test: https://github.com/mautic/mautic/pull/6765
