### ISSUE TITLE
Organise segments/campaigns/emails by category instead of 1 long table

### ISSUE THREAD

**Issue by tadinski** [mautic/mautic#3956]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | ✅
| Enhancement? | 
<img width="1245" alt="screenshot" src="https://cloud.githubusercontent.com/assets/6358371/25615902/11287e46-2f3a-11e7-85b3-af59b81e7f1e.png">
<img width="1317" alt="screenshot2" src="https://cloud.githubusercontent.com/assets/6358371/25616098/09c5b582-2f3b-11e7-808f-db14f47e24b8.png">

## Description:
It would be nice to have an ability to group segments/campaigns/emails by category. These sections become cluttered very quickly, I either have to use the search (which is just fine) or do a CMD/CTRL + F. Visually it would be much more structured and organised.

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
