### ISSUE TITLE
Ability to Split Contact Segments Into Smaller Segments

### ISSUE THREAD

**Issue by CodeBradley** [mautic/mautic#3960]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | x
| Enhancement? | 

## Description:

I've been using Pardot the last few years and I decided to give Mautic.com a try. The first thing I noticed was that it lacks the ability to split segments into smaller ones. When clicking on an indvidual list (segment) in Pardot, it presents you with a Split button where you can then split the list by percentages or evenly across the number of splits needed:

![pardot-list1](https://cloud.githubusercontent.com/assets/3913066/25640346/d95c4900-2f54-11e7-89df-4c7b243cec95.png)
![pardot-list2](https://cloud.githubusercontent.com/assets/3913066/25640345/d95bd6aa-2f54-11e7-927f-7fa1c3c0ea42.png)

This was a nice feature to have when you have a sending limit or if you want to send to a list over a period of time.

---

Another thing I'm wondering is if there is an option to add a DKIM record for Mautic.com?

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
