### ISSUE TITLE
Reports : Sorting on Calculated columns

### ISSUE THREAD

**Issue by YannickBiet** [mautic/mautic#3971]
| Q  | A
| ---| ---
| Bug report? | No
| Feature request? | Yes
| Enhancement? | Yes

## Description:
Mautic 2.8.0 introduced the possibility to group by and add Calculated columns
But there's no way to sort the data using this Calculated columns

My scenario is : group all contacts per country, count contact ID, and SUM the points
Order by numbers of contacts DESC, and then by number of points DESC.

No way to achieve that as the Calculated columns are not listed within the "order" part

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
