### ISSUE TITLE
Feature: Add Padding Left and Right for Sections on Email Builder 

### ISSUE THREAD

**Issue by luizeof** [mautic/mautic#3981]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | Y
| Enhancement? | Y

## Description:

Add option on email builder for Left and Right padding for Sections.

![download](https://cloud.githubusercontent.com/assets/257004/25673562/3b1b6586-300e-11e7-9608-340a7b16c9a2.png)

**Comment by luizeof** [comment]
@mqueme @virlatinus @alanhartless @escopecz

**Comment by merlin0** [comment]
I am not sure if this is really usefull since only some email clients support padding/margin.  I would recommend implementing a solution that works in every email client or atleast add a fallback.

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
