### ISSUE TITLE
Feature: Change Query Expr ->eq To ->like on Search for URL in Method getLeadHits of HitRepo

### ISSUE THREAD

**Issue by peteratnsight** [mautic/mautic#4014]
In order to request easily Page and Domain Hits of an Identified Lead via the
HitRepository pls. change the search expression on the URL-Options in 
Row 90 of File /ap/bundlesPageBundle/Entity/HitRepository.php 

from:
            $query->andWhere($query->expr()->eq('h.url', $query->expr()->literal($options['url'])));
to:
            $query->andWhere($query->expr()->like('h.url', $query->expr()->literal($options['url'])));

**Comment by escopecz** [comment]
It would have a bad effect on performance. But I wouldn't have anything against a new option in the `getLeadHits` method. For example

```
if (!empty($options['url_like']) {
    $query->andWhere($query->expr()->like('h.url', $query->expr()->literal($options['url_like'])));
}
```
Are you able to send a pull request with that code change?

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
