### ISSUE TITLE
Distinguish generic mtc.js from dynamic mtc.js

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#4017]
| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | ✔️ 

## Description:
The load of the mtc.js file is quite long on web browser. One of the opportunity to optimize that load, is to add a cache control to the mtc.js.

Unfortunately, there are small dynamic pieces in the mtc.js if the mautic user has **web notifications**, **pages**, (**gated videos** ?) and **dynamic contents**. Because of that, it is NOT possible to add the cache control.

### Recommandation

1. Create a core mtc.js that is ALWAYS the same and that includes a cache control.
2. Create a "dynamic" script (eg: mtc_dynamic.js) that includes variations hereabove which will be generated each time if needed.

-----
_Can be related to https://github.com/mautic/mautic/issues/3656 ?_

**Comment by merlin0** [comment]
+1

**Comment by RCheesley** [comment]
+1

**Comment by caesarcxiv** [comment]
+1

**Comment by winers1290** [comment]
+1

The load time on the mtc.js file is extraordinary. This sounds like a very good compromise.

**Comment by funkolector** [comment]
+1

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._

**Comment by directpromo** [comment]
found here is such the patch https://gist.github.com/nextgens/ca501d3c1b149a62c09b0b409e0651a7 In my case it helped
