### ISSUE TITLE
Allow editng of og:image meta data for landing pages

### ISSUE THREAD

**Issue by gingerling** [mautic/mautic#4051]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | Y
| Enhancement? | 

## Description:
Creating social share for landing page where primary element is embedded video, facebook is using misc. images from page for sharing, so I wish to set a still of the video as the og:image - I am kindof able to do this by using

 <meta property="og:image" content="http://www.ethical-pets.co.uk/themes/ethicalpets/add_images/still.png"/> 

in a code mode box in the builder but it is less than ideal as a) it's in the body not the head and b) once it's in I can't find it to edit it again. It does seem to work on facebook, but I would feel safer having a way to implement this correctly.

It could be done as a "featured image" or space to edit the header code manually

## If a bug:

| Q   | A
| --- | ---
| Mautic version | mautic.net
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._

**Comment by RegisScaggiante** [comment]
For me, this is a very important feature request.
