### ISSUE TITLE
Make 1/2/3 column width configurable

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#4057]
| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | 
| Enhancement? | x

## Responsiveness
The fact of adding 1/2/3 column structure in template and builder is GREAT but it would be greater if it would be responsive.
You can find an article here explaining what could be added in CSS to automaticaly make it responsive : https://innotiom.com/responsive-multi-column-sections-mautic/

Touching this https://github.com/mautic/mautic/pull/3476. @escopecz i don't know if https://github.com/mautic/mautic/pull/3587 takes in charge what is mentionned in the article.

## Width control
It should be also great to be able to modify the width of the structure. Because mautic forces 600px. When you try to integrate that in a landing page.. it is a bit brutal.
### Settings to add in the left configuration panel

- Width of structure
- Width of each column (in %)
- Padding

**Comment by escopecz** [comment]
I think it's duplicate of these:
- https://github.com/mautic/mautic/issues/3871
- https://github.com/mautic/mautic/issues/4032

**Comment by npracht** [comment]
@escopecz the width control is not the same. The guy here has an issue. On my side i'm saying that it should be settable.

**Comment by pcantellow** [comment]
+1

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
