### ISSUE TITLE
Allow Sparkpost Email Type

### ISSUE THREAD

**Issue by ninjoan** [mautic/mautic#4060]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | N
| Feature request? |T 
| Enhancement? | T

## Description:
Enable the Sparkpost option to select the email type using the Mautic Action Email in the campaign builder that allow choosing Marketing or Transactional email type. I was reading in the Sparkpost documentation that you can enable this since is disable by default using `transactional`  `true`
Documentation https://developer.sparkpost.com/api/transmissions.html

Under Options Attributes section

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
