### ISSUE TITLE
Merge function does not give enough detail to select the correct contacts.

### ISSUE THREAD

**Issue by iwantaspeaker** [mautic/mautic#4117]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | x

## Description:
When i select to merge in contacts, i get a list of name to merge with, but no other detail.
How do i know which are the correct contacts if there are multiple people with the same name.
[See image ](https://www.dropbox.com/s/onmr418txhpdh0s/Screenshot%202017-05-22%2015.54.46.png?dl=0)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by kgroveshok** [comment]
I think there is a consistent effect of which one wins based on the contact you edit and the one you then select. Cant off hand remember which way round it goes. Found out by trial and error but yes, would be useful to actually be informative instead of relying on memory ;-)

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
