### ISSUE TITLE
Extend code mode non interpretation to code mode blocks

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#4124]
| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | 👍 

## Description:
The code in code mode blocks is modified by the builder (landing pages and email). I suggest to use this https://github.com/mautic/mautic/pull/4123 to extend non-modification code to the code mode blocks.

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
