### ISSUE TITLE
[Enhancement / Feature Request] Separate email viewing event from campaign triggers

### ISSUE THREAD

**Issue by MaxWebmecanik** [mautic/mautic#4126]
What type of report is this:

| Q                | A        |
| ---------------- | :------: |
| Bug report?      |          |
| Feature request? | &#x2713; |
| Enhancement?     | &#x2713; |

## Description:

Today, when an email is viewed, the tracking pixel it contains triggers all related campaigns immediately. This makes that process very resource intensive.

We were thinking, couldn't we introduce a new _mode_ in Mautic, that would allow the _email view_ event to be seperated from the campaign update by introducing a new cronjob.

In this new mode viewing (and probably clicking) an email would register that event in the database but would not trigger any further actions. The new cronjob would then _consume_ these events at a controlled rate.

Before starting work on that feature, we would really love to have some input. @alanhartless @matishaladiwala, I'm looking forward to your feedback!

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
