### ISSUE TITLE
Distinguish page (SEO) title from page name

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#4138]
| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | x

## Description:
As there is in the setup right hand panel a meta description zone. It would be awesome to have a SEO Title that would be injected in the HTML as `<title>` tag.
Because today it is the internal mautic name that is used as page title.

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
