### ISSUE TITLE
Campaign source excluding contact segment

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#4140]
| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | x

## Description:
It would be nice to have the ability in the campaign segment selector for campaign source, to be able to exclude segments.
eg: make something like including `segment A` & `segment B` and excluding member of `segment C`

![capture d ecran 2017-05-24 a 14 30 41](https://cloud.githubusercontent.com/assets/14075239/26403200/aa97b1d2-408d-11e7-8abb-9dc315a6ec67.png)

It would avoid to create to many segments beforehand.

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
