### ISSUE TITLE
Feature request for option to override Send as owner setting

### ISSUE THREAD

**Issue by snoek8** [mautic/mautic#4170]
What type of report is this:

| Q  | A
| Bug report? | N
| Feature request? | Y
| Enhancement? | Y

## Description:
I love the option to send emails from the contact owner but in some cases have a need to send a segment emails using the Advanced mail field values. But even if I set the sender specifically it still uses the owner. I suggest adding an option to override the Send as Owner option for individual segment/campaign mails.

**Comment by MxyzptlkFishStix** [comment]
https://mautic.org/docs/en/emails/mailer_is_owner.html

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._

**Comment by isleshocky77** [comment]
@npracht @escopecz It doesn't appear (according to #6071) that this ever made it into milestone 2.14.0; it appears it still hasn't made it into the code-base.

**Comment by escopecz** [comment]
You are right. Changed the milestone to 2.16.0 as https://github.com/mautic/mautic/pull/6071 is adressing it.
