### ISSUE TITLE
Got `undefined` on database updates during 2.8.2 installation

### ISSUE THREAD

**Issue by shulard** [mautic/mautic#4183]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
Hello, 

I've just updated my installation from 2.8.1 to 2.8.2 and I got a warning on the databases updates :

<img width="1440" alt="screen shot 2017-06-02 at 15 37 17" src="https://cloud.githubusercontent.com/assets/482993/26728227/c674ad92-47a9-11e7-8d29-93c5c0896d80.png">

I saw on the release announcement that there wasn't any database updates to be made on 2.8.2. Maybe the auto updater can inform that there is no updates instead of displaying a warning.

The update ending successfully.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.1
| PHP version | 7.1

### Steps to reproduce:
1. Go to `/s/update`
2. Trigger the 2.8.2 update process.
 
### Log errors: 

No errors in the log...

**Comment by a1exe1** [comment]
ve got same issue

then 

ive done this 

php app/console doctrine:migration:status 

php app/console doctrine:migration:migrate

seems some migrations should be done by hand in some cases

**Comment by escopecz** [comment]
Just to give you a heads up, the web upgrade UI is not recommended to use for upgrade because it suffers by the HTTP request limits. Use the upgrade script if you can:

https://www.mautic.org/community/index.php/7785-2-8-2-released

The upgrade UI will be removed some time in the future. 

But yes, it seems it has this issue if the upgrade package doesn't contain any database migrations. It does not cause any harm to the process.
