### ISSUE TITLE
Bug! Cannot delete point triggers

### ISSUE THREAD

**Issue by tmorrison01** [mautic/mautic#419]
Hi, I cannot delete point triggers. When i delete them i get a message that says No trigger with an id of 1 was found! This also affects the lead list filters and leads are not automatically added to the list.

**Comment by alanhartless** [comment]
I can duplicate the Point Trigger bug and we will get that fixed.

But I can't replicate not being able to delete lead list filters within a list or lead lists themselves. Are you getting errors when you try to delete one?

For the leads not automatically getting added, is that related to #417?

Thanks!
Alan

**Comment by tmorrison01** [comment]
There was no issue with deleting lead list filters instead it appears that once the issue with the point triggers occurred i suddenly began to experience problems with the email campaigns not sending out the emails. I am not sure if this is related but i am also having an issue with the cron. The minute setting is auto changing on its own over nite from the original setting that i am entering. I have set it for 3 minutes (*/3) for testing purposes. When i check the cron the next day it varies but changes to */15 to */21. Not sure why. Can you resolve this.

**Comment by alanhartless** [comment]
I'm afraid that we have no control over the cron job settings. If that's happening, then it is something taking place server side.  You'll have to check with your host on that one.

If the issue is that emails for leads newly added to a campaign are not getting sent, then I would be inclined to say it's related to the cron job not executing.  If no email is getting sent, i would check the configuration settings and make sure the mailer is working by using the Test Connection and/or Test Send Email buttons.  Either way, if you can confirm it's definitely an issue, create a new issue for it with as much details as you can give so we can try and track it as it's own bug.

Thanks!
Alan

**Comment by tmorrison01** [comment]
Great. How are the updates made available and where can i access them.

**Comment by tmorrison01** [comment]
Update for cron issue. The issue i had with the cron automatically changing intervals was due to the hosting company Hostgator. Shared accounts and reseller accounts have a minimum cron setting of 15 minutes. Thanks.
