### ISSUE TITLE
Enhancement - Webinar number in form results

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#4194]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | ✔️ 

## Description:
When you have GoToWebinar configured on a form and you add "send result to contact" form action, the value of the Selected webinar is the number. I think it would be more user friendly to have the name of the webinar instead.

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
