### ISSUE TITLE
Outlook plugin FR: Tracking by default enabled

### ISSUE THREAD

**Issue by arthurscholten** [mautic/mautic#4201]
Feature Request:
Sometimes I forget to enable the mautic tracking when sending an email. It would be great if I could set an option in the mautic outlook plugin to have mautic outlook tracking enabled by default.

**Comment by vinner0** [comment]
When will this be enabled? Any chance of getting it any time soon?

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
