### ISSUE TITLE
Outlook Plugin FR: Tracking for replied items

### ISSUE THREAD

**Issue by arthurscholten** [mautic/mautic#4202]
Feature request:
When replying or forwarding an email in Outlook the Mautic tracking button is missing, meaning I can't track emails that are replied or forwarded.

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
