### ISSUE TITLE
Wrong timezone set for countries experiencing DST

### ISSUE THREAD

**Issue by SamWebmecanik** [mautic/mautic#4221]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
When a contact visits a page and his timezone is found by Fingerprint2, the wrong timezone is set if  this contact is experiencing DST. 
The bug is at this line : 480 & 482 Mautic\PageBundle\Model\PageModel in 2.8.2

## If a bug:

| Q   | A
| --- | ---
| Mautic version | ~2.7 & 2.8.2
| PHP version | 5.6.25

### Steps to reproduce:
1. Contact visit a page with timezone DST, in France for exemple
2. See for this contact a timezone at Europe/Helsinki and not Europe/Paris

**Comment by MaxWebmecanik** [comment]
Hey, to clarify a bit, Fingerprint2 uses your offset from UTC to determine your timezone, and since not only do not all countries experience timezones, some don't experience it at the same time, so there's no simple way to tell what the contact's actual timezone is.

Therefore, I think the best thing to do is to remove the following block
https://github.com/mautic/mautic/blob/fe4cabceacd6e2586b5d813e53f327821e79f422/app/bundles/PageBundle/Model/PageModel.php#L477-L482

**Comment by RCheesley** [comment]
Closing as fingerprint has been deprecated in Mautic 3.x.

**Comment by pjeby** [comment]
What does timezone detection have to do with fingerprinting?  AFAIK, the usecase for timezone detection is to send campaigns at appropriate times.

**Comment by RCheesley** [comment]
Re-opening due to a misunderstanding on my part.
