### ISSUE TITLE
FR | Mautic | UI | Create New Segment From Form Create Page 

### ISSUE THREAD

**Issue by vexersa** [mautic/mautic#4225]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | X
| Enhancement? | 

## Description:
It would be great if it were possible to create a new segment from the 'Edit Form > Actions > Add a submit action > Modify contact's segments'' menu location.

Use case: New Mautic instance installed. I'd like to create a Form. I create Form only discover that I am unable to add new contact created by this form to a new segment I still need to create. 
Please see below screenshot:
https://www.screencast.com/t/JBCe0UY6kj4
I understand that this does not add any functionality, but I feel like it would make the user journey much more efficient. Speaking from my own experience, I usually create forms before segments and run into this issue often.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
