### ISSUE TITLE
Page Builder: New feature to add background image to a section

### ISSUE THREAD

**Issue by itp69** [mautic/mautic#4229]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | X
| Enhancement? | 

In the landing pages page builder, the ability to add an image as the background property of a section would offer new styling opportunities. Additionally setting background size and position would be good, though these could be set to a default (probably cover and center).

Within the current system, I've achieved a similar effect by placing a full width image slot in a template with absolutely positioned elements over the image (thumbnail preview below). However, I'm uncomfortable with making these themes freely available as this solution comes with at least two disadvantages.

1. Absolutely positioned elements may extend outside of the image bounds at smaller screen sizes
1. It's not possible to position a new dragged element by the absolutely positioned elements - element gets placed at start or end of section (possible I've done something wrong with my templates)

![thumbnail](https://user-images.githubusercontent.com/24919162/27039593-a0e79318-4f8e-11e7-9170-e7de51e0ca66.png)

Thanks

**Comment by escopecz** [comment]
Would this video help? https://www.youtube.com/watch?v=g18Q81xBAyo

**Comment by npracht** [comment]
hey @escopecz i have to admit that it works, but this i not a feature. You almost need to be developer..
Keep in mind that mautic users are marketers and they first don't know how and second don't have time to inspect element, get a class, etc.

What would be expected here is when you click on a section you can add a background image extra of color and that from the interface with a native feature.

**Comment by escopecz** [comment]
Gotcha

**Comment by itp69** [comment]
Thanks @escopecz, the video achieves the result but my worry is the same as mentioned by @npracht. In my hack I used an image slot so that a user can click on it and change the image, but as mentioned it isn't an ideal solution because of at least two issues.

**Comment by luizeof** [comment]
@virlatinus @kuzmany @mqueme do you know how to add this feature? Thanks!

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
