### ISSUE TITLE
User password security policy settings

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#4238]
| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | x
| Enhancement? | 

## Description:
It would be great to have the ability to add a security policy concerning the user password management.
* Minimum length of caracters
* Maximum value in time (recycle every X months)

**Comment by evrentekingr** [comment]
Further security policy settings should be available. Some most used examples are below:
- must contain at least one number
- must contain at least one upper case character
- must contain at least one lower case character
- must contain at least one special character
- must not contain your username
- must not repeat any of your previous x passwords
- must not contain any dictionary words

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
