### ISSUE TITLE
Feature request: Remove all contacts form campaign that is not published 

### ISSUE THREAD

**Issue by merlin0** [mautic/mautic#4243]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? |  X
| Enhancement? | 

## Description:
Currently it's not possible to remove leads from a campaign when it's not published. This can be a issue because sometimes during an update something goes wrong or you need to edit a campaign and it's not possible to remove the contacts. In this it would be really nice to have a button, or option that would allow you to remove all the contacts at once from a campaign.

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
