### ISSUE TITLE
Twitter app - clarify meaning of "client id"

### ISSUE THREAD

**Issue by gingerling** [mautic/mautic#4250]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | y

## Description:
In the twitter  plugin set up it asks for a "client id" - by which is means what twitter calls the "Consumer Key (API Key)" 

Please add a tooltip or change the name so it is clear what is being asked for to a non technical user.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by RCheesley** [comment]
This is still the case in 2.15.3, have added the enhancement label as it would be helpful to have a tooltip or some guidance. Should be an easy first issue!

**Comment by RCheesley** [comment]
It looks like we are using a [generic string](https://github.com/mautic/mautic/blob/staging/app/bundles/PluginBundle/Translations/en_US/messages.ini#L31) rather than a twitter specific string so if we make updates to the label it would need to apply to all - see all uses in [this search](https://github.com/mautic/mautic/search?q=mautic.integration.keyfield.clientid&unscoped_q=mautic.integration.keyfield.clientid).

I don't think that this is going to be feasible to do right now without a fair bit of reworking, and as we will likely be doing some work in the future to improve the social integrations I am going to close this issue down.  We will make sure to add this as a request to make it clearer what the fields mean.
