### ISSUE TITLE
Escaped data in database & preventing XSS vulnerabilities

### ISSUE THREAD

**Issue by MaxWebmecanik** [mautic/mautic#4256]
| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | ✓

## Description:

Today, all the data submitted into Mautic, be it by an internal form (like lead creation) or an external form is escaped, then stored to the database.

This means that data has to be given raw when displaying in the browser or explicitly decoded when exporting plain text.

This also means that if any unescaped data makes it to the database and it ends up being displayed on a page that expects pre-escaped data, it might result in XSS vulnerabilities. i.e. **it is made easy to introduce XSS vulnerabilities**.

It would be a lot easier simply storing the raw data and systematically escaping output. This is really easy in twig templates as it is the default. As for PHP templates [escaping is supported out of the box by Symfony](http://symfony.com/doc/current/templating/PHP.html#output-escaping).

The rule then becomes banning naked `echo`s and sticking to Symfony's `echo $view->escape($var)`.

From what it looks to me, the characters that are stored in their escaped form in the database are [the ones escaped here](https://github.com/mautic/mautic/blob/91195321c7d1ced9c31c5e22f6d7c3b171c8a540/app/bundles/CoreBundle/Helper/InputHelper.php#L180) with the following filter:

<table>
<tr>
        <td><strong><code>FILTER_SANITIZE_SPECIAL_CHARS</code></strong></td>
        <td>
         HTML-escape <em>'"&lt;&gt;&amp;</em> and characters with
         ASCII value less than 32, optionally strip or encode other special
         characters.
        </td>
       </tr>
</table>

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._

**Comment by npracht** [comment]
@dbhurley that should not be considered as a feature. There is no user that expects that. Isn't more about data structure and security. The way it is done today is not standard and generated XSS vulnerabilities (we already corrected several of them), it should better be considered as a bug?!

Thanks,
