### ISSUE TITLE
One-off Queueable Broadcast Email Type For Newsletters

### ISSUE THREAD

**Issue by robwent** [mautic/mautic#4257]
| Q  | A
| ---| ---
| Bug report? | 
| Feature request? |  X
| Enhancement? | X

## Description:
Currently, when using Mautic to send out timed newsletters the only option is to create a segment email to target the users on the mailing list and setup a broadcast cron to automatically process the mail to be sent at the right time.

If the mail creator doesn't set an unpublish time on the mail, any new users that get added to the same segment get automatically queued up to receive all previous emails.

It's easy for some mails to slip through the cracks and not get a publish down date, which can lead to someone new signing up for a newsletter to instantly get a bunch of outdated emails.

Not such a problem if you are the only administrator, but if you have multiple users with differing levels of skill it seems to happen regularly ;)

My initial thoughts were that there should be a third email type (eg 'newsletter' or 'one time segment broadcast' or similar). Where it can be assigned to a segment, but once it has been queued to send, no more users get added to receive it. It may also cut down the work the crons need to do when queueing up new users when there are many mails in the system?

Another option would be to globally set a default publish down date in the main configuration such as 1 day after the mail is set to send. That way only mails that were truly intended to be permanently published would need to be set to never expire (or the other way around if global was set to never expire).

I think this will catch many users by surprise when they are used to using things like mailchimp which just assigns a mail to the users on a list at that point in time.

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
