### ISSUE TITLE
Feature - Be able to assign reports, emails, segments, etc to other users

### ISSUE THREAD

**Issue by fonderco** [mautic/mautic#4259]
As an admin I often help users by creating reports, segments, emails, etc for them.  But this is cumbersome as I have to login as their user before I can do that.  It would be great if I could create an item and then "share" or "assign" it to a different user or users.

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
