### ISSUE TITLE
Specify form redirect in the campaign action, page and so on

### ISSUE THREAD

**Issue by ronnieduke** [mautic/mautic#4268]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | Y
| Enhancement? | Y

## Description:
When using the same form embedded in multiple areas of a site, it would be helpful to be able to specify the URL of the form fill in the Campaign builder. For example, if a form is used on **domain.com/landing-page-1** and also embedded on **domain.com/landing-page-2**, in the campaign flow, if they filled out the form on landing-page-1, send them one way (i.e. add to SFDC campaign) and if they filled out the form on landing-page-2, send them a different way.

![image](https://user-images.githubusercontent.com/742579/27361094-db10e5f2-55d9-11e7-9fad-1a59eb437b17.png)
_Currently, cannot specify URL the form was filled out on_

This is common for things like Free Trial or Quote request forms that are used on various landing pages on the website and CPC-tailored landing pages.

**Comment by ronnieduke** [comment]
@escopecz - to clarify, I'm looking to trigger an action based on the URL the form was filled out on, not specify the redirect URL.

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
