### ISSUE TITLE
All Contacts - System Default Segment

### ISSUE THREAD

**Issue by ronnieduke** [mautic/mautic#4275]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | Y
| Enhancement? | Y

## Description:
It would be great to have a default system list called "All Contacts" that we can use as a starting point for campaigns. I realize you can create a segment called "All Contacts" and have a filter like "email address LIKE @" or something, but it seems silly to have to do that for every new Mautic instance we set up.

**Comment by ronnieduke** [comment]
I think that's exactly why something like this is needed in order to
establish continuity and best practices across Mautic instances. There
should be no reason why the logic for my "All Contacts" should be any
different than your "All Contacts" (your date added is a good idea btw).

As Mautic grows, agencies like ourselves will likely be involved in
multiple instances of Mautic so it would be helpful to have some base
consistency for things like this.

**Comment by PeterTL** [comment]
Although I like standard / best practice approaches, I agree with @escopecz: everyone defines "all" differently. For me - and this has to do with the german market - I define "all" with "all contacts who have double opt-in completed". There is (almost) no way in Germany to contact persons without double opt-in (even system communication can be critical if a court **might** interpret a marketing message) so a list with all contacts can be dangerous if misused accidentally.

**Comment by ronnieduke** [comment]
@PeterTL - your concern for legal in Germany is certainly valid. My intention was not to use "All Contacts" list for email sending, but rather as a base for either creating marketable segments, and also for list maintenance. Our agency does a lot of data cleaning so we often use an "All Leads" list as a starting point to make bulk data changes. 

Again, I realize this is is accomplishable using @escopecz method above, but seems silly to have to do that as a step for every client.

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
