### ISSUE TITLE
History of change of values in fields

### ISSUE THREAD

**Issue by FerRubioMorales** [mautic/mautic#4277]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | X
| Enhancement? | 

## Description:
It would be nice to have a history of changing a property's values. This information is valuable in order to be able to store data and to be able to take actions on that history of values. An example would be to have a "History" option that will display and show you what values you have had on different dates.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. Go to contact details
2. Click on history
3. show values by date that property has had
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
