### ISSUE TITLE
Enhancement - hide focus item on the current page after conversion

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#4282]
| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | x

## Description:
It would be great that when a visitor submits a for or click on the button on Focus Item, it automatically on the current page, hide the focus item.

**Comment by wittwerch** [comment]
I think that could be done with #4253 ?

**Comment by npracht** [comment]
It could be considered at the same time but it is a different need :)

--
*Norman Pracht*
Chief Marketing Officer
Webmecanik
+33 6 49 46 70 68
Discover how Renault Sport
<http://www.webmecanik.com/fr/automation/resources/whitebooks/success-story-…>
has
increased it's email open rate by 75% thanks to Marketing Automation!
Webmecanik Demo
<https://www.youtube.com/watch?v=PbeyJBDeXR8&feature=youtu.be> - How to
deploy Webmecanik Automation in a few clicks
<https://www.youtube.com/watch?v=e22q644HzPI>

2017-06-22 16:08 GMT+02:00 Christian Wittwer <notifications@github.com>:

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
