### ISSUE TITLE
Being able to drag and drop filters inside segment to change their location

### ISSUE THREAD

**Issue by mellsaid** [mautic/mautic#4286]
| Enhancement? | 

## Description:
At the moment, the segment filters must be added in the right order to be able to build the segment properly. If a small mistake, or a change in the future happened, the whole filteration has to be rebuilt from scratch. 

We had a segment that was built, and a new tag was introduced to hold users from filtering through to that segment. 
We can't drag and drop that filter and change it the condition to AND at the moment. 
Also it isn't a solution to do that as a condition at a campaign level, as a lead can only join a campaign once which means that when the tag removed, the lead will not run through the campaign set for that stage. 
SO the solution at the moment, is the the user has to rebuild the filteration from scratch to include the tag. 

It would be quite handy to be able to drag and drop filters in segments in the location required and change the conditions to form the correct filteration criteria. 

![image](https://user-images.githubusercontent.com/22168697/27472445-42d43d0e-57f3-11e7-9b02-b0dc79c7233f.png)

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
