### ISSUE TITLE
Enhancement - improved email screen sort options

### ISSUE THREAD

**Issue by programmatix** [mautic/mautic#4289]
I use the email screen a bunch to find which emails I need to improve.  It would help a lot if I could sort the emails by their open rate and click-through rates (if https://github.com/mautic/mautic/issues/4288 is accepted).

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
