### ISSUE TITLE
Enhancement - emails send in a campaign, could show better stats

### ISSUE THREAD

**Issue by programmatix** [mautic/mautic#4290]
When I click through to the detail screen for an email, one that's been sent in a campaign, I see:

a) A line chart with 6 different lines showing opens, reads, loads of things.  I find this impossible to parse and it doesn't provide any useful info to me, to be honest

b) A bar chart of opens split by device.  Kinda useful, I guess.

c) A table of all the links in the email, with their counts.  This is handy.

But here's what I'd **really** like to see:

a) Number of sends & opens & clicks etcs..  Just plain numbers, not in a graph

b) Open rate, click-through rate (across all links).  And rates of unsubscribes etc. too

c) That links click table is useful but I'd also like to see the % CTR on each one (e.g. number of clicks on that link divided by number of times email was sent)

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
