### ISSUE TITLE
Add ability to preview email from the emails table

### ISSUE THREAD

**Issue by programmatix** [mautic/mautic#4291]
Cause loads of times I want to either quickly view the email (to remind myself what it contains) or to make a quick edit.  And right now I have to click Channels, Emails, an email, Edit, Builder.  5 clicks and quite a bit of waiting.

It would be nice to have:

a) The option to leap to the Edit Email screen from the campaign editor

b) The same option from the Emails screen (in that Edit, Clone, Delete dropdown)

**Comment by escopecz** [comment]
It actually is in the campaign editor:
![campaign-preview-email](https://user-images.githubusercontent.com/1235442/27479391-0ac2c2b6-5814-11e7-894c-66f4d3d1d583.png)

**Comment by grahampople** [comment]
Oh hey, so it is.  Sorry, please ignore that part of the request then.

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
