### ISSUE TITLE
When exporting anonymous contacts IP is not incuded

### ISSUE THREAD

**Issue by gingerling** [mautic/mautic#4320]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:

When you toggle anonymous contacts the IP address is presented in the name column. When you export this search the IP is not included in the csv file, under name, or under any other category. This makes it harder for people to move their install or share data between installs / merge installs of mautic.
![screenshot from 2017-06-28 14-27-07](https://user-images.githubusercontent.com/2853040/27639441-1c59cf9e-5c0e-11e7-9633-e69deb1e0347.png)
![screenshot from 2017-06-28 14-27-15](https://user-images.githubusercontent.com/2853040/27639440-1c583e18-5c0e-11e7-881e-4b0c7b697d9d.png)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by Woeler** [comment]
I'm quite confident this is because the ip address is not actually a replacement for the name of the contact. It's rather just a substitute value for making browsing the list easier. IP addresses and contacts are two different objects and they are also stored separately. Even if you would manage to export the IP address under the name column, importing it to another install will then create an actual 'name' value with the ip address in it rather than an IP address object with all the details.

If you are trying to export contacts and IP addresses I would highly recommend to migrate your database or do it via the API from one install to another.

I think this is intended, not a bug, but this post would fit under a feature request.

**Comment by gingerling** [comment]
Ok, I see. I sure there is a technical reason why the IP address is not treated the same as name or email etc, but from a users perspective in Mautic they are both equally important. After all, the reason they are displayed this way in the contacts page is that the IP is the primary way of identifying new leads before they give you their email and become a real contact. I generally would expect to be able to export all relevant contact info in a csv for analysis, it's a good indication of untapped conversions etc.

**Comment by escopecz** [comment]
IP is not the identifier. It used to be, but it was changed because multiple contact could access from the same IP at the same time and would be merged into one contact.

So the primary identifier for anonymous contacts is cookie ID.

But what is possible since Mautic 1.0.0 is that a contact can be linked to multiple IP address.

If you want to export contact with IP address, go to reports, select contacts as a data source and IP address as a column. Then you can export that report.

**Comment by gingerling** [comment]
Thats awesome thanks, I will document this :)
