### ISSUE TITLE
Display a configurable message when a contact saves the preference center

### ISSUE THREAD

**Issue by FaustoTu3w** [mautic/mautic#4325]
Hello! 

Where can I configure the thank-you page, after the user has updated his settings in preferences screen when contacts click unsubscribe in an email?

Thanks!

**Comment by escopecz** [comment]
I don't follow what you want. You want to thank contact for unsubscribing?

**Comment by Arjoni** [comment]
I am not the OP but I think he wants to customize the text shown after a user unsubscribes and/or the unsubscribe page.

**Comment by FaustoTu3w** [comment]
Hello, I need to know where can I configure the thank-you page after the contacts select the preferences settings like "Contacts frequency preferences" or "Contacts category preferences" and select "save", currently after this no notice comes out as "thanks your preferences were saved" or something like that.

thanks.

**Comment by FaustoTu3w** [comment]
I would also like to know where I can deactivate "contact by text message" I would like this option not to appear in the setting preferences contact.

**Comment by escopecz** [comment]
The source of my confusion is that I'm not aware there is any unsubscribe thank you page or message. So should this issue be a feature request to add a message?

About the text message question, make sure you have the Twilio plugin disabled if you don't want to use it.

**Comment by FaustoTu3w** [comment]
This issue is a request so that after the person saves his / her contact preferences in unsubcribe page comes a notice of "Preferences saved, thank you" or something like that. Currently they click on "save" but there is no confirmation message. 

About the text message, I'll deactivate the plugin Twilio and try..

Thanks!

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
