### ISSUE TITLE
Central Contact Event Log

### ISSUE THREAD

**Issue by yourdigitalclub** [mautic/mautic#4348]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? |  Y
| Enhancement? | 

## Description:
I've been browsing through my site log and saw some 404s, I managed to find the same missing links as page hits within mautic. After unsuccessfully trying to export all page hits to view all 404s I think it would be wise to have an area within contacts where we can view all contact events like page hits that can be filtered for more detail.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.2
| PHP version | 7.0.2.0

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
