### ISSUE TITLE
How to track bounced/failed email message events?

### ISSUE THREAD

**Issue by aarsla** [mautic/mautic#435]
I have send test email to 2 email addresses, one of which was fake.lead@nonexistent.test.
Obviously, postfix returned

May 19 12:27:03 mautic postfix/smtp[8445]: C6870729E: to=<fake.lead@nonexistent.test>, relay=none, delay=0.49, delays=0.4/0.01/0.09/0, dsn=5.4.4, status=bounced (Host or domain name not found. Name service error for name=nonexistent.test type=AAAA: Host not found)

However, this was not reflected in Mautic GUI - Graph never shows "Failed" column which is always at zero.

What do I need to do in order to catch failed/bounced messages in mautic?
Thank You

**Comment by alanhartless** [comment]
With SMTP, once we pass off the message to the postfix server, we no longer have control over what the server does with the email, or the responses that it gets.  We will be working on a bounce reply path feature so that bounced emails can be monitored.  

For now, the only built in bounce management is through Mandrill's webhooks.  

Here's a blurb from the 1.1.0 announcement on it:
```
If you're a Mandrill user, this will cause you to do a little jig. Our Mandrill integration now uses their API to send emails. Ports are no longer an issue; emails are sent faster and tokenized; and bounce callbacks are now supported. To leverage bounce callbacks, create a Mandrill webhook that points to http://your-mautic.com/mailer/mandrill/callback . Configure it to post to the events bounces, soft bounces, and failures. Finally create two custom metadata fields of hashId and leadId. Woohoo! If you're not a Mandrill user, we'll be adding similar support for other supported email services in future versions.
```
