### ISSUE TITLE
Error after entering the database details

### ISSUE THREAD

**Issue by trinath503** [mautic/mautic#4350]
Getting error
The site is currently offline due to encountering an error. If the problem persists, please contact the system administrator.

This error is showing after entering the database details,i am using on windows local machine using of xamp

please fix it

**Comment by mqueme** [comment]
It would help if you posted the error message in your logs.

**Comment by Woeler** [comment]
This is a community project. Sentences like "please fix it" are really not going to help your case here. Also it would help if you would use the template we have for reporting bugs/errors/requests instead of writing a short text that contains almost no relevant information to the issue.

- What database type?
- What PHP version?
- Which server are you using?
- What do your error logs say?
- What does your database look like at the moment?

**Comment by trinath503** [comment]
I fixed it, thank you all helping, the solution is we need to give permission to the files
sudo chmod -R 777 /var/www/html
