### ISSUE TITLE
Focus show on specific contacts by given filters

### ISSUE THREAD

**Issue by dgram** [mautic/mautic#4352]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | N
| Feature request? | Y
| Enhancement? | N

## Description:
Hi, i want to ask if its planned to make the focus feature more flexible.
The following feature i've thinked about.

Instead of directly inject the focus on the page via html/js, it will be really nice to define for example an campaign and show the focus pages only for users with given filters.

For example, if you have users with tags for specific products (mats, drinking bottles etc.) show them the specific focus page.

I hope i described it clearly enough.

regards

**Comment by ronnieduke** [comment]
+1 on this...would be create to customize based on different segments

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
