### ISSUE TITLE
Feature Request : Dashboard default timerange

### ISSUE THREAD

**Issue by YannickBiet** [mautic/mautic#4354]
| Q  | A
| ---| ---
| Bug report? | No
| Feature request? | Yes
| Enhancement? | Yes

## Description:
On home page, user can define time range to display the graph
for example last month : from 1st june to today july 5th

But tomorrow the timerange will always be june 1st - july 5th so the graph will not be updated anymore with the most recent values.

Note that mautic does not allow to enter a date in the future so we can't fix for example that we want to see from January 1st to December 31 right now. you would have to update the timerange everyday! :(

Mautic remembers the timerange entered on the dashboard even after having disconneted the session
Thus a not so well trained user will forget about this filter and think that mautic buged and can't refresh the graphs.

There's should be default buttons like : this week, last week, current month, last month, 30 last days and then the timerange inputs.

Thus a user can select easily if he wants to have a "dynamic" dashboard with everyday results.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8
| PHP version | 7.0.6

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
