### ISSUE TITLE
Make text field column size configurable 

### ISSUE THREAD

**Issue by MaxWebmecanik** [mautic/mautic#4372]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | ✓

## Description:

Today, all text contact fields are stored in the database as `VARCHAR(255)`. This makes it really easy to reach the maximum row size.

I ran some tests on my machine running MariaDB `10.2.6` where I would add columns of the same size to a table until it broke.

Here are the results:

| `VARCHAR` size | Number of columns |
| --- | --- |
| 255 | 85 |
| 127 | 171 (almost a two-fold increase!) |
| 63 | 196 |
| 31 | 196 |
| 15 | 196 |
| 7 | 367 (a pretty good increase as well) |

Maybe we could introduce a few contact field _types_
- We keep the normal text type and maybe relabel it
- a 127 char type
- a 7 char type that could be used for short codes

**Comment by escopecz** [comment]
That's interesting. Thanks for the table!

**Comment by MaxWebmecanik** [comment]
@escopecz My pleasure 🙂 
Here's the script I used for my tests: https://github.com/MaxWebmecanik/varchar-madness/blob/master/mad.php

**Comment by Loanatik** [comment]
This has been an issue for me too.  Just tons of unnecessarily wasted space in my tables.

**Comment by FerRubioMorales** [comment]
Maybe this  PR should fix this? : #4465

**Comment by Loanatik** [comment]
What's the thought behind making the field fixed at 255/127/7 rather than setting the default width and allowing the user to configure exact size?

**Comment by MaxWebmecanik** [comment]
@Loanatik If you look at the table in the description, you'll see that in my tests, there were no advantages to having a 15 character field over a 63 character field (note how these are all powers of two subtracted by one).
This is due to the way MySQL works internally.
In my opinion, it would be better to provide the user with a few useful options rather than the ability to control precisely the number of characters as they might get confused to see no advantage in a 15 character field over a 63 character field.

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._

**Comment by YosuCadilla** [comment]
Might this be helpful?
https://www.safaribooksonline.com/blog/2012/11/06/avoiding-too-many-keys-in-mysql/
