### ISSUE TITLE
Prevent user to delete segment used in campaign

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#4392]
| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | 
| Enhancement? | x

## Description:
It would be awesome to prevent the user to delete segments that are used in a campaign as campaign source or in a campaign action. Then it would avoid campaign issues/error (and probably side effect).
Could also be concerned for point actions/triggers and forms action.

We could imagine to have an alert when you try to delete a segment used saying
> This segment is currently used in xxx & yyy, please modify them before remove this segment

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9.0
| PHP version |

**Comment by Loanatik** [comment]
Instead of please modify, maybe it could offer to remove the campaign or assign it to another segment?

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
