### ISSUE TITLE
Error: The site is currently offline due to encountering an error. 

### ISSUE THREAD

**Issue by sagarnangare** [mautic/mautic#4404]
What type of report is this:

It is a | Bug report? | 
 

## Description:
The more details the better...

## If a bug:

| Q   | A
| --- | ---
| Mautic version | Latest
| PHP version | 7.0

### Steps to reproduce:
1. Installation on Ubuntu 16.04

 
### Log errors: 
Logs not generated.

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
There must be an error recorded somewhere. Read https://mautic.org/docs/en/tips/troubleshooting.html and try to find it again.

By Latest Mautic, do you mean latest stable version 2.8.2 or latest beta version 2.9.0-beta?

Since this issue doesn't contain any information we could use to try to replicate it, I'll close it for now. But when you comment with an error message, I'll reopen it.
