### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by VR51** [mautic/mautic#4439]
I like Mautic (self hosted) and believe it will one day compete with hosted services like Mailchimp but there are a couple of items where I think Mautic needs improvement. Forgive me if I've missed a feature that already exists.

Now keep in mind I usually work with WordPress.

1) I don't quite understand the need to set cron jobs during the set up process, at least not the reason for creating so many of them. I think installation would be easier for many users if Mautic had its own internal cron management that can be activated either when a page of the Mautic site is visited (e.g. an email or landing page) or that can be activated with a regular ping from an external service (which could be a single cron job set on the web server or a ping from a mobile/desktop app etc...).

2) Upgrades. Would be useful if there were an easy way to reinstall Mautic from the admin area. This would help those with broken systems caused by a stalled or broken upgrade, or just be helpful when an admin feels the software files have been compromised. As well as a backend admin 'Reinstall' button, there could be a randomly generated URL to ping to force re-installation of Mautic.

3) I read that there was work being conducted on an RSS-to-email plugin. I'm not sure how well developed that plugin is but I'm wondering whether it might be easier to write such plugins if Mautic had it's own inbuilt XML feed reader which could then be hooked into by a plugin to convert RSS content into email content. I imagine that once the feed reader is in place in core that all a plugin would need to do is add mail-merge tags for use in email templates.

4) Themes for the overall site appearance, email and landing pages. Would be handy if new themes could be installed from the admin area and if customizations to themes could be saved as new themes.

As a quick note, while editing a theme during email creation I was unable to delete background images without deleting whole sections that contained those background images. The editor button failed to show when those sections were selected and when the editor options did show for a selected section the background image was not alterable. Maybe this was because the images were coded outside of the editor's scope.

5) Quick Start Button. I had to create a list of contacts, then a segment then an email channel so that I could send an email to subscribers. I read instructions but I don't always read them deeply. The dashboard is great in that it shows statistics and I think it would be incredibly useful to include a set of Quick Start buttons at the top of the dashboard screen that help users get started with email creation e.g. segment -> email, and segment -> campaign, and list -> segment -> campaign -> email creation. Or maybe just a single button that prompts and advises as it takes the users through the email creation process, e.g. Import List? Y/N, Y -> List import, N -> Prompt to choose an available list; Create Segment? Y/N, Y -> Create segment, N -> Prompt to select an available segment; Create Campaign? Y/N, Y -> Create campaign, N -> Jump to channels; Create Channel? Y/N, Y -> Create channel, N -> Offer an existing channel.

I am new to Mautic. I found the program out of blind luck because I needed to reconfirm an email list ready for import into Mailchimp. Having played with Mautic I see much potential for the software and will write about it in my blog to help increase awareness.

Thanks for releasing Mautic on Github.

**Comment by Woeler** [comment]
The latter points are not really in my fields of expertise

1.  but you really do not want your cronjobs to be called by an external source or by a page visit. This is extremely inefficient as each hit would trigger the cron to run, which is a waste of resources on your machine. Cron has been and is an excellent tool for many, many years and I do not see any reason why Mautic should work around this, when it's just as simple as setting up a cron. Cron is also available on even the cheapest of shared hosts.

Furthermore, scripts that work with data, process data or do background jobs should not have an external trigger when it is not needed. It adds extra risk factors and is prone to misuse. It's simply bad practice.

But even if you would need this, you could technically write a script that executes the cronjobs, which you then call from an external application. Though **I do not recommend this at all** unless there is some kind of special situation where this would be absolutely needed.

2. This problem is easily solved by making backups. The system even advises to make a backup before doing any kind of update. If people choose not to do so, that is their responsibility. Something I expect every developer and/or hoster to do is make regular backups, especially when upgrading.

**Comment by VR51** [comment]
Thanks for your reply but they do not answer the needs behind my suggestions.

## Cron jobs

Internally managed cron jobs work well for many other systems, e.g. WordPress and (Drupal)[https://www.drupal.org/docs/7/setting-up-cron/overview].

I think you misunderstood my suggestions.

A randomly generated URL that only the site admin is aware of would be difficult for some other person/bot to find so security risks and the accidental trigger risks are minimal.

Moreover, the more important need for this that you missed is that I suggested multiple server set cron jobs could be condensed into a single server set cron job which activates a Mautic internally managed cron process.

There could be a method to en/disable the preferred cron management system i.e. server cron jobs, URL ping, or Mautic admin dashboard managed.

Configuring cron jobs is simple enough for me or other experienced developers but not everyone is a technologically proficient. A method of managing cron jobs from the Mautic admin area would improve the user experience for regular (non developer) people.

## Cron jobs and failed upgrades

There are several scripts that provide a push button way to run tasks. One is available (here)[https://www.mautic.org/community/index.php/5092-mautic-2-0-up-cronjob-update-2-5-x/p2#p18695] and another is (here)[https://gist.github.com/ChgoChad/fe9950c628ad8169cd27a58ee64106e8].

When I dig into the Mautic plugin system I will see whether I can find time to convert those scripts into a plugin.

## Backups

Backups are great at saving us from disaster but they don't help us to fix the causes of failed upgrades. Backups help us restore pre-upgrade versions pending bug fix releases.

What I read is that Mautic upgrades fail regularly at the database stage. End users, specially non technical people, really shouldn't need to worry about backup restoration when a force reinstallation option could be made available.

**Comment by escopecz** [comment]
1. There are 2 technical issues with your suggestion:
    1.1 Running all background jobs via 1 endpoint - There are many cron jobs right now for different features. It's waste of resources to run them all if the user doesn't use 50% of them. And very often one job doesn't have to run as frequently as the other.
    1.2 Executing cron jobs via a HTTP request inherits the time limit for HTTP requests. 30 seconds by default. Executing a CLI command has the limits much higher. That's the big one. Take it from the creator of Cronfig.io.

2. It's a bit hard to display the dashboard when an upgrade fails and there is some error. But I agree we have to make it more easy to fix a broken instance. It will probably have to be a 3rd party script though so it won't depend on Mautic's code. If there is an issue with cache, nothing will work.

3. You can [search for RSS in the issues](https://github.com/mautic/mautic/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20rss) to read about the latest development in that area.

4. New themes [can be installed](https://mautic.org/docs/en/themes/manage_themes.html) from the administration. Saving an email as a new theme is something we talked about and we thing it's a good idea.

Thanks for your suggestions! Next time try to search the issues here at GitHub to see if someone started the discussion for the topic already. And if you'd like to create a feature request, break it down to one topic per request which makes it easier to keep the discussion focused and the developers can handle the development in small time period.

I will close this PR since it continues many feature requests. Some of them already exist in the other issues.

**Comment by VR51** [comment]
Thank you, @escopecz.
