### ISSUE TITLE
Set reminders linked to contacts and companies, display them in calendar.

### ISSUE THREAD

**Issue by yyil** [mautic/mautic#4451]
| Q  | A
| ---| ---
| Bug report? | N
| Feature request? | Y
| Enhancement? | N

The calendar is underutilised. It would be very useful to be able to set reminders linked to contacts and companies. These would appear in the calendar and also send emails to user on date/time.

This would be a very useful CRM feature, without much overhead complexity (I would imagine).

**Comment by escopecz** [comment]
Something like this?:
![notes](https://user-images.githubusercontent.com/1235442/28306712-a64c357e-6ba0-11e7-9407-0414bf1839a5.png)

**Comment by yyil** [comment]
Yes @escopecz 
However this does not place an item into the calendar, or set a reminder.

I think it would be better to keep reminders and notes apart (separation of concern).
 
An **+ Add reminder** button could be provided:

* Main contact details page (i.e. Edit, Send email, Add reminder, Close)
* On the calendar page (need to include a contact picker)

Reminders Needs a note field and a date/time picker.

Reminder items will display on the calendar -- which can be clicked to view details in a modal. Could provide edit/delete buttons within the modal.

Reminders are sent via email to contact owner.

Could reminder email delivery be bundled into the Email Queue cron job?

**Comment by yyil** [comment]
There was this plugin under development a while back.. Aimed at doing similar thing..
https://www.mautic.org/community/index.php/1167-task-plugin-feedback/p1
https://github.com/redmantech/Mautic_CRM

Seems abandoned.

**Comment by yyil** [comment]
Bump.

**Comment by viraljadhav** [comment]
Yes. This is happening only for 2nd to 4th week of Febraury. If we update for March, it works. But dont work for February. It seems love in the air in this month force mautic to forget. Jokes apart, but yes, client is furious and I cant explain that this will not work for 3 weeks of February and will work for all months...

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
