### ISSUE TITLE
Quick segments for campaigns

### ISSUE THREAD

**Issue by ronnieduke** [mautic/mautic#4461]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | Y
| Enhancement? | 

## Description:
Sometimes campaigns are used for database maintenance, or quick one-time operations where it is a bit tedious to create a segment, then create a campaign off of that segment, then go back in and delete that segment because it's no longer needed. 

It would be very helpful to be able to create a "quick segment" for a campaign that uses the same filtering logic for segments but can be built at the same time as building the campaign.

Here is a potential mockup:
![image](https://user-images.githubusercontent.com/742579/28331742-063210f2-6ba7-11e7-8801-48e23dde9479.png)
![image](https://user-images.githubusercontent.com/742579/28332033-2112e2a6-6ba8-11e7-9d37-5b5b7adc0ed4.png)

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
