### ISSUE TITLE
TimeStamp needs to look to more signifcant digits to correctly sort Events on the Contact View

### ISSUE THREAD

**Issue by cougar2009** [mautic/mautic#4468]
Shouldnt these be in reverse order???   first the email is read and THEN the reading of that email schedule the campaign event.  they have the same time stamp of course, but maybe they need to go out to seconds or milliseconds for correct sort order???

![image](https://user-images.githubusercontent.com/19396480/28384286-5f8e2dc2-6c81-11e7-8968-a02c37fd7004.png)

**Comment by escopecz** [comment]
That's question of MySql version. [MySql 5.7+ does that](https://dev.mysql.com/doc/refman/5.7/en/fractional-seconds.html). Older versions doesn't have support for miliseconds.

I'll close this issue since I don't think Mautic itself can do something about that. But MySql upgrade should fix it for you.

**Comment by cougar2009** [comment]
This is on Mautic hosted.  Are you guys not on 5.7+  ??

**Comment by ttencate** [comment]
@escopecz Minor correction: [MySQL 5.**6**+ is sufficient for having fractional timestamps](https://dev.mysql.com/doc/refman/5.6/en/fractional-seconds.html). In MariaDB they are [supported from 10.1.2 up](https://mariadb.com/kb/en/datetime/#internal-format).
