### ISSUE TITLE
Campaign action trigger time based on campaign start

### ISSUE THREAD

**Issue by dgram** [mautic/mautic#4489]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | Y
| Enhancement? | 

## Description:
Hi, i have the problem, that i need the time to wait till the action gets triggered based relatively on the campaign start and not based on the lead source.

The only way to make it possible is, to define an condition and give them an hardcodet date and time, but thats pretty hard for us, because we have to test them (on the test we establish short future times, on production far longer durations) and after the test we need to change all conditions over all our campaigns, and we have pretty much campaigns for our action.

regards

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
