### ISSUE TITLE
Tiny bug in Form Management

### ISSUE THREAD

**Issue by alvinbenavides** [mautic/mautic#45]
Hi. Not a critical error and I guess you have to be lazy like me in order to catch it... 

I'm adding actions in form configuration. If I add "Create/update lead" or "Modify leads list" I just need to fill necessary fields, the Name field is automatically generated based on the selected action.

With 'Send email to lead' action, if I choose an email but don't fill the action name, validation fails and gives me an error saying "Select the email to be sent." Error message is confusing since I selected the email, is the name I didn't filled. Maybe it can be auto generated like with the other actions.

This only happens on my own installation, I'm using latest from github. I test it on mautic.com without  this error but I guess is not the same version because there the action is called "Send predefined email to lead" and in my installation is called "Send email to lead".

**Comment by alanhartless** [comment]
Hi,

I believe this is related to the bug fixed with commit https://github.com/mautic/mautic/commit/6b061af121de158c6f81be55c4449455bf5dab34.

Really all you need out of that commit to fix this is to overwrite media/js/app.js with https://github.com/mautic/mautic/blob/6b061af121de158c6f81be55c4449455bf5dab34/media/js/app.js.

It happens when a modal is duplicated, leading to two of the same form.  When you submit, the values of the hidden identical form (with all blank values) are sent to the server  rather than the one you actually filled in leading to failed validation.  That file should fix that.

Thanks!
Alan

**Comment by alvinbenavides** [comment]
It works. Thanks
