### ISSUE TITLE
Add "Between" to the criteria for defining a segment.

### ISSUE THREAD

**Issue by calevans** [mautic/mautic#4505]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | Y
| Enhancement? | Y

## Description:
When creating a segment, you have many options that map to SQL where clause options. One that is missing is "BETWEEN". I am trying to define a geographic segment and it just so happens that all the US zip codes are sequential. If I had "BETWEEN" I could put the starting and ending zip codes and be done with it.

Cheers! :)
=C=

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
