### ISSUE TITLE
Lead removed from campaign when it ends

### ISSUE THREAD

**Issue by rodrake1** [mautic/mautic#4517]
Hi,

I don't know if this is normal, but when a lead reaches the end of my campaign, as it has its segment changed, it is removed from the campaign. I no longer can see the lead on the camapign after this as it has never been there. This is standard procedure? If not, what could be causing this behavior?

**Comment by escopecz** [comment]
Please open new issue and fill in all the requested information. In your case also note if you use some additional 3rd party plugins, if it happens for every contact and every campaign or only some. If so, how does the campaign looks like? Do you use the delete contact action in it somewhere?. I'll close this issue since it's missing Mautic version, PHP version and so on.
