### ISSUE TITLE
Form Templates

### ISSUE THREAD

**Issue by ronnieduke** [mautic/mautic#4541]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | Y
| Enhancement? | Y

## Description:
If a company has many gated resources offered on their site such as eBooks, Whitepapers, etc, That is a lot of forms to maintain in Mautic. So when the time inevitably comes where the company wants to change the fields on all the forms, one has to go back in and manually update every single form.

An idea to alleviate this would be to create "form templates" (verbiage pending) where you could create a standard set of fields (First Name, Last Name, Job Title, Company, Email, etc) in a form template, such as "Resource Form Template". Then when you go to build forms for each of your individual assets, you can select the "Resource Form Template" which would automatically inject those fields into every form that is using it (while also having the ability to append additional fields locally to that form if you needed).

Then down the road, if you decide to drop 'Job Title' from all resources forms to help increase conversion rates, or change "email" to "Business Email", you simply edit the Resources Form Template and it will automatically update all forms using that template.

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
