### ISSUE TITLE
Owner signature not sent ?

### ISSUE THREAD

**Issue by YannickBiet** [mautic/mautic#4553]
| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
I enabled Mailer is owner option in mautixc system config
I assign a contact to user A
I setup a different signature for this user A using "my account"
Once logged under user A, I select the contact and press the send email button

The from name / from email address is ok and display "User A"

Problem is that adding signature tag will always continue to send the default signature configured within mautic and not the specific one for user A

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.2
| PHP version | 7.0.12

**Comment by YannickBiet** [comment]
Ok we have a PR ready for that 

when mailer is owner is OFF --> send mail on contact will use logged in user "from name" and "email" but signature will be the default one (current 2.9.2 behavior)

when mailer is owner is ON --> send mail on contact will use logged in user "from name" and "email" but signature will be the logged in user.

So the owner signature will still not be used but at least it tries to use the current logged in user instead.

Seems the send mail button currently does not use the "mailer is owner" to retrieve the right sender name/ sender email and sender signature.

At least it allows to use the current logged in signature.

@escopecz does it makes sense to push this PR even if it is not really fixing the "owner" part ?

**Comment by isleshocky77** [comment]
I just ran across this while working on #7066 and looking into #6071,#4170.

A lot of these edge case come from the fact the helper is being used in many different use-cases.

* Send an email from a Campaign
  * Send as Owner
  * Send not as Owner
* Send an email from Contact > Send Email
  * Send as logged in User
* Preview an email from Campaign > Preview Campaign

I actually agree with the functionality of if you go to Contact > Send Email, that it sends the email as if the User is sending the email - meaning replacing from_name & from_email with the logged in user. This means that the {signature} should be replaced with the signature of the currently logged in user as well and not rely on whether "Send as Owner" is enabled or not.

This is what the current bug is.  The helper `app/bundles/EmailBundle/Helper/MailHelper.php:357` checks if `$useOwnerAsMailer` is enabled; this doesn't matter if the Email is coming from the sendAction.

I'm confirming that this bug is still present on 2.15.0

**Comment by isleshocky77** [comment]
@YannickBiet I meant to ask you where the PR is for this issue?

**Comment by mihaicirstea** [comment]
This bug is not just when sending email using the logged-in user (ex: user A). 

We are trying to use this feature but even when "Send as Owner" is enabled - the name, email address & signature sent is always the "default" one. 

Therefore when enabling a campaign or form submit action to send an email - it's not using the lead owner info at all as it should.

Can anyone clarify if they are successfully using the "Send as Owner" feature? It looks to me that it has never functioned as it should.

**Comment by autoize** [comment]
Can reproduce @mihaicirstea 's issue on Mautic 2.15.2 running on PHP 7.1.28.
These troubleshooting steps were attempted but the form action (thank you email) was still sent to the contact using the default sender name and email address. 

- Turn "Sender is Owner" option off, and on again, then clear Mautic cache 
- Deleted and re-added the "Send Thank You Email" form action
- Rebuild the form in question from the Mautic dashboard
- Remove the default return-path address in the Configuration > Email Settings

The only way to override the email sender was to hardcode a From: name and address in the Advanced tab of the Email Builder, but this is _not a replacement_ for the "Mailer is Owner" option as we do not want to hardcode a different sender name. Each email should be sent with the Contact Owner's name and custom signature. @isleshocky77 

Thanks in advance for taking a look at this.

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
