### ISSUE TITLE
Render dynamic content on email test

### ISSUE THREAD

**Issue by ronnieduke** [mautic/mautic#4581]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | Y
| Enhancement? | Y

## Description:
When using dynamic fields in an email, such as first name, last name, etc, it would be helpful have the fields actually render when sending an email test, if the email you're sending to is actually a contact in your database. So if I send a test to myself, and my email address exists as a contact in the database, the test would say "Hello Ronnie," instead of "Hello [First Name]".

If there are no contacts in the db that match the email, it would then render "Hello [First Name]" or whatever placeholder for that field. 

The current workaround for this is to create a segment of just the test person you want to send it to, clone the email, and send to that segment. Seems like this could be much simpler by looking up the real contact data when sending a test.

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
