### ISSUE TITLE
Mautic Contacts Search : OR operand

### ISSUE THREAD

**Issue by YannickBiet** [mautic/mautic#4587]
| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
You can search using or filters like 
email:(test1@company.com OR test2@company.com)

But you can't search this way :
email:test1@company.com OR email:test2@company.com

For more complex searches we could want something like
email:%@company.com OR lastname:TEST

Or operand can only applied inside a single command (email: lastname: ...) ?

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.2 and 2.9
| PHP version | 7.0.12

**Comment by Ri100** [comment]
+1

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
