### ISSUE TITLE
Conversion tracking / segment or campaign value in $ / £ ?

### ISSUE THREAD

**Issue by gingerling** [mautic/mautic#4591]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | Y
| Enhancement? | 

## Description:
I attended a webinar by Drip (https://www.drip.co) the other day, it seems pretty similar to mautic. One thing they have which is super sweet though is monetary tracking for conversions. So, say you send a campaign with link to buy a product in an email, the product is $5 and 10 people click the link and buy the product, then the campaign shows a value of $50. I have no idea how they do that, but it sounds AWESOME :) 

Could this sort of thing be a future feature for Mautic?

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by caesarcxiv** [comment]
+1

**Comment by gingerling** [comment]
Yay! My first +1! Thanks buddy 😊

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
