### ISSUE TITLE
Better usage of the user agent data

### ISSUE THREAD

**Issue by YannickBiet** [mautic/mautic#4645]
| Q  | A
| ---| ---
| Bug report? | No
| Feature request? | Yes
| Enhancement? | Yes

## Description:
I don't think this is a real FR maybe more an improvment

Current tracker only save and then display back user agent as a simple string
For marketing users, this long string is complex to decrypt while we browse the timeline (on our last training we had questions about that : why while browsing with Chrome it is saved as Mozilla 5....

For each activity containing a user agent, should be real good to help the user to understand it 

For example you can reading this webpage 
http://www.whoishostingthis.com/tools/user-agent/#reading

to know how to decrypt better the user agent

I know there's no standard  but implementing Chrome FF Safari Edge Opera ones would covers most of the use cases

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
