### ISSUE TITLE
Creating a company bug (at user creation time)

### ISSUE THREAD

**Issue by YannickBiet** [mautic/mautic#4646]
| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
In contacts, click new to create a contact
![image](https://user-images.githubusercontent.com/930391/29208528-ba2a0e7a-7e8a-11e7-80e3-d76cf0c5a353.png)

Fill in FIRSTNAME

Imagine you want to link this contact to "YourCompany"
Open the company field

![image](https://user-images.githubusercontent.com/930391/29208574-db7e8b96-7e8a-11e7-8b8f-b1cade54ce2f.png)

If you already know the company is not working you will press "create new..." button and it will display the following popup to create your company

![image](https://user-images.githubusercontent.com/930391/29208592-f416d744-7e8a-11e7-82fc-9ec0ccc06d45.png)

That's ok

Now imagine you don't already know if the company is existing in Mautic DB, you will search for it then typing its first characters. 

To reproduce the bug you need to enter enough characters to have the same answer screen :
![image](https://user-images.githubusercontent.com/930391/29208734-83f7e9de-7e8b-11e7-8245-42529028d76a.png)

As you don't find it, you will erase the value 
Sometimes the "create new option" will not even appear anymore :

![image](https://user-images.githubusercontent.com/930391/29208773-bee46e1e-7e8b-11e7-8a6f-709bc7846281.png)

And even if it appears, if you press create new, nothing will happen then ! You will not be able to create the company.

Only solution : start over or save the contact without company and re-edit it

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9.2
| PHP version | 7.0.12

**Comment by maxSupermoney** [comment]
FYI this seems to be a bug with the implementation of Ajax Chosen. When certain keys are pressed (backspace, less than 2 chars), the html select box does not have its options updated to match what's showing visually. So when the visual options is selected, there's no corresponding value to perform the action with. The visual list looks to update independently and is probably using cached data to update.

You can probably bypass this by entering more than 2 characters hitting the delete key which will force an update, or entering some other input that triggers an actual update.

I couldn't find the code where the core issue resides, but a somewhat suitable patch might be to treat the backspace key normally instead of ignoring it. But that still doesn't resolve issues with the visual list not matching up to the select options. I'll research more and possibly create a patch for the backspace key when I have more time.

**Comment by oytuntez** [comment]
This bug is quite deep. These dropdowns are really difficult to modify. I spent some time in 3a.chosen.jquery.js, it's a mess and requires hardcore debugging.

I'll update here if I come up with something. This is huge customization over a standard component library, not sure if this much custom code was really needed (this tells me the library choice was wrong in the beginning).

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
