### ISSUE TITLE
Attempt to send to a DNC should not cause a Notice

### ISSUE THREAD

**Issue by calevans** [mautic/mautic#4680]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | Y 

## Description:
Personally, I consider this a bug, but I'll understand if other's don't. :) When somone is in a campaign and marks themselves as DNC, the campaign still tries to send to them and puts a notice in my "Notices".  This should not happen. There is no need for me to "Notice" that an email was not sent because someone marked themselves as DNC. This is the system working as designed.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9.2
| PHP version | 7.1

### Steps to reproduce:
1. Create a campaign with at least 2 email sends.
2. Add someone to the campaign
3. After the first email, mark the person as DNC. 
4. Watch the notices pile up.

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
