### ISSUE TITLE
Show the number of contacts on each node of the campaign tree graph

### ISSUE THREAD

**Issue by merlin0** [mautic/mautic#4713]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? |  x
| Enhancement? | 

## Description:
It would be great to see how many contacts will enter a campaign when you publish it. For example if there are 50 people in a segment you get the following pop-up by publishing this campaign 50 contacts will be added to the campaign, are you sure you want to continue?

**Comment by escopecz** [comment]
There is the "Contacts" tab in the campaign detail page which shows the contacts within the campaign and you can see the total number below the pagination.

The popup will get tricky, because it can show completely different number until `mautic:campaigns:update` command will run. So it can be misleading and I'm sure new bug reports about this will follow. Another tricky part is when you publish a campaign for the second time. Should it count also contacts which are in different stages of the campaign? Or only those which are about to trigger the first child events of the campaign source?

I mean this will be quite big code change with confusing result at the end. Is it worth it?

**Comment by merlin0** [comment]
Maybe it's not the ideal solution but now there is no way of knowing what is going to happen when you publish a campaign. Let's say if you send emails right away and you select the wrong segment there is no point of return.  Currently I always double check if the segment I selected is the right one and if it contains contacts. Maybe it would possible to show how many contacts are currently in a segment when you select the segment as campaign entry?

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
