### ISSUE TITLE
dynamic email content filter fields

### ISSUE THREAD

**Issue by tomdavidson** [mautic/mautic#4724]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | x |
| Feature request? | 
| Enhancement? | 

## Description:

Available fields to filter dynamic email content are not consistent. For example, there is not a social category nor is the tag field available. Also, disabled fields such as position and title are available for filters.

## If a bug:

| Q   | A
| --- | ---
| Mautic version |  Mautic Cloud Pro |
| PHP version | 

### Steps to reproduce:
1. self explanatory 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by dsp76** [comment]
I just tried to setup (a) dynamic campaign(s), which should guides a user through a setup process on his own selection of next steps. Unfortunately I can't display dynamic content based on existing tags (e.g. mark certain tasks as "done" in the E-Mail) nor segments. 

I just wanted to add this comment to show you an interesting usecase, that would benefit from it.

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._

**Comment by tomdavidson** [comment]
@dbhurley this is a bug not a feature request

**Comment by dbhurley** [comment]
Thanks! I've reopened. 👍

**Comment by npracht** [comment]
This is an enhancement not a bug. Let's move this to the forum

**Comment by npracht** [comment]
Hello!
The mautic policies requests that all the feature requests and integration requests are discussed on the [mautic slack](https://mautic.slack.com) or on the [mautic forums](https://www.mautic.org/forums/).
Github is better used for issues reporting and code proposition.
Thanks for contributing!

N.
