### ISSUE TITLE
Hide default themes (setting ?)

### ISSUE THREAD

**Issue by YannickBiet** [mautic/mautic#4728]
| Q  | A
| ---| ---
| Bug report? | No
| Feature request? | No
| Enhancement? | Yes

## Description:
Currently in theme section, the delete option is available only for non default themes
Problem is that customers using mautic taking time to define multiple themes continue to see these default themes.

Would be cool if we could "hide" the default themes (I understand we can't delete them maybe as the update process would recreate them at next update ?)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9
| PHP version | 7.0.12

**Comment by escopecz** [comment]
Yes, that is the reason.

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
