### ISSUE TITLE
Include contact stage and tags in exports

### ISSUE THREAD

**Issue by briansuthoff** [mautic/mautic#4730]
Feature request
Enhancement

## Description:
Contact stages and tags are available in Segments, which is helpful, but it would be more helpful if they were included in exports too. They should be importable too.

Multiple segments could be created as a workaround, but that quickly becomes unwieldy as the number of stages and tags grow.

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
