### ISSUE TITLE
Ability to send internal notifications as part of a form action

### ISSUE THREAD

**Issue by matishaladiwala** [mautic/mautic#4777]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | No
| Feature request? | Yes
| Enhancement? | No

## Description:
As a Mautic user, I'd like the ability to trigger emails to internal team when a contact timeline event is recorded - a new contact is created, a contact clicks a link in an email, visits the pricing page, etc . - so that I can let a named user and the contact owner know immediately to followup with the contact.
## If a bug:

| Q   | A
| --- | ---
| Mautic version | N/A
| PHP version | N/A

### Steps to reproduce:
1. N/A
2. N/A
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by Loanatik** [comment]
Isn't this already available?  PR #4458 allows you to send a notice to anyone for any reason as part of a campaign action.

**Comment by Maxell92** [comment]
@Loanatik This issue is related to Forms and Point triggers.

**Comment by ronnieduke** [comment]
@matishaladiwala - Would be great if this idea extended to campaigns as a top-level trigger as well. So instead of having to always start campaigns based off segments or campaign forms, campaigns could trigger off of contact created, clicks email, visits webpage, etc. Then you could do all kinds of actions based off that such as send notification, push to integration, add to segment, etc.
