### ISSUE TITLE
Broadcast messages on Twitter

### ISSUE THREAD

**Issue by matishaladiwala** [mautic/mautic#4787]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | No
| Feature request? | Yes
| Enhancement? | No

## Description:
As a Mautic user I want to create and schedule broadcast campaigns on Twitter from my Twitter account so that I can reach all the people that follow me in an automated way
## If a bug:

| Q   | A
| --- | ---
| Mautic version | N/A
| PHP version | N/A

### Steps to reproduce:
1. N/A
2. N/A
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by ankitpr89** [comment]
Rather than broadcast, shall we say we should plan to do drip tweets for the targeted users through tweet and direct messages on Twitter?
This usually give far better result. And this will also include, welcome tweet/ welcome dm to the end follower.

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
