### ISSUE TITLE
Distance based segmentation of contacts

### ISSUE THREAD

**Issue by matishaladiwala** [mautic/mautic#4788]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | No
| Feature request? | Yes
| Enhancement? | No

## Description:
As a marketing user I want to segment my list based on distance from a particular city so that I can invite people within a certain mile radius to my event
## If a bug:

| Q   | A
| --- | ---
| Mautic version | N/A
| PHP version | N/A

### Steps to reproduce:
1. N/A
2. N/A
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by medianicus** [comment]
Is this still on the roadmap?

**Comment by AkkuFresh** [comment]
Good idea.

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
