### ISSUE TITLE
Multi level and/or filters

### ISSUE THREAD

**Issue by matishaladiwala** [mautic/mautic#4793]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | No
| Feature request? | Yes
| Enhancement? | No

## Description:
As a Mautic user I would like advanced filters for segments and reports so that I can create more complex logic using a combination or Ands and Ors to get to the report or list I am looking for

## If a bug:

| Q   | A
| --- | ---
| Mautic version | N/A
| PHP version | N/A

### Steps to reproduce:
1. N/A
2. N/A
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by ankitpr89** [comment]
Yes, this is required to make mautic more useful.

**Comment by XRaccourci** [comment]
This would be helpful to me too.

**Comment by cirdan** [comment]
I agree : the segment definition is not very obvious to use right now, the behaviour of the interface is difficult to predict.
My 2 cents : maybe a additionnal interface to create "criterias" that the user could use in the definition of segments could allow a lighter interface ...and maybe not :-)

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
