### ISSUE TITLE
"Send form results" form's action incomplete when using with field option "show when value exist"

### ISSUE THREAD

**Issue by YannickBiet** [mautic/mautic#4799]
| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? |No 
| Enhancement? | Yes

## Description:
Maybe between Bug and Enhancement.
When you use multiple fields in a form, it is useful to use the "show when value exist" option

![image](https://user-images.githubusercontent.com/930391/30113525-451baa36-9315-11e7-8211-5d78c0f80c87.png)

Thus the form length is not so long and only new / empty fields are asked to the identified contact.

But when the form is submitted, if you use the "send form results" action, only the displayed/submited fields on the current form will be filled in .

Other fields remains empty, although we actually have data in the database and the contact is identified (else we will have displayed all fields)

We will receive an email looking this way :

Here the fiels entered by the contact :
-----------------------
Firstname: 
Lastname: {formfield=nom}
Company: {formfield=societe}
Email: {formfield=email}
Téléphone: 
Fonction: 
Effectif: 1-50 

Note that the empty ones are fields that were displayed (not required) and left empty by the contact
Fields hidden by configuration in the form will remain in the email and be printed as the tag code {formfield=fieldname}

I think Mautic should rather query the DB and replace the missing value by actual DB value. (maybe it could mention by a syntax that the field was not directly input by contact but retrieved in DB

like for example :
**email:**_yannick@company.com (from DB)_

(in italic)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9.2
| PHP version | 7.0.12

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
