### ISSUE TITLE
Clean up standard country list

### ISSUE THREAD

**Issue by matishaladiwala** [mautic/mautic#4822]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | No
| Feature request? | No
| Enhancement? | Yes

## Description:
 As a user I want a clean list of standard values in the country picklist so that I don't look unprofessional by showing values which are not real countries

## If a bug:

| Q   | A
| --- | ---
| Mautic version | N/A
| PHP version | N/A

### Steps to reproduce:
1. N/A
2. N/A
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by justinfortes** [comment]
test comment

**Comment by justinfortes** [comment]
The country list. 

Afghanistan
Albania
Algeria
Andorra
Angola
Antigua and Barbuda
Argentina
Armenia
Australia
Austria
Azerbaijan
Bahamas
Bahrain
Bangladesh
Barbados
Belarus
Belgium
Belize
Benin
Bhutan
Bolivia
Bosnia & Herzegovina
Botswana
Brazil
Brunei
Bulgaria
Burkina Faso
Burundi
Cabo Verde
Cambodia
Cameroon
Canada
Central African Republic
Chad
Chile
China
Colombia
Comoros
Congo
Costa Rica
Côte d'Ivoire
Croatia
Cuba
Cyprus
Czech Republic
Denmark
Djibouti
Dominica
Dominican Republic
DR Congo
Ecuador
Egypt
El Salvador
Equatorial Guinea
Eritrea
Estonia
Ethiopia
Fiji
Finland
France
Gabon
Gambia
Georgia
Germany
Ghana
Greece
Grenada
Guatemala
Guinea
Guinea-Bissau
Guyana
Haiti
Holy See
Honduras
Hungary
Iceland
India
Indonesia
Iran
Iraq
Ireland
Israel
Italy
Jamaica
Japan
Jordan
Kazakhstan
Kenya
Kiribati
Kuwait
Kyrgyzstan
Laos
Latvia
Lebanon
Lesotho
Liberia
Libya
Liechtenstein
Lithuania
Luxembourg
Madagascar
Malawi
Malaysia
Maldives
Mali
Malta
Marshall Islands
Mauritania
Mauritius
Mexico
Micronesia
Moldova
Monaco
Mongolia
Montenegro
Morocco
Mozambique
Myanmar
Namibia
Nauru
Nepal
Netherlands
New Zealand
Nicaragua
Niger
Nigeria
North Korea
Norway
Oman
Pakistan
Palau
Panama
Papua New Guinea
Paraguay
Peru
Philippines
Poland
Portugal
Qatar
Romania
Russia
Rwanda
Saint Kitts & Nevis
Saint Lucia
Samoa
San Marino
Sao Tome & Principe
Saudi Arabia
Senegal
Serbia
Seychelles
Sierra Leone
Singapore
Slovakia
Slovenia
Solomon Islands
Somalia
South Africa
South Korea
South Sudan
Spain
Sri Lanka
St. Vincent & Grenadines
State of Palestine
Sudan
Suriname
Swaziland
Sweden
Switzerland
Syria
Tajikistan
Tanzania
TFYR Macedonia
Thailand
Timor-Leste
Togo
Tonga
Trinidad and Tobago
Tunisia
Turkey
Turkmenistan
Tuvalu
U.K.
U.S.
Uganda
Ukraine
United Arab Emirates
Uruguay
Uzbekistan
Vanuatu
Venezuela
Viet Nam
Yemen
Zambia
Zimbabwe

**Comment by galvani** [comment]
Hi @justinfortes is this the final list?

**Comment by Dreiser** [comment]
I created little python script to go through current list and find out that there is 43 missing in list. Some of them due to different name

**Justin's name** - **In regions.json**
Bosnia & Herzegovina - Bosnia and Herzegovina
Brunei - Brunei Darussalam
Cabo Verde - Cape Verde
DR Congo - Congo, The Democratic Republic of the
Iran - Iran, Islamic Republic of
Libya - Libyan Arab Jamahiriya
Micronesia - Micronesia, Federated States of
Montenegro - Serbia and Montenegro (Serbia is independent since June 2006 so Montenegro is correct)
North Korea - Korea, Democratic People's Republic of
Russia - Russian Federation
Sao Tome & Principe - Sao Tome and Principe
Serbia - Serbia and Montenegro (Same as Montenegro)
South Korea - Korea, Republic of
South Sudan - Sudan (no other Sudan in regions.json)
Syria - Syrian Arab Republic
Tanzania - Tanzania, United Republic of
U.K. - United Kingdom
U.S. - United States

Missing:
Andorra
Antigua and Barbuda
Barbados
Dominica
Gabon
Georgia (In United States but not as separated region),
Grenada
Holy See
Laos
Liechtenstein
Malta
Monaco
Nauru
Nepal
Palau
Saint Kitts & Nevis
Saint Lucia
San Marino
Seychelles
Singapore
St. Vincent & Grenadines
State of Palestine
TFYR Macedonia
Tonga
Tuvalu

**Comment by Dreiser** [comment]
So about countries.json. I made some corrections (replaced & for "and" and so..) I ended up with:

Cote dIvoire in coutries.json but should be as Justin says Côte d'Ivoire (not sure about encoding)
Holy See - missing (or with another name)
Timor-Leste - missing (or with another name)

So i can remove extra, add two missing and let me know about Côte d'Ivoire

**Comment by AndrassGray** [comment]
Just a thought : Does this list has to match integrations? And what happens if an integration is running on a different language user interface ?

**Comment by angeloluidens** [comment]
Why not keep the country list current based on the ISO-3166? This already an ongoing international effort from a reputable organization (International Standards Organization) to keep the list of countries current. Here the reference for your information and use: https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes
