### ISSUE TITLE
Bulk update contact's preferences from contact view

### ISSUE THREAD

**Issue by matishaladiwala** [mautic/mautic#4843]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | No
| Feature request? | No
| Enhancement? | Yes

## Description:
As a user of Mautic I want to be able to bulk update the contact's preferences from the summary contact view so that I don't have to update each contact's preferences one at a time.

Go into a contact's detail page (/s/contacts/view/ID), there's a Preferences button in the action drop down top right. That will activate a modal with preferences very similar to the unsubscribe page (I think they actually use the same template if not customized). Go back to the list view (/s/contacts) and check a few contacts. The batch dropdown will activate around the checkall in the table header. Click that and you'll see all the batch actions available. Add the same preference center functionality for batch management.

**Comment by ankitpr89** [comment]
This is most required

**Comment by galvani** [comment]
@ankitpr89 could you please explain what means: preferences? Which field's are to be updated?

**Comment by galvani** [comment]
This task is getting a little bit difficult. 

Standing preferences dialog:
![image](https://user-images.githubusercontent.com/556426/34485840-da1707c0-efcc-11e7-93f0-eb856d4d1632.png)


1. There are multiple channels, for each of them preferences may be saved separately. 
2. Preferences may be set in 3 ways: **set** **unset** **ignore** 
This will make the form dialog really huge, perhaps even worth whole page view instead of dialog

Regarding the preferred channel. 
If the user doesn't have this channel enabled. Is the channel to be enabled? Should there be a check implemented if the user filled in all required information in order to enable given channel. Or should the channel be ignored. Or should the user have the choice to do either?

**Comment by galvani** [comment]
## Standing preferences dialog ##
![image](https://user-images.githubusercontent.com/556426/34485840-da1707c0-efcc-11e7-93f0-eb856d4d1632.png)

## Thoughts regarding the form ##
- Preferences may be set in 3 ways: **set** **unset** **ignore** 

## Thoughts regarding the preferred channel. ##
- If the user doesn't have this channel enabled. Is the channel to be enabled? 
- Should there be a check implemented if the user filled in all required information in order to enable given channel. 
- Should the channel be ignored?
- Should the user have the choice to do either?

**Comment by javjim-mautic** [comment]
Is there a PR assigned to this?

**Comment by davevurby** [comment]
https://github.com/mautic/mautic/pull/5858

**Comment by mleffler** [comment]
@escopecz Does this make sense for you to bring over the finish line, since you have bene in this code?  TY

**Comment by mleffler** [comment]
@justinfortes This is going to be rewritten, so not sure how you would prioritize it.

**Comment by heathdutton** [comment]
Been tested and will ship with the next feature release. #5962

**Comment by Woeler** [comment]
Merged https://github.com/mautic/mautic/pull/5962
