### ISSUE TITLE
Sort by country first, then state, then city

### ISSUE THREAD

**Issue by yyil** [mautic/mautic#4874]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | N
| Feature request? | N
| Enhancement? | Y

## Description:
Currently, when I click the "Location" heading on the contacts page, the rows are sorted according to city name. I think it makes more sense to sort by country, then state, then city.

This way we can drill down to city level of sorting if we need, simply by paginating anyway.

### Steps to reproduce:
1. Click "Contacts"
2. Click on heading: "Locations"

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
