### ISSUE TITLE
Import Leads not from Web interface?

### ISSUE THREAD

**Issue by kithokit** [mautic/mautic#492]
I have a set of leads from MongoDB and it keeps changing.

I want to use "import" back to Mautic DB and use this software. But how can we import it not from Web interface as I want to sync the leads user to Mautic periodically.

Is it possible or can we have such feature?

**Comment by alanhartless** [comment]
Hi Kithokit,

Are you able to export the leads as a CSV file? If so you could use that and import into Mautic using the Import button on the Manage Leads page.

Otherwise, if by not from web interface, you mean not through a browser at all, you might have to write something to do the syncing for you using our API.  There's a PHP library at https://github.com/mautic/api-library to give you an idea.

**Comment by kithokit** [comment]
that's cool, perhaps try your api-library to import leads then

**Comment by qarlyblue** [comment]
.

**Comment by qarlyblue** [comment]
class TestController
{
    public function indexAction()
    {
    	        $settings = array('userName'   => 'KLIC', 'password'   => 'KLIC1111');
		$initAuth = new ApiAuth();
		$auth = $initAuth->newAuth($settings, 'BasicAuth');
 		$apiUrl = 'http://dev.mautic.com/api/';
		$api = new MauticApi();
		$contactApi = $api->newApi('Contacts', $auth, $apiUrl);

                         $rows = array_map('str_getcsv', file('D:/mautic/tags.csv'));
		$header = array_shift($rows);
		$csv = array();

		for ($i=0; $i < count($rows); $i++) {
			$csv[$i] = array_combine($header, $rows[$i]);
			$contact = $contactApi->create($csv[$i]);
			echo date("H:i:s ");
			print_r($csv[$i]);
			echo "<br>";
		}

    }
}
