### ISSUE TITLE
Custom Tags field in forms

### ISSUE THREAD

**Issue by Rixita** [mautic/mautic#4946]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | Yes
| Enhancement? | 

## Description:
The possibility to have a custom multi select field in forms, which behave´s like the tags feature within the contacts details in the backend.

That way the visitor could choose from the custom tags. Extra feature would have the option to let the visiter create a new tag if none of the presented tags are applicable.

For ex. i visiter wants to get information about particular countries / regions / cities.
That way the visitor can choose different options from the tag list, and if a country / region or city is not present, he can insert a new tag.

![bildschirmfoto 2017-09-18 um 15 26 22](https://user-images.githubusercontent.com/31830294/30544127-c5c03a34-9c85-11e7-95fe-db95d177792b.png)

Extra nice would be:
- to have these custom tags shown within the contacts page (right border below the original tags). 
- to be able to use these tags for filtering etc.

Why not use this feature with the orignal tags? Well there might be some tags, you don´t want the visitor to see ;).

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
