### ISSUE TITLE
[feature] Conversion rate for forms/pages available on reports

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#495]
It would be pretty vital I think to be able to report the conversion rate - e.g. proportion of unique visits who go on to complete the form on a landing page, or anywhere in fact.

I can't see any way of reporting on this data currently.

**Comment by joshwalsh** [comment]
I agree with this wholeheartedly. We have to do this currently using Google Analytics with goals, or by manually running reports in excel using page hit reports and form submitted reports.

**Comment by dsukhin** [comment]
Evaluating Mautic right now. Very, very impressed so far but this type of conversion tracking (mentioned in this issue) seems to be the most missing feature right now. It seems it wouldn't be too hard to measure how an individual campaign is performing on some metric using the same framework as a/b tests use to determine stats and progress thru a funnel using custom events. 

I see this feature request was recently closed. I'd like to know:
(1) what is the standard way (how are others doing it) of doing this type of conversion tracking/campaign optimization while using Mautic? Would love to hear from others. 
(2) is there any clever way to set this up within Mautic today (custom reports, custom events, etc) given that this issue was backlogged and closed about a month ago?

Thanks!

**Comment by claytoni9bh** [comment]
Mautic is a very good platform, but really this is a essential information. If anyone has a way to do this, post here.
