### ISSUE TITLE
"Apply" button doesn't work with dynamic content in emails

### ISSUE THREAD

**Issue by cceruti** [mautic/mautic#4963]
What type of report is this: Bug

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
The more details the better...
It just causes the DC box to show the token without saving any of the actual dynamic content, or it causes DC box for 15 seconds and then shows "Hello {customefield=first_name}!" as "{dynamiccontent="Dynamic Content 2"}" and then dynamic content cannot be edited once saved changes are applied (after waiting 15+ seconds).

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. Launch email builder
2. Add Dynamic Content and hit apply...wait 15+ seconds
3. Try to edit dynamic content
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by rowlandhill** [comment]
When you hit "apply" within the builder, you're unable to go back and edit DC, but if you hit "close builder", then "save and close", then back to "edit", you can select the DC, so that seems to be isolated to the "apply" button (please see attached video).
[DC uneditable after creation.zip](https://github.com/mautic/mautic/files/1369401/DC.uneditable.after.creation.zip)

**Comment by yourdigitalclub** [comment]
I have this same issue but I don't need to waiting 15 seconds for it to display something else... you just can't edit the dynamic content at all after hitting apply

**Comment by virlatinus** [comment]
Fixed in #5140
