### ISSUE TITLE
Don't log updates to (contact) fields as changes, if they didn't change

### ISSUE THREAD

**Issue by dsp76** [mautic/mautic#4985]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? |  Y
| Enhancement? | 

## Description:
We do send updates to Mautic fields from external systems via API. They update (contact) fields regularly. Mautic does log it as a change in the contact event log - even if the update was no change. This fills up the event log.

Wanted behaviour: Only log "phase changes" if the phase really changed. Could be the same for other events as well.

### Steps to reproduce:
1. regularly update e.g. a customer phase field
2. an event about a phase change will be logged for the contact, even if it the state remains the same
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
