### ISSUE TITLE
Feature Request: Add error messages across platform

### ISSUE THREAD

**Issue by sarahwernik** [mautic/mautic#5044]
What type of report is this: Feature Request

| Q  | A
| ---| ---
| Bug report? | No
| Feature request? | Yes
| Enhancement? | No

## Description:
We need error messages and notifications all over the platform whenever an error could occur. For example, for Dynamic Content within Emails, if you're using code view to add in your HTML then there should a notification that if you don't close out of code view before saving then the email will clear out.

Additionally, if a user is trying to add a new contact with an email address within the Quick Add section then there should be an error message if the email address they've inputted is invalid. It should not be allowed to save if the email is invalid.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by sarahwernik** [comment]
@cceruti

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
