### ISSUE TITLE
"Secured" Assets URL

### ISSUE THREAD

**Issue by YannickBiet** [mautic/mautic#5052]
| Q  | A
| ---| ---
| Bug report? | No
| Feature request? | Yes
| Enhancement? | No

## Description:
When creating an asset, the download URL generated by Mautic is : https://mautic.company.com/asset/1:internal-id-of-asset

Customers asked us why the internal id was facing the public url generated.

We thought it was for security concerns : 
maybe mautic would check that both internal-id and numeric id match before processing the download but not as soon as you type in URL

https://mautic.company.com/asset/1:any-string

the download is processed

This way, a competitor knowing that you're using Mautic could request all the assets by creating a single batch to loop accross all numeric Ids.

I think mautic should implement a URL verification for both the numeric id and internal name provided.

If the internal name does'nt match the numeric ID, download should be forbidden.

Ps : maybe we should lock internal-id modification once the asset has already been created (like for custom fields)

Any feedback from the communauty ?

**Comment by dbhurley** [comment]
Good comment. This should be addressed.

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
