### ISSUE TITLE
Forms > New verification before adding a field

### ISSUE THREAD

**Issue by YannickBiet** [mautic/mautic#5053]
| Q  | A
| ---| ---
| Bug report? | No
| Feature request? | No
| Enhancement? | Yes

## Description:
We trained a customer yesterday to use the mautic's forms.
Our customer was really happy until he tried to create form by himself.

He selected the text type, added labels and help messages but each time he forgot to select the matching contact field! 

He told us that this was not so logical to ask on first tab if field should be saved in database but that the software does not control if a matching field is then defined in next tab.

So Enhancement would be labelled :
"If a field is flagged to be savec in DB, mautic should prevent the user to close the popup without having selected a matching field"

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
