### ISSUE TITLE
Custom form field classes f* up Mautic UI

### ISSUE THREAD

**Issue by metriclive** [mautic/mautic#5055]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
If you add custom classes to form field elements they should not be active in the mautic UI. It can fuck-up to user interface. Those classes should be ignored when in the form edit interface.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | all versions
| PHP version | all versions

### Steps to reproduce:
1. add bootstrap classes to form field (eg. col-md-12)
2. edit form buttons become un-clickable

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
