### ISSUE TITLE
Custom emails don't register email open from tracked link

### ISSUE THREAD

**Issue by AndrassGray** [mautic/mautic#5069]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | ?
| Feature request? | Y
| Enhancement? | 

## Description:

I have sent a custom email, containing a tracked link. Thunderbird blocks the tracking-pixel, so no way for Mautic to identify the open. Fine so far.

Opening the embedded link doesn't register as email open, although the page hit is recognised and attached to the right contact.

The feature request would be to recognise an email-open from a page-visit, thus bypassing (sort-of) the tracking-bug. Which would in turn enable "email-open"-sensitive campaigns to take action.

![m-custom-emails](https://user-images.githubusercontent.com/30862808/31048846-84b65e74-a626-11e7-8622-2de01979074b.jpg)

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
