### ISSUE TITLE
Enhanced unsubscribe function

### ISSUE THREAD

**Issue by merlin0** [mautic/mautic#5114]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | x
| Enhancement? | 

## Description:
Currently the unsubscribe system is in our view limited. There are some problems we face with the current implementation of the unsubscribe system. 

 - There is no way to edit the unsubscribe page or edit the text. (Currently Mautic is working on this issue)
- There is no good way to see from which segment or campaign the lead has been unsubscribed. There is only the do not contact tag/ icon. There is no way to manual edit or add an tag.
- There is no way to create a good flow around unsubscribing because there is no unsubscribe event.  Therefor it is not possible to give a lead negative scoring, or change their segment etc. or send a conformation mail the lead has unsubscribed with instructions how to resubscribe . 

That's why we've been working on plugin to add these features. Because of our limited time we can't make enough progress so we think it's the best solution to share it with the community in the current state.

@sahidjeurissen [Has been working on the plugin for some time now.  ](https://github.com/mautic/mautic/pull/5104)
-We've already added a custom unsubscribe page with custom text.(The translation files are in place for the copy of the unsubscribe page. )
-A setting page where you can select the campaigns you want to people to be able to unsubscribe from.
-A new decision event in the campaign builder that can trigger actions when a user unsubscribes from a campaign. 

Wishlist:
-Add other channels besides email.
-Add functionality to sync the opt in with different systems like CRM, newsletters tools etc.

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._

**Comment by merlin0** [comment]
I've linked to the code we produced, should I attach it in an other way?

**Comment by npracht** [comment]
Hello!
The mautic policies requests that all the feature requests and integration requests are discussed on the [mautic slack](https://mautic.slack.com) or on the [mautic forums](https://www.mautic.org/forums/).
Github is better used for issues reporting and code proposition.
Thanks for contributing!

N.
