### ISSUE TITLE
Stages and Tags available in Reports

### ISSUE THREAD

**Issue by rowlandhill** [mautic/mautic#5127]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | YES
| Enhancement? | 

## Description:
It is not possible to build reports on Stages or Tags.  It is possible to filter them with Segments, but tracking the customer journey through stages is not possible, because Segments will not allow you to track when Contacts leave a Stage, how many left and when.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._ 

@cceruti

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
