### ISSUE TITLE
Option to add twitter and facebook markups [meta name="twitter:card"] and [meta property="og:image"] in landing pages

### ISSUE THREAD

**Issue by LucasFarley** [mautic/mautic#5136]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | X

## Description:
I would like to have an option to add twitter and facebook markups [meta name="twitter:card"] and [meta property="og:image"] in landing pages. 
it is extremely important to share pages in social media.

**Comment by luizeof** [comment]
+1

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
