### ISSUE TITLE
Users should be able to choose which GTW to include in email token link

### ISSUE THREAD

**Issue by sarahwernik** [mautic/mautic#5141]
What type of report is this: Enhancement

| Q  | A
| ---| ---
| Bug report? | No
| Feature request? | Yes
| Enhancement? | Yes

## Description:
When using the GTW integration, a user has the option to send out a "reminder" or "join" email from Mautic for the upcoming webinar. At this point in time, the logic behind inserting a "join" token to the email looks at the last webinar that the contact registered for. This doesn't work for most marketers as they're promoting multiple webinars at a time. The user needs to be able to choose which webinar should be included in the token link, i.e. {webinar_link=WEBINAR_NAME}

Enhancement from #3817

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. Set up GTW plugin
2. Register for 2 webinars through Mautic
2. Build an email with GTW token of {webinar_link}
3. Send a test email to the contact that registered
4. Click on the join link. It will take you to the login for the most recent webinar you registered for 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
