### ISSUE TITLE
Import contact csv with varying tags

### ISSUE THREAD

**Issue by JoshFialkoff** [mautic/mautic#5143]
What type of report is this:

| Q  | A
| ---| ---
| Feature request? |  Y

## Description:
It would be great if Mautic users/admins could import lists of contacts with multiple, varying tags. Attached is a XLSX with sample contacts who each have multiple tags which are not all the same.
[mautic import example.xlsx](https://github.com/mautic/mautic/files/1380153/mautic.import.example.xlsx)

**Comment by JoshFialkoff** [comment]
For instance, I have a list of hundreds of contacts and they have different tags. For instance, some have a,b,c,d,e and others have a,b,f,g,h and others have i,j,k,l,m,n. There are too many combinations to do different imports for each tag.

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._

**Comment by eugenp** [comment]
Hi, 
Quick question here - was that migrated to the Ideas Forum? If so - is there any chance of a direct link to that discussion there?
Cheers, 
Eugen.
