### ISSUE TITLE
Pipedrive full sync mode

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#5164]
| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | x

## Description:
As a user, i'd love to have the same feature from mautic to pipedrive as today from pipedrive to mautic --> any modified contact in mautic is directly synced. to pipedrive.
I'd call that the "full sync. mode".

### Suggestion:
Can we complete the command line to use it as CRON every X min for the modified contacts in that timeframe ?

**Comment by kuzmany** [comment]
My solution for Pipedrive full sync mode 

I recommend use Mautic webhooks on this issue, because you are able to provide webhooks  provide realtime or on large sites you can provide  it in queue.  

My suggestion should works like this: 

I will add to Pipedrive plugin new hook url:
https://mauticdomain.tld/plugin/pipedrive/webhook.

 Then this URL clients who wants add full Pipedrive sync mode  just added this url to Mautic Configurations > Webhooks with these events: 

- Contact Deleted Event
- Contact Identified Event
- Contact Updated Event

I think webhooks can  speed up  full sync integration. Time saver at the moment.

**Comment by npracht** [comment]
This is great!

Envoyé de mon iPhone

**Comment by kuzmany** [comment]
Just for note: I discovered some stuff  on SalesForce and SugarCRM integration how it integrate with crons based on integration API. I will try this way, it's more logic.

**Comment by kuzmany** [comment]
Please try test: https://github.com/mautic/mautic/pull/5383 
Now I am tired and I my brain is out of work. 
Maybe this solution not work properly with already created contacts. Will see tomorrow.

**Comment by kuzmany** [comment]
@npracht let me know about PR https://github.com/mautic/mautic/pull/5383
This PR resolve just sync actual data, that means if you create new contact in Mautic > contact will import to Pipedrive. If you edit this contact, already will update in Pipedrive.
This solution not solve situation if contact already exist in Mautic but no Pipedrive. 
Than If you edit Contact in Mautic, it's not sync to Pipedrive (doesn't matter if exist in Pipedrive or not), because it's not linked in Muatic db (integration_entity table).

Pipedrive integration works just:
- If contact is created in Mautic or Pipedrive, plugin create connection in integration_entity table and sync data
- Then if you edit contact in Mautic or Pipdrive  with connection from integration_entity table, data are sync

Hope It's clear.
Do you wanna add also  sync data if integration_entity row doesn't exist  for update action?
It's little more work. But not so hard.

**Comment by kuzmany** [comment]
Ok, guys. 
Let's test:

https://github.com/mautic/mautic/pull/5383
