### ISSUE TITLE
Template Email vs Segment Email

### ISSUE THREAD

**Issue by nickian** [mautic/mautic#5210]
This is more of a feature request / question clarification than anything...

What is the reason for designing the email system this way? Is it necessary to segregate "template" emails vs "segment" emails? Why can't there just be "emails"? That is, one email template format versatile enough to be used and reused in both ways? Either in automation via campaigns or sent/scheduled in the UI manually.

Every time I want to send something, I have to ponder whether or not to make it a "segment" email or a "template" email and the consider consequences of that decision. It's often a compromise. Or I'll have to duplicate the email and have a "template" and "segment" version of it. I've never seen this in other email marketing software before.

I'm curious if anyone else has thought about this or found it frustrating.

For reference, the documentation (https://mautic.org/docs/en/emails/index.html) defines the difference:

**Template Emails**
Template emails are transactional by default and can be used in campaigns, form submit actions, point triggers, etc. These can be sent to the same contact as many times as needed. These cannot be sent to a contact outside of another Mautic component except when sending an email directly to a contact in which the content is cloned (template emails sent directly to a contact are not associated with the template email itself and thus stats are not tracked against it).

**Segment (Broadcast) Emails**
These are marketing emails by default. Segments are assigned to the email which will determine which contacts receive the communication. Note that each contact can only receive the email once - it's like a mailing list.

**Comment by dbhurley** [comment]
Thanks for bringing this up. There will certainly be some improvements to the email paths in the coming releases.

**Comment by sanderdatema** [comment]
I'm just curious, has there been any thoughts on this? While the documentation of the two types has been changed over time, it seems the path hasn't yet.

**Comment by aspiers** [comment]
I agree, as a newcomer to Mautic I find this confusing.  Actually, I wonder when segment mails would ever be useful.  It seems that everything they offer can be achieved via a template/campaign combination, except perhaps the simplicity of setup.

I also don't find the terminology "transactional" vs. "marketing" very helpful since the terms are not defined anywhere.  Surely all email is transactional, and all email sent with Mautic is marketing in some form?

I made this table to try to understand it better - is this correct?

| | template | segment (broadcast) |
|---|---|---|
| nature | transactional, [also marketing via campaign](https://www.youtube.com/watch?v=qEPnuxOxK1Q) | marketing |
| # of times can be sent to person | many times | just once |
| recipients | anyone | people in single segment at send-time |
| trigger | campaign/form action/points trigger etc. | schedule date + time |
| change after sending | yes | **NO** |
| add recipients after sending | yes | needs rescheduling |
| direct send to individual | yes | no |
| open/click tracking | no? | via trigger element, i.e. campaign/form etc.? |

Since this is still an issue, I would have preferred it to be kept open.

**Comment by WillN-Bridgevine** [comment]
From a high level I understand why it was done this way. You have to think of it from 2 perspectives, architecture and CANSPAM. The definition of a transactional email is an email that does not fall under CANSPAM - these would be order confirmations, password changes etc. There is no unsubscribe option for these types. In the case of Mautic, you can look at the segment email as a transactional trigger segment. If you have an ecom connected via api that sends order confirmations to a specific segment, it would fire off the email template associated with it transactionally.

With marketing emails that does fall under CANSPAM - emails that market to the customers post transactional, you can use any segment and campaign with them.

At lease this is how i'm thinking on utilizing the platform. Any comments are welcome!

**Comment by aspiers** [comment]
That's helpful, thanks!  Although I had to google CANSPAM first - it's a USA-only thing so the rest of us aren't familiar with it.

**Comment by WillN-Bridgevine** [comment]
> That's helpful, thanks! Although I had to google CANSPAM first - it's a USA-only thing so the rest of us aren't familiar with it.

Ah, yes - CANSPAM doesn't apply to Europe.

**Comment by virgilwashere** [comment]
Or this side of the pond.

:au: :beach:
