### ISSUE TITLE
Feature request - Add 'code mode' as a permissions option for roles

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#5217]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | x
| Enhancement? | 

## Description:
Often there would be a need to prevent a user from having access to code mode, but it is not an option in the builder for landing pages or emails to restrict code mode by role. Presume it would be relatively easy to add as a feature and could prevent a lot of headaches!

**Comment by dbhurley** [comment]
👍  not a bad idea. :wink:

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
