### ISSUE TITLE
Maintain form field specifier if possible, when changing form (in campaign builder)

### ISSUE THREAD

**Issue by gingerling** [mautic/mautic#5218]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | y

## Description:
One thing that always catches me out when cloning campaigns and forms. I have a standard campaign framework that I use for trade shows, however, to help me measure how well each show has gone for us I clone all forms and emails, editing things like the event name and prizes if there is a competition. 

I then clone the campaign and edit replace the forms and emails with those I just cloned and edited - the actual campaign flow is the same, but about 5 changes are made each time - for example the triggering form and the emails. 

One thing which catches me out each time is that if I have specified a campaign action to only trigger for those who responded a certain way to an item form, if I swap out the form, it resets the limitation to email: yes. The forms I am swapping are the same in all but name, unedited clones, so the fields are the same. It would be good if mautic could remember the last setting and just keep the same set up if the form has the same fields and values.

Thanks!

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
