### ISSUE TITLE
Reports on Page Hits, Form Submits filtered by Segment

### ISSUE THREAD

**Issue by rowlandhill** [mautic/mautic#5232]
What type of report is this: Feature Request

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | Yes
| Enhancement? | 

## Description:
As a user, I would like to be able to see which of my contacts within a certain segment have either visited a page or submitted a form which were not included in a campaign or within an email.  If I send an email with no links, I would like to see if that email drove any of those contacts to any of my websites.  As of right now, this is not possible.

I would like to be able to create a report with Page Hits as the data source and the following options available as filters:
- Segment
- Page url (could use condition "includes" or "equals" to track part of a website or a specific page)

I would also like to be able to create a report with Form Submissions as the data source and the following options available as filters:
- Segment
- Form ID

## If a bug:

| Q   | A
| --- | ---
| Mautic version |
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
