### ISSUE TITLE
Add a "Send Test" button in the email editing screen

### ISSUE THREAD

**Issue by calevans** [mautic/mautic#5234]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | Y
| Enhancement? |  Y

## Description:
It would be nice to have a "Send Test" email button next to "Apply" and "Close Builder". Currently to test my email, I have to save it, exit the builder and the edit screen and then I can send a test. 

Here is a picture of where I think it would work nicely. 
![mautic_email_panel](https://user-images.githubusercontent.com/426938/32136001-0a44bf9e-bbd6-11e7-9c81-8c17ca8dd65d.PNG)

TIA!
=C=

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
