### ISSUE TITLE
Have Mautic remember who I send test emails to.

### ISSUE THREAD

**Issue by calevans** [mautic/mautic#5235]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | Y
| Enhancement? | 

## Description:
Currently, every time I send a test email, if it is going to more than just me, I have to add the others in manually. It would be nice if, after the first time I sent a test for a particular email, that Mautic remembered who I sent tests to. It doesn't have to be stored in the DB and be persistent, just add a cookie or add it in to the $_SESSION and remember it until I log out.

**Comment by dbhurley** [comment]
Good suggestion for a minor usability feature improvement. Thanks!

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
