### ISSUE TITLE
Lead Referral

### ISSUE THREAD

**Issue by namankumar** [mautic/mautic#5236]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | | 
| Feature request? | x | 
| Enhancement? | |

## Description:

Have the ability for a lead to send referral links to others.

While referrals are usually reserved for product teams not marketing, they are needed for marketing to create virality. Referrals are the secret to dropbox success. The idea would be that an identified lead can refer others. If they accept, the leads receives x points and the referral receives y points. You can obviously run campaigns on this as well.

I would love to work on this but I cannot commit the time right now, I'm not very familiar with the codebase. If anyone is interested, please feel free to work on this. 

I think it can be done in this way:

1. Have the lead enter email addresses and names using a Mautic form
2. Generate a hash with the seed as a string made of email addresses of the lead and the referral
3. Store the lead, the referred email address, and the hash in "referral" table in the database
4. Make email, with hot code like {referrallead=email} {referree=email} {referrallead=accept} where accept is the hash code
5. Send email
6. Referral clicks on link to acceptance link
7. Link brings to landing page where everyone gets points

**Comment by AkkuFresh** [comment]
I agree. Affiliate / referral marketing tools are very important tools in a Marketing Automation system like Mautic. Existing Mautic features and tools are good base for the create an extension for this purpose.
I am familiar with coding and would be glad to work on it.

**Comment by namankumar** [comment]
Thanks @AkkuFresh

**Comment by namankumar** [comment]
Hi @AkkuFresh, wondering if I can help with this? Would be happy to brainstorm the implementation... let me know!

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
