### ISSUE TITLE
Contacts page returning HTTP 404

### ISSUE THREAD

**Issue by dmelo** [mautic/mautic#5237]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
HTTP 404 on /s/contacts page "The requested URL /s/contacts was not found on this server." . The dashboard works just fine. Trying to access individual contacts also works perfectly (/s/contacts/view/3). But if I try to access the contacts on the left bar, it doesn't load. If I try to open it on a new tab, I get the 404.

I'm getting the same behavior with /s/segments and /s/reports .

## If a bug:

| Q   | A
| --- | ---
| Mautic version | v2.11.0
| PHP version | 7.1.10

### Steps to reproduce:
1. Fresh install the system
2. Login
3. Click on the "Contacts" link asking the browser to open on a new tab.
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by void-gh** [comment]
I'm seeing a similar issue with the "Contacts" link. Basically if you click on the link Mautic will refuse to respond. If you type in the URL into the browser Mautic will return a "Site is offline" error. However, in our case if we try to access an individual directly (/s/contacts/view/3) we still get the same offline error.

We upgraded from 2.9.2 to 2.11.0 via the web browser. The upgrade appeared to go well; however, when clicking around the application we noticed this issue. Going through John Linhart's "[Uh Oh, Mautic upgrade was not successful](https://johnlinhart.com/blog/uh-oh-mautic-upgrade-was-not-successful)" suggestions, the only thing that appeared to be out of wack was one database schema update that was not applied with regards to dropping an index on the leads table. Applying this update and restarting the service had no effect.

Looking in both the Mautic app/log as well as the web server's error log when attempting to access the "Contacts" page shows the following errors:

Mautic Log
```
[2017-11-02 09:46:35] mautic.WARNING: PHP Warning - require(/htdocs/MAUTIC/app/cache/prod/doctrine/orm/Proxies/__CG__MauticStageBundleEntityStage.php): failed to open stream: No such file or directory - in file /htdocs/MAUTIC/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php - at line 209 [] []
[2017-11-02 09:46:35] mautic.ERROR: PHP Notice: require(): Failed opening required '/htdocs/MAUTIC/app/cache/prod/doctrine/orm/Proxies/__CG__MauticStageBundleEntityStage.php' (include_path='.:/pear/lib:/var/www/pear/lib') - in file /htdocs/MAUTIC/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php - at line 209 [] []
[2017-11-02 09:46:35] mautic.ERROR: Symfony\Component\Debug\Exception\FatalErrorException: Notice: require(): Failed opening required '/htdocs/MAUTIC/app/cache/prod/doctrine/orm/Proxies/__CG__MauticStageBundleEntityStage.php' (include_path='.:/pear/lib:/var/www/pear/lib') - in file /htdocs/MAUTIC/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php - at line 209 [] []
```

Web Server Error Log
```
PHP message: PHP Warning:  require(/htdocs/MAUTIC/app/cache/prod/doctrine/orm/Proxies/__CG__MauticStageBundleEntityStage.php): failed to open stream: No such file or directory in /htdocs/MAUTIC/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php on line 209
PHP message: PHP Fatal error:  require(): Failed opening required '/htdocs/MAUTIC/app/cache/prod/doctrine/orm/Proxies/__CG__MauticStageBundleEntityStage.php' (include_path='.:/pear/lib:/var/www/pear/lib') in /htdocs/MAUTIC/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php on line 209
```

It appears the upgrade didn't completed successfully even though the status message indicated otherwise. We have not yet attempted to do a manual upgrade to see if this resolves the issue...

**Comment by dmelo** [comment]
@void-gh About the error you have described on the logs, check if the files are still belonging to apache/www-data user. My guess is that you have cleared the cache using php app/console cache:clear with a user different then your HTTP server's and it is not being able to create/access resources within your cache directory.

About the problem with the contact page. I couldn't figure out what to do then I just decided to use the v2.10.1 instead.

**Comment by void-gh** [comment]
@dmelo So the cache folders were all owned by the web server process; however, for whatever reason the cache wasn't being repopulated after the upgrade to 2.11.0.

So I went the manual upgrade method: Stopped the web service, backed up the existing Mautic web directory, blew it away, manually downloaded the latest 2.11.0 installer and expanded it, copied over the app/config/local.php from the backup, reset the folder permissions, and then restarted the web server.

Went to the Mautic login page, signed in and accessed the "Contacts" section without any issues. And all the error messages in the log files are gone.

So nutshell summary, the in-app updated process didn't work 100% and left the application in a partial limbo state that was resolved by a manual upgrade.
