### ISSUE TITLE
INCLUDE and EXCLUDE operators for ALL fields using CSV.

### ISSUE THREAD

**Issue by omert37** [mautic/mautic#5239]
What type of report is this:

| Q  | A
| ---| ---
| Feature request? | Yes|

## Description:
I wish that the "include" and "exclude" operators in the segmentation (for the Country field AND ALL fields) could support the use of a long comma delimited list of values.

e.g. COUNTRY include United States, United Kingdom, France, Mexico....
e.g. PET exclude Dog, Cat, Parrot, Hamster...

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
