### ISSUE TITLE
Allow Segments, Components, Channels & Campaigns to be archived

### ISSUE THREAD

**Issue by sarahwernik** [mautic/mautic#5248]
What type of report is this: Feature Request

| Q  | A
| ---| ---
| Bug report? | No
| Feature request? | Yes
| Enhancement? | No

## Description:
After an email has been sent out a user may not want to delete it because they may want to send it out again at the same time next year, but they don't want the email to take up space in their UI. Allow users to archive emails, segments, components, etc from the UI. The user should be able to access these items again in the future.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. Select an item
2. From the dropdown menu select, "Archive"
3. The item disappears from the main UI, but is accessible in the future if Mautic allows the user to "only show archived items" vs "only show available items"
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by ronnieduke** [comment]
Yes please!!! :-)

**Comment by gingerling** [comment]
Similar with: https://github.com/mautic/mautic/issues/5490

**Comment by gingerling** [comment]
Please also sort by ID or Creation date by default - there isn't any logical reason to sort alphabetically by default, it has no bearing on how people use the software x

**Comment by cStuartHardwick** [comment]
I've added a similar request under the new "Ideas" forum, which cannot be searched by any means I can see. If someone has already moved this request, merging is in order. If not, you all might want to vote for/comment on the one I added. https://www.mautic.org/topic/archive-old-emails/

**Comment by denispavliha** [comment]
I don't understand why such a feature has not been implemented yet. Am I the only one who has at least 3 pages of emails/campaigns/segments/forms, many of them being unpublished (due to being history) and want a cleaner look at actual items? :)

**Comment by ronnieduke** [comment]
@denispavliha I completely agree. Virtually every other MA system I’ve used has some kind of folder/organizational structure to deal with this.

**Comment by AlbanL74fr** [comment]
If it's about grouping things in folders, I can see an advantage, because categories are useful but do not really make things look ordered. Besides the search feature is a total mess, and there is no be a built-in category filter (you must type category:%category-alias%). Folders would allow to access quickly entities, and clean things.
On the other hand, I, personally don't see any use case for needing to archive any type of entity in Mautic. Unpublish, delete does the job. Would archiving serve as a kind a soft delete, to avoid unintentional loss of data?

**Comment by cStuartHardwick** [comment]
Yes, I use categories, but that's a pain because as you say, you have to type the word category. I actually do most of my analysis of leads directly in the database, but that's not possible with emails.

You guys who support this idea are voting in the new topic on the Mautic site, right? You know they are no longer managing improvement requests here (though I do not understand why not--their topic thread doesn't even have search.) https://www.mautic.org/topic/archive-old-emails/

**Comment by gingerling** [comment]
thanks for note,  yes, I have now starred, followed and commented here:  https://www.mautic.org/topic/archive-old-emails/

**Comment by denispavliha** [comment]
Any new tips on how to get this into development? I think it's a must-have new feature for everyone with 100+ campaigns/emails/segments/... and sure hope that someone among developers or decision makers thinks the same way.
