### ISSUE TITLE
Reports: remember filter settings

### ISSUE THREAD

**Issue by kerleba** [mautic/mautic#5251]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | X

## Description:
1. Create a report with filters (e.g. date)
2. Set filter to desired value
3. Log off
4. Log in again
5. You have to set the filter again

It would be very useful to have option to keep filter setting between sessions.

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
