### ISSUE TITLE
Include the actual email "click-thru URL" in the Email and Emails sent reports

### ISSUE THREAD

**Issue by sarahwernik** [mautic/mautic#5276]
What type of report is this: Enhancement

| Q  | A
| ---| ---
| Bug report? | No
| Feature request? | No
| Enhancement? | Yes

## Description:
Users would like to pull a report on the click-thru links from their emails. Today, the links are not included in the Emails or Emails Sent reports. Right now, the reports only offer the number of times the email was clicked. The user would like to do analysis on where in their emails the links were clicked.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
