### ISSUE TITLE
Allow a contact to go through a campaign more than once

### ISSUE THREAD

**Issue by sarahwernik** [mautic/mautic#5279]
What type of report is this: Enhancement

| Q  | A
| ---| ---
| Bug report? | No
| Feature request? | No
| Enhancement? | Yes

## Description:
Allow contacts to go through a campaign more than once for birthday/anniversary renewal/dates. So, on a particular campaign level maybe (?) or a slider option allow repeats (yes or no). Have it automatically set to "no" but gives users the option to send contact more than once

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by gcoli6** [comment]
+1

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
