### ISSUE TITLE
301 redirect loop when using mautic behind an SSL terminating proxy

### ISSUE THREAD

**Issue by lvnilesh** [mautic/mautic#5285]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | y
| Feature request? | 
| Enhancement? | 

## If a bug:

| Q   | A
| --- | ---
| Mautic version |  2.11.0
| PHP version |  7

### Steps to reproduce:
Setup mautic 2.11.0 behind an SSL terminating proxy.

Observe that the default mautic local.php site setting is http not https
Default mautic settings show up like this.
```
cat app/config/local.php |grep site
    'site_url' => 'http://domain.com',
```

Now clear cache 

    sudo rm -rf app/cache/

No issue if I keep it like this.
```
cat app/config/local.php |grep site
    'site_url' => 'http://domain.com',
```

However, I would like to mautic to serve https links to I edit 
```
cat app/config/local.php |grep site
    'site_url' => 'https://domain.com',
```

and clear cache

    sudo rm -rf app/cache

only to run into an infinite 301 redirect loop.

The workaround is to put setting back to http like it was to begin with 
```
cat app/config/local.php |grep site
    'site_url' => 'http://domain.com',
```
and clear cache again and then the infinite 301 redirect loop breaks.

**Comment by luizeof** [comment]
Try Fill "Mautic Trusted Proxy" with 0.0.0.0/0

**Comment by lvnilesh** [comment]
Thanks luizeof. I will try your workaround as well.

**Comment by lvnilesh** [comment]
Thanks to @luizeof and @mingfang. 


When using mautic behind Traefik (an SSL terminating proxy) with a setup like this. 

```
browser  ->  https  ->  Traefik  ->  http  ->  mautic
```
The resolution is to keep `http` in `site_url` like this. 

```
cat app/config/local.php |grep site
    'site_url' => 'http://domain.com',
```
and set the traefik CIDR block for your front end network (something like `10.0.1.0/24`) in mautic  ->  settings  ->  configuration  ->  trusted proxies` and save.

**Comment by jcward** [comment]
I also got an infinite `301` redirect loop while behind an nginx SSL terminating proxy, but it didn't manifest until I started playing with the mautic API:

![image](https://user-images.githubusercontent.com/2192439/49966700-fa938700-fedd-11e8-9d06-5a6c8f821482.png)

I got it fixed by implementing @luizeof's suggestion above: under Configruation -> System Settings -> Miscellaneous Settings, set **Trusted proxies** to `0.0.0.0/0` (and I also had to restart my web servers, thanks to the cached 301's.)

Personally, I'd change all 301 redirects within mautic to 302's -- 301's are a nightmare.

**Comment by petebytes** [comment]
any security issues with setting trusted proxies to 0.0.0.0/0?
for cloudflare, this package may be a useful way to only add the necessary ip's
https://github.com/monicahq/laravel-cloudflare

**Comment by ka4a** [comment]
adding this in index.php solve this issue
$_SERVER['HTTPS'] = 'on';

**Comment by onhout** [comment]
> adding this in index.php solve this issue
> $_SERVER['HTTPS'] = 'on';

Worked for me

**Comment by jos0405** [comment]
Worked for me as well.

**Comment by benbehringer** [comment]
$_SERVER['HTTPS'] = 'on'; solved it for me as well! Got a loop after updating from 3.0.1 to 3.0.2

**Comment by dennisameling** [comment]
@benbehringer I'm trying to understand what we broke in 3.0.2 that's causing this issue.

Looking at the diff below, the only thing that I think might be related is some change to the CORS middleware:

https://github.com/mautic/mautic/compare/3.0.1...3.0.2#diff-31f96ec879757b60b8ff73b30f05593fR29

Does it make any difference if you remove `Authorization` from that file again? That'd really help us troubleshoot this further. Thanks in advance!!

**Comment by andrew-dixon** [comment]
Just had this with the upgrade from 3.2.2 to 3.2.5 and the only fix from the above that worked was the adding of:

```
$_SERVER['HTTPS'] = 'on';
```

to the `index.php`. The "trusted proxies" setting seemed to have no effect at all.

**Comment by colethorsen** [comment]
You can also do this in the .htaccess instead by adding:

`SetEnvIf X-Forwarded-Proto https HTTPS=on`

This won't set HTTPS unless HTTPS is actually the protocol being sent from the loadbalancer. I'm not exactly sure how the update process works, but the .htaccess might be less likely to get overwritten than the index.php

**Comment by MarketSmart** [comment]
I know this is old and i just wanted to provide another fix for those google searching. 

Here is how to fix it in apache when im using ELB proxy pointing to an ec2

Add this to your VirtualHost
```
     RewriteEngine On
     RewriteCond %{HTTPS} off 
     RewriteRule ^ - [E=HTTPS:on]
```

**Comment by jcalfee** [comment]
I just got the redirect loop error after upgrading Mautic to 4.4.6 and clearing the cache.  I'm running Mautic behind a Traefik proxy as well where Traefik takes care of the SSL cert.  It was fixed in 4.4.6 when I added `$_SERVER['HTTPS'] = 'on';` to `index.php`.  

> https://github.com/mautic/mautic/issues/5285#issuecomment-342044375

Is the CIDR network settings still the recommend solution?  I really like `$_SERVER['HTTPS'] = 'on';` because it does not depend on knowing and hard-coding (in settings) the internal network address.

**Comment by nepomuc** [comment]
Is there a solution for the Docker version of Mautic? Maybe @colethorsen ?

**Comment by colethorsen** [comment]
I'm unsure as I no longer use Mautic, and never used it with Docker

From my experience with Docker on other projects you'd simply set it as part of the configuration,  depending on the configuration of your Docker Container any of the solutions listed above could work as well since presumably you'd be running a LAMP stack inside the container.

Cole Thorsen

p. 905.512.9597 | e. ***@***.*** | w. impulsestudios.ca ( https://impulsestudios.ca )

Sent via Superhuman ( ***@***.*** )
