### ISSUE TITLE
Automated publishing is not working - scheduled for a time in the future but not being published

### ISSUE THREAD

**Issue by cceruti** [mautic/mautic#5287]
What type of report is this:Bug 

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
1. Build a campaign
2. Schedule it to be published sometime in the future
3. Check campaign after it should have been published and see that is has not been published

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
Mautic actually doesn't change the publish state based on the un/publish dates. Make the campaign published and set the un/published dates and the campaign will be published only within that time range.

**Comment by void-gh** [comment]
I know this has been marked as closed; however, I've been trying to resolve the same issue and didn't find an answer until I saw this post. Checking the Mautic manual on [Campaigns](https://mautic.org/docs/en/campaigns/index.html), as well as documentation on [cron jobs](https://mautic.org/docs/en/setup/cron_jobs.html) neither one of them mentions the functional difference between the _Publish_ button, and the _Publish at_ / _Unpublish at_ options.

Since there is confusion, and a lack of documentation, regarding this I would suggest in the Campaign Builder changing the label for the button from _Published_ to _Enabled_.
