### ISSUE TITLE
Add Download Actions - speeds up and improves processes

### ISSUE THREAD

**Issue by dsp76** [mautic/mautic#5307]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | Y
| Enhancement? | 

## Description:

Currently I can add actions to form submits, which is quite useful. I would like to have that for an asset download as well:

- add / remove a tag
- add / remove contact to / from a segment

This would speed up things, as today I need to setup a campaign just for recording that download. Especially when I used a standalone form to provide a download link, there would be no need for a campaign at all initially.

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
