### ISSUE TITLE
Is there a way to see the QUEUE STATUS?

### ISSUE THREAD

**Issue by omert37** [mautic/mautic#5312]
What type of report is this:

| Q  | A
| ---| ---
| Feature request? | Yes
|Enhancement|Yes

## Description:
When I send out a campaign, the system marks it as SENT even though I'm in QUEUE mode. And I know that my QUEUE is currently being processed little by little. Is there a way for me to see the Delivery QUEUE status?

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
