### ISSUE TITLE
Feature: ability to simultaneously move multiple boxes within campaign builder

### ISSUE THREAD

**Issue by rowlandhill** [mautic/mautic#5317]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | NO
| Feature request? | YES
| Enhancement? | YES

## Description:
As a user, I would like the ability to move multiple boxes within the campaign builder simultaneously. 
 From an organization and editing standpoint, moving all the boxes around individually in a large campaign is a time-consuming task when making major edits, or want to clean up the look of the campaign.  Would be a great feature, similar to selecting multiple cells in spreadsheet using shift or command/ctrl and dragging them where I would like to place them.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._ 

@cceruti

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
