### ISSUE TITLE
Adding Current Date/Time to Campaign Conditions

### ISSUE THREAD

**Issue by nickian** [mautic/mautic#5337]
| Q  | A
| ---| ---
| Bug report? | N
| Feature request? | Y
| Enhancement? | Y

## Description:
I woud love to see the current, local date and time added as a condition in campaigns. For example, maybe I want an automated email to send when a form is filled out, and I want it to go out 30 minutes after the form is submitted. However, I don't want this to happen if it's 3 AM. If that were the case, I'd like it to send at a later time (e.g., 7 AM).

Thanks!

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._

**Comment by pjrobertson** [comment]
Agreed that this is a much needed feature. There should be the options for example to use a condition:

<TODAYS DATE>  <is> <10th March 2023>

or similar
