### ISSUE TITLE
Opens as a percentage of actually delivered emails

### ISSUE THREAD

**Issue by corradofiore** [mautic/mautic#5346]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | N
| Feature request? | N 
| Enhancement? | Y

## Description:
Mautic currently shows opens as a percentage of (delivered + bounced).  The rest of the industry, however, calculates opens as a percentage of delivered messages only (thus resulting in slightly higher rates).  I would like to suggest to align to them.

**Comment by dongilbert** [comment]
"The rest of the industry" - Can you give some clarification? Who are you comparing to?

**Comment by npracht** [comment]
@dongilbert & @corradofiore if it includes bounces it is true that it is not a good idea.
Openers are the people who made the action to open the email ---> they have an engagement action.

@dongilbert mailchimp, marketo, hubspot, etc. work like that !

**Comment by ronnieduke** [comment]
+1 - Stats should be based on delivered, not sent. "Delivered" should even be a separate stat (Sent - Bounced/Failed).

**Comment by corradofiore** [comment]
Hi,

some other email marketing services that calculate opens as a % of actually delivered messages:
*  Voxmail.it (quite popular in Italy)
*  Campaign Monitor (https://www.campaignmonitor.com/blog/email-marketing/2007/01/all-about-email-open-rates/)

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
