### ISSUE TITLE
Audit Log incorrect for [Tags] when using API

### ISSUE THREAD

**Issue by LucasFarley** [mautic/mautic#5353]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
When a contact is updated via API with Tag value equal the old value in database, the Mautic is recording a Audit Log incorrectly.

See the picture in attached.
<img width="898" alt="trace" src="https://user-images.githubusercontent.com/22159940/33022712-2c5e0238-cded-11e7-8f7a-280dd637863f.png">

## If a bug:

| Q   | A
| --- | ---
| Mautic version | v2.11.0
| PHP version | PHP Version 5.6.31-1~ubuntu16.04.1+deb.sury.org+1

### Steps to reproduce:
1. Update a contact that has tags by API. The tag in update process must have the same value that exist in Mautic DataBase.

**Comment by dsp76** [comment]
@LucasFarley a question, because I try to find out if I identified another bug: Is "Monitor Service" the name you assigned to the API credentials or the name of the Mautic User where you added the API Key? I get the impression, the log history shows the name of the user instead of the Key name of the service connecting through the API.

**Comment by djmonzyk** [comment]
I get this behavior as well, but when adding or removing tags with campaigns, not the API.

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
