### ISSUE TITLE
feature email builder drag and drop button

### ISSUE THREAD

**Issue by johbuch** [mautic/mautic#5356]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | X
| Enhancement? | 

## Description:
I want to create a new LP or email, I choose a developped theme and go to the builder.
When I drag and drop a button zone, it is always the same (button per default)
<img width="123" alt="capture d ecran 2017-11-17 a 11 30 21" src="https://user-images.githubusercontent.com/31535432/33062144-8a29873c-ce9e-11e7-8c2d-0649bba7d9fd.png">
Even if we set the css style in the theme for the button, this button is inline so he has priority.
<img width="694" alt="capture d ecran 2017-11-17 a 11 30 11" src="https://user-images.githubusercontent.com/31535432/33062206-c7a0dd36-ce9e-11e7-984e-f949c57050ee.png">

# Suggestion
Add a file in the theme that manages the default zone types. Then we can (when coding the theme) change the default code of each zone.

**Comment by dbhurley** [comment]
This is an interesting feature but I'm not sure I understand the value. Show a good use case and I'll reopen 😉

**Comment by npracht** [comment]
Hello @dbhurley !

You have the great ability with mautic to create themes that helps you to create great emails that matches to your company guidelines.
Nevertheless, when you create your theme and then add a new CTA button on the email drag and drop builder, the button style is not following the theme directives but the mautic core button style.

Consequently, it is simply impossible to restyle an button which was not previously planned in the template ---> the drag and drop feature becomes useless.

# Suggestion
With a config file in the theme structure, we could allow theme developers to redefine the standardization of slots (zones) to drag and drop.
That way, instead of a standard mautic button, you could drag and drop a theme styled button and take benefit of the power of drag and drop email UI !

**Comment by Shirkit** [comment]
I vouch for this as well. It can be really simple, like just grabbing from a default style that we preset, it would be already a huge save in time.
