### ISSUE TITLE
Mautic don't sends email to emails with plus[+] on the address

### ISSUE THREAD

**Issue by wpon** [mautic/mautic#5378]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
Mautic don't sends email to emails with plus[+] on the address, for example:
my+email@mycompany.com

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9.1
| PHP version | 5.6.30

### Steps to reproduce:
1. Insert a new user on Mautic list with "+" on email address;
2. Send email to all users;
3. Users with "+" on email address don't receive emails.

### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by Bizcrony** [comment]
Have you set up cron Jobs accordingly

**Comment by wpon** [comment]
@Bizcrony if I understood well your question, it doesn't related. You mean cron Jobs to send?

What I mean is:

Receiving email:
myemail@mycompany.com

Not receiving email:
my+email@mycompany.com

**Comment by micschk** [comment]
I've just verified that a direct mail to an address containing a '+' works correctly on my environment. Could still be an issue with sending to lists, but the examples you gave could indicate the problem is caused by the address itself.

If you're using gmail/Google for your e-mail (I think this also works on MS365), you can create an 'alias' email by using a +, but this only works if you add the '+' after the part before the '@'.

Eg; if your address is wpon@mycompany.com, wpon+test@mycompany.com works, but wp+on@mycompany.com does not.

**Comment by dbhurley** [comment]
Can't replicate.
