### ISSUE TITLE
Send Example problem

### ISSUE THREAD

**Issue by miguelpascual** [mautic/mautic#538]
Hi

I created one email and after saving it I tested it.

two issues:

The first thing I receive is this:

![image](https://cloud.githubusercontent.com/assets/10166840/8108225/7eda81fc-104f-11e5-99aa-0330a0171784.png)

And the second:
It counts my test as one sending. I think it's better that the test doesn't count.
![image](https://cloud.githubusercontent.com/assets/10166840/8108219/76250d7a-104f-11e5-932f-b1fa3d4ecd03.png)

And the email global page shows 

![image](https://cloud.githubusercontent.com/assets/10166840/8108567/8ac3a7f8-1051-11e5-9f92-f8322b6c68c9.png)

This is confusing

**Comment by onlineth** [comment]
I am also experiencing issues with {} like {pagelink=1} not showing up correctly (actually showing {pagelink=1} and not a link to it)

**Comment by alanhartless** [comment]
I'll look into this.

The preview emails don't replace the token holders as there's nothing to replace them with (since it's not going to a specific lead.  We could replace them with a visual placeholder like we do in the editors? Or we could query a random lead I suppose?  What would be the most desired option?

There definitely shouldn't be any tracking going on with those test emails so marking that as a bug to look into.

@onlineth Is your issue also related to preview emails or any email sent out?

Thanks,
Alan
