### ISSUE TITLE
Re-organise feature tab of CRM integration

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#5418]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | x

## Description:
Today, the way that leads and contact are managed does not permit to select where you push/pull leads. Push and pull are often related even if it is a very different action to manage well contact depending on companies preferences.
In some CRM it pushes contacts to CRM contacts and leads, sometimes not, etc.

For a better understanding i'd suggest to reorganize the feature plugin tab as following:
______________
![whatsapp image 2017-11-29 at 09 29 34](https://user-images.githubusercontent.com/14075239/33678565-58318e3a-dabc-11e7-9334-0904f8dce783.jpeg)
______________

@dbhurley & @justinforte what do you think about it?
If you think this is a good idea, i'd be very happy to talk about that with you.

Thanks,

N.

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
