### ISSUE TITLE
Add possibility to import company to leads relations

### ISSUE THREAD

**Issue by RCooLeR** [mautic/mautic#5431]
| Q  | A
| ---| ---
| Feature request? | Yes
| Enhancement? | Yes

## Description:
Add possibility to import company to leads relations (company_lead object)

**Comment by justinfortes** [comment]
@RCooLeR can you expand on this a bit more with a more detailed description and what the outcome you are expecting?

**Comment by RCooLeR** [comment]
We have people/leads who works with few companies.
How to import from csv relations? 
I have 2.5mln leads and 3.5 companies doing that manually impossible.

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
