### ISSUE TITLE
Segment Emails not Sent even though cron runs

### ISSUE THREAD

**Issue by IADDIC** [mautic/mautic#5435]
| Bug report? | 

## Description:
Segment emails do not get sent.  When a new email is created, segment added, and scheduled.  The email never gets sent.  The cron job is executing and the cron log reports 

+---------+--------+----------+
| Channel | # sent | # failed |
+---------+--------+----------+

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.0
| PHP version | 5.6.32

### Steps to reproduce:
1. create email
2. schedule it
3.) attach segment
4.) wait
5.) wait
6.)wait
 
### Log errors: 

no errors logged

**Comment by npracht** [comment]
What is the command you’re using? There are 2 different commands for emails and one is dedicated to segment email.

Envoyé de mon iPhone

**Comment by IADDIC** [comment]
Correct, I have them both.  And because there are so many people with this problem and so many people trying to help each other the list of potential solutions is large and no "official" direction or remedy.

So far I have tried: with mautic:broadcasts:send as the base cron command suffixed with (in various combinations or none at all)

--id=#xx  (with and without the #)
 --channel=Email 
--env=prod 
-- force

deleted file SendChannelBroadcastCommand.php from app/bundles/CoreBundle/Command folder

spent maybe 6 hours trying the various options, creating new emails, adding segments adding contacts to segments, setting crons to fire...and NOTHING is working.  and no error logs...

This is a pretty basic requirement for an email marketing system. The user base is struggling to keep up

**Comment by dbhurley** [comment]
Okay, so looking at the docs I see this:

> Starting with Mautic 2.2.0, it is now possible to use cron to send scheduled broadcasts for channel communications. The current only implementation of this is for segment emails. Instead of requiring a manual send and wait with the browser window open while ajax batches over the send - a command can now be used. The caveat for this is that the emails must be published and must have a published up date - this is to help prevent any unintentional email broadcasts. Just as it was with the manual/ajax process - only contacts who have not already received the specific communication will have it sent to them.

`php /path/to/mautic/app/console mautic:broadcasts:send [--id=ID] [--channel=CHANNEL]`

https://mautic.org/docs/en/setup/cron_jobs.html#send-scheduled-broadcasts-e-g-segment-emails

Based on what you shared I'm wondering if you don't have a *published up* date set. This would prevent the email from sending.

**Comment by IADDIC** [comment]
@dbhurley been there - checked all that first.  the published up date setting strategy has been played with a lot as well.  for example:  I've set the date in the past.  I set it an hour into the future, I leave unpublished date blank, I've set it to a future date....

again, the matrix of possibilities has been large and this has taken a bunch of time before I wrote the bug report.

**Comment by robwent** [comment]
Do you see anything related in the error logs in the app/logs folder or in your server error logs?

**Comment by IADDIC** [comment]
@robwent no, no, no that is what makes this so particularly painful.

**Comment by robwent** [comment]
Without more information, it's pretty hard for anyone to help.

The fact that the table is empty in the cron report makes it look like there's nothing queued up to be sent (Or at least Mautic thinks there's nothing to send).

What type of hosting are you running on?
Do you have SSH access to try and run the commands manually?

**Comment by IADDIC** [comment]
I have already run update commands and the cron commands via command line.  I see I am not the only one with this issue and without more information, it is EXTREMELY frustrating.  Things were working nicely until I upgraded to 2.12 from 2.11.  not a big jump.  And there are no events logged.  My install stalled (like others) and I ran the install process a second time.  It went through but obviously it is not right.  

The only clue I have today over yesterday....I attempted an email on a large segment and things stalled (manually  -- not via cron)  I then and ran a smaller segment (manually - not via cron) and all went well.    So where is the limitation coming from?  For the moment I am reduced to running small batched in small segments...kinda sucks but at least I will eventually get through

**Comment by robwent** [comment]
I found this thread yesterday searching for issues with broadcasts (turned out to be user error on our end) and this is the only report on the problem I have seen. Where are all these other people who are having the same problems?

I understand your frustration, but there won't be any information until someone can replicate the problem. No one will be able to replicate it until there is a clear idea of what is causing it.

So again, what type of hosting do you have Mautic installed on?
Which version of php are you using?
What is your cli version of php (type `php -v` on command line)?
How many people in the segment you are trying to send to?
What was the batch size set to when it stalled?

If something is stalling on a large batch size then it sounds like either a php memory or timeout issue, but even after stalling it should pick up the next time the cron runs again.
If commands work manually but not when run by cron then it sounds like some kind of limitation put in place by the host.

If other people are having the same problem, ask them to come and comment here (With details of their hosting) so we can work out some commonality in your setups that might be causing the problem.

**Comment by a1exe1** [comment]
same issue - broadcast not sending

**Comment by amagdy3** [comment]
Not sure if this is related but I'm getting an error in my error log every time the "mautic:broadcast:send"  Cron command runs:

Cron Command:
7,17,27,37,47,57 * * * * php /var/www/html/comm/app/console mautic:broadcasts:send [--id=ID] [--channel=CHANNEL] >/home/ec2-user/cron_log 2>&1

Error log:
[2018-01-28 08:47:02] mautic.NOTICE: Symfony\Component\Console\Exception\RuntimeException: Too many arguments, expected arguments "command". (uncaught exception) at /var/www/html/comm/vendor/symfony/console/Input/ArgvInput.php line 182 while running console command `mautic:broadcasts:send` [] []

**Comment by robwent** [comment]
@amagdy3 Your problem is your cron command.

The parts in brackets are optional arguments. You need to change them, not copy them verbatim from the docs.

eg, if you want all broadcast emails to be sent then you need to use:

    7,17,27,37,47,57 * * * * php /var/www/html/comm/app/console mautic:broadcasts:send --channel=email

If you just wanted one email to send out then you would use the --id argument with the id of the email that you want to send.

**Comment by amagdy3** [comment]
My bad. Thanks for the heads up @robwent :)

**Comment by BenJackGill** [comment]
Can this be made clearer in the docs?

I'm new to Mautic and thought I was supposed to copy this line from the help docs exactly: 

https://docs.mautic.org/en/setup/cron-jobs
`php /path/to/mautic/app/console mautic:broadcasts:send [--id=ID] [--channel=CHANNEL]`

Setup with these cron jobs is confusing already, and now after lots of searching I'm finding out that I should leave off those ending arguments.
