### ISSUE TITLE
Action triggers to change stage based on contact field value such as date field or tags

### ISSUE THREAD

**Issue by mellsaid** [mautic/mautic#5454]
| Feature request? | 

## Description:
We save customer's birthdays and customer's system renewal anniversary and date field that has the renewal date for customers who use a competing system so we can campaign to them.  We currently do a work around but seems to be process intensive and not really effective as campaigns crons run frequently and they can add up. 

Here is the condition in campaign builder
![image](https://user-images.githubusercontent.com/22168697/33997600-dc7b3ada-e0dc-11e7-90be-23db202d0c58.png)
and here is the campaign:
![image](https://user-images.githubusercontent.com/22168697/33997768-56daf810-e0dd-11e7-8b80-a9bd483920ef.png)

It would be good and makes more sense if we can add these actions triggers to change stage/add to campaign based on date field in the or based on tags contact profile . 

So 
A) if a customer reaches that date, we can add them to a campaign that says happy birthday. 
B)if a customer gets close to the renewal date for their system with a competitor, we would move their stage from with competition to cold lead in order for them to start to get the nurturing email sequences for example. 

This will be more effective and logical as action crons runs less frequent and seem to be less intensive than the campaigns workaround we do.

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
