### ISSUE TITLE
Forms: Add attributes to response messages.

### ISSUE THREAD

**Issue by jaydeesigns** [mautic/mautic#5455]
This is a feature request: Is it possible to add data attributes to response messages? we're building a multi-lingual site and we're using data attributes to store label names in different languages, it would be very useful to store the translated response messages in data attributes as well.

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
