### ISSUE TITLE
Feature Request: Company Segments

### ISSUE THREAD

**Issue by mburamorde** [mautic/mautic#5457]
Hello,

I totally love mautic and the new data privacy novella 2018 in Europe will help the mautic as self hosted version to spread  in Europe ;).

Unfortunately the company management area is very "minimalist". One missing must have thing are segments on company level and not on contact level.

Are there plans for this?

**Comment by dbhurley** [comment]
Yes, the company section within Mautic is definitely in need of improvements.

**Comment by mburamorde** [comment]
Do you have any idea about a timeframe?

**Comment by juicerocket** [comment]
I want to send emails to my entire list that are associated with particular Segments. For example, Brand A is Segment A and Brand B is Segment B -- I want to be able to put all my contacts in both segments, then when I send a newsletter, specify which segment the newsletter is attached to. Then if a contact unsubscribes from a Segment A newsletter, it only unsubscribes them from Segment A, and not Segment B.

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
