### ISSUE TITLE
Configuration of checkbox group condition in Campaign builder is wrong

### ISSUE THREAD

**Issue by XRaccourci** [mautic/mautic#5458]
Type of report : 

| Q  | A
| ---| ---
| Bug report? |  YES
| Feature request? | 
| Enhancement? | 

## Description:

Bug in the configuration of a condition on the values of a form result when the field type is a checkbox group .

Before validating the configuration of the condition, the choice of the value is made by a possible selection list containing the different labels. However the attached value is not the value of the checkbox but its label !

Once we add the condition, when we return to the configuration we end up with a text field (instead of the value select list) and the value is that of the label and not the actual value of the checkbox.

In the normal case, when we select an item in the list, the registered value should be the <select> value and not the <select> label.
Similarly, the configuration should always be a list to respect the good value of the checkbox.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.0
| PHP version | 5.6.30

### Steps to reproduce:
1.  Create a campaign form with a field type checkbox Group. Add multiple values.
2. Create a campaign, select "Campaign forms"
3. Add a condition on "Form field value".
4. Select the previously created form.
5. Set the Field to the Group.
6. Select a value in the list
7. Add the condition
8. Return in the configuration of this condition and notice that the value is the label and that the field is a regular text field rather than a select list.

 
![issue_bug_value_forms_campaigns](https://user-images.githubusercontent.com/32296295/34115291-7d41381c-e415-11e7-84c8-9f84591c5f93.jpg)

### Log errors: 

X

**Comment by XRaccourci** [comment]
I think I have the solution to fix this problem. 
The lists are populated with the labels because of the use of the format "FormFieldHelper::FORMAT_BAR". This is done in ListModel (in LeadBundle, on line 704). If we change this format with "FormFieldHelper::FORMAT_ARRAY", then we have the label in the list attached to the correct value.

What do you think of this ?


File **Mautic\LeadBundle\Model\ListModel** -> Line **704**

_BEFORE CHANGE_ 
                    $properties['list']     = (isset($properties['list'])) ? FormFieldHelper::formatList(
                        FormFieldHelper::FORMAT_BAR,
                        FormFieldHelper::parseList($properties['list'])
                    ) : '';

_AFTER CHANGE_ 
                    $properties['list']     = (isset($properties['list'])) ? FormFieldHelper::formatList(
                        FormFieldHelper::FORMAT_ARRAY,
                        FormFieldHelper::parseList($properties['list'])
                    ) : '';

**Comment by MaraKasubke** [comment]
I still have the same problem with Mautic 3.3.3 ... Is there any kind of solution?

The problem is now, that I need the values 0 or 1 in forms so that the right value is set in the contact. Previously we just populated the form field with the same text in label and value so that the campaign condition was working - as it still takes the label instead of the value. And previously that workaround produced a "YES" in the connected contact field. But now it is set to "No". But if I change the values in the form from the text of the label to "1" then in the contact field it sets correctly to yes - however in the campaign it still takes the label so that the condition renders always untrue as it checks only the label and not the value - so the condition still needs value and label to be the same.
