### ISSUE TITLE
Integration of Google Analytics - should allow "anonymizeIp" option too

### ISSUE THREAD

**Issue by dsp76** [mautic/mautic#5483]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | Y

## Description:
While adding Google Analytics via the ID only is a very comfortable approach, it lacks some flexibility. In EU - at least in Germany - you are asked to use Google Analytics only in an anonymized way. Google provides the "anonymizeIp" flag for that. 

Solution: 
1.) Add a switch to allow to turn on/off this flag
2.) Allow to add the complete Google Analytics tracking script instead of ID only.

more about the implementation:
https://developers.google.com/analytics/devguides/collection/analyticsjs/ip-anonymization

**Comment by kuzmany** [comment]
Lets test: https://github.com/mautic/mautic/pull/5525

**Comment by dsp76** [comment]
@kuzmany Thanks for the speedy development ;) Would love to test. Is this included already in the "alpha release", which I could install via config?

**Comment by kuzmany** [comment]
@dsp76  nope.  Need more tech skills for this. Not recommend for you do this tests. 
Wait for  another developers or Mautic core team.

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._

**Comment by kuzmany** [comment]
Label: Ready to test
