### ISSUE TITLE
Make it possible to not merge two identified contacts

### ISSUE THREAD

**Issue by kumgabor** [mautic/mautic#5495]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? |  Y
| Enhancement? | 

## Description:
Make it possible to not merge two identified contacts.
A possible solution could be to define a unique contact field (email address or other unique identifier) in settings and according to this field one contact can't be automatically merged to another. Another solution could be an additional parameter in the tracking code which says "don't merge an identified contact who used this computer earlier with this identified contact who is using the computer now".
This should work with identified contacts only, and should not affect merging a non-identified contact to an identified one.

This could be a huge improvement for membership sites using Mautic.

The current contact merging method could have legal issues in some countries, especially if one contact is subscribed to some type of communication but the other is not, and after merging, the non-subscribed one will receive e-mails which he has never subscribed to. 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. Let's imagine that you have two identified contacts. The first one logs on to your website, and you tell Mautic who he is, providing the contact's e-mail address (or other unique identifier) with the tracking code.
2. If he leaves the site (logs out) and an another identified contact logs in from the same browser some days later, Mautic will merge these identified two contacts.

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
