### ISSUE TITLE
ErrorHandler.php on line 587

### ISSUE THREAD

**Issue by albertobraschi** [mautic/mautic#5500]
[:error] [pid 14562] [client ::1:46413] PHP Parse error:  syntax error, unexpected '.', expecting '&' or variable (T_VARIABLE) in /var/www/mautic/app/bundles/CoreBundle/ErrorHandler/ErrorHandler.php on line 587

then in file:
        function debug_it($log, ...$context)

I remove the thee dots and work.

**Comment by albertobraschi** [comment]
latest version! 
PHP 5.6.32-1+ubuntu14.04.1+deb.sury.org+2 (cli)

**Comment by dongilbert** [comment]
If you look at the code there, it's using the splat operator that was introduced in PHP 5.6

```
namespace {
    use Mautic\CoreBundle\ErrorHandler\ErrorHandler;

    if (!function_exists('debugIt')) {
        function debug_it($log, ...$context) // <---- Splat Operator
        {
            if ('dev' === MAUTIC_ENV) {
                // Only allowing dev mode just in case uses accidentally left in code
                if (count($context) === 1 && true === $context[0]) {
                    ErrorHandler::logDebugEntry($log, $context, true);
                } else {
                    ErrorHandler::logDebugEntry($log, (empty($context)) ? [] : $context);
                }
            }
        }
    }
}
```

It's possible your CLI php uses PHP 5.6, but your Apache PHP uses an older version. Variadics (splot operators) are supported in PHP since version 5.6, so this shouldn't be an issue if you're using 5.6+, which is the minimum supported version for Mautic.
