### ISSUE TITLE
Break tag <br>  added in visual email editor after

### ISSUE THREAD

**Issue by pcottrell** [mautic/mautic#5514]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  *
| Feature request? | 
| Enhancement? | 

## Description:
When creating an email and adding images to it in the visual editor after you save a <br> break tag is added.  You do not see it till you reload or test the email and then you will see it.  Basically it is adding a <br> tag.  I cannot find a way to turn it off so i am labeling this a bug.

## If a bug:

| Q   | A
| --- | ---
| Mautic version |  v2.1.2.0
| PHP version | 7.1

### Steps to reproduce:
1.  create an email add an image in a table or div
2.  save
3. reopen and see or send test email
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by ojacquet** [comment]
This issue still exists in 2.14.0. When you replace an image from a template a br tag is added. Sometimes even within the img tag, which is strange because it is not consistent.

If you play with adding and removing a link from the image and replacing the image you can even have multiple br tags which completely breaks the design. You can see the tags being added if you inspect element.

I can provide a screen capture if needed. Not sure if this is a Mautic or Froala issue.

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
