### ISSUE TITLE
Skip sending BCC if email address is already in TO field

### ISSUE THREAD

**Issue by denispavliha** [mautic/mautic#5522]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | *
| Enhancement? | 

## Description:
When sending emails, if a recipient is already in the TO: field of an email and at the same time in the BCC: field, don't send it twice but instead skip sending BCC: to that email address since it obviously will receive the email being in TO:. Otherwise, two emails are received by the same recipient.

**Comment by mMuck** [comment]
How do you use the BCC? This is only a small glitch in the very rare case you have the BCC address within the list of senders. Right?

**Comment by denispavliha** [comment]
Yes, it's a rare case, normally not plausible. Yet it cost me about an hour of debugging. :)

Namely, I have a service that automatically generates quotes and sends them using Mautic by uploading a file as an asset through the REST API of Mautic. Of course, I was testing on my email address, and have also prepared the email for production use by having my email address in BCC. After an hour of guessing why the email is sent twice through the REST API (honestly, I thought it was a bug there), I've managed to figure out that I have BCCed myself.

I can agree it's not a big issue whatsoever, but it occurs.

**Comment by mMuck** [comment]
OK - I can understand this (because of the hour of debugging).
But - I never tested this - if you push an email with the same address in TO an BCC to a send service, this will deliver this twice, or? RFC-thing... No issue here IMO. ;-)

**Comment by denispavliha** [comment]
This is what I would have thought, too. But sadly... :)

I'm using Mailgun's SMTP in my Mautic's instance. Maybe I can take a look in Mailgun's logs to see if Mautic sends each email separately (that would actually explain it).

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
