### ISSUE TITLE
Option to not overwrite data on merged records on import.

### ISSUE THREAD

**Issue by toddviau** [mautic/mautic#5543]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | *
| Enhancement? | 

## Description:
Mautic should not overwrite data in a contact record while merging during the import process. If the field is blank, it's ok to update it with the imported data, but if the field contains data, then leave the original contents and skip the imported data.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12
| PHP version | 5.6

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by alanhartless** [comment]
If we made this possible, it would need to be an option. A lot of Mautic users use the import feature to mass update data.

**Comment by toddviau** [comment]
An option would be fine. We would like to keep the list source data for ROI reports.

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
