### ISSUE TITLE
CRON job error

### ISSUE THREAD

**Issue by wderuijter** [mautic/mautic#556]
I'm getting this error using the cron to send emails, the rest of crons are working fine:

[Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]
You have requested a non-existent service "swiftmailer.transport.real".

mautic:send:emails [--message-limit[="..."]] [--time-limit[="..."]] [--do-not-clear] [--recover-timeout[="..."]] [--clear-timeout[="..."]]

**Comment by jhrocha** [comment]
I have the same problem :(

**Comment by alanhartless** [comment]
I've only seen that error happen when you don't actually need the email cron job because the system is configured to send email immediately.  A catch was added in https://github.com/mautic/mautic/pull/532 to cleanly exit the script rather than allowing the error to be thrown if the system is not configured to queue email.

Thanks!
Alan
