### ISSUE TITLE
Changing domain name breaks form submission

### ISSUE THREAD

**Issue by letharion** [mautic/mautic#5562]
What type of report is this:
Bug report? Perhaps.

## Description:
A mautic instance is setup up to respond on `example.com`. At some point the setup is altered so mautic is now responding on `example.org` instead, and `example.com` _ceases to be used_.

Later someone notices that form submissions aren't working.

It then turns out that the forms generated by mautic are stored as HTML in the DB, with `<form action="https://example.com/..."` which means that the forms continue to send their results to the old domain, which now doesn't work. (In my case there was no valid cert anymore on the old domain, so the browser just refused to establish a HTTP connection).

The solution was simply to re-save the forms and their actions were regenerated.

I don't know if it's a bug, or if any update is required really. Perhaps it's enough for this issue to exist for others to find. One possibility would be for the forms to be regenerated when the cache was cleared, which doesn't appear to be the case now.

**Comment by dbhurley** [comment]
Forced cache-clearing and regeneration of the form HTML needs to occur whenever the domain name is changed in configuration. 


| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

| Q   | A
| --- | ---
| Mautic version | 2.12.1
| PHP version | 6.x

### Steps to reproduce:
1. Create a form
2. Change the domain name in the configuration
3. Attempt to submit the form
4. Notice form submission unsuccessful due to wrong form action
