### ISSUE TITLE
Campaign with multiple condition form field value (based on select multiple) doesn't work 

### ISSUE THREAD

**Issue by tpilet** [mautic/mautic#5570]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | YES
| Feature request? | NO
| Enhancement? | NO

## Description:
The more details the better...

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.1
| PHP version | 7.0.11

### Steps to reproduce:
1. Create a campaign form with a custom field
<img width="772" alt="capture d ecran 2018-01-15 a 08 42 35" src="https://user-images.githubusercontent.com/20974155/34932080-cf6db35a-f9d1-11e7-8e90-3dd84289b868.png">

<img width="621" alt="capture d ecran 2018-01-15 a 08 42 49" src="https://user-images.githubusercontent.com/20974155/34932084-d498629e-f9d1-11e7-9ed5-9c54f0bc36da.png">

2. Make 3 emails with title Velo1, Velo2, Velo 3

<img width="1035" alt="capture d ecran 2018-01-15 a 09 00 56" src="https://user-images.githubusercontent.com/20974155/34932325-aef7a4fe-f9d2-11e7-92e0-7c17a154c6a2.png">
<img width="1042" alt="capture d ecran 2018-01-15 a 09 01 09" src="https://user-images.githubusercontent.com/20974155/34932331-b32ba2d2-f9d2-11e7-944f-bc86119dda40.png">

3. Make a campaign with the the form and  make a condition
<img width="967" alt="capture d ecran 2018-01-15 a 08 58 17" src="https://user-images.githubusercontent.com/20974155/34932219-4fd3c818-f9d2-11e7-9b2c-2338840e6d8f.png">
<img width="618" alt="capture d ecran 2018-01-15 a 08 59 05" src="https://user-images.githubusercontent.com/20974155/34932247-6797715c-f9d2-11e7-9d5f-b2c5c51bf797.png">

<img width="631" alt="capture d ecran 2018-01-15 a 08 59 17" src="https://user-images.githubusercontent.com/20974155/34932249-6af71b40-f9d2-11e7-8ad5-b4c2a846679d.png">

4. Fill the form. 

<img width="660" alt="capture d ecran 2018-01-15 a 09 02 47" src="https://user-images.githubusercontent.com/20974155/34932379-e3a0a08e-f9d2-11e7-8885-2410cee1cdf4.png">

5. The campaign is launch but the results are wrong

<img width="593" alt="capture d ecran 2018-01-15 a 09 03 46" src="https://user-images.githubusercontent.com/20974155/34932411-09a8a07e-f9d3-11e7-9be4-e7530e188ec5.png">

 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by XRaccourci** [comment]
I'd like to fix the bug regarding the decision filter on multiselect form fields.

Apparently, the "LIKE" operator that is used is not suited for this case, because
the values are on the same field, just separated by commas.
I am suggesting the following code changes:
- In Mautic/FormBundle/Entity/SubmissionRepository, in the compareValue method:
  add '%' to the start and end of the lookup value.
I think there can be a problem in the campaign builder if we don't constrain the
values to only those available in the form. In the case of a multiselect list,
even though the first selection involves a selection in a dropdown, that value
is editable. As an example, if you set the field value to "Bike" contains "bike",
and the possible values in the form are "red_bike" and "green_bike", then the
condition would be met no matter what the value is.

I propose this change in the file **Mautic/FormBundle/Entity/SubmissionRepository** in function **compareValue** line **443** before create the query builder =

 if($operatorExpr === "like" || $operatorExpr === "notLike"){
            $value = "%".$value."%";
 }

**Comment by escopecz** [comment]
Should be fixed by https://github.com/mautic/mautic/pull/5551. Could you test?

**Comment by XRaccourci** [comment]
After testing the pull request #5551, I am afraid that the problem is not solved.
When a form is created with a field of type "checkbox group" and when a campaign
is linked to this form, it fails.
The condition on the form result values for the field of type "checkbox group"
does not work, whether the operator is "equals" or "contains".
The way to fix it that I underscored earlier in the previous post seems ok to me
and is easy to apply, and it does give correct results.
![test-report-pr-5551](https://user-images.githubusercontent.com/32296295/35379752-6d1dfac8-01b7-11e8-91c1-00f1077e469b.jpg)

**Comment by escopecz** [comment]
@XRaccourci please test it on 2.12.2-beta. It worked for me.

**Comment by seojcarlos** [comment]
How is the possible solution to this error?
