### ISSUE TITLE
activity log: a history of what tasks Mautic recently performed

### ISSUE THREAD

**Issue by 4evermaat** [mautic/mautic#5583]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | No
| Feature request? | Yes 
| Enhancement? | Yes

## Description:
Would like an "activity log" that could post a log of all tasks/activity that Mautic completes.
Currently you only log errors.  But a separate log that logs successful transactions would be great.  I was thinking for the last 48 hours, but perhaps a more practical implementation is to limit the size of the log to xxxx lines or xx MB, then delete old entries that exceed the limits.

There could also be some tweaks to determine the "verbosity" or what to include/exclude.

Yes, technically I can create a cron job log with each cron job and use `>>` vs `>` to self-generate a log file that appends, but:

1. - this only applies to cron jobs, does not include other tasks done immediately or requested during mautic web admin panel
2. -  can control the formatting and verbosity when the admin is allowed to generate its own log

Given the amount of tasks that mautic is responsible for, I'm kind of surprised regular logging isn't already available.  Removes guesswork and having to commit to memory which tasks were performed.
## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.1
| PHP version | 7.0.27

**Comment by YosuCadilla** [comment]
Activity log would be great to have.

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
