### ISSUE TITLE
Implement a "to inline css" solution for email templates

### ISSUE THREAD

**Issue by ChrisRAoW** [mautic/mautic#5589]
What type of report is this:

| Q  | A
| Bug report? |  N
| Feature request? |  Y
| Enhancement? | Y

## Description:
In mailchimp stylesheets in the head of the template are automatically converted to inline css. This definitely improves the display of the emails across the different mail clients. Besides of that it improves the maintainability of the templates. To my knowledge mautic doesn't have something like this. It think it's worth implementing it, maybe as an option on a theme / template. What do you think?

There is a github library that can be easily used to accomplish this:
https://github.com/jonkemp/inline-css

**Comment by stephenvoisey** [comment]
This would definitely be nice and from a user perspective, much easier to manage. Technically however you could create a template right now that has inline-css automatically. I think Foundation Email's build process will do this, but it is easy enough to run through a third party like inline-css to create the code required. Definitely _not_ a fun job making HTML Email templates.

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
