### ISSUE TITLE
SugarCRM - Companies Sync problems

### ISSUE THREAD

**Issue by Dcoutelle** [mautic/mautic#5617]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
Companies created in SugarCRM are pulled empty in Mautic and empty line created multiple times

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.1
| PHP version | 7.0.4

### Steps to reproduce:

1. Make sure a SugarCRM 6.x integration is properly setup and syncing
2. Create a company in Sugar with all needed fields.
3. Wait 2min
4. Trigger the fetchleads console/cron job php app/console mautic:integration:fetchleads --integration=Sugarcrm --time-interval="5 minute"
5. Wait for the sync to complete and then check the corresponding record in the Mautic UI. Observe that empty company is created

 
### Log errors: 
On the second console run, you have error below :  
`PHP Notice:  Undefined offset: 1 in /app/bundles/LeadBundle/Helper/IdentifyCompanyHelper.php on line 132`

**Comment by stancel** [comment]
Hi @Dcoutelle 

We experienced this same issue initially. In an earlier version of Mautic. The temporary workaround for us was to make sure to put something in the email address field of the SugarCRM/SuiteCRM Account, then wait for the Mautic sync and it will appear. We then just did a mass update of the email address field and modified timestamps (Accounts and Contacts) in our SugarCRM database which worked. That then brought us to the next issue which was #5103 . After several days I finally debugged it and found the root cause (of I believe both issues). Please see this pull request here (https://github.com/mautic/mautic/pull/5610) and let us know if it resolves your issue.

**Comment by stancel** [comment]
The latest #5610 pull request commits now include the code fix from #5637
