### ISSUE TITLE
Feature Request: Import user activity from other marketing service

### ISSUE THREAD

**Issue by LEAP-nishit** [mautic/mautic#5659]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  N
| Feature request? | Y 
| Enhancement? |  N

## Description:
We are users of Act-On and have been using Mautic for a while. We would like to import past user activity from Act-On into Mautic. The data and relation are JSON responses obtained from Act-On's api. 

We are happy to sponsor any development in this regard.

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
