### ISSUE TITLE
mautic:integration:fetchleads slows down for large imports

### ISSUE THREAD

**Issue by YosuCadilla** [mautic/mautic#5704]
| Bug report? | 
| Feature request? | 
| Enhancement? | 

NOT SURE

## Description:
The mautic:integration:fetchleads --fetch-all command slows down very quickly, to a point where adding 1 new contact takes 1 second (yes 1 second per every new contact).

A new import with an empty database runs very quickly (at 100 contacts/second or more) but this speed decays really fast and after 100K contacts have been added the speed is 100 times slower.

And the speed keeps deteriorating the more data is present on the Mautic database, for example, right now I am working on an import of 1,3 million leads from SF to Mautic, my calculations say that at the current slow down rates it will take 5 months to import all the leads.

I understand MySQL inserts are slower the more data in the database, but in my experience 100 times slower would indicate the code needs optimization/improvement.

I suspect the inserts are done one row at a time, which is perfectly fine for small updates, but when the --fetch-all modifier is used, the intent is obviously to fetch a large amount of records, in which case grouping the inserts instead of doing inserts one by one is a best practice recommended by MySQL, MariaDB, Percona, etc.

## If a bug:
| Mautic version |  2.12.1 
| PHP version | 7.0.25
Database: MariaDB  10.0.33
OS Ubuntu 16.04
Platform AWS-EC2 m4.xlarge

### Steps to reproduce:
1.  Import a large amount (100K or more ) of leads or contacts from salesforce using the SF plugin and using the command: mautic:integration:fetchleads --integration=Salesforce --fetch-all

If you use an empty database you will see the leads loading really fast, wait until you have at least 20K loaded into your DB to start noticing the delayed times, after 50K it's really obvious, after 100K it's 100 times slower than in the beginning. 
 
### Log errors: 

NONE

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._

**Comment by pdxrlk** [comment]
This is a but, not a feature request. I'm seeing the exact same behavior, rendering Mautic imports useless.
