### ISSUE TITLE
Bulk SMS using AWS SNS to send (text messages) besides Twilio.

### ISSUE THREAD

**Issue by BognarB** [mautic/mautic#5708]
Description: Guys, we'd like to use AWS SNS to send SMS (text messages) besides Twilio.

**Comment by npracht** [comment]
Label: Feature Request

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._

**Comment by vinodhdoniv** [comment]
yes i also need AWS sns feature to send sms.

**Comment by JefferyReidKnowde** [comment]
Yes. We need this feature as well. Thx

**Comment by indorock** [comment]
Is there any roadmap regarding adding support for AWS SNS as sms transport, or alternatively an existing plugin?

**Comment by RCheesley** [comment]
The appropriate place for these discussions is https://forum.mautic.org - not here on a very old closed issue.

**Comment by indorock** [comment]
> The appropriate place for these discussions is https://forum.mautic.org - not here on a very old closed issue.

Thanks. I also found [this](https://forum.mautic.org/t/using-amazon-sns-for-mobile-push-notifications/12588) but it's just as unhelpful as this closed issue is.

**Comment by ksaltik** [comment]
They don't give any sh... to us. And this is why mautic is not so popular. Unless AWS SNS integration I will not use it

**Comment by ksaltik** [comment]
Without listening people they will not click the sponsor button below

**Comment by RCheesley** [comment]
@ksaltik please be mindful of our [Code of Conduct](https://contribute.mautic.org/policies/code-of-conduct) when you are posting on our GitHub repository. 

SNS will not be something we support in Core (we are in the process of slimming down Mautic's core and moving things out to optional plugins) but there are already a lot of other third party plugins that you can access, and if you desperately need SNS for sending text messages I am sure that either someone has already done that, or would be willing to create a plugin for it. Make a post on our Commercial forum category if you want someone to create that for you.

The appropriate place for this discussion is https://forum.mautic.org, not here on a closed issue from 2018 as has already been quite clearly communicated.
