### ISSUE TITLE
[Feature request] Set default sort order for tables

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#5717]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | x
| Enhancement? | 

## Description:
When using Mautic with very large data sets and a large amount of emails, campaigns etc it is time consuming and a waste of resources to have to manually sort data every time to your desired layout.

It would be good if we could somehow offer the ability for a sort preference to be remembered - for example if I always want the emails layout to sort by the highest ID first (e.g. show me the most recently created email at the top of the stack) then I should not have to re-apply this sort order every time I log back in.

Ideally this could be set somewhere in my profile as a user, based on the fields available? Or have some kind of default option to always sort all data by whatever I choose as a default.

### Steps to reproduce:
1. Go to your Emails view, and sort so that the highest ID is at the top of the stack
2. Log out
3. Log back in, and the sort order has been lost.  You have to re-sort. Every single time you log in!

**Comment by npracht** [comment]
Label: Feature Request

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
