### ISSUE TITLE
Update needed on GoTo plugin before 14th August

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#5736]
| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | 
| Enhancement? | 

## Description:

> Dear LogMeIn GoTo Developer,
> 
> Thank you for using the LogMeIn GoTo Developer Center. We want to make sure you are aware of important changes that will impact use of the Center and APIs. Please note that your action is required.
> 
> To improve security for our API program, we are going to start to enforce a strict OAuth 2.0 authentication protocol.
> 
> This change in authentication protocol is available now, however, the old protocol will also remain in place until August 14, 2018 to give you time to test and update your code to use the new authentication services available under h‌ttps://api.getgo.com/oauth/v2.
> 
> These changes affect the following APIs: GoToMeeting APIs, GoToWebinar APIs, GoToTraining APIs, GoToAssist APIs, GoToAssist SeeIt APIs and related Administrative APIs. GoToAssist Corporate APIs are not impacted by this change.
> 
> Please review the OAuth Migration Guide (http://go.logmeininc.com/JG1QAO0rqF04Ymu3Hm006r0) for details. Please direct any questions to developer-support@logmein.com.
> 
> Our number one priority continues to be delivering great service and a best-in-class experience to you, our valued customer. We are here to help should you have any questions!
> 
> Thank you,
> 
> The LogMeIn GoTo Developer team

**Comment by npracht** [comment]
Label: Bug

**Comment by sfahrenkrog** [comment]
At the moment the goto webinar plugin is no longer working. After we activated the live oauth keys, no registration for webinars was possible. 

I think the problem is this: 

OAuth Version 1 Shutdown
https://status-goto-developer.logmeininc.com/

Quote: 
3) Starting February 1st, 2019, newly registered GoTo Developer Center apps will not be able to use the legacy authentication endpoints (h://api.getgo.com/oauth).

For existing keys: 
or existing GoTo Developer Center apps, there is a limited extension until October 1st. Please expect issued tokens to expire early if they are not actively used for API traffic. Please watch the status page for updated details of this limitation.

**Comment by wittwerch** [comment]
Stumbled across that, the plugin is basically broken.
@npracht do you know whether somebody is already working on that?

**Comment by npracht** [comment]
As far as i know, no.

**Comment by npracht** [comment]
@sfahrenkrog @wittwerch can you test the related PR ? :)

**Comment by sfahrenkrog** [comment]
@npracht Will do my best to test it. I contacted our client and waiting for a good time to test it with him

**Comment by corycast** [comment]
Hello @npracht @sfahrenkrog we are experiencing the same issue.  The mautic plugin seems to be operating on OAuthv1 and Go2Web now requires OAuthv2?

Has this bug been fixed?

Thanks

**Comment by sfahrenkrog** [comment]
@corycast  Yes. In Mautic 2.15.2

**Comment by corycast** [comment]
@sfahrenkrog Thanks
