### ISSUE TITLE
Fullcontact plugin - not storing social profiles

### ISSUE THREAD

**Issue by TiagoGouvea** [mautic/mautic#5739]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | 
| Enhancement? | 

## Description:
After setup fullcontact plugin, and request to get a contact data over full contact, the contact get updated with name and city, but not their social network links.
Getting the same contact on fullcontact api directly, it return the social profiles.
I tried with five contacts with same condition. The FullContact API return me the contact with social profile links, but, when Mautic try to get, it don't store the social profiles.

## If a bug:

| Q   | A
| --- | ---
| Mautic version |  2.11.0
| PHP version | 5.6.3

### Steps to reproduce:
1. Integrate full contact api
2. Get some contact data over full contact, clicking on "Lookup usign full contact"
3. If the contact was updated, call the full contact api on terminal (outside mautic)
4. Check if full contact returns the social profiles
5. Verify, that API return that data, but mautic don't save it on contact

**Comment by ZipoKing** [comment]
Hi @TiagoGouvea - I've made fresh installation of Mautic and checked with my own email address - all social profiles are loading. I will be happy to make some fixes on that plugin but for now I don't see any issues.

**Comment by bitoutshop** [comment]
Sorry I have a question relating to this Plugin, I cant get it to work at all. am getting error
![image](https://user-images.githubusercontent.com/36680933/52450211-31101a00-2b8e-11e9-8d57-910cd94790d9.png)

My Callback URL just shows 
![image](https://user-images.githubusercontent.com/36680933/52450230-45541700-2b8e-11e9-8268-7b0fe9d79b4e.png)

**Comment by IADDIC** [comment]
@bitoutshop were you ever able to resolve this?  I have the same issue and can't find a resolution.  Thanks, Rich

**Comment by IADDIC** [comment]
@ZipoKing - Are you the author of the Fullcontact plugin for Mautic.  I am experiencing the same issue as bitoutshop and I have not been able to find or develop a solution.  Can you help?

**Comment by ZipoKing** [comment]
@IADDIC I am not but I have experience with both platforms

**Comment by IADDIC** [comment]
@ZipoKing Thank you for replying.  Do you currently have FullContact Integration with Mautic working.  And - have you seen the error message noted by @bitoutshop?  I have the exact same error and would like to get this running.  I am not a programmer but  can edit code when directed, and dig into things to do checks.  Would you be willing to help me get this running?

**Comment by bennywaters** [comment]
Did anyone end up getting this to work??

**Comment by IADDIC** [comment]
@bennywaters I have not and nobody responds here or on slack.  I don't know if that's because there are more pressing issues or interest in getting this plugin to work is that low.  Either way, if you happen to find a solution or hear from someone on how to fix it, please let me know. I'll do the same by replying back here.  Sorry and good luck.  Rich

**Comment by bennywaters** [comment]
@IADDIC Thank you. I am busy testing all sorts of ways to combat this. Not sure if its a permissions issue, a server issue, a mod_security issue or a cors issue caused by my wordfence firewall in Wordpress. I am trying all options.

**Comment by ericseguin** [comment]
Same issue here. Fullcontact says they can't help me because it's not their plugin, and recommend using zapier instead. I'd rather not have an extra step in between and pay for every zap!.
I have mautic installed on an Amazon AWS instance and i'm getting the same message about it not being a publicly accessible URL. If I navigate to that URL it doesn't even exist, so I don't know what i'm missing.  I showed this error to my developer friend, and he said the URL should be https://<domain here>/plugins/integrations/authstatus/fullcontact
Manually going to that url shows a blank page with a button, so I assume it's correct, but the plugin set up screen doesn't allow you to change the current URL that's shown.

**Comment by ericseguin** [comment]
Sorry the URL should be https://domain.com/plugins/integrations/authstatus/fullcontact

Replace domain with your own.
