### ISSUE TITLE
Categorize/group lead points

### ISSUE THREAD

**Issue by ronnieduke** [mautic/mautic#581]
In addition to the global lead points, having the ability to have multiple lead point fields would be helpful for companies that have different types of product or service offerings. That way if leads land on specific pages of a certain product for example, you could increase the points for that product line. Then, when a lead hits MQL, the sales rep can easily see what the lead's product interest score is and plan accordingly.

**Comment by jakemrktr** [comment]
Yes, I feel that this feature would be very important for my company.

**Comment by fmenossi** [comment]
it would be a great feature. big platforms like marketo have this kind of stuff;

**Comment by escopecz** [comment]
Quick fix for multiple lead points could be adding leads to different Smart Lists on their actions instead of points. For example 

- Product A - visitor
- Product A - learner
- Product A - subscriber
- Product A - whatever
- Product B - visitor
- Product B - learner
- Product B - subscriber
- Product B - whatever

I actually like this segmentation better that points. It tells me more information and I can work with each list differently.

**Comment by superedo73** [comment]
I think this is an essential/key feature, in order to compete with other platforms!

I'd like to use a single installation for multiple products/campaigns not related between them.
Despite this, you will have a better representation of lead behavior about different product/lines (and therefore arrange specific cross-product actions).

At the present, the workaround suggested by escopecz is not suited to our needs (too many logic / actions involved) where leads can have a wide range of points assigned. Maybe it's ok for small/discrete workflows.

**Comment by zapur1** [comment]
A thought to add to this is with tagging coming in, the points could be linked to tags. For instance, two different ways to approach it.

1. When a tag is first added it starts at 0 and the number of points can be increased without limit, you could then have triggers off of when a threshold as been reached.

2. A tag starts at 0% or 100%, when another tag is added it spreads the weighting (50%,50%) or adds it with 0% initially. When you increase the percentage of a tag the others are reduced so they all total to 100%, when it comes to a action a scaling factor can be applied so one action has a precedence over another. While it would be complicated it would mean that if you categorised your sites pages you could then have a action that adds the tags and be able to see at a glance the leads main tagged based activities..... It would complicate it though

**Comment by that0n3guy** [comment]
@zapur1 If we had flexible points, you could do the tag thing above w/o specifically tying points to tags.  Example: Tagging leadA causes 5 points to be added to a contact.

I think you just need to tie point categories (or create another "category" like "point types") to points.  

This wouldn't take away from the leads global points.  Any points added to the user in a specific category would still add to the total.

**Comment by superedo73** [comment]
I agree with the absolute number of points bound to a tag.
This allows to manage properly campaigns related to unrelated products.

The percentage solutions, on the other way, seems best suited for globally categorize a lead (is he an A guy vs a B guy?)  aiming to compare the weight of the different tags - actually this is not my need as I'm trying to manage completely different points.

Es: the lead A has 25 "product A" points and 129 "product B" points and 3421 "service C" points

Enrico

**Comment by npracht** [comment]
Hi,

This feature is key.
The categories we have the opportunity to attached to each scoring action could be the solution.
* You have a sum of point for each category
* You can trigger depending on the sum of point of a defined category
Or at least something similar.

N.

**Comment by npracht** [comment]
Also,

It would be great to be able to score depending on a value in a leadfield.
Then we can score activity + lead profile (eg: my target is CTO, if CTO in Title field --> +50pts)

N.

**Comment by escopecz** [comment]
@npracht lead and form field value campaign conditions will be available in 1.2.1 (https://github.com/mautic/mautic/pull/906)

**Comment by npracht** [comment]
Hi John @escopecz,

Great. But it would be also great to manage that in the scoring section as standard rules.
I personally always prefer to add standard scoring rules (applied any time) than adding special rules into a campaign.
That's better to have a global view of the scoring settings.

What do you think ?

N.

**Comment by escopecz** [comment]
Yep, I agree.

**Comment by viniciuscastro** [comment]
Hi, I'm new on Github, I do not know it very well.

I believe multiple points is a feature key to scoring leads for these reasons:

I use the scoring lead looking for two points "activity" and "lead profile". 
For example, a marketing agency:

LEAD A
Industry: Technology
Position: Director
Number of downloads: 01
Points: 50 (lead profile)

LEAD B
Industry: Retail
Position: internship
Number of downoads 25
Points: 50 (Lead activities)

The two have the same points, but only the LEAD A is interesting for my sales team, because of his profile. If I have two notes can verify this very easy way and my lead scoring will be much better.

What do you think?

PS: sorry my english haha.

**Comment by wucherpfennig** [comment]
same here. company with multiple products / services... as of now it is quite hard to distinguish good and bad leads.

**Comment by hirokii** [comment]
Am interested in this feature. Is there any plan of this feature to be developed?

**Comment by mmcduffie1** [comment]
Has this feature made it to the drawing board yet?

**Comment by YannickBiet** [comment]
+1 here, we definitively need this regarding competitors like Netresults for example....

**Comment by seanschroeder** [comment]
+1!

**Comment by YannickBiet** [comment]
As it seems this FR is in standby since June 2015, I began to write specifications for a first approach as I need it in a current project.

Please feel free to comment in order to have something clear and ready to answer standard and classical needs. I hope that this first approach will be good for most use! 

I think we will begin the dev in one or two weeks

[Mautic-MutlipleScoring.pdf](https://github.com/mautic/mautic/files/1104746/Mautic-MutlipleScoring.pdf)

@npracht Normal, I am looking forward your feedbacks.

**Comment by ronnieduke** [comment]
@YannickBiet - read through your spec this morning and it looks exactly like what I was looking for back in 2015 ;-)

Thank you for putting this together and I look forward to seeing the PR!

**Comment by YannickBiet** [comment]
@escopecz 

Hi John,
could you please add a WIP tag on this one, we have finished to develop the feature at 90% and we are in the testing stage right now. We will then pull the code to communauty right I set my approval on the feature :)

(i will the contact you in order to be sure on all documentation and steps to do in order to submit this properly as this is quite a large feature release besides the traditionnal small bug fixes we send)

Regards

**Comment by npracht** [comment]
@YannickBiet the best approach that mautic team is recommending is hat you make your PR right now with WIP in the title of the PR.
Then the community knows that someone is already working on it, we can test and comment you PR :)

This is how they prefer working :)

**Comment by YannickBiet** [comment]
Many Thanks @npracht  for sharing with me the process. 

I am currently still running the final tests here but this should be done until tomorrow

Then I asked the team to send the WIP PR to community.

I think we will have multiple feedbacks to fixes in order to have the PR accepted (for example how we need to document the feature, the code to insert for versions updates (SQL schema update) vs fresh installs...

It will be our first big feature commitment so please be patient and many thanks in advance for the community help as we are planning to be more and more present here !

**Comment by npracht** [comment]
@YannickBiet concerning the documentation i don't know what you think you have to do, it is very easy by forking github.com/mautic/documentation, add your modification and then PR.
I think you should modify the following files of the documentation (in EN and FR folders 😄 ) :
* Campaign event, add point action description: https://github.com/mautic/documentation/blob/master/fr/campaigns/campaign_events.md
* Contact overview: https://github.com/mautic/documentation/blob/master/fr/contacts/contact_overview.md
* Form action: https://github.com/mautic/documentation/blob/master/fr/forms/manage_forms.md
* Point readme (maybe adding a point_category.md file?): https://github.com/mautic/documentation/tree/master/fr/points

If you need help to do so, i'd be very happy to help.
_____

Concerning the PR for the code, you can PR now and add commit over it later on.. As you like, as i told you, mautic proceeds like that, they prefer to start by PR and then push commits.

Best,

N.

**Comment by YannickBiet** [comment]
@npracht I was refering maybe to documentation for DEV and any other requirments other than Doc : Unit tests, schema update, ...

As I mentioned my team has instruction to publish the code asap I gave the first internal tests "green light" (we had few last bugs with basic clone/delete features this morning)

**Comment by rodrigocvb** [comment]
I wish I could add 1 to a number custom field each time a lead requests a trial of one of my products (we have more than one). So far I can only increment points. It would be valuable for several other use too.

**Comment by YannickBiet** [comment]
Hi Rodrigo with our PR to come, you will be able to create a score category "trial download" (not a custom field) in order to add 1 point when the contact submit the form (please note you can't use Points actions for now as they are only triggered once per contact like campaigns, this is another feature request)

**Comment by YannickBiet** [comment]
Note to community : i asked our team to send the PR no latter than this week so it should be available shortly

**Comment by RCheesley** [comment]
Given that the PR for this has been closed since January, am going to close down this issue. If somebody wants to pick up the work that was done previously they can review the PR #4670 or implement via a plugin.

**Comment by patrykgruszka** [comment]
For all of you who are interested in this topic - I've prepared a similar feature for Mautic 5 and it's ready for testing: https://github.com/mautic/mautic/pull/11891
