### ISSUE TITLE
Sparse mail template layout problem in Outlook and Windows Mail

### ISSUE THREAD

**Issue by dsp76** [mautic/mautic#5837]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? |N 
| Enhancement? | N

## Description:

The second text section of Sparse Mail template is a bit wider than the rest of the mail. Does look like a bug, not like design ;)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.2
| PHP version | 7.0

### Steps to reproduce:
1. Create and send a mail with sparse template.
2. View it with Outlook 2016 and or Windows Mail.
![inked2018-03-20_15-10-17_li](https://user-images.githubusercontent.com/1241376/37659973-9f0a9824-2c51-11e8-9ed3-2ca0f6df05f5.jpg)

**Comment by Gambert** [comment]
I had this issue as well, it seems all that is needed to fix this is to change **left and right padding** of the table cell containing image, from 60px to 55px (makes sense I guess since image is 440px, plus 55px*2, equals the expected total max width of 550px). I.e. to change:<br>
`<td align="center" class="shrinker" style="padding: 0 60px; text-align: left;" valign="top"><img width="440" height="243" ...></td>`
<br>
To:
<br>
`<td align="center" class="shrinker" style="padding: 0 55px; text-align: left;" valign="top"><img width="440" height="243" ...></td>`

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by dsp76** [comment]
yes, its still the case
![image](https://user-images.githubusercontent.com/1241376/88484293-dcbd4d80-cf6d-11ea-95b7-ca609da3e373.png)

**Comment by RCheesley** [comment]
Great, thanks for checking! Should hopefully be a fairly quick fix in the theme CSS!
