### ISSUE TITLE
When using SES as Service to send mail through, the test connection button spins infinitely.

### ISSUE THREAD

**Issue by johnlmccurdy** [mautic/mautic#5873]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | 
| Enhancement? | 

## Description:
As per the title, when I am trying to set up Amazon Ses as the 'Service to send mail through' I click the test connection button and it spins inifinitely. 

- We host on siteground. 
- We have verified the domain for sending with Amazon, 
- We have verified the emails for sending with Amazon, 
- I have applied to amazon to increase the limit and move us out of the sandbox
- I have checked which port works with site ground and they have said 465
- We have set up the cron jobs already.

I have seen this problem before on this git and it was to do with a get call() error which was replaced with get method () (I think?) This from memory was V2.6.

Any help would be appreciated.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.2
| PHP version | 7.0.28

### Steps to reproduce:
1. Steps are as above.
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by TiagoGouvea** [comment]
When it try to resolve the aws smtp server, some time (most of time) it cannot complete the request, because the dns each time return a new IP. 

Asking on siteground support I got:

"The reason is that the host name that you provided uses many IPs. In our system port 25 is closed for outgoing connections by default for security reasons. We could only open it for certain IPs. And since we do not know the full range of their IPs, we cannot whitelist them all. If you manage to get the full list from them, we could do it." 

In fact, the send mail get a timeout, and the ajax request cannot refresh it.

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
