### ISSUE TITLE
Console command "mautic:email:fetch" hangs

### ISSUE THREAD

**Issue by afonseca08** [mautic/mautic#6195]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
In the process of configuring cron jobs I ran the following command in the console:
`[~/www/mautic]# php app/console mautic:email:fetch`

This command does not return, it just hangs. I checked the logs and no errors were reported. 

I have confirmed my settings in Email Settings, Monitored Inbox Settings are configured correctly and verified "Test connection and fetch folders" displays a "Success!" message.

I'm not sure how to troubleshoot beyond this.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.13.1
| PHP version | 5.6.33

### Steps to reproduce:
1. Open terminal window and navigate to Mautic directory
2. Enter the command, `php app/console mautic:email:fetch`
3. Observe the command does not return and just hangs
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._ 

No errors were reported in the logs.

**Comment by nemesis82x** [comment]
Hi,
I had the same problem and I solved by emptying the imap inbox folder.
Try and let me known

**Comment by arvage** [comment]
I have the same problem. we are using our own in-house email server and when I look into logs I do see that Mautic was connected to mail server but there is no evidence that mautic is doing something.
Unfortunately I have thousands of bounced back emails in my inbox which I need to process and can't empty my inbox.

**Comment by nemesis82x** [comment]
Hi Armin,
if you have your personal email server you can move all the imap email file into a temp dir and copy only a range of file into imap directory to process them.
Is not a “clean” solution but you can try.

Bye
Fabio

Inviato da iPhone

**Comment by dsukhin** [comment]
Having the same issue. I also have tons of messages in my bounce account. Should i expect the task to eventually finish or is it hanging? Will it always take this long to run of there are lots of messages in there?

Could someone direct me to the section of code that does this processing. I'd like to explore a bit as well to help diagnose.

**Comment by dsukhin** [comment]
I read thru the code a bit and was have a better sense of what is going on and have a few observations - 

I have over 40K emails in my bounce folder and responses folder combined. The command itself does not show anything while its running but I did notice the unread count going down in my mailboxes so everything does appear to be working as intended... just VERY slowly, roughly 2-3 seconds per email so it will take over a day to finish - but that should only be the first run as it marks everything as seen so that's good.

One unfortunate observation is that for the "replies" mailbox, it also marks messages as "Seen/Read". I understand the logic here but this is very intrusive to other workflows (like my ticketing system) which also use the read status to open tickets and manage when the are replied to. There should be a setting to limit to a subset of the latest messages (by doing a date range select and storing the last time the email check was run) rather than marking as read. For bounces and unsubscribes this is fine (that's Mautic's domain) but **replies are outside the scope of a marketing automation system and are handled elsewhere so they should be observed in a read only way**.

**Comment by arvage** [comment]
Thank you for the suggestion but I'm on mbox format and emails are stored in one huge text file. as of now I have 370,000 emails in my inbox (3.7GB)I can change my server to use maildir instead of mbox and convert my mbox file into email files but processing that many emails and split them into thousands of processing will be brutal as new emails are constantly coming in. I was hoping to find more automated way of doing it but I'll do it if I had no choice.

    On Monday, August 13, 2018, 10:55:51 AM PDT, nemesis82x <notifications@github.com> wrote:  
 
 Hi Armin,
if you have your personal email server you can move all the imap email file into a temp dir and copy only a range of file into imap directory to process them.
Is not a “clean” solution but you can try.

Bye
Fabio

Inviato da iPhone

**Comment by arvage** [comment]
in order to see if the fetch process is stuck or going but very slow, you can turn your imap server logging on.I'm using dovecot pop/imap server and turned on logging as below:
/etc/dovecot/conf.d/10-logging.conflog_path = /var/log/dovecot.log
the fetcher file located at /app/bundles/EmailBundle/MonitoredEmail/Mailbox.php
I noticed that the expunge command is also not working.
Hope you can find something in there
    On Saturday, August 18, 2018, 2:57:50 PM PDT, dsukhin <notifications@github.com> wrote:  
 
 
Having the same issue. I also have tons of messages in my bounce account. Should i expect the task to eventually finish or is it hanging? Will it always take this long to run of there are lots of messages in there?

Could someone direct me to the section of code that does this processing. I'd like to explore a bit as well to help diagnose.

**Comment by hrouissi** [comment]
Same issue here. 
My inbox only contains 193 messages with a total size of 4.4 MB.

No email is fetched to Mautic.

**Comment by sixmillonisntenough** [comment]
I am having the same issue right now; the process hangs and seems to run in some cases forever, some just for a long period of time.  It looks like there are in excess of 50k messages in the inbox. Any way to prevent the fetcher from running if it is already processing messages or for it to work concurrently with the other process?

**Comment by RCheesley** [comment]
Closing as this relates to an old version of Mautic

**Comment by namratasaun** [comment]
Mautic 3.2 getting this error when I try to to run mautic: email:fetch.
I can confirm it was running on the same server with the same email some time back. I tried with another email from same domain and it is working there too. Just giving this error on this specific email

0 emails processed for {imap.gmail.com:993/imap/ssl}[Gmail]/Spam with a criteria of UNSEEN
PHP Notice:  Unknown: [CLOSED] IMAP connection broken (server response) (errflg=2) in Unknown on line 0
