### ISSUE TITLE
Support contact token in {unsubscribe_text}

### ISSUE THREAD

**Issue by LevryKurniawan** [mautic/mautic#6266]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | No
| Feature request? | No
| Enhancement? | Yes

## Description:
When I put **{contactfield=email}** into **Text for the {unsubscribe_text} token** column, the email sent to the recipient remains displayed as {contactfield=email}. But, if I also put it into the content in the email builder, then both will display the contact's email address as it should be.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.13.1
| PHP version | 5.6.36

### Steps to reproduce:
1. Go to **Configuration ⇒ Email Settings ⇒ Unsubscribe Settings**
2. Insert **{contactfield=email}** or other dynamic lead fields into **Text for the {unsubscribe_text} token**.
3. Try sending an email with the **{unsubscribe_text}** token in its content.
 
### Log errors: -

**Comment by levrykurniawan** [comment]
Thank you for your attention.

I think this is a pretty important feature, because in the Bulk Senders Guidelines by Gmail ([https://support.google.com/mail/answer/81126](https://support.google.com/mail/answer/81126)) it's mentioned that you should explicitly indicate the email address subscribed to your list.

Provisionally, I include the recipient's email address token hidden in the body email so that tokens contained in {unsubscribe_text} can also work.

I really hope this feature can be supported in the next version of Mautic.

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)

**Comment by LevryKurniawan** [comment]
Hi @npracht, sorry to just reply now. I just tried Mautic 3 and can confirm this feature is still not supported.
