### ISSUE TITLE
Mautic will not send newly added emails to contacts in the campaign

### ISSUE THREAD

**Issue by hippich** [mautic/mautic#6323]
Not sure if this is FAD or this is a bug.

Basically, if I create campaign, publish, trigger cron jobs to send emails and later add new Email into campaign - this email get stuck forever in "Pending actions".

See screenshot below. "Send email" action was added when campaign was created. After all relevant cron jobs run, I've added new action "2" which sends different email. And not it sits at "Pending actions" and never executed.

![image](https://user-images.githubusercontent.com/361630/42720647-98f20c5c-86f0-11e8-972a-41d8d73b04c9.png)

**Comment by MRG95** [comment]
Sorry, I don't have a solution, but I would like to mention that I am experiencing this issue as well. It is very bad and will get me stuck if I cannot append new emails to a campaign when I need to.

**Comment by alanhartless** [comment]
This is on purpose because Mautic campaigns are not just email centric and can be as simple or as complex as one will want. So we can't have Mautic executing every new event added to a complex campaign after the contact has already moved beyond that point in the campaign. If you add new events, you have to do it in such a way that chains it after an event that has not already executed for the contact. For example, if you have 3 emails scheduled, add contacts have not received the 3rd yet, add a condition to the 3rd action that matches everyone, then chain the new 4th email to it.

**Comment by alanhartless** [comment]
That works. By the way, 2.14.0 now has the feature to send contacts through campaigns multiple times built in.

**Comment by MRG95** [comment]
Yes I'm aware of that, but is there a way to resent all contacts again at once?

**Comment by alanhartless** [comment]
That's true. You'd have to basically remove them from the campaign and readd them. Changing the campaign source to a bogus segment, run the campaign update command, then add change it back to the original would effectively do that.

**Comment by MRG95** [comment]
@alanhartless Hello again! I've decided that my proposed workaround sucks because it reintroduces delays that the contact has already experienced.

I'm trying to create a workaround using what you described about adding new events to events that haven't been fired yet. You said "add a condition to the 3rd action that matches everyone, then chain the new 4th email to it."

I cannot get anything to work. I tried every set up I can think of, but new emails simply never get sent.

I've tried:

- Adding a new 'always true' condition and then an email after it. (Condition or email stuck at pending)
- Adding an email after an existing 'always true' condition who's delay is 100 years, and then reducing that to 1 min. (Condition gets fired instantly, email stuck at pending)
- Modifying an existing email with new contents that is after an 'always true' condition who's delay is 100 years, and then reducing that to 1 min. (Reduction of delay doesn't cause email to get sent)

No matter what I try, I cannot seem to create a campaign that lets me append new actions to it. They just never get fired.

Can you provide an example campaign please? Thanks for your time.

**Comment by MRG95** [comment]
I finally made a workaround that works relatively well, but will break the email success percentage counters (Might open another issue).

When you're ready to add a new email, do the following:

1. Add a decision action of type "Submits form" and set to a bogus form.
2. Add an email action to the failed side of the decision action.
3. Set the delay to whatever you want.
4. Click Apply.

The decision action will for some reason be fired for existing contacts, as well as the email action that follows. I believe this is because decision actions are the only actions that don't have their outcomes determined when the contact first comes across them. No idea.

I have tested this in several different scenarios. For example, leaving the last campaign action as that decision action and then adding the email later. Either order works thankfully, so you will never get "stuck" in case you forget to add one thing or the other. It should all just work.

**Comment by YosuCadilla** [comment]
Since preventing the contact reaching the "end of the campaign logic" allows emails to be sent, it seems to me the problem is Contacts which are reaching the end of the campaign seem to be entering a weird state where they are not removed but not fully  *IN* the campaign (at least for whatever relates to emails).

I hope that narrows down the problem enough so it's worth taking a look at it.

**Comment by MRG95** [comment]
@npracht why did you mark this as a duplicate when it was opened 20 days before the other one? This is the original with a full workaround in the comments.

**Comment by npracht** [comment]
Because this is the closed one. They are linked to each other so nothing is lost.
If you think it is more appropriated i can re-open this one and close the other one?

**Comment by MRG95** [comment]
@npracht ah I understand. No you don't have to switch it, the other post was more descriptive. I forgot this one was closed...

**Comment by npracht** [comment]
Great then :)
Thanks a lot for your contributions.

**Comment by johndjchan** [comment]
hello guys, i am having the exact same issue, all email subs stuck in pending and it just wont run the tags,segment and settings... any help pls?
