### ISSUE TITLE
Add flag to commands to bypass sleep() usage for more resource flexible servers

### ISSUE THREAD

**Issue by kithokit** [mautic/mautic#635]
https://github.com/mautic/mautic/blob/staging/app/bundles/CampaignBundle/Model/EventModel.php

They are quite no. of places add `sleep(1)` when triggering sending email events.

This make the sending email action not scalable enough. Say if we want to send 50000 email. we need at least 50000 seconds, which spend more than 12 hours.

Why do we need to add sleep(1)? to avoid CPU overkill? , i think we can adjust by the no. of batch to be send each time

**Comment by alanhartless** [comment]
It was added added for cpu control with shared hosts in mind. If kicking off a campaign with a thousands of leads, Mautic would likely be kicked off every shared host due to the CPU usage that climbs to 100% during the long going loops of processing the large number of leads x the number of events per lead. 

Many shared hosts also have minimum cronjob intervals as well, like 15 or 30 minutes. If we processed x number of leads/events then stopped and the script doesn't fire for another 15/30 minutes, the we would be prolonging execution even more. 

However VPSs can probably get away without it or something more relaxed. So maybe we can add a flag to bypass the throttling code. 

Definitely open to suggestions if there's a better way while keeping shared hosts in mind on both resource use and cronjob limitations. 

Thanks!
Alan

**Comment by alanhartless** [comment]
I'll look at at the code though once not mobile as it should not be sleeping on every event.

**Comment by kithokit** [comment]
Thanks for the explanation. Perhaps add a comment on the sleep would be good.

I think in the future, we can add a flag to do it. and in installation wizard, allow user to choose the type of hosting, either VPS or shared host to set the flag.

**Comment by alanhartless** [comment]
This was improved in 1.2.  But for system admins, a specific amount of time can now be set by adding the key `batch_event_sleep_time` key with a defined seconds to the local.php file then deleting app/cache/prod.
