### ISSUE TITLE
Support for BCC in Send Custom Email manually from the contact profile

### ISSUE THREAD

**Issue by drimlike** [mautic/mautic#6392]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | No
| Feature request? | Yes 
| Enhancement? | Yes

## Description:
How could I add a BCC email address when using "Send a custom email to" directly from the contact page? It's not part of a campaign, it's the direct email feature when you send the email manually.  i.e. I want to send a custom email manually to John Smith, so I'm using a template, but I would like my manager (manager@domain.com) to receive the email I've sent in BCC for the follow up if needed. Any idea?

### Steps to reproduce:
1. Open a contact profile
2. Click on the Send Email button at the top right
3. Load a template email
4. No BCC field, so it's not possible to add someone in BCC
5. Send email

**Comment by Gambert** [comment]
This would be a great enhancement, I need this too.

Actually I thought it was possible already, because under the "Advanced" tab when editing an template email I have another address as BCC already, but when then sending that email to a single contact, then that is ignored, and the email is not sent to the address defined as bcc. Is that the intended behavior?

**Comment by RCheesley** [comment]
Hi folks, seems like this would be a nice feature, and hopefully quite easy to implement (honestly I thought it was there already!)

If anyone would like to pick this up and submit a pull request please don't hesitate to reach out to the Product Team - we're happy to help guide you with this.
