### ISSUE TITLE
Mautic Landing page responsive

### ISSUE THREAD

**Issue by alfredosimoes** [mautic/mautic#6670]
I have created several landing pages in Mautic but no one of them is responsive. Can we add a responsive page?

**Comment by npracht** [comment]
Hello @alfredosimoes,

I think several themes are responsive like the fresh series.
After that being said, feel free to develop new themes using the documentation: https://developer.mautic.org/#themes

And if you like (that would be awesome), feel free to share the responsive theme you will develop with the mautic community.

I'll close this issue because we use Github for mautic bugs management.
Thanks for your contribution !

**Comment by alfredosimoes** [comment]
Thanks for your help.
Although this is not a bug, as a sugestion i tthink that Mautic should be distributed at least with a responsive landing page and form. It should be able to be used as a standard solution in any device (computer, tablet and smarthphone). Most of today's visitors came from smartphones.

I am a fan of Mautic and i would like to be able to recommend it based in its good features and quick support.

We can make Mautic better? 
Yes, we can.
