### ISSUE TITLE
Action not trigger when replies to email

### ISSUE THREAD

**Issue by KevinBlanc** [mautic/mautic#6724]
I launched a camppaign yesterday and as you can see it is based on a "yes or no" question. If the contact doesn't answer the email then he will get another email but if he does answer then the contact must be automatically updated.
The problem it is that I got some answers and none contact has been updated. 
So I would like to know whether or not the campaign is correctly build and I want to be sure that if someone answer to my email then he will not get another email. 
Thanks for your help
Kevin

![image](https://user-images.githubusercontent.com/44093986/46875972-1c538d80-ce0b-11e8-89b7-c0a61c29ef97.png)

**Comment by KevinBlanc** [comment]
Hey @npracht 

So if I get this right if we use Gmail at work it is impossible to use this feature?

**Comment by escopecz** [comment]
Yes, Gmail is modifying the email headers and therefor Mautic has no clue if it is a reply.

**Comment by janwinkler** [comment]
Actually Mautic could/should be a bit more clever! E.g. we use a single inbox for mautic only. All mails that appear in this inbox should be checked for the senders address and if it matches, it should be treated as a reply to the last email sent to this email address (or additionally check the subject in order to further ensure that it matches).
