### ISSUE TITLE
Focus item links point to 500 page (EDIT: Only when in same browser as Mautic user logged-in session) (2.14.2)

### ISSUE THREAD

**Issue by albanleandri** [mautic/mautic#6869]
## Bug Description

The links in focus items were working just fine in 2.12.2, but the feature broke (silently) as I upgraded to 2.14.2

| Q   | A
| --- | ---
| Mautic version | 2.14.2
| PHP version | 7.0.32
| Browser | Chrome Version 70.0.3538.77 (Official Build) (64-bit)

### Steps to reproduce
1. Create a new focus item
2. Choose "Emphasize a link" / "Modal" / HTML content
3. Add a link in your item
4. Insert the item in a page of your website
5. When in your page, and the focus item shows, click on the link
6. You see a 500 error page instead of the destination page

![image](https://user-images.githubusercontent.com/23435414/48390728-04d33180-e736-11e8-8096-3f83196290c3.png)

Settings to "NO" this option didn't help 
![image](https://user-images.githubusercontent.com/23435414/48391587-d6efec00-e739-11e8-91d0-ae9f92baf2f4.png)

 
### Log errors

```
[2018-11-13 16:46:02] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Call to a member function getId() on null" at /var/www/html/app/bundles/LeadBundle/Helper/ContactRequestHelper.php line 173 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function getId() on null at /var/www/html/app/bundles/LeadBundle/Helper/ContactRequestHelper.php:173)"} []

```

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by escopecz** [comment]
Please provide the error from your logs.

**Comment by AlbanL74fr** [comment]
@escopecz I added it to the description

**Comment by AlbanL74fr** [comment]
@escopecz I was logged in Mautic while clicking the link, I realized. I tried to logout, it worked... Is it expected?

**Comment by escopecz** [comment]
Thanks! That helped a lot. I bet you are testing in the same browser as you are logged in... Ah, you just commented that you are. That's it. Mautic do not track Mautic admin users.

It should not throw the error obviously, but your contacts will be fine.

**Comment by pety-dc** [comment]
@escopecz 

I use mautic 2.14.2

I believe I have run into the same problem. On 173. row of Mautic\LeadBundle\Helper\ContactRequestHelper mautic fails due to $this->trackedContact being null.

The request comes in to `Mautic\PageBundle\Controller\PublicController::redirectAction()` which calls `$lead      = $leadModel->getContactFromRequest(['ct' => $ct]);` 

In that method a LeadModel instantiates `$contactRequestHelper = new ContactRequestHelper(...)` and then returns `return $contactRequestHelper->getContactFromQuery($queryFields);`

In the `Mautic\LeadBundle\Helper\ContactRequestHelper::getContactFromQuery` method calls 
`$this->trackedContact = $this->contactTracker->getContact();`
But the getContact() method returns null if a mautic user is logged in:

`if ($systemContact = $this->getSystemContact()) {
            return $systemContact;
        } elseif ($this->isUserSession()) {
            return null;
        }`

In the `Mautic\LeadBundle\Helper\ContactRequestHelper::getContactFromQuery`  method then `$foundContact         = $this->getContactFromUrl();` is called which makes a check against the tracked contact:

`if ($foundContact->getId() !== $this->trackedContact->getId()) {
            // A contact was found by a publicly updatable field
            return $foundContact;
        }`

But because a mautic user is logged in $this->trackedContact is null, which leads to the "Call to a member function getId() on null" error

**Comment by escopecz** [comment]
Can you guys check the latest Mautic? I know there are several fixes in this area every release.

**Comment by pety-dc** [comment]
Unfortunately I cannot afford to try this on a newer version. But I'll try not to forget to check back to this thread when we upgrade to 2.15.X

**Comment by RCheesley** [comment]
Hi @pety-dc did you get to check this again on 2.15.x?

**Comment by pety-dc** [comment]
@RCheesley 

Based on how I described the error previously, I believe this issue was address in this commit: https://github.com/mautic/mautic/commit/6bf7dfbd886ead16db68f909245f2f0e87bcf49c

Which I believe made its was to 2.15.2
