### ISSUE TITLE
Unsubscribe form empty

### ISSUE THREAD

**Issue by CrystalMethod** [mautic/mautic#702]
Mautic Version: 1.1.3

I've set up a newsletter with set "unsubscribe form". The sent email contains a generated link to the unsubscribe form as follows ``https://a.b.c.d/mautic/email/unsubscribe/55af61884311d``. But the unsubscribe form is always empty and defaults to the Mauve theme which I'm actually _not_ using. Did I miss something to configure? Btw: The preview of the unsubscribe form looks well.

```html
<!DOCTYPE html>
<html>
    <head>
        <title>Mautic</title>
        <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" type="text/css" />
        <link rel="stylesheet" href="/mautic/themes/Mauve/css/mauve.css" type="text/css" />
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
        <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
            </head>
    <body>
                <div class="well text-center">
    <h2></h2>
    </div>            </body>
</html>
```

**Comment by PietroMantovani** [comment]
Same here.. don't know if I'm missing something on this unsubscribe function.

**Comment by alanhartless** [comment]
Hi,

Was the email sent with the unsubscribe URL sent as a result from a campaign, email blast, or a form submit to an actual lead? Or was this sent as a test email and/or a one-off set directly to a lead?

First, test emails are not associated with an actual lead nor is there a stat stored.  So if you click the unsubscribe link in a test email, it doesn't show any text because there's no body to associate with.  

If you sent the email as a one off (via the lead's profile), the unsubscribe form doesn't show because the email record stored in Mautic isn't associated with a Mautic email (because it was something custom) thus not associated with a form.

To change the default template displayed for the unsubscribe page either change the default in Mautic's Configuration or if a form is assigned, it'll use the template assigned to the form. 

Hope that helps.

Thanks!
Alan

**Comment by PietroMantovani** [comment]
Thanks you very much for these detailed explanation.
And thank you for this fantastic software.
Regards,
Pietro Mantovani
Il 28/ago/2015 02:18 AM Alan Hartless <notifications@github.com> ha scritto:Hi,

Was the email sent with the unsubscribe URL sent as a result from a campaign, email blast, or a form submit to an actual lead? Or was this sent as a test email and/or a one-off set directly to a lead?

First, test emails are not associated with an actual lead nor is there a stat stored.  So if you click the unsubscribe link in a test email, it doesn't show any text because there's no body to associate with.  

If you sent the email as a one off (via the lead's profile), the unsubscribe form doesn't show because the email record stored in Mautic isn't associated with a Mautic email (because it was something custom) thus not associated with a form.

To change the default template displayed for the unsubscribe page either change the default in Mautic's Configuration or if a form is assigned, it'll use the template assigned to the form. 

Hope that helps.

Thanks!
Alan
