### ISSUE TITLE
Suite/Sugar integration doesn't update records (Mautic 2.15.00 /  SuiteCRM 7.10.10)

### ISSUE THREAD

**Issue by bbnes66** [mautic/mautic#7112]
The connection plugin only creates new leads from Mautic to SuiteCRM, but fails to update them when some change in integration fields happens.

| Mautic 2.15.00 |
| SuiteCRM 7.10.10 |
| PHP 7.0 |
| Google Chrome |

Steps to reproduce
activate the plugin and choose:
Triggered action push contacts to integration
Pull contacts and/or companies from integration
Push contacts and/or companies to this integration
choose also to pool at least "leads"
map (at least) email address and first and last name, choosing Mautic to SuiteCRM as update direction for every field
create a lead in Mautic
give the following command through the console:
php -f console mautic:integration:synccontacts --integration="Sugarcrm" --time-interval="2 hours"
go to SuiteCRM and you'll see that the contact has been created
update the contact created in Mautic changing the first and last name
give again the command:
php -f console mautic:integration:synccontacts --integration="Sugarcrm" --time-interval="2 hours"

the console will give you the following output:

" Number of leads/contacts fetched: 1
Updating/creating leads from Mautic to Sugarcrm
Number of contacts pushed: 0 updated, 0 created, 0 had errors and 0 were ignored (likely duplicates or didn't match field criteria) "

So, the system wasn't able to update the record in SuiteCRM.

There is no error in the Mautic log file.

**Comment by tsummerer** [comment]
I believe that I have tracked down the underlying cause here. I haven't figured out a fix yet and would be happy to have suggestions.

The `mautic:integration:fetchleads` (or `synccontacts` same thing) command calls the following functions in this order:
1. `SugarcrmIntegration::getLeads`  (to fetch Leads from CRM)
2. `SugarcrmIntegration::getLeads`  (to fetch Contacts from CRM)
3. `SugarcrmIntegration::getCompanies` (to fetch Accounts from CRM)
4. `SugarcrmIntegration::pushLeads` (to push Leads/Contacts to CRM)
5. `SugarcrmIntegration::pushCompanies` (to push Companies to CRM)

In steps 1/2, Mautic requests all CRM records where Date Modified is within the specified range (2 hours in example above). 
```php
line 586:
// $query['start'] = {date 2 hours ago}
// $query['end'] = {now}
// $query['limit'] = 100
// $query['fetchAll'] = false
// $query['offset'] = 0
// $object = "Leads"

$result           = $this->getApiHelper()->getLeads($query, $object);
$params['offset'] = $result['next_offset'];
$executed += $this->amendLeadDataBeforeMauticPopulate($result, $object);
```
For each result, we run through the (poorly named) `amendLeadDataBeforeMauticPopulate` function. 
This behemoth does a bunch of processing, but at the end it **creates or updates an IntegrationEntity record**. If it updates it, it **sets the `last_sync_date` to Now**.

```php
// line 929
$integrationId = $integrationEntityRepo->getIntegrationsEntityId(
    'Sugarcrm',
    $object,
    $mauticObjectReference,
    $entity->getId()
);

if ($integrationId == null) {
    $integrationEntity = new IntegrationEntity();
    $integrationEntity->setDateAdded(new \DateTime());
    $integrationEntity->setLastSyncDate(new \DateTime());                   <-------!!!!!
    $integrationEntity->setIntegration('Sugarcrm');
    $integrationEntity->setIntegrationEntity($object);
    $integrationEntity->setIntegrationEntityId($record['id']);
    $integrationEntity->setInternalEntity($mauticObjectReference);
    $integrationEntity->setInternalEntityId($entity->getId());
    $integrationEntities[] = $integrationEntity;
} else {
    $integrationEntity = $integrationEntityRepo->getEntity($integrationId[0]['id']);
    $integrationEntity->setLastSyncDate(new \DateTime());                  <-------!!!!!
    $integrationEntities[] = $integrationEntity;
}
```


Moving on, we later get to step 4. The first thing to do here is to determine which Mautic records need to be pushed to CRM. 

```php
//line 1289:
$leadsToUpdate = $integrationEntityRepo->findLeadsToUpdate($this->getName(), 'lead', $fields, $limit, $fromDate, $toDate, ['Contacts', 'Leads']);
```

`findLeadsToUpdate` runs a big query that includes this:
```sql
SELECT ...
FROM leads l INNER JOIN integration_entities i ...
WHERE
...
...
...
AND (l.date_modified > i.last_sync_date)
...
```

And that's our killer. Mautic is only going to push Leads where the date_modified is greater than the last_sync_date. And it literally set the last_sync_date on many of these records milliseconds ago. 

So, for example, if you run the cron job every 30 minutes and both Mautic and CRM update their respective records within the 30 minutes, then the Mautic->CRM portion of the sync won't run.
The only time it will completely work is if you never update records in CRM. 


So how do we fix this? 
Do we prevent Steps 1/2 from updating the last_sync_date? Maybe do it at the end? (Could we safely wait to flush the entities until the end??)

Can we refactor that query somehow? Maybe it shouldn't consider the last_sync date?

**Comment by RCheesley** [comment]
Hi folks, if anyone can help with testing #7420 it would be really appreciated!

**Comment by RCheesley** [comment]
Closing due to lack of recent engagement - if the issue remains please open a new issue and link to this one.
