### ISSUE TITLE
Campaign Builder "Email to send" Drop Down Displays Some Not All Emails Saved

### ISSUE THREAD

**Issue by Khaled4** [mautic/mautic#7253]
## Bug Description
In Channels --> Email, I created some email messages and saved them.
In Campaigns, I created a campaign but when I wanted to select a particular email I saved earlier it was not available for me to choose from the drop down "Email To Send" although I could see other emails.

| Q   | A
| --- | ---
| Mautic version 2.15 | 
| PHP version 7.2| 
| Browser Chrome and Firefox | 

### Steps to reproduce
1. Go to Campaign Builder, Select a Segment, Select a decision: Send Email To User (or Send Email)
2. From Drop Down "Email To Send" find the email you designed and saved (in my case not all were there but only some were)
 
### Log errors
Mautic will not see this as an error as it is not a system error as such.
Thanks, Khaled

![mautic campaign builder email to send missing email](https://user-images.githubusercontent.com/15167986/52899969-de77d300-3209-11e9-8567-3160bc478753.jpg)
![mautic saved email](https://user-images.githubusercontent.com/15167986/52899970-de77d300-3209-11e9-9d27-4744443446cb.jpg)

**Comment by npracht** [comment]
If you write the name, it does not appear ?

**Comment by Khaled4** [comment]
I was able to find out where the problem is (see below) and I would like to copy this design issue into a "Feature Request". I am not sure if this was available in earlier versions of Mautic (I am new to Mautic!).
Basically, Mautic is limiting us in Campaigns to choose emails that were created from within the campaign itself. So:
Campaign -> New
Decision -> Send Email
Choose Email -> (only emails that were created in Campaigns appear in pull-down) Or
Choose Email -> (create new email)
Needless to say, this is impractical and we need to have an option to choose any email previously created and stored on the system not just the ones created from within campaigns.

**Comment by Khaled4** [comment]
I reopened this issue since Mautic:
1- Prefers to have ideas listed in mautic.org
2- In mautic.org I cannot register as "User registration is currently not allowed."
So I'm back here treating this issue as a BUG.

**Comment by dongilbert** [comment]
The issue is much more simple than you make it out to be, and it is not a bug.

As seen in your screenshot, the emails that are NOT appearing in the campaign dropdown are _segment emails_ (as indicated by the miniature pie chart to the right of the email name in the list view).

By design, segment emails to not show up in the campaign "Send Email" action form.

Also, emails are _not_ required to be created within the campaign builder itself in order to show up in that list. It's just that emails created from within the campaign builder are automatically set to be Template Emails instead of Segment Emails.
