### ISSUE TITLE
Multi-select can't be emptied on form

### ISSUE THREAD

**Issue by maryisdead** [mautic/mautic#7275]
## Bug Description
It is not possible to completely reset a multi-select field on a contact through a form. Reset meaning that no checkbox is set and the field is saved empty.

| Q   | A
| --- | ---
| Mautic version | 2.14.2
| PHP version | 7.1
| Browser | Chrome 72

### Steps to reproduce
1. Have a multi-select field in a form, have it and its options linked to a multi-select field on a contact, have it pre-filled with values from contact.
2. Check some checkboxes, submit the form. Contact now has the checked values set.
3. Reload form, previously selected checkboxes get checked as expected.
4. Now, uncheck all checkboxes and submit form.
5. Reload form, previously unselected checkboxes are still checked as they have been like on step 3.

The issue is rather simple: The browser won't submit any checkbox that is not checked so nothing is send to Mautic and it won't act on the field.

~~My solution was to prepend my specific checkbox group with a hidden field with the same name, like so:~~

~~`<input name="mauticform[fieldname]" value="" class="mauticform-hidden" type="hidden">`.~~

~~This should by done by default imho.~~

Edit: Proposed solution does not work. Not sure what had me thinking it did. It seems Mautic doesn't handle the posted and empty value. Issue remains.

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by maryisdead** [comment]
No, I can't confirm because I have neither time nor resources to do. Good to see you took the easy route.

**Comment by RCheesley** [comment]
@maryisdead unfortunately having started with over 900 open issues six months ago (currently under 400, we are making progress!), and being a team of 3 trying to triage and work through these, we are somewhat reliant on the help of folk who created the issues to check whether they still exist. 

I am sure that you can appreciate having limited time and resources yourself, that this is a massive job to undertake, particularly as two of the three are doing this in their spare time as volunteers.  Therefore we are closing any issues where we do not have a response within a reasonable timeframe (in this case, there was no reply for 26 days - we are generally applying a 14 day time period).

If you happen to find the time in the future to re-test in Mautic 3 (mautibox.com is available for this purpose if you don't have your own test instance) and determine that this issue does persist in 3.0.2 then we will of course re-open the issue and investigate further.

There is no need for sarcasm (please take a look at our [Code of Conduct](https://contribute.mautic.org/policies/code-of-conduct#4-expected-behavior) for the expected and unacceptable behaviours in this community).  The team of volunteers is doing the best we can to work through this massive amount of technical debt, and we really do appreciate every contributor who is able to help us with this process but we also do not see it as being helpful having an open issue from nearly 18 months ago when we don't know if persists and the original person reporting the problem is unresponsive. 

I hope that at some point you may be able to help us, but also appreciate that time is a very precious resource!  If you're interested, you can track our progress on the community health dashboard [here](https://dashboard.mautic.org).
