### ISSUE TITLE
The batch API responses use weird and non-standard JSON, making them hard to deserialize

### ISSUE THREAD

**Issue by StoppingBuck** [mautic/mautic#7385]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Several of the current API batch endpoints return response JSON in an uncommon format that makes it hard for some systems (such as Salesforce) to easily deserialize them.

As an example, using the `PATCH /api/contacts/batch/edit` endpoint to update contacts return this if you only PATCHed one contact:

```
{
         "contacts": [
             {
                 "id": 5,
                 "points": 5
                 [...]
             }
         ],
         "statusCodes": [
             200
         ]
}
```
(I.e. it returns a JSON object containing an array of JSON objects - contacts - and a statusCodes array of integers. So far so good)

...but this is the response if you PATCHed multiple contacts:

```
{
        "contacts": {
            "0": {
                "id": 5,
                "points": 5
            },
            "1": {
                "id": 3,
                "points": 43
            }
        },
        "statusCodes": [
            200,
            200
        ]
}
```
(I.e. it returns a JSON object containing a JSON object called 'contacts' which contains multiple custom objects named incremented integers as strings. The statusCodes array remains the same)

This last example is a very bizarre way to handle multiple JSON objects, and is extremely difficult to deserialize in some languages (like Salesforce's Apex), since it requires knowing the number-strings to access the individual contacts.

Instead, a common JSON array should be used to produce something like this:

```
{
    "contacts": [
        {
            "id": 5,
            "points": 5
        },
        {
            "id": 3,
            "points": 43
        }
    ],
    "statusCodes": [
        200,
        200
    ]
}
```

This way, the `contacts` can be universally recognized as an array of JSON objects and can be effortlessly deserialized and looped through.

I believe the same sort of syntax is used in other batch endpoints as well.

Obviously, there are backwards compatibility issues to consider, but it should still be possible to make the change happen smoothly.

| Q   | A
| --- | ---
| Mautic version | 2.15.0

**Comment by StoppingBuck** [comment]
In addition to the above, the API call to batch delete is even more puzzling, as it needs the contact ids in this format: `https://mautic.site/api/contacts/batch/delete?ids[]=194&ids[]=192`

@npracht (or @escopecz since I wrote about it with you some time ago): Seeing as changing this would likely be a breaking change, perhaps it can be slated for M3?

**Comment by StoppingBuck** [comment]
Oh, and #8153 too per the same reasoning

**Comment by petersondmg** [comment]
Another point is that since the batch response is using an object with `id / item` paris instead of array, sorting is not guaranteed.

JSON specs says that `An object is an unordered set of name/value pairs`. 

Although some JSON parsers will keep the original order, this will not happen in most cases (ex. Golang's default encoding/json) since it's not part of the original spec, making sorting from the API uneffective.

**Comment by StoppingBuck** [comment]
@petersondmg That's a good point. Keeping the statusCodes separate also makes it a bit harder to know what statsCode is regarding what batch.

All in all, I'd propose something like re-working the current
```
{
        "contacts": {
            "0": {
                "id": 5,
                "points": 5
            },
            "1": {
                "id": 3,
                "points": 43
            }
        },
        "statusCodes": [
            200,
            200
        ]
}
```

Into something like this:

```
[
    {
        "contact": {
            "id": 5,
            "points": 5
        },
        "statusCode": 200
    },
    {
        "contact": {
            "id": 53
            "points": 43
        },
        "statusCode": 200
    }
]
```

Thus keeping the contact object (and the changes within it) along with its statusCode in a combined object inside an array. I'm not an expert, but I'd guess that's much closer to adhering to the standard.

**Comment by StoppingBuck** [comment]
Just an update: I finally got a local dev environment set up, and tested the newest `staging` code and it seems that the `PATCH /api/contacts/batch/edit` now returns a changed format:

Request:

```
[
	{
		"id": "1",
		"email": "new_email@gmail.com"
	},
	{
		"id": "2",
		"tags": "some_tag"
	},
	{
		"id": "845",
		"email": "doesnot@exist.com"
	}
]
```


```
{
  "contacts": [
    {
      "isPublished": true,
      "dateAdded": "2020-06-09T14:14:39+00:00",
      "dateModified": "2020-06-09T14:17:41+00:00",
      "createdBy": 1,
      "createdByUser": "Mads Peter Rommedahl",
      "modifiedBy": 1,
      "modifiedByUser": "Mads Peter Rommedahl",
      "id": 1,
      "points": 0,
      "color": null,
      "fields": {
        "core": {
          "points": {
            "id": "9",
            "label": "Points",
            "alias": "points",
            "type": "number",
            "group": "core"
            [...]
          }
        }
      }
    },
    {
      "isPublished": true,
      "dateAdded": "2020-06-09T14:14:40+00:00",
      "dateModified": "2020-06-09T14:17:41+00:00",
      "createdBy": 1,
      "createdByUser": "Mads Peter Rommedahl",
      "modifiedBy": 1,
      "modifiedByUser": "Mads Peter Rommedahl",
      "id": 2,
      "points": 0,
      "color": null,
      "fields": {
        "core": {
          "points": {
            "id": "9",
            "label": "Points",
            "alias": "points",
            "type": "number",
            "group": "core"
            [...]
          }
        }
      }
    }
  ],
  "statusCodes": [
    200,
    200,
    404
  ],
  "errors": {
    "2": {
      "message": "Item was not found.",
      "code": 404,
      "type": "api"
    }
  }
}
```

So, it seems the weird numbering field names in the `contacts` object are gone, which is at least a step in the right direction. I'll still see if I can't figure out how to turn the entire response body into an array of JSON objects.

**Comment by RCheesley** [comment]
@StoppingBuck not sure if you had a chance to look at the comment no the other issue about the PR #8959 - would that address this issue? If not, what help do you need to create a PR to address it?

**Comment by StoppingBuck** [comment]
@RCheesley Sorry, I've looked at it and no, it's not really related.

I have a pretty good idea of what would be needed to change this (just haven't had the time). However, it will invariably cause BC break because the request body will be changed to a JSON array (instead of the current, weird custom JSON object). So this one should probably be slated for M4.

**Comment by RCheesley** [comment]
Ok thanks - will tag this for the 4.0 release, if you're able to make a WIP PR and chip away at it over time that would be really great!

**Comment by StoppingBuck** [comment]
@RCheesley Oh! I didn't know WIP PRs were allowed! That would certainly make things a bit easier, if I don't have to ensure that everything works at once locally before making a PR :)

**Comment by RCheesley** [comment]
Please pop WIP in the PR title, and one of the team will apply the appropriate labels. 

For something like this I think there will be a good deal of collaboration needed. 

It might also be worth just dropping a short post at https://forum.mautic.org/c/ideas explaining what the issue is, how you think it should be approached etc. 

That would allow for a bit wider discussion and also enables folk who might not be living in GitHub to learn about what you're proposing and how they can get involved/what impact that might have.  

Doesn't have to be an essay - if you mention it in the PR it will automatically link up to the forum thread which will then direct people here!

**Comment by sharon-asana** [comment]
i hope someone could help me here, i'm sending the `contacts/batch/edit` with python while it was working before until i've migrated my Mautic installation to a new server.
i'm using a package i've added the batch_edit function to, since it didn't exist before. https://github.com/sharon-asana/python-mautic/blob/master/mautic/api.py

the data i'm sending looks like the following:
`[
{
"id":"1738833",
"activities_workouts_7d":2,
"activities_sleep_7d":0,
"activities_focus_7d":0,
"activities_quiz_7d":0,
"activities_meditations_7d":0,
"activities_planks_7d":0,
"activities_updated_at":"2021-03-15"
},
{
"id":"2665147",
"activities_workouts_7d":4,
"activities_sleep_7d":0,
"activities_focus_7d":0,
"activities_quiz_7d":0,
"activities_meditations_7d":0,
"activities_planks_7d":0,
"activities_updated_at":"2021-03-15"
}
]`

could anyone think of a reason why i'm getting a 200 response while no changes are made?
