### ISSUE TITLE
Tag Manager acknowledge malware in mautic tracking code

### ISSUE THREAD

**Issue by iurisilvio** [mautic/mautic#7524]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
GTM triggers malware warning to mautic tracking code. I don't think mautic has a malware, but I'm looking for a fix for it. I'm unable to serve this tag while it is recognized as malware.

| Q   | A
| --- | ---
| Mautic version | 2.15.1

### Steps to reproduce
1. Add mautic tracking code to GTM and wait some time (?) for their malware checker. It can be 5 minutes or days.
2. GTM will acknowledge mautic tracking code as malware. 

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by escopecz** [comment]
Can you post a screenshot? Can you contact Google support to give us some explanation?

**Comment by iurisilvio** [comment]
Google support exist, so I tried here first.

I found some other with the same issue, but not with mautic.

https://support.google.com/tagmanager/thread/3549859

Based on this report, I obfuscated my URL (`['mautic', 'domain', 'io'].join(".")` instead of `mautic.domain.io`) and it is working. Looks like the malware alarm triggers for different URLs (.io domains?).

I'm closing it because it is not really a mautic issue. Maybe you can add some troubleshoot docs about it, but it is too specific.

**Comment by JohanFactory** [comment]
Hello,

Unfortunately I meet the same issue since 3 days, and even if it's a false positive, imho it's related to Mautic.
- changing domain don't solve the issue.
- changing config (anonymize ip, etc...) don't solve the issue.
- changing the js file name don't solve the issue.
- hosting elsewhere don't solve the issue.

Everytime, we use a new tag, and it's marked as malware a few minutes after validation.
FYI, we use Mautic since 3 weeks, on a fresh domain, without bad reputation (mailings are ok).

For some reasons, Google doesn't like the way Mautic track visitors. 
The related page doesn't help much : https://support.google.com/tagmanager/answer/6328489.

Integrating the tracking code directly in source code to avoid this issue ?
It's more dangerous, as we face the risk to get the entire website blocked for all Chrome visitors, as illustrated here : https://cypressnorth.com/web-programming-and-development/what-to-do-if-your-site-appears-as-malware-on-google/

It deserves further investigations, as for now, tracking feature of Mautic is not usable anymore, and that's quite annoying :(

**Comment by AkkuFresh** [comment]
I use Mautic tracking code and Google tracking code from different JS without any problem. I suggest to do not mix these items.

**Comment by iurisilvio** [comment]
I reopened the issue, because it is critical to anyone using AdWords, AdSense, GTM or even Google Search (everyone). It is not clear to me why this is tagged as malware. I added the tag without GTM and today my adwords were marked as malware.

![image](https://user-images.githubusercontent.com/105852/58962007-a2e52280-8780-11e9-951e-c8e76e45f341.png)

I removed `mtc.js` script to continue working with AdWords and a possible Google Search/Google Chrome flag.

Google give some useless links. No way to understand the issue.

https://support.google.com/adspolicy/answer/6020954?hl=en#311
https://support.google.com/google-ads/answer/1704381?hl=en

**Comment by iurisilvio** [comment]
GTM has a program to whitelist third-party tags. Have no idea if it would work. https://developers.google.com/tag-manager/program/

**Comment by wlandgraf** [comment]
Have you solved this?

**Comment by iurisilvio** [comment]
No, I removed the mautic tag from my critical path to be able to use ads.

**Comment by RCheesley** [comment]
Is this still an issue for people?

**Comment by RCheesley** [comment]
https://forum.mautic.org/t/create-a-google-tag-manager-template-for-mautic/11568 I made a feature request to create a community template for the template gallery.

**Comment by baaajola** [comment]
Same problem happened on my two websites recently.  2 weeks ago my ads in Google AdS were denied because of a malware on my websites. I didn´t know where the malware came from, so I sent a question to Google. They didn´t answer anyway after 1 week they made my ads work again. Today I wanted to add a new tag to Google Tag Manager and I found a big red warning there about a malware in the Mautic js code. I am attaching the screenshots. The Mautic forms on my websites still work but Google Tag Manager warns me that if I don´t remove the codes, they will be dissabled. I would appreciate you to solve it. I use Mautic version 2.13.1 Thx

![01](https://user-images.githubusercontent.com/57686598/68711206-805dfd80-0599-11ea-940d-c247b90ca6f0.JPG)
![02](https://user-images.githubusercontent.com/57686598/68711208-805dfd80-0599-11ea-85d3-e52a387007f4.JPG)
![03](https://user-images.githubusercontent.com/57686598/68711210-805dfd80-0599-11ea-867c-97bebde78d06.JPG)
![04](https://user-images.githubusercontent.com/57686598/68711211-80f69400-0599-11ea-8a9f-cae5da77ac5d.JPG)

**Comment by escopecz** [comment]
We need to know what Google finds malicious in that code. Please whoever has this problem send a question to Google. Until we know the reason we cannot resolve it.

**Comment by escopecz** [comment]
Fun fact: The Mautic tracking script was heavily inspired by the Google Analytics tracking script. Now Google finds it malicious 🤷‍♂

**Comment by baaajola** [comment]
I opened the Google Ads today and the warning is suprisingly gone. So it seems like solved. :-)

**Comment by RCheesley** [comment]
It seems it's not completely solved though if this continues to happen! I wonder if we just need to make a community template and get it accepted? I can try to find out more through some SEO channels in the meantime!

**Comment by RCheesley** [comment]
Closing this issue but let's keep an eye in case it reappears!

**Comment by Ferhat55** [comment]
This is still an issue. We use the generate.js to load forms in our website. Google Ads has identified this file as malware. Google says the domain where generate.js is loaded from contains malware (generate.js). They say this file reads personal information. 

Seems like we can only use the generate.js if we use it as non-functional cookies.

**Comment by gregorybrad** [comment]
This is still an issue for us as well. Any ideas on how to resolve it?

**Comment by gregorybrad** [comment]
@RCheesley do you have any suggestions on how to resolve this?

**Comment by gregorybrad** [comment]
@escopecz @RCheesley @iurisilvio 

Please could we reopen this issue?

**Comment by marcel-ambta** [comment]
We have called with Google multiple times on this problem without result, the only thing they advise us is to remove the javascript codes for the site. The tracking and the form javascript codes are marked as 'malware'. See the next support topic: https://support.google.com/google-ads/thread/33921288

I suggest everyone replying on that topic so to show the community members and Google that it is a serious problem.

**Comment by gregorybrad** [comment]
Looks like google has said that https://support.google.com/google-ads/thread/33921288?hl=nl# is the wrong place to ask the question. Does anyone know where the right place is to ask the question?

**Comment by dev-marcel** [comment]
I also have send a complaint with the complaint form, responded with the question where we can go and send a extensive mail to the Adwords support team.

Will let you guys know when i get any response.

**Comment by dev-marcel** [comment]
I have received the following response on 1 of my messages:

> Hello Marcel from Nuil,
>
>On Wednesday March 18, you filled in a contact form regarding malware detection of the Mautic >program . You have also shared the link of Github with us, which is very good of you that you have >started doing research yourself. I also looked at the thread that you prepared, it is a clear >statement.
>
>I can inform you that Google Ads cannot always guarantee that everything will work in >conjunction with " Third Party Programs ". Because of this, I can mention to you that Google >Mautic probably wouldn't whitelist . In addition, I would advise you to use a so-called " >Workaround ", since you indicate that you are using a code for a form, I was curious if you are >familiar with " Lead form Extension " in Google Ads, since this can work as a potential solution.
>
>We thank you for your feedback and it will be forwarded to the appropriate department.
>
>We cannot guarantee an outcome and we cannot promise that you will receive another message >about this. But I hope for you that something can be changed in the future, so that you can also >organize your website the way you want and with that you can also advertise. 
>
>I hope to have helped you with your questions, if you still have more questions regarding this >email, please let us know.

Due to the slow process on this we are working on a work-around for our own websites, if we find a good solution we will let it know.

**Comment by dev-marcel** [comment]
2 new updates on this:

1. An update from the community, the asked me to contact Mautic...
>I would suggest to contact Mautic, because I can not imagine you're their only user who faces these issues.

2. Adwords has now figured out they have blocked the whole domain where we host multiple Mautic environments. So not only the tracking code and form code are marked as malware also the domain has now been marked as harmfull. That means al sites that has any references to that domain are blocked from Adwords.

**Comment by Ferhat55** [comment]
I've also had contact with Google Ads about this issue. After a lot of communication they eventually told us that Mautic uses trackingscripts which do not ask for consent. Because of that Mautic is marked as malware. The only solution is for Mautic to contact Google to find a solution for the whole community is what Google told me. 

In the meantime we can't do much, but wait for Mautic and Google to work together on this issue.

**Comment by gregorybrad** [comment]
This is going to be a large issue for Mautic. So many sites run adwords as well as Mautic.

**Comment by gregorybrad** [comment]
Hi everyone, are there any ideas on how to assist with this?
Happy to help where I can.

**Comment by Ferhat55** [comment]
There is not much we can do. Google told us that Mautic should pick this up with Google Ads. @RCheesley Any luck finding a solution?

**Comment by RCheesley** [comment]
@Ferhat55 I posted on the forums the steps we need to follow in order to submit a template to their community gallery. Whether or not that will stop the problem I don't know!

Here's the forum thread: https://forum.mautic.org/t/create-a-google-tag-manager-template-for-mautic/11568

**Comment by OmerGafny** [comment]
Can confirm the issue is also happening in 2.16.0

**Comment by coreyworrell** [comment]
Any updates on this? Currently we cannot run Google ads at the same time we use Mautic on any of our client's site.

**Comment by gregorybrad** [comment]
@coreyworrell there is a post by @RCheesley in this thread on creating a template for google tag manager. I have no clue how to do it but I believe that's the next step to help with this problem.

**Comment by RCheesley** [comment]
Hi folks, I managed to get in touch with some folk at Google and here's where we are at:   

Google does run all Custom HTML tags through a malware detection system. If a URL that a script uses is flagged by that system, it will accordingly flag and pause the tags in GTM as malware. There are occasionally false positives, or it could be possible that their URLs are associated with malware in some way. More information is here on ways to resolve those issues: https://support.google.com/tagmanager/answer/6328489?hl=en

Secondly, if you implement the Mautic script as a custom template - https://developers.google.com/tag-manager/templates - instead of a custom HTML tag, then that should help.  

Lastly, **if we can provide a domain that's failing, the team can do more digging** to see if there are any incorrect malware flags.

So as a starter **we need to write a custom template for GTM** and get that shared in the [community template gallery](https://developers.google.com/tag-manager/templates/gallery). Anybody up for taking that on?

If anybody has an instance that is currently failing and throwing the malware warning please message me on Slack!

**Comment by RCheesley** [comment]
Still an active issue :)

**Comment by beananimal** [comment]
It is not just you guys... Google appears to mark just about any tracking script or affiliate marketing pixel and associated domain as "malicious" and there is no recourse. None of this appears in any google transparency report, tool or support mechanism. This is by design.  This is not about google protecting end users, it is about google preventing affiliate revenue that they are not monetizing. Sadly, with each passing day, more advertisers are rebuilding their landing pages and websites around GTM and the problem is becoming prolific.

**Comment by ill13** [comment]
Will website running ```mtc.js``` or any Mautic tracking object be delisted from Google search? 

-Should I remove the tracking code from my websites or risk blacklisting?

**Comment by dev-marcel** [comment]
Personally I think we as a community should look at server side tracking to keep Mautic future proof. Cookie tracking will slowly become impossible. 

In our eyes the proper way should be:

1. (Short-term) We start with making it possible to add a local JavaScript file, nobody knows exactly how the Google algorithm works but i think loading the js from the same domain will decrease the chance of being blocked by Google.

2. (Short-term) We change the logic so the cookies will be placed (with logic in the local js file) on the same domain. (We can use API calls with identifiers)

3. (Long-term) We create  PHP/.NET files that you can run on the same domain that can receive messages, then over the API (or for now to keep it simple with a curl post to the normal tracking endpoint).

4. (Long-term) We create/update plug-ins for common CMS systems where it is fully server side and the form logic also happens server side.
We then give the site developer the option to send extra data/trigger actions over a local API (See Gravity forms for example: https://docs.gravityforms.com/category/developers/php-api/)

5. We can look for 1 shared cookie to track over multiple domains as an optional option. 

Feel free to share your opinion/views on this.

**Comment by clouedoc** [comment]
Another solution would be to use something such as the open-source
FingerprintJS (https://github.com/fingerprintjs/fingerprintjs)

**Comment by eruizmillan** [comment]
Hi, Is there new information on this? I see that the incident has been open for years and the problem continues. Do you know any information?
