### ISSUE TITLE
Hebrew Page Title Tracking Error

### ISSUE THREAD

**Issue by morettic2015** [mautic/mautic#7525]
## Bug Description

@escopecz I have an issue with Hebrew Language. After update to 2.15.1, Tracking URL is not storing original page title but a different not hebrew not english. Gibrish. 

Take a look at the screenshot. The original page been tracked is in Hebrew. Before update it worked fine. Now we have this strange behavior.  Any idea? 

<img width="960" alt="hebrew error" src="https://user-images.githubusercontent.com/11476006/57651920-d7f8bd80-75a4-11e9-91d3-d2bef877c8ab.png">

| Q   | A
| --- | ---
| Mautic version | 2.15.1
| PHP version |  7.0.32-4+ubuntu18.04.1+deb.sury.org+1
| Browser |  Chrome

### Steps to reproduce
1. Visit a page been tracked in Hebrew language
2. Open Contacts on Mautic 
3. See the page title been tracked
 
### Log errors
There are no error log related to this issue at Mautic.

**Comment by escopecz** [comment]
Ok, you've created a new issue as well. Here is copy of the comment from your [previous report](https://github.com/mautic/mautic/issues/7146#issuecomment-491974632):

@morettic2015 your issue is very different from the original description. Please start a new issue or find a better one. This is the change that causes troubles: #7080

So far we are not which is better. If it fails completely in some cases or if the transliteration is more problematic.

**Comment by rmrmnrm** [comment]
I came from #7568 
The bug with contents of #7080   occurred when upgraded to 2.15.1.
It did not occur before the upgrade (2.15).

**Comment by morettic2015** [comment]
Same here @rmrmnrm 

It was working before 2.15.1 upgrade. So need a fix not even one that is temporary 🗺️. Like some UTF UNICODE on some part of Mautic core.

Any ideias?

**Comment by morettic2015** [comment]
I did the upgrade for 2.15.2. Problem remains so i decided to investigate and found a particular fix fo hebrew language.

Solution is doing no transliteration from page Title. Take a look @npracht @escopecz @rmrmnrm @davelester 

It just fixed the issue for me at 2.15.2; Crazy.

<img width="854" alt="transliteration solution for herbew 2 15 2" src="https://user-images.githubusercontent.com/11476006/62735450-9475ea00-ba01-11e9-94df-7c2979b97e5a.png">
.

**Comment by escopecz** [comment]
That's how it used to be. The transliteration was a fix for SQL errors caused by emoticons or similar characters that MySql cannot store unless it uses utf8mb4 encoding. Unfortunately, this is one of the cases where one code change helps use 1 case and breaks another. It will be solved with Mautic 3 which can enforce use of the utf8mb4 encoding.

**Comment by sjima** [comment]
@escopecz 
Could you let me know when will Mautic 3 be released?

**Comment by escopecz** [comment]
I would like to tell you. But nobody knows.

**Comment by chendwww** [comment]
> Ok, you've created a new issue as well. Here is copy of the comment from your [previous report](https://github.com/mautic/mautic/issues/7146#issuecomment-491974632):
> 
> @morettic2015 your issue is very different from the original description. Please start a new issue or find a better one. This is the change that causes troubles: #7080
> 
> So far we are not which is better. If it fails completely in some cases or if the transliteration is more problematic.



> That's how it used to be. The transliteration was a fix for SQL errors caused by emoticons or similar characters that MySql cannot store unless it uses utf8mb4 encoding. Unfortunately, this is one of the cases where one code change helps use 1 case and breaks another. It will be solved with Mautic 3 which can enforce use of the utf8mb4 encoding.

Hi, we set our MySQL database to utf8mb4 (new database), but we still can't get the correct page title? How to solve it?

**Comment by chendwww** [comment]
I just test it on Mautic 3.0.1, the issue is still there, see: #8984
