### ISSUE TITLE
[bug] Find social network profiles not working

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#76]
When I add a new lead, if I go to search for social profiles I'm not getting any results for folk I know have profiles with the same name/email address (and a Gravatar has already been found) - no error message either.

**Comment by alanhartless** [comment]
Right now, only fields that can return exact matches are used.  So for Facebook, Twitter, and Instagram, you need a lead field with an alias of facebook, twitter, and/or instagram and have the lead's handle already populated. Google Plus will allow us to search by email so it'll search for values in email and/or googleplus lead fields.  Foursquare will allow us to search by email and/or twitter handle (lead field with twitter as the alias).

The APIs that allowed fuzzy searches based on name or email sometimes resulted in hundreds of results.  We did explore the option to filter through and choose potential matches but ditched that for now due to the number of results based simply on name. Unfortunately, only G+ and Foursquare allowed search by email.

We definitely plan to integrate social media a lot more in future versions.

Thanks,
Alan

**Comment by RCheesley** [comment]
OK, that wasn't clear at all but is probably more due to my own expectations, but I'd still have expected Google+ to have found it, or Foursquare.  I know the users I was searching for have the email listed on their G+ page and I've got the G+ API set up.

**Comment by alanhartless** [comment]
Okay, found a bug that double encoded the email resulting in the user not being found.

**Comment by alanhartless** [comment]
Oh and about the clarity, I apologize.  Maybe this will clear it up bit (or it could make it muddier :-/ ):

On the left is the network; on the right are the required lead fields in order to find the profile (listed as the field's alias and of course requires the lead to have a value for the field)

Facebook    - facebook
Twitter          - twitter
Instagram    - instagram
Google+      - googleplus, email (if set to public)
Foursquare - twitter, email

**Comment by alanhartless** [comment]
The issue with finding users based on email in Google+ and Instagram should be fixed in RC3.  Let us know if this is not the case and we'll reopen the issue.

Thanks!
Alan
