### ISSUE TITLE
How can I attach a picture file or a pdf file to a contact in the user interface?

### ISSUE THREAD

**Issue by bbs2009** [mautic/mautic#7609]
Good day.
Thank you very much for the wonderful product.
I have a question. How can I attach a picture file or a pdf file to a contact in the user interface?
Or how can this be done in another way?
We want to attach copies of invoices to contacts.

Thanks you. Bogdan

**Comment by kuzmany** [comment]
Search in pull requests for notes attachment

**Comment by kuzmany** [comment]
https://github.com/mautic/mautic/pull/7386

**Comment by npracht** [comment]
Hi @bbs2009 can you please test: https://github.com/mautic/mautic/pull/7386/ ?

**Comment by everettmarshall** [comment]
Hey - I'm new to Mautic and just figuring out its development.  What is the status of this feature? Is it not in the final build? I have a client with 4.2.2 and the feature does not appear to be active.

**Comment by RCheesley** [comment]
@everettmarshall  it hasn't been released because we haven't had enough testers.

Please take a look https://github.com/mautic/mautic/pull/7386 - you should be able to click to open it in Gitpod to test it.

We have the last day of our community sprint tomorrow so if you need help with testing please join us on Slack (https://mautic.org/slack for an invite) and join #community-sprint.
