### ISSUE TITLE
Add support to separate label from values in form field checkboxes, radios, and selects

### ISSUE THREAD

**Issue by healthstatus** [mautic/mautic#761]
I have added two fields in my lead list with type of Boolean, want_a_brochure, and want_a_demo.

I want to put two checkboxes on a form, that when checked will populate each field.  There is no way to add a 1/0 response (that I can figure out) in the form builder.

**Comment by npracht** [comment]
_Hi, this feature is very important to sort a high data quality and allow flexibility to show option for visitors. Let's add a bit more of description._

## Need
When you create a `select form input`, it is very important to display a value which is "marketingly" acceptable. Most of the time, the way **you'd like to show values** is far from how **you wanna stock it in the database**.
 
## "How to proceed" recomandation
On the input setting, you could simply modify it by instead of having 1 column of values:
* Displayed values
* Saved values (ON/OFF)

![capture d ecran 2016-04-05 a 20 33 19](https://cloud.githubusercontent.com/assets/14075239/14293833/9d805e64-fb6e-11e5-9b63-9ed0cde7b90a.png)

## Competitor example

![capture d ecran 2016-04-05 a 20 42 37](https://cloud.githubusercontent.com/assets/14075239/14293920/f9672ba4-fb6e-11e5-88ce-c64c4a7e3129.png)
