### ISSUE TITLE
nginx, Symfony 4.x, ... why not?

### ISSUE THREAD

**Issue by antondachauer** [mautic/mautic#7701]
Why are you not up to time? Mautic uses Symfony 2.8. Why not Symfony 4.2 or 4.3?
And why is nginx not supported by default?

The `index.php` file is in the root folder - why not in an seperated `web` folder? Thats better in case of security on nginx servers.

**Comment by virgilwashere** [comment]
Mautic runs fine with nginx.

```nginx
index index.html index.php

#rewrite /index.php/blah to /index.php

location / {
    tryfiles $uri $uri/ /index.php?$is_args$args
}

# location blocks for cache control
# no php support in uploads,
# no access to /app except */Assets/*

location ~* ^/(index|upgrade|upgrade/upgrade)\.php$ {   #ish !!!!
    index index.php
    include snippets/fastcgi-php.conf
    fastcgi_pass unix:/run/php/php7.2.sock
     fastcgi_params SCRIPT_FILENAME $request_filename
}
```
(from memory, on phone)

What security issue are you referring to?

As for Symfony framework, I'm not a PHP developer.

**Comment by npracht** [comment]
Hi @antondachauer! Simply because this is a lot of work and because mautic exists for more than 3 years when Symfony 2 was running!
But the plan is to move to Symfony 3.x in next major release Mautic 3.0. If you'd like to help fo the refactoring this is awesome.
Please join the community chat on Slack in the #community channel and share your wish to contribute.
