### ISSUE TITLE
Mautic Dynamic Content not working on WordPress

### ISSUE THREAD

**Issue by AsianAmericanManAD1979** [mautic/mautic#7708]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Mautic Dynamic Content not working on WordPress

| Q   | A
| --- | ---
| Mautic version | v2.15.1
| PHP version | 7.1.28
| Browser | Google Chrome Version 75.0.3770.142 (Official Build) (64-bit)

### Steps to reproduce

I want to selectively display an email subscription form in a WordPress post.  I'm using WordPress 5.2.2 with the Mautic WordPress plug-in.

If a visitor has already entered his or her email in the email subscription form, I want that form to no longer display when the user visits again.

So, I created a Dynamic Web Content item with the slot name hidden-form, with empty content, and with a 'not empty' email filter item.

I've inserted the following HTML code in my WordPress post.

<div data-slot="dwc" data-param-slot-name="hidden-form">
  (Mautic form display code here.)
</div>

However, no cigar.

When I enter an email address in the form and press the submit button, the email address correctly gets added to the Mautic contacts.

However, when I refresh the WordPress post webpage, the form still displays.

Is this a problem in Mautic, or am I doing something wrong?

I followed the instruction in the Mautic doumentation, but it didn't work.

Is it possible to make a Mautic form no longer display on a WordPress web page, once the visitor enters an email in the form and presses the submit button?  Or is this currently a bug in Mautic?

 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment]
Hi @coding-machine0001 could you write a clear **How to reproduce** procedure. We need that.
Also did you try with some content instead of empty ? Maybe that's the issue ?

**Comment by coding-machine0001** [comment]
I have tried setting the Dynamic Content content to something other than blank.  It still doesn't work.

WordPress version is 5.2.2—the most recent version yet.


The following is the step to reproduce the problem.

1.  Create an AWS (Amazon Web Services) Lightsail instance ($5 per month, 1 GiB RAM), with the WordPress Multisite blueprint by Bitnami.

2.  Create an AWS (Amazon Web Services) Lightsail instance ($5 per month, 1 GiB RAM), with the LAMP (PHP 7) blueprint by Bitnami.

3.  Follow the instruction at https://docs.bitnami.com/aws/infrastructure/lamp/get-started/add-applications-amp/ to install Mautic on the LAMP (PHP 7) AWS Lightsail instance.

4.  Install and activate 'WP Mautic' WordPress plugin.

5.  Install and activate 'Insert Headers and Footers' WordPress plug-in to include the Mautic form JavaScript in the footer.

6.  Install and activate 'SiteOrigin CSS' WordPress plug-in to include the Mautic form CSS.

7.  In Mautic, create an email subscription form.

8.  In Mautic, create a dynamic content item with the internal name 'hidden form', with no contents, with the slot name hidden-form, and with an email-not-empty filter.

7.  In 'Insert Headers and Footers' WordPress plug-in settings, include the Mautic form JavaScript.

8.  In 'SiteOrigin CSS' WordPress plug-in, include the Mautic form CSS.

9.  Create a WordPress blog post as a super admin user with the following code in a custom HTML WordPress editor block.

<div data-slot="dwc" data-param-slot-name="hidden-form">
  (Mautic form display code here.)
</div>

10.  Click Update to publish the post.

11.  View the published post.

12.  Enter an email address and click the submit button.  (This email address gets added to Mautic contacts, as it should.)

13.  Refresh the post webpage.  (the Mautic form still displays, although it shouldn't, since the email address is now present in Mautic contacts.)


If you need more info, let me know.

Thank you.

**Comment by veponen** [comment]
I have similar issue. I am not using wordpress.

**Comment by RCheesley** [comment]
Hi there,

Did you try this with some actual content in the slot rather than it being empty?

Also, if you can try this with Chrome's developer tools open, can you see the requests going to Mautic for the dynamic content? If so, does it receive it OK or are there any errors?

**Comment by sensalot** [comment]
Are you able to do it successfully on a Mautic Landingpage. First do that, then move to WP.

**Comment by adiux** [comment]
I'm using dynamic content on my site and DWC works. It's Wordpress 5 with Mautic 2.16.1. Campaign-based and not. I use the WordPress Mautic Plugin. E.g. I display a dynamic product based on user behaviour, or all.

`[mautic type="content" slot="product-spotlight"]<a href="/mautic-installation/">Show Products</a>[/mautic]`

See it in action:  https://www.idea2.ch

**Comment by RCheesley** [comment]
Hi @adiux can you confirm if this is also working for 3.2.1?

**Comment by npracht** [comment]
Closing for lack of feedback. If more later, we'll re-open the issue.

**Comment by diamondtheta** [comment]
Hello!

I have a similar issue.
My mautic dynamic content is not loading for the first page load, but it loads every time after F5 page refresh.
So the code should be properly set up, but it seems that my mautic subdomain is too slow and it can't get back the data in time to here for example: https://orult.hu/video/hatekony-irodai-munkavegzes/
Under the "( Ha netán nem látnád akkor frissíts és várj +10 másodpercet ! "
text there is the mautic dynamic content (the one link with blue) what only shows after refresh .
What could be the problem?
Should something be load async? how??

Thanks,
