### ISSUE TITLE
Campaign actions stuck on pending

### ISSUE THREAD

**Issue by chodalski** [mautic/mautic#7751]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Made a campaign that takes anyone who has submitted a form and is added to a segment.
![Campaign Automation Screenshot](https://user-images.githubusercontent.com/11725033/62286753-49cbff00-b450-11e9-868e-40aa2b6362a1.png)

However, the campaign's action to add them to a segment is stuck on pending and has been for the last couple of days.

![Campaign Outline Screenshot](https://user-images.githubusercontent.com/11725033/62286887-96afd580-b450-11e9-98c4-a173eff88559.png)

It's finding the contacts fine when they submit the form and put them into the campaign it just never advances past that and them to the segment. Was hoping you could help me?

| Q   | A
| --- | ---
| Mautic version | v2.16.0-dev
| PHP version | PHP Version 7.0.33-0+deb9u3
| Browser | Google Chrome Version 76.0.3809.87 (Official Build) (64-bit)

### Steps to reproduce
1. Create a segment for a campaign.
2. Create a form.
3. Create a landing page using a form created in step 2.
4. Create a campaign that adds contacts that submitted the form to segment created in step 1. 
5. Have contacts enter in their details and submit the form.
6. Check to see if contacts are added to the campaign.
7. Check to see if campaigns actions complete

 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by CarlVanderLaan** [comment]
@chodalski, were you able to fix your issue? If so, would you be able to share with me what you did? I'm having the same issue.

**Comment by gmenezesg** [comment]
Same here.

**Comment by Gp2mv3** [comment]
Hi,
I have the same issue with a decision (on a contact field value). In version 3.1.1
And we also had it in the past with version 2.6.x with Emails.

what was your fix if you solved it ?

Regards

**Comment by linuxhead2** [comment]
Is this solved? Facing the same issue - whats the point of having Mautic if you can't send emails. This is a useless product.

**Comment by linconrezende** [comment]
I'm had the same problem.
PHP Version 7.3.26
Mautic v3.1.2

I managed to solve by finding out what file was throwing the error and then fixing the bug comparing with other migration files that was working. 
In my case, the problem was the file: Version20191017140848.php

I had to:

- comment this line: // use Doctrine\DBAL\Migrations\SkipMigrationException;
- add this line: use Doctrine\Migrations\Exception\SkipMigration;
- change the line: throw new SkipMigrationException('Schema includes this migration');
to the following line: throw new SkipMigration('Schema includes this migration');


![image](https://user-images.githubusercontent.com/9609091/107804068-39355e00-6d42-11eb-9ef7-85645a0f25f3.png)
![image](https://user-images.githubusercontent.com/9609091/107804174-5833f000-6d42-11eb-8ffb-d4b72f304407.png)

After that...
/usr/bin/php /var/www/html/mautic/bin/console doctrine:migration:migrate
![image](https://user-images.githubusercontent.com/9609091/107804288-7994dc00-6d42-11eb-8fae-ac66a48e6e7a.png)

/usr/bin/php /var/www/html/mautic/bin/console doctrine:migration:status
![image](https://user-images.githubusercontent.com/9609091/107804391-9a5d3180-6d42-11eb-8736-5b9f3a26c5e2.png)

So far it seems to be working. I think everything is fine now.
