### ISSUE TITLE
Error installing Mautic 2.15.2

### ISSUE THREAD

**Issue by jameswill** [mautic/mautic#7771]
I have noticed that the new version for Mautic has been released on github. i. e 2.15.2 https://github.com/mautic/mautic/releases However when I try to download the package from the official website ( https://www.mautic.org/download/ ) it redirects to previous stable version and downloads Mautic 2.15.1 package.

Also when I try to install manually through package which I have downloaded from Github (2.15.2) I am not getting installation page to install the script. Instead it gives following error. 

Not Found - 500

Internal Server Error.

On further debugging, I found out that the installer starts on apache >= 2.4 but the requirement for the same is set to apache 2.x https://www.mautic.org/download/requirements/  However, installation doesn't completed on apache 2.4 as well.

Can anyone please let me know is there any issue in the package or am I missing out on something ?

**Comment by directpromo** [comment]
perhaps this is due to errors like #7758 and #7769
Сan you check the server logs?

**Comment by escopecz** [comment]
@jameswill Thank you for your report! The problem that it's downloading 2.15.1 instead of 2.15.2 on https://www.mautic.org/download/ is on me. I forgot to add the asset to the right category when the automatic release process failed. I can easily fix that but there are other significant issues reported for 2.15.2 so I will keep the official download on 2.15.1 for now. 

I downloaded 2.15.2 from Github release page and installed it from scratch. I was able to do it and log in to the fresh Mautic. So I will close this issue as @directpromo noted it will be related to one of those other 2 issues. For the record, I have `Apache/2.4.39 (Unix) OpenSSL/1.0.2s PHP/7.2.18`.
