### ISSUE TITLE
Form [action] don't respect configuration URL

### ISSUE THREAD

**Issue by ricardojlrufino** [mautic/mautic#7849]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Form [action] don't respect configuration URL.
That way the scripts don't work correctly.

| Q   | A
| --- | ---
| Mautic version |  v2.15.1

### Steps to reproduce
1. Access mautic by URL: marketing.site.com.br
2. Configure Site URL (settings) : marketing-direct.site.com.br:3333

In frame: The Script will generated using SITE URL from configuration
But the form[action]  use the url I'm accessing by browser

Using diferente URLs is a workaround to this #7684

**Comment by npracht** [comment]
Hi @ricardojlrufino this is known, it is because how the cache is constructed. You should access your mautic instance via URL 2 to generate the correct relative links in mautic form.
Or you can rebuild form cache with the action hereunder:
![Capture d’écran 2019-09-04 à 15 44 26](https://user-images.githubusercontent.com/14075239/64260280-e4759d00-cf2a-11e9-9adc-6e82f071ef43.png)

**Comment by RCheesley** [comment]
Closing this issue due to a lack of recent responses.
