### ISSUE TITLE
500 on view, Timestamp instead of date in sql ?

### ISSUE THREAD

**Issue by robov** [mautic/mautic#7876]
mautic 2.15.1

On viewing a newly created contact I get 500
In the log there is the query containing : 
`SELECT ip.date_AND (l.date_added >= '1568445835')) `

When I run the query direct into the database I get :
`Incorrect DATETIME value`

Which seems logical as it is a timestamp that is passed into the sql

**Comment by robov** [comment]
Just upgraded to 2.15.2 , issue still remains

**Comment by heathdutton** [comment]
The issue is in your MySQL syntax.

When using quotes, you are not using a timestamp but a string. True timestamps are integers. Secondly, these are datetime fields not timestamp fields. So internally MySQL is storing a timestamp but presenting it as YYYY-MM-DD HH:MM:SS. So you will want to use something like ISO8601.  'YYYY-MM-DD HH:MM:SS' would work.

If you want to use timestamps for some reason, you totally can... Just change your query accordingly using `l.date_added >= UNIX_TIMESTAMP(1568445835)` or similar. That will convert your integer timestamp into a datetime format for you.

**Comment by robov** [comment]
I just took the docker container. I did not change anything on the code
it shows up in both the 2.15.1 and 2.15.2

The only thing I changed on the docker setup is that I use another mysql container than in the default docker setup that creates another container. So it is not in the code, it might be due to different mysql versions

I do not have any plugins installed

**Comment by robov** [comment]
Could it be related to mysql versions ? / settings ?

**Comment by altendorfme** [comment]
> Poderia estar relacionado a versões mysql? / configurações ?

https://github.com/mautic/mautic/issues/7612

**Comment by RCheesley** [comment]
Closing as a duplicate of #7612
