### ISSUE TITLE
Mautic Campaign is not sending a emails

### ISSUE THREAD

**Issue by athaylean** [mautic/mautic#7949]
## Bug Description
Hey guys, I have configurated Mauric with SMTP from Mailgun. Everything works fine including segments and testing mails, but when I try to send mails via capagain Mautic doesn't do that. There is no created messages files in `app/spool/default`, no errors in logs. I tried doing it manually running comands from CLI, but no results. I tried run it without superuser permissions and had this error: 

```
$ php /ops/applications/mautic/app/console mautic:campaigns:update --force
```
```
PHP Warning:  fopen(/ops/applications/mautic/app/cache/prod/../run/sf.mautic-campaigns-rebuild.328b5aa5123471bb393f5cab2dbbfae288ed5e0086e91338bd36cd286a80e7d4.lock): failed to open stream: Permission denied in /ops/applications/mautic/app/bundles/CoreBundle/Command/ModeratedCommand.php on line 157
PHP Warning:  flock() expects parameter 1 to be resource, boolean given in /ops/applications/mautic/app/bundles/CoreBundle/Command/ModeratedCommand.php on line 158
Failed to lock /ops/applications/mautic/app/cache/prod/../run/sf.mautic-campaigns-rebuild.328b5aa5123471bb393f5cab2dbbfae288ed5e0086e91338bd36cd286a80e7d4.lock.
Script in progress. Can force execution by using --force.
```

| Q   | A
| --- | ---
| Mautic version | 2.15.3
| PHP version | 7.2.19-0
| Browser | Chrome 77
 
### Log errors
I turned on debug mode.
https://pastebin.com/vaZwcUwQ

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by osidney** [comment]
+1

**Comment by altomarketing** [comment]
I had the same problem, but it was I who had caused it. **Attached as I solved it, maybe it will serve someone.**

My mistake was how I did not know if I was configuring the delivery crons well, and I am very impatient, I tried to run the cron command from the console but as root and not as the Apache user who owns the website where mautic is hosted.

This caused the cron to save files in / app / cache as root, and then the Apache user  wants to run the cron to send, could not delete those files because they belong to the root user, giving me the same error.

I solved it by deleting the / app / cache folder completely and waiting patiently for the Apache user to run the cron in due course, generating the corresponding cache files, but not as root.

**Comment by RCheesley** [comment]
@athaylean does @altomarketing 's suggestion help resolve your issue at all? Are your file/folder permissions/ownership as would be expected?

**Comment by altomarketing** [comment]
my suggestion resolved my issue, because root was generating files as root (my mistake) and mautic could not erase those files in the next cron.

**Comment by athaylean** [comment]
@RCheesley I was off for last week. I am going to check this today.

**Comment by RCheesley** [comment]
@athaylean great, please update accordingly!

**Comment by athaylean** [comment]
I tested it for last 2 weeks and everything works. Thanks for help :)

**Comment by emmanueladk** [comment]
This is the best response, thank you for sharing it.
