### ISSUE TITLE
Campaign Lists: Downloads of Assets don't link to Forms

### ISSUE THREAD

**Issue by lance-spurgeon** [mautic/mautic#80]
As you can't link two 'Decisions' together its a causes a problem when the intention is to send a email to complete the form:

Send Email --> Complete Form --> Download Asset

1. Complete form -->  download of the asset (Y/N) (I can only link to No.2  send a send a thank you email - which doesn't make sense)
2. Complete form -->  Send thank you email --> Opened (Y/N) ...

What is the solution to this

**Comment by alanhartless** [comment]
How are you connecting the asset to the form? Is it downloaded immediately after submitting the form (via a form submit action) or a link in an email sent to the user after submitting the form? If immediately downloaded, then I'm not sure there is a need for download of an asset (y/n) decision as it is a given yes when they submit the form. So you would just have the flow of number 2 above and you'd be good.

If you are sending the asset as a link in the thank you email and opening the asset is the real focus, then you would skip the 'Opens email' decision and just use the 'Downloads asset' decision since if they downloaded the asset, it is assumed they opened the email.  If you want to differentiate actions based on whether they just opened the email or opened the email and downloaded the asset, then you would  have to have to create and possibly duplicate actions attached to an opens email and downloads assets decision paths.  In this scenario, the yes path of the downloads asset decision would only have the actions that would NOT happen if they just opened the email. Does that make sense?  Your campaign may look something like this:

http://cl.ly/image/1L0V1a0D1R0d/Image%202015-02-28%20at%204.42.54%20PM.png

If they open the email, the lead gets 5 points. If they also click the link and download the asset, they end up with a total 15 points.

As we talked about, we do plan to change this flow to allow an action to be associated with multiple decisions in a future version of Mautic.
                                                                            
Thanks,
Alan
