### ISSUE TITLE
M3: Mailer Transports - MandrillTransport

### ISSUE THREAD

**Issue by alanhartless** [mautic/mautic#8019]
Refactor Swift Mailer 5.x to 6.x 

- [x] \Mautic\EmailBundle\Swiftmailer\Transport\MandrillTransport

```
6.0.0 (2017-05-19)
------------------

* added Swift_Transport::ping()
* removed Swift_Mime_HeaderFactory, Swift_Mime_HeaderSet, Swift_Mime_Message, Swift_Mime_MimeEntity,
  and Swift_Mime_ParameterizedHeader interfaces
* removed Swift_MailTransport and Swift_Transport_MailTransport
* removed Swift_Encoding
* removed the Swift_Transport_MailInvoker interface and Swift_Transport_SimpleMailInvoker class
* removed the Swift_SignedMessage class
* removed newInstance() methods everywhere
* methods operating on Date header now use DateTimeImmutable object instead of Unix timestamp;
  Swift_Mime_Headers_DateHeader::getTimestamp()/setTimestamp() renamed to getDateTime()/setDateTime()
* bumped minimum version to PHP 7.0
* removed Swift_Validate and replaced by egulias/email-validator
```

**Comment by alanhartless** [comment]
Completed to get M3 loadable https://github.com/mautic/mautic/commit/a41ba1a2ca305f50ca5318d9aaae1d3576cf0b93

**Comment by escopecz** [comment]
Mandrill doesn't exist anymore.

Can we remove Mandrill from the supported email transports? When I try to log in to Mandrill it shows a warning that Mandrill doesn't exist anymore and that I should log into Mailchimp. When I log in to Mailchimp I can either create API key which doesn't work for the Mandrill integration or create a Mandrill API key but that just redirects me back to the same page so I cannot create a Mandrill API key.

**Comment by escopecz** [comment]
So it seems it's only a paid option for Mailchimp users. We cannot test it. I can test that it tries to connect but fails on an invalid API key. We will have to wait till somebody from our community who use it will tell us that it has issues.

**Comment by jclimac** [comment]
Hello!

Sorry if I re-open this issue, just do that because this is the last issue I found related to Mandrill.

Not sure if this issue was tested or abandoned due to no use.

I'm using Mandrill and I'm getting the error bellow when I try to send or test connection on Email setting screen. 

Despite the error the email is sent with no errors. Both the test and regular emails are sent normally. But even though emails are sent they are not being registered as sent, so Mautic is not registering clicks and openings related to that emails.

`[2020-07-24 11:15:14] mautic.ERROR: [MAIL ERROR] Mandrill failed to authenticate (send); my@email.com {"exception":"[object] (Swift_TransportException(code: 0): Mandrill failed to authenticate at /var/www/mautic.dir/app/bundles/EmailBundle/Swiftmailer/Transport/AbstractTokenArrayTransport.php:300)"} []`

From Mandrill API logs, this is the response:
`[
    {
        "email": "to.email@test.com",
        "status": "sent",
        "_id": "bcf9f58ef651437dbe941d9645903cDS",
        "reject_reason": null
    }
]`

I'm on Mautic 3.0.1

Is there anything I can to to solve this? 

Thank you!!
