### ISSUE TITLE
Categorized Points

### ISSUE THREAD

**Issue by that0n3guy** [mautic/mautic#818]
Categorized points could be used for specific product marketing for example.  

If userA has 400 "product 1" points, event fires.  
A Different event fires if userA has 100 "product 2" points.

**Comment by that0n3guy** [comment]
I think this is similar to: https://github.com/mautic/mautic/issues/581

**Comment by zapur1** [comment]
Another thought that I had of how to implement this is to have a percentage attached to a tag so a tag effectively has points but can be started at say 1% and then incremented up to 100% or down from there.

Would that work for what you were thinking?

**Comment by escopecz** [comment]
@zapur1 I think you can imagine points to be percents and use it like that. Question is what should happen if some lead already have 100% and he triggers a new action with one more percent. Should he get 101%?

Or do you want it to be like a contest percent? Like 100% is the point amount of the lead with the most points and then you'll also see how successful a lead is in comparison to the most successful lead?

I'll mark this as duplicate, because it is similar to https://github.com/mautic/mautic/issues/581

**Comment by that0n3guy** [comment]
Thanks for the quick response.  I agree with @escopecz in that the percentage thing causes issues.

> Or do you want it to be like a contest percent? Like 100% is the point amount of the lead with the most points and then you'll also see how successful a lead is in comparison to the most successful lead?

This seems like a reporting or dashboard "widget" thing which may be a different feature request.

I'll put any further comments/ideas in #581.

**Comment by alanhartless** [comment]
Closing in favor of #581
