### ISSUE TITLE
How to use Amazon SES API protocol instead of SMTP

### ISSUE THREAD

**Issue by Arnaud-lebrief** [mautic/mautic#8241]
Hello,

i am looking for a solution to improve my sending performances.

I use Amazon SES with dedicated IP adresses and a capacity of 120 mail/second. But it takes 20 minutes to send to a 7k emails list of suscribers. 

I would like to transfer my whole database (160K) on mautic but i will need to send to the whole list in less than 15 minutes...

**Comment by hrouissi** [comment]
see :  [#7805](https://github.com/mautic/mautic/pull/7805)

**Comment by npracht** [comment]
@hrouissi what is the link with the mentioned PR ?

**Comment by hrouissi** [comment]
> @hrouissi what is the link with the mentioned PR ?

Post updated with the right link. #6977

**Comment by maxitromer** [comment]
Hi @Arnaud-lebrief 

I'm sending 250k in 14 hours with Mautic and Amazon SES SMTP spending so much time in speed and optimization of the system.

> I would like to transfer my whole database (160K) on mautic but i will need to send to the whole list in less than 15 minutes...

Since Amazon SES API is not avaible for now in Mautic the bottleneck to achieve something like this is the mail transport including not only the speed and optimization of your Mautic instance (PHP version, cron jobs , CPU, memory, etc.), you have to think in a variety of factors like distance from your server to your SMTP, size of your mail files, and so on.

What are you using now to send at that speed?

**Comment by wise-gorilla** [comment]
@RCheesley I think this issue can be linked with #9005 so it can be closed automaticly upon merge.
