### ISSUE TITLE
SMS Messaging Issue: SMS transport is not enabled

### ISSUE THREAD

**Issue by ScottTradepost** [mautic/mautic#8328]
I've gone through the other options, and cleared the cache multiple times, and verified the settings. Mautic keeps indicating the message is sent, but when you check the log, it shows the message:  "Primary SMS transport is not enabled. "  When I check Twilio, it doesn't show where a message went to the server.
I'm currently running Mautic 2.14.2

Has anyone seen this issue and successfully resolved it?

**Comment by OmerGafny** [comment]
Is Twilio set under Config > Text Message Setting?

**Comment by ScottTradepost** [comment]
That is set, do you know of any other locations or anything to check in the config files? There isn't much info on the web on what to check manually to verify settings.

**Comment by RCheesley** [comment]
Hi @ScottTradepost, sorry to hear you're having a problem. According to this issue: https://github.com/mautic/mautic/issues/6177 the problem was resolved by clearing the cache.

Two side notes: 

Firstly, for your information, support requests should be shared at https://forum.mautic.org/c/support/8 and not in Github, so if you can please post there in the future as a first attempt to troubleshoot a problem, that would be super.

Secondly: You are running a very outdated version of Mautic. [Check out the releases](https://github.com/mautic/mautic/releases), we are currently at [2.15.3](https://github.com/mautic/mautic/releases/tag/2.15.3) so you're running potentially vulnerable version (several of the recent releases were addressing security vulnerabilities).
