### ISSUE TITLE
Page builder does not close

### ISSUE THREAD

**Issue by roderik** [mautic/mautic#833]
Using the latest "staging" the page builder does not close. A JS error is visible in the console

![safari - ma kunstmaan be - - screen shot 28 aug 2015 22 18 21](https://cloud.githubusercontent.com/assets/16780/9556156/ef341e5c-4dd2-11e5-9a06-306dee5f1ec9.png)

**Comment by dbhurley** [comment]
Was this an upgrade on a previous installation? If so, did you apply the upgrades to the schema? I know there have been a few lately.

**Comment by alanhartless** [comment]
Hi!

It's highly recommended to not use staging in production because the CSS/JS assets are not compiled for the production environment nor are there migration paths for the database schema.  In this case, assets are not compiled and thus missing required functions in the prod environment.  In the dev environment, assets are loaded individually.

Staging right now runs a risk of losing data if the schema update is forced.  We will be releasing very soon which will include a schema migration path to prevent data loss.

If you're testing staging, read through https://github.com/mautic/mautic#disclaimer to ensure the schema is up to date.  Noting the risk that data could be lost.  

To force Mautic to regenerate the assets to ensure they are up-to-date, delete the app.* and library.* files in media/css and media/js.  Refresh the page and Mautic should automatically recompile them.

Thanks!
