### ISSUE TITLE
Pre-roll, mid-roll, post-roll video ads functions

### ISSUE THREAD

**Issue by RonPimplebut** [mautic/mautic#8333]
It would be very usefull and logic to add a pre-roll, mid-roll, post-roll video ads functions, so we will be able to add pre-roll, mid-roll, post-roll andùo popup ads to your videos. It may also let marketers to add custom ad skip times…just like we see on YouTube. Also maybe being able to set these same ads to run for different videos in a "pre selected playlist".

Thanks

**Comment by RCheesley** [comment]
Hi @RonPimplebut thanks for your suggestions for improving Mautic!

We invite proposals for new features to be posted on the forums here: https://forum.mautic.org/c/ideas/14.  Once a discussion has been had, people have voted for it and there is some code behind it, we move the thread over to a (connected) Github issue.

Please share in the forum above your proposal, and explain how it would work (e.g. with screenshots, or a screencast, explaining the functionality) so that others can understand and chime in with their thoughts.  I will close this issue down in the meantime.

Many thanks again for your suggestions, I look forward to hearing more about them over in the forum!
