### ISSUE TITLE
Mautic update via UI failed

### ISSUE THREAD

**Issue by bernardoklock** [mautic/mautic#8411]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The same error as thousand of people: the dashboard updating error! No cache cleaning, no script, nothing solve the issue.

| Q   | A
|  | ---
| Mautic version 2.15.13 | 
| PHP version  7.0 | 
| Browser Chrome| 

### Steps to reproduce
1. Updating via dashboard - crashed everything
2. Tried every single tips found here and everywhere
3. Unninstall Mautic completely
4. Install it again
5. Erveything's working fine, but I needed to make every automation and forms again
6. Now, after hours, everything's gone again.

It's a sorry, but I'M DONE! Mautic no more. Never.

Don't you feel ashamed for an error like this happening and happening again with hundreds or thousands of your customers for years and nothing happen?

Really. I'm very angry for this kind of unprofessional issue hapening again and when I search I see hundreds of people with the same error.
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by PierreAmmeloot** [comment]
Hello @bernardoklock,
How many contacts do you have on your database ?

Best regards,
Pierre

**Comment by npracht** [comment]
What is the message in your logs ?

**Comment by RCheesley** [comment]
Hi @bernardoklock, and sorry to hear about the problem you are experiencing. 

I appreciate that it is frustrating when errors occur, however as a community we do have agreed ways in which we communicate with each other - even when we are upset or angry about something.

Please take a look at our [Code of Conduct](https://www.mautic.org/code-of-conduct/) - in particular the section on Expected Behaviour.

In order for us to troubleshoot what might be causing this problem, and hence help both you and others who might experience this problem as well, we require some further information. 

As you have seen above, people are trying to help.

Please provide the information requested so that we might be able to get to the bottom of this problem.  

If you require assistance in locating the error logs requested we can help with that, just ask!

Let's see if we can't track down the problem and hopefully resolve the issue for you and as a result, the hundreds of other people with the same error which you mention in your bug report.
