### ISSUE TITLE
How Campaigns work... questions

### ISSUE THREAD

**Issue by that0n3guy** [mautic/mautic#842]
I've started a list of "what if" or "what happens when" questions below.  I'll be happy to submit a documentation PR with answers.  

* What happens if lead is re-added to campaign that they never completed (manually removed from campaign)?  Do they start over or continue where they left off?
* What happens if a lead is added to a campaign they are already in?
* What happens if a lead goes through an entire campaign then is re-added.
* What happens if you add another action (ex: "send email" ) in the middle of a campaign that someone has already been all the way through?
* What happens if you add an action to an campaign at a point "before" where a contact might be (example, lead has been in campaign for 10 days... you add a "send email" to the campaign with a wait of 5 days)?
* What happens if you make changes to actions at a point the future of where people are example, lead has been in campaign for 5 days, you add a "send email" to the campaign with a wait of 10 days)?
* Are "waits" on the false side of a decision timed since the previous action (before the decision)?  Example, `send email > opened email decision > (false side) wait 7 days - send email`   When does that send email go? 
* Are "waits" on the true side of a decision timed since the previous action (before the decision) or when decision fires? Example, `send email > opened email decision > (true side) wait 7 days - send email`   *When does that send email go? 
* What happens if a decision becomes true after its fired as false? Example, "Opens email" is marked as false, start going down the false path... then they open the email.  Do they stop going down the false path... or does the true path never start since its already started down the false?
* What happens if you publish a campaign after people submit campaign forms?  Are waits timed from the campaign publish date for those leads?
*

**Comment by alanhartless** [comment]
Just as a FYI, this type of post is more geared toward the forum rather than Github.  But I'll try answer the questions:

`What happens if lead is re-added to campaign that they never completed (manually removed from campaign)? Do they start over or continue where they left off?`

Currently, if a lead is removed from the campaign, their log entries for what they've done in the campaign is deleted as well. So if they are readded, they'll start over.

`What happens if a lead is added to a campaign they are already in?`

Nothing. The system checks for current membership prior to adding or removing.

`What happens if a lead goes through an entire campaign then is re-added.`

Each event in a campaign can only be executed by the lead once.  So if they complete the campaign, they are done and will not be sent through it again unless removed and readded. 

`What happens if you add another action (ex: "send email" ) in the middle of a campaign that someone has already been all the way through?`

If they have already passed that point in the dripflow, they should not execute the event.  

`What happens if you add an action to an campaign at a point "before" where a contact might be (example, lead has been in campaign for 10 days... you add a "send email" to the campaign with a wait of 5 days)?`

If the action is connected into a decision that the lead has already executed and thus been logged, they will not receive the new email.  If the send email is added to the root of the campaign and the lead has already executed other events at the root level, they will not be sent the email.  If the send email is associated with a decision the lead has not executed yet, they will get the email 5 days after executing that decision.

`What happens if you make changes to actions at a point the future of where people are example, lead has been in campaign for 5 days, you add a "send email" to the campaign with a wait of 10 days)?`

If the actions are connected into a decision the lead has not executed yet, they will receive the email in 10 days from the point of executing that decision.  If the send email is at the root of the campaign, they will not receive the email as the system considers them as already passed that point in the drip flow.  

`Are "waits" on the false side of a decision timed since the previous action (before the decision)? Example, send email > opened email decision > (false side) wait 7 days - send email When does that send email go?`

Correct.  If the lead has not executed the decision within 7 days of the previously logged action (or the start of the campaign if applicable), the system will execute the events associated with the inaction path.  If the actions associated with the inaction path of the decision have different wait times, the earliest wait time is used by the system to decide if the lead should be sent down the inactive path.  Any other actions associated with the path will be scheduled based on their defined wait times.  So for example let's say you have an "opens email" decision and two follow up send email actions, one with a wait time of 5 days and one with 7 days.  On day 5, the system will say this lead has failed to take action thus send them down the inactive path of the decision. It will send the email with the 5 day wait time and schedule the one with the 7 day wait time for two days later.

`Are "waits" on the true side of a decision timed since the previous action (before the decision) or when decision fires? Example, send email > opened email decision > (true side) wait 7 days - send email *When does that send email go?`

From the point the decision was made.  In this case, 7 days after executing the decision. 

`What happens if a decision becomes true after its fired as false? Example, "Opens email" is marked as false, start going down the false path... then they open the email. Do they stop going down the false path... or does the true path never start since its already started down the false?`

Once a lead is sent down the inaction path, the true path is never executed.  Currently, a lead never backtracks.

`What happens if you publish a campaign after people submit campaign forms? Are waits timed from the campaign publish date for those leads? *`

If the campaign is unpublished and the lead submits the form, they will not be added to the campaign to begin with. However, let's say there's the scenario that you have leads in the campaign, and for some reason haven't ran the `mautic:trigger:campaigns` cron job so the campaign never kicked off for them, the date the command is executed (now) will be the starting point. 

Of course if you would like to see how Mautic handles any of these scenarios changed, submit an issue for it and we'll discuss!

**Comment by that0n3guy** [comment]
Awesome.  Thanks for the feedback.  This will help a lot when building campaigns.

**Comment by mellsaid** [comment]
not for nothing, but THIS should be in the documentation. It's an eye opener for so many uncertainties our guys had in the background. Specially about adding events in mid campaign.

**Comment by escopecz** [comment]
@mellsaid could you please add it to the docs? https://github.com/mautic/documentation#how-to-contribute-to-the-docs

**Comment by mellsaid** [comment]
@escopecz  Oh wow. Actually, yes. I will check how to over the weekend ant attempt to add it!.

**Comment by that0n3guy** [comment]
Its been over a year since @alanhartless posted his response.   I think it would be nice for him to verify that the information is still accurate since a lot of development has gone into Mautic since then.

**Comment by mellsaid** [comment]
> Currently, if a lead is removed from the campaign, their log entries for what they've done in the campaign is deleted as well. So if they are readded, they'll start over.

Actually yes, As I've just noticed after building our campaign, that the above doesn't work. Neither does a lead continue where they stopped/been removed fromt he campaign. Also timed conditions dont even run... We removed a lead from a campaign that he is not active in as he didn't open two emails. We added him to a nurture campaign. He sucessfuly hit our criterea so we moved him back to the original campaign to continue where he stopped. the lead didn't get the email. Also there was a timed condition (not connected to anything) that wasn't ran before. That didn't run either. It currently all boils down to how can we remove someone from mid campaign to follow up, and then adding them again to the campaign to continue...

**Comment by ZitaDusa** [comment]
@alanhartless hey Alan, you seem to have a good grip on mautic rules. We are trying to figure out who we can manually or automatically take a lead out of a running campaign which is built on a segment. I tried to do this by removing them from the campaign manually or adding an action 'remove from segment' but they are still left in the campaign.. hope you can help.

**Comment by sykyck** [comment]
@ZitaDusa  do you run cron jobs of mautic:campaign:update they should remove them from campaign

**Comment by Tabish911** [comment]
Hello fella, I have a small query regarding edit in running a campaign. Hope someone will help.

If I want to re-edit the existing campaign and make some changes in that campaign would it get reflect in the future and act according to the changes made.

**Comment by escopecz** [comment]
> would it get reflect in the future

Yes, the changes will apply for the new contacts added to the campaign.

> act according to the changes made

It depends. If a contact is in the middle of a campaign flow and you change the campaign around then no one can predict what will happen to contacts in the middle of the campaign flow.

**Comment by Tabish911** [comment]
@escopecz
I have an issue that I want to send all of my customers a review mail after every purchase regardless of their frequency of purchase 
if I make a segment that has all my woocommerce customer from beginning till the current date,&  I have run the campaign to tag them as old customer till/13/1 now, I have to build another campaign that will exclude them and I can send the review mail easily,

But then again this situation occurs if the client purchase again with same mail id he will not be getting the mail.

can you please help me, thanks
