### ISSUE TITLE
Mautic Sendout Failure - contacts received over 25 identical e-mails

### ISSUE THREAD

**Issue by rekordmarkeLisa** [mautic/mautic#8450]
Hi there, 

last week we experienced a failure in the sendout of a campaign that was meant to be sent to a segment of 11,571 contacts. Around 300-500 contacts in that segment received their e-mail around 25 times, which resulted in a dispatch of 20,622 emails instead of 11,571.

I checked a few contacts and I can see that the campaign ran smoothly up until around 10:52 am (campaign started at 10:00 am, February 8th). Then the campaign appears to have stopped for around one hour. At 12:02 am the email dispatch restarted which is also when the failure happened. After that contacts received over 25 times the identical email. At 12:20 I noticed the error and stopped the campaign.

Has this happened before to someone else? Does anyone know how this might have happened and how I can avoid this problem next time?

Thanks in advance!

**Comment by RCheesley** [comment]
Hi @rekordmarkeLisa you didn't provide any details about your Mautic version, PHP version and so forth. 

Please can you give more details including log entries so we can identify whether this is a bug, or if it's something to do with an outdated version or configuration issue.

**Comment by rekordmarkeLisa** [comment]
Hi @RCheesley ,  thank you for your reply. Here are some more details: 
PHP Version: 7.0
Mautic Version: v2.15.2
There was no log entry. Do you need any more information?

**Comment by RCheesley** [comment]
OK, I seem to remember there being a particularly nasty bug that was fixed which caused emails being sent out in this way when something failed, I will see if I can find the old PR. I'm fairly sure it was in 2.15.3 or 2.15.4.

We're now on 2.16 so you're a few releases out of date.  Please make sure you take a full backup before doing any kind of update though, and ideally test in a dev area first/update at command line.

**Comment by rekordmarkeLisa** [comment]
Thanks, that would be great if you could find that PR.

So I guess the only way for me to make sure this won't happen again is to update my version of mautic to the newest onde?

**Comment by RCheesley** [comment]
Here is the PR in question: https://github.com/mautic/mautic/pull/7733 which was merged in 2.15.3. 

It sounds remarkably like the situation that you mentioned, although you did not state whether the emails were transactional or marketing?

**Comment by RCheesley** [comment]
Could you also share what email transport you're using to send your emails? Thanks!

**Comment by rekordmarkeLisa** [comment]
The emails were meant to be sent as marketing but I have just checked my campaign and noticed that instead I chose transactional by accident. Normally I don't use transactional campaigns which is probably why this hasn't happened before.

We are using AWS SES to send our emails.

**Comment by RCheesley** [comment]
OK so I am pretty sure that given your Mautic version, that you're using transactional emails and that it seems exactly to replicate the issue mentioned above, that this is due to the previously reported bug and would have been addressed with the PR which was released in 2.15.3.

To answer your question:

> So I guess the only way for me to make sure this won't happen again is to update my version of mautic to the newest one?

Yes, that would have prevented this problem, so far as we can tell.

Please ensure that you make a full backup (files & database) and run the update at command line, ideally testing the update in a development area before you make the update on your production environment.  You may need to clear and then warm up the cache once the update is complete. Shout if you need any assistance on Slack, I'll close this issue down and the security email you sent as well.
