### ISSUE TITLE
Support twig in email content

### ISSUE THREAD

**Issue by that0n3guy** [mautic/mautic#849]
Using twig to process the body/subject of email templates would allow you to easily use many of the twig functions within an email.  Things like:
- conditional content ( {% if leadFields.gender is male %} different content for males)
- Auto capitalize names of lead ( Hello {{ leadFields.firstname | title }} )
- build tables with ease with for loops
- etc...

Note:

We built an email marketing module for our CRM that uses twig for this... it works very well.

**Comment by alanhartless** [comment]
We are looking into using Twig for custom templates, etc and thus can explore this as well. Of course PRs are welcome if you would like to contribute some code to the project :-D

**Comment by that0n3guy** [comment]
I'll add this to our backlog.  If you start working on this before we do, let me know so we don't duplicate work on it and I'll do the same :).

**Comment by kuzmany** [comment]
:+1:

**Comment by l2aelba** [comment]
+1

**Comment by dmarkotter** [comment]
+1 
I'd like to be able to replace a blank field with default text:
e.g. {leadfield=firstname:there}
Hello Joe
Hello Bob
Hello there
Looks as if Twig would do this?

**Comment by that0n3guy** [comment]
Yup, twig can do this pretty easy: http://twig.sensiolabs.org/doc/filters/default.html

**Comment by alanhartless** [comment]
@dmarkotter Use a bar instead of a colon and that should work currently. If doing this with the editor, you'll need to view the source and manually edit the token in the data-token attribute in the visual placeholder's html. 

```
{leadfield=firstname|There}
```

**Comment by xethorn** [comment]
Good morning, considering this is a very useful feature to create custom emails to users, and increase the impact of our reach, what can we do to help this feature be available sooner?

**Comment by xethorn** [comment]
To give you a preview: as part of the onboarding process, an email is sent 10 days after the user has signed up to tell give some advices / insights based on what he has filled so far and highlight different users based on their location and school they attended. Using the builder makes this incredibly complex (more than 100 different scenarios + localization of all those emails in 3 languages).

**Comment by chandon** [comment]
:+1: 
very important feature !

**Comment by trops** [comment]
Has this been implemented? I tried in 2.2.1 and can't seem to get this working.

**Comment by kuzmany** [comment]
@trops Now, but you can use dynamic content

**Comment by trops** [comment]
Ok cool I see it! I am using it now and was wondering if there was a way to create the Dynamic Content on a universal level similar to the landing page dynamic content. I have a paragraph of text I want to send in EVERY email and as far as I know I have to create the same Dynamic content for every email I create...

Is this true?

**Comment by trops** [comment]
I also noticed the contact fields do not auto populate within the dynamic content section of the emails. I typed it in manually to display first name and it didn't work.

**Comment by chandon** [comment]
@trops i've submited PR #2819 to enable contact fields within dynamic content, feel free to test it...

**Comment by FabianTe** [comment]
This is still an important yet missing topic!

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._

**Comment by corvis** [comment]
Hey guys, 

We implemented a [plugin](https://github.com/Logicify/mautic-advanced-templates-bundle) to enable [TWIG](https://twig.symfony.com/doc/2.x/templates.html) templates in the emails.  It does exactly what was requested I believe.

**Comment by fullofcaffeine** [comment]
Hi @that0n3guy,

I'm wondering if you ever found any workarounds/solutions for having conditional dynamic fields in the email subject? I need to output a slightly different word based on the gender value of a contact. It's actually a very common case in gender-sensitive natural languages such as Spanish and Portuguese.

I thought @corvis' plugin could solve it, but it doesn't process the email subject at the moment (See: https://github.com/Logicify/mautic-advanced-templates-bundle/issues/2). I also created an issue here (since the Mautic forums are closed for new member atm): https://github.com/mautic/mautic/issues/7247.

 I'm actually very surprised dynamic content is not supported in subjects because I'd think that subjects can very well change based on the same criteria variants in the body do. I'd prefer to have a conditional language though, something like Liquid. Maybe there are other plugins available?

If anyone could give me any insights about this, I'd be very grateful.

**Comment by yangenmanuel** [comment]
Any updates on this?
