### ISSUE TITLE
Improve JavaScript Form Processing Hooks API to use ID instead of name

### ISSUE THREAD

**Issue by coreyworrell** [mautic/mautic#8504]
https://developer.mautic.org/#js-form-processing-hooks

```js
MauticFormCallback['replaceWithFormName'] = {}
```

Since the form name changes when you change the actual title of the form, hooks will no longer work after a title change without a code change... If the form ID was used instead then the hooks would continue to work.

**Comment by RCheesley** [comment]
@coreyworrell thanks for flagging this, would you be up for making a PR to address this?

**Comment by coreyworrell** [comment]
@RCheesley I'm not sure if I'm familiar enough with Mautic code to create a PR.

It would need to be backwards compatible, so after a quick look over the code, maybe adding a `data-mautic-form-id` attribute to the `<form>` element [here](https://github.com/mautic/mautic/blob/8cb3c509a09224fe9c71abe84faebdb69c11c934/app/bundles/FormBundle/Views/Builder/form.html.php#L53) could work.. Then [this line](https://github.com/mautic/mautic/blob/cee17f154a24606406dddaa9d2dca9690646d2a3/media/js/mautic-form-src.js#L117) would somehow need to check for either attribute value (the existing `data-mautic-form` or the new `data-mautic-form-id`).

If I were to make a PR, I'm also unsure how `media/js/mautic-form-src.js` becomes `media/js/mautic-form.js`.

**Comment by RCheesley** [comment]
@coreyworrell thanks for looking into it, I am sure we can help fill in any gaps!

JS/CSS assets will render as the source files if you are in [dev mode](https://contribute.mautic.org/contributing-to-mautic/developer/local-environment-setup#development-environment) rather than minified so that makes it easier if you are tinkering with the -src files to see the changes and troubleshoot as the changes in those files will be directly visible on refresh.

If you want to see the change in the production environment, you have to run the `bin/console mautic:assets:generate` command.

Here are some [resources on working with PR's](https://contribute.mautic.org/contributing-to-mautic/developer/code/pull-requests) that may be helpful!

**Comment by dennisameling** [comment]
@coreyworrell Good point. I also think it would make a lot of sense to use the form ID rather than the form name. Don't know why it was implemented that way in the first place, could only find this PR from 2015 which adds some functionality to it: https://github.com/mautic/mautic/pull/549

I like your idea to add a `data-mautic-form-id` attribute so that we'll maintain backwards compatibility. We then might use that attribute to refactor the other code later in some major release in order to keep things consistent. The other option is to do it "first time right" and change everything to use the form ID rather than the form name. But we could only release that in Mautic 4 then due to it being BC-breaking.

I guess you'd do something like this, right:

```JavaScript
Form.customCallbackHandler = function (formId, event, data) {
    const mFormName = formId;
    const mFormId = 'FORM_ID_FROM_DATA_ATTRIBUTE';
    
    if (typeof MauticFormCallback !== 'undefined' &&
        typeof MauticFormCallback[mFormName] !== 'undefined' && // update this logic to check for both mFormName and mFormId?
        typeof MauticFormCallback[mFormName][event] == 'function' // update this logic to check for both mFormName and mFormId?
    ) {
        if (typeof data == 'undefined') {
            data = null;
        }

        return MauticFormCallback[mFormName][event](data);
    }

    return null;
};
```

The `formId` that you get as the function parameter will always be the form name if you leave all other functionality intact, so you'd need to loop through all form elements to find an element which has an `data-mautic-form-id` attribute that matches. Similar to what is done [here](https://github.com/mautic/mautic/blob/010bc06b41ec2a7e576d35ea231e81cd5f362938/media/js/mautic-form-src.js#L131-L139).

Is that enough info for you to get started with writing a PR, or do you need any other info?

**Comment by coreyworrell** [comment]
Thanks @dennisameling . It should be enough for now, I will attempt to work on it if I have some time soon.

Just to note, it looks like there is also an undocumented [`mauticFormValidations`](https://github.com/mautic/mautic/blob/010bc06b41ec2a7e576d35ea231e81cd5f362938/media/js/mautic-form-src.js#L184) that also uses similar API to set validation rules, so that should be covered too by this update.
