### ISSUE TITLE
Optimize email copies in email_stats table to use less disk space

### ISSUE THREAD

**Issue by BartKaminski** [mautic/mautic#857]
Hello,
after just sending first newsletter to 30K subscribents my mautic database shows 1.35GB in size.
Table 'email_stats' shows 1.3GB
Should it be that way?
Mayby it's possible to do some optimalization or add option not to save each sent email separately.
Regards,
Bart

**Comment by alanhartless** [comment]
A copy of the message is saved in the email_stats table for the webview and lead timeline (we don't dynamically regenerate because an email could be changed or deleted from the Manage Email view). Each email is saved separately to track which lead opened the email and to track various stats surrounding opening the email.  

Did the email you sent have a lot of content? You could wipe out the copy column of the email_stats table if the space is an issue for you.  Of course, if you do that, webview and the links in the lead's timeline won't work.

**Comment by allafa70** [comment]
Sorry I have the same Issue.
After sending the first two HTML newsletter my DB is now 4GB.

I think you should think to an alternative (regenerating is the better one) because many other peaple will have the same issue sending HTML newsletter to a lot of people (30.000).

I think is not an issue if the regenerated web view does not work for just few people (e.g. because you deleted the email in the backoffice) but instead is a BIG issue to manage databases so big. 

thank you for your attention

Fabio

**Comment by that0n3guy** [comment]
What about compression https://dev.mysql.com/doc/innodb-plugin/1.0/en/innodb-compression-internals-storage-blobs.html .   I've never used it, but its worth looking into.

The other option would be to store the email copy on the filesystem and reference the file in the DB.  

A third option, that won't help w/ DB size but might help with future performance when there are lots of rows would be to normalize out the copy of the email (IE, put it in its own table) since its not really read in bulk like the other info in the stats table.  This would also allow you to compress the new normalized table w/o doing the email stats table.

**Comment by allafa70** [comment]
I think compression is not an acceptable solution.
At the moment my DB gzipped is 450Mb ... and after sending just two newsletter.
What will happen after a Year of sending newsletter every week?

**Comment by dbhurley** [comment]
Actually I think we need a new option for storing emails; this is something we've been discussing in chat for a bit.

**Comment by allafa70** [comment]
Hi,
I wiped the copy column but now the stats table goes from 5gb to 1.5gb.
This is not acceptable for a DB size after sending 2 newsletter.
Can I wiped some other column?

Thank you for tour help

**Comment by alanhartless** [comment]
Maybe the tokens column? That would be the only other column that would hold anything of size although not even a fraction of what would be in the copy column.

As David mentioned, we're planning to do a table that holds a tokenized copy the email_stats table references and where a new entry will only be created if it's determined the email body has been changed from the previous send. Along with that, we're planning to add some mechanism to cleanup old stats. That should significantly decrease the storage required. But that will still require storing the tokens in a column so if that's what's taking up the space you're worried about, I'm not sure the change will help.

**Comment by allafa70** [comment]
Hi alanhartless,
thank you for your reply.

Cleaning up the copy column I'll loose the web version.
Ok I can arrange my newsletter to not include the web version link so can be a marginal issue (even if I'll have to clean the column after send).
What exactly I'll loose cleaning the tokens column? 

thanks

**Comment by allafa70** [comment]
Hi again,
I tried to wipe the column "tokens" in my test site and now links like unsubscribe doesn't work anymore.

If this is true, Mautic is not ready for production environment ... is that true?
You should warn users in your home page that Mautic is not yet usable to send HTML newsletter in production environment.
Nobody can handle DB with many GB of data.

I switched from Interspire Email Marketer to Mautic because of it's new interface and functionality but after MANY YEAR of usage my Interspire DB is now just 1.17Gb.

Do I have to switch back?

**Comment by ptcc** [comment]
wow, I just found this thread... my email_stats table had 5.2 Gb and my mautic was slowwww.
I wiped copy and tokens columns and now its all good :) thanks

**Comment by Salamek** [comment]
Ehm...
![2019-01-10_18-56](https://user-images.githubusercontent.com/1226241/50987277-7a2a6b00-1509-11e9-908d-537875149613.png)

**Comment by fgsants** [comment]
Incredible how there still seems to be no solution to this 4 years later, unless you count losing functionality implementing the "solutions" proposed above....

**Comment by martinduplex** [comment]
Hi, how do we wipe clean email tokens, I assume it's "user_tokens" table? If we wipe clean "email_copies" and "user_tokens" tables would that reduce the size for "email_stats"?

**Comment by nikhilthecool** [comment]
I am on a shared hosting plan and my Mautic instance was suddenly stopped by my hosting provider stating the reason that I have exceeded the database size limit of 750 MB. I checked that Mautic database alone has exceeded 850 MB and the 'email_stats' table alone has exceeded 450MB. This is after sending emails to about 65000 leads.

It is high time that the Mautic development looks into the issue positively as it may not be feasible to run Mautic on a shared hosting platform any more.

**Comment by dataforxyz** [comment]
Is there any update on this. I feel like I am having the same issue. GB in size only a few million emails in.

**Comment by diamondtheta** [comment]
Yes, please PRIORIZE this HUGE PROBLEM in development, because it threatens the usability , the mere existence of mautic ! 
I have only sent about 1-2 thousand emails and already have 1,3 GB database in just a few days!! What will be if I send 100x times much email in every monh???????????????????? There will be 1,5 TERRA BITE database size in just only 1 year??? Most people plan big, that is why we dont use mailchimp......!!!! PLEASE, this should be the most important issue in development !!!!!!!!!! At least make an option to turn OFF those GB eating functions (and not only with commands but with admin page radio buttons exactly in settings and everywhere where they are on admin page please )!!!!! There is absolutely NO USE of them if they make mautic unusable !!!!!!!!!!!

**Comment by npracht** [comment]
Obviously 130Gb ?
Do you have any suggestion about how we could optimize this ?

**Comment by diamondtheta** [comment]
Yes, I just have wrote the solution: developers can see what tables , what data are actually the huge ones, and just please make an option on the admin page to **"don't save huge GB eating XY stats" checkbox** or "don't save each copy for emails" option also, etc. and write that then what will happen (like unsubscribe links won't work, etc and NOT here, but write these please under the setting , next to the radio button or checkbox on the admin page please). Or "don't save unknown contact option under setting" , or "auto delete X+Y or X / YZ / or X if ZX" conditionally options on admin pages like for example "only save visited pages for X days for known/unknown contacts"  etc please, because most users dont even know about cron jobs, or how to parameter right, or cant even run commands because they dont have own server , etc. 

So look please that **other similar email senders, CRMs how are solving huge sizes?** I dont think that all others are eating +130 GB / months if they are sending only 100 000 emails / month... big companies are sending TENS or HUNDREDS of MILLIONS of emails, and I don't think that they eat +200 petabites each month in database tables :(

+ Others also wrote more solutions, for example to **COMBINE** emails for only ONE instance instead of 666 000 instances, (and make on option for this, and this way one campaign will save only 1 email not every sending a separate one..) So if I or a contact see only ONE updated newly generated email template is STILL MUCH, MUUUUCH LESSER problem than the database reaching limits and stops the whole system from working or slowing down to a point that it is unusable !!

+ Or for example another solution is to **save NON-important or NOT-fast-acces-needing data into FILES and not into the database to slow down all other important functions what really needs fast loading** (like dinamics content is NOT EVEN LOADING anymore until 2. refresh !!). So many functions like dinamic content's proper FAST loading is MUCH MORE important than to "load email or visited pages stats from database fast FOR ONLY ADMINS on the admin page. Admins can WAIT for stats much more (even if the hard drive is from the stoneage), but contacts will NOT wait, so **database should only contain things that  REALLY needs fast access!**  so for example even if I refresh the page the DWC dynamic web content loads about 7 sec slower AFTER the whole webpage is loaded, what is unacceptable for a landing page !!! And that was much faster earlier , I see the slowing with the increasing DB! That way the dynamics content options are also not usefull for nothing !! So you could SEPARATE ALL "NEED fast loading" data to database, and all other "NOT needing fast load"  into FILES because admins can wait for detailed stats etc.  ! And files also don't have SO LOW gigabite limits as databasees on cpanel shared hostings ! **I can have UNIMITED disk space but very limited database size** ! :(
And folders should conain "deletable_huge_stats" or something very similar name with dated subfolders for non-pro mautic users where huge stat files are stored to be KNOWN exactly what can be deleted and what crashes core functions if deleted!

So for example dynamic content needs very fast loading, but If someone wants to see a web version he can wait +2 seconts there. Or for example form showing needs fast loading, but to see what pages was visited by XY person stats can be wait a few seconds more ! **So admins can wait, contacts, users WONT wait!!** (if for example  a link in newsletter is loading in only 15 seconds because database is huge they will just leave!!!!! So admin page stats are not as important as FAST access needing functions like URLs working in emails. They also very slow if the database is getting bigger and is only getting slower and slower +1 sec / month even with very little uses (little lists, few emails)????? So database only should contain those data what are REALLY needs FAST access like links in emails, dynamic contents, forms, etc. and ALL other data can go into files into stone age hard drives also... !

+ I have tons of TXT files and the hugests are only 1-2 megabite, so I can't even imagine what is mautic storing in 1,3 gigabite, because I have literally only about 200 contacts and very low visited pages tracked only (like 100-200 visitors / day), and 12 emails, 4 champaigns, so very few things. So can't imagine how could I scale up... even with private server it seems very risky if I send not only a few yearly for a few, but  use as a regular often used system and send NORMAL dose to medium lists!! And don't think that other email senders eat that much GB if I have only this less, so they surely solve this somehow even if I don't know exactly how but they surely solved this even on shared hostings!!!! :((((

Thanks much!!!!

**Comment by luiszxcv** [comment]
This greatly afflicts me too, slow mautic and database at 3.5 gb! This is unacceptable. Any improvements or suggestions for corrections?

**Comment by luiszxcv** [comment]
I am Brazilian, forgive me for my English.
