### ISSUE TITLE
Font folder is empty when importing new Theme via GUI

### ISSUE THREAD

**Issue by nilyin** [mautic/mautic#8657]
Hi,

Mautic 2.16.1 (docker)
PHP Version 7.1.33

when I import new custom theme (this theme root directory has fonts folder with fonts). After import succeeded I have checked the server and found the fonts folder on mautic server is empty.

steps to reproduce:
1. prepare the theme as zip file and select it with GUI
2. press Import button wait for message about successful import
3. login itto the server and find folder for newly imported theme (archive file name) and open its fonts/ folder
4. it will be empty

notes:
1. I use fontawesome-webfront
2. server's the theme folders have the same RWX rights as for the other (css, html) folders for www-data user/group

I can shoot a video or provide my theme if you cannot reproduce it locally.

**Comment by RCheesley** [comment]
Hi there, I think this could be due to the font files not being on the list of allowed extensions rather than a bug - take a look at this area in the settings: 

![screenshot-local mautic3-2020 07 06-09_50_58](https://user-images.githubusercontent.com/2930593/86574818-531def80-bf6e-11ea-96be-4d42c358344b.png)

Please report back if this resolves the issue for you!

Also in case you weren't aware, for questions/support please search/post your issue over at https://forum.mautic.org/c/support as often there will be answers and that's where most folk go with questions like this!

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
