### ISSUE TITLE
Use case for Marketing Messages feature

### ISSUE THREAD

**Issue by PierreAmmeloot** [mautic/mautic#8762]
Hello everyone, I'm looking for the use cases of the Mautic Marketing Messages feature.
It seems to be duplicated with the Emails part.

Who uses this feature?
If so, how do you use it concretely?

Pierre

**Comment by RCheesley** [comment]
Hi Pierre, Github is for issues rather than questions. Please post this on the forums at https://forum.mautic.org. Also please take a look at the documentation here: https://docs.mautic.org/en/channels/marketing-messages

**Comment by PierreAmmeloot** [comment]
Hello @RCheesley, I think this lift belongs here.
Because if this feature has no concrete use then I suggest removing it to simplify the code and its maintenance.
I have read the documentation, but I search concrete use case. ;-)
Do you have usage for this feature ? Otherwise why not remove this feature?

What do you think?
Pierre

**Comment by npracht** [comment]
You can allow user to choose themselves what type of support they would like to get, a prior. It is an advanced feature because it implies an advanced preference center and campaigns to ask your user their prefered channel.

As mentioned Ruth, if you wanna discuss that it should be on forum and chat, not github.
Thanks.
