### ISSUE TITLE
mail configuration problem

### ISSUE THREAD

**Issue by miguelpascual** [mautic/mautic#877]
Every time I change the mail configuration I got a non stop Please Wait...

![image](https://cloud.githubusercontent.com/assets/10166840/9758177/38bf0c6a-56e5-11e5-869d-8e741b426045.png)

It dont write the changes...

**Comment by drmmr763** [comment]
This is caused by either the writing action failing due to a timeout or an error.

Can you check your error log in app/logs - delete any existing logs and then go and re-perform the config save action and see if a new log shows up? 

If no log shows up, let's try increasing your php configuration to allow longer execution times.

**Comment by alanhartless** [comment]
Any update on whether this is still an issue?

**Comment by escopecz** [comment]
Closing for lack of feedback. Feel free to re-open if you still experience the issue.

**Comment by Loanatik** [comment]
I have the same issue.
