### ISSUE TITLE
Refused to display '<form result>' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

### ISSUE THREAD

**Issue by vijayhrdm** [mautic/mautic#8789]
I have my website at https://mydomain.com and Mautic installation at https://m.mydomain.com
The problem is with Forms. After filling the form, the buttons shows "Please wait" and mautic returns this error:

Refused to display '<https://m.mydomain.com/form/submit?formId=1>' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

Browser: Chrome (latest)
Mautic Version: 2.16.2
PHP: 7.2

### Steps to reproduce
1. Install Mautic, create a form, display the form via mautic plugin for Wordpress
2. Fill the form and 'Inspect element' to open the console where you can see the error

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)

**Comment by putzwasser** [comment]
@RCheesley I feel like closing this wasn't a good decision. This is a problem. See https://github.com/mautic/mautic/issues/7498

I ran into the same problem with a vanilla installation on a subdomain and the page on the TLD. If mautic is on a subdomain instead of the TLD it causes this problem. I think this is rather a bug than a topic for the forum.

**Comment by RCheesley** [comment]
This is likely due to the misconfiguration of your web server, which is something that is a support issue and not a bug with Mautic. Please check the forums, for example: https://forum.mautic.org/search?q=%27X-Frame-Options%27.
