### ISSUE TITLE
[Feature] Add to lists based on conditions

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#88]
It would be great to be able to add to lists based on the values submitted on a form.

Example, if someone is filling out an enquiry form and they are interested in services X and Y, then add them to mailing list X and mailing list Y.

**Comment by tkostenko** [comment]
Yes exactly.

**Comment by pitus** [comment]
I vote very much for that feature.
We are just launching 6 campaigns, one for each site we control and we had to create 6 separate Forms just because each one needs to add Leads to a different list.
It would be nice if we could define just one form and one process and just link it all together based on parameters - either by linking lists with forms and campaign processes to create a specific campaign (treating form & process as a template of sorts) or by making decisions in the campaign definition based on form data (hidden field for each domain or detecting which domain the form was on...)
Other software uses Tags heavily - one could tag anything - form, lead, campaign, any other packet of data and then base decisions on these tags, set/clear them...

**Comment by MaxOnTheHill** [comment]
:+1: definitely a GOOD thing .... and going back to the tags ;)

**Comment by dbhurley** [comment]
Fixed in 1.2.1
