### ISSUE TITLE
mautic 2.16.2 not able to track returning users on safari 13,12 & 11 on iOS devices

### ISSUE THREAD

**Issue by RaianHN** [mautic/mautic#8804]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
mautic 2.16.2 not able to track returning users, as cookies are not getting set in safari browsers on iOS devices

| Q   | A
| --- | ---
| Mautic version | 2.16.2
| PHP version | 7.3
| Browser | safari 13 , 12 & 11

### Steps to reproduce
1.  Create landing page in  site1.domain1.com and 
2. embedd mautic form code  from --> site2.domain2.com on  landing page in site1.domain1.com
3.  User from iOS device, browser: safari 13 - use devtools to investigate the cookies
4. user visits landing page site1.domain1.com, fills the form, submits the form. 
 
 ### Log errors
Go to - browser's dev tools  --> 
click resources tab to check if the cookies are set for site2.domain2.com, you wont see any, as samesite=none attribute is not getting passed.

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RaianHN** [comment]
Hi,
I'm yet to try mautic 3.0.1, will try the test case on the mautic 3.0.1 and
update if that works,
thank you for following up.

--
Raian |9945353739

**Comment by RCheesley** [comment]
Great, thank you!

**Comment by RaianHN** [comment]
Could you point me to upgrade documentation ? from mautic 2.16.2 to 3.0.1

**Comment by RCheesley** [comment]
Sure, take a look at the release announcement here: https://www.mautic.org/blog/community/mautic-3-building-stable-foundations basically update to 2.16.3 then you'll be able to migrate. Ensure you take a backup, check the minimum requirements are met (the script won't allow you to migrate if the aren't!)

**Comment by zietbukuel** [comment]
I'm having this issue in the latest Mautic release (fresh install). I see these errors in the console and of course I'm not able to track users at all.

> Some cookies are misusing the recommended “sameSite“ attribute 3
Cookie “mtc_id” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To know more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite mtc.js:3:571
Cookie “mtc_sid” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To know more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite mtc.js:3:571
Cookie “mautic_device_id” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To know more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite

**Comment by RCheesley** [comment]
Hi folks, looks like this might be related to the samesite cookie issue which is being tracked in #9019 so I will close this in favour of discussing the problem over there.
