### ISSUE TITLE
Error with Trusted Proxies on M3 and Docker

### ISSUE THREAD

**Issue by luizeof** [mautic/mautic#8834]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Following Symphony docs:

If it's Mautic behind a reverse proxy you can set a list of comma-separated CIDR network addresses it sets those addresses as trusted proxies. https://symfony.com/doc/current/deployment/proxies.html

this is the local.php setting for Mautic 2, but generates an error with Mautic 3:
```
'trusted_proxies' => array('0' => '0.0.0.0/0'),
```

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 
| Browser | 

### Steps to reproduce
1.  Setup Mautic 3 over a Reverse Proxy
2. Setting up Trusted Proxy in local.php
 
### Log errors

mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\DependencyInjection\Exception\RuntimeException: "Invalid JSON in env var "resolve:MAUTIC_TRUSTED_PROXIES": Syntax error" at /var/www/html/vendor/symfony/dependency-injection/EnvVarProcessor.php line 128 {"exception":"[object] (Symfony\\Component\\DependencyInjection\\Exception\\RuntimeException(code: 0): Invalid JSON in env var \"resolve:MAUTIC_TRUSTED_PROXIES\": Syntax error at /var/www/html/vendor/symfony/dependency-injection/EnvVarProcessor.php:128)"} []

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by alanhartless** [comment]
@luizeof This happens to be a compatibility issue with Mautic 3. Mautic 3 refactored how it leverages configuration parameters to no longer be dependent on Symfony's container rather it now uses Symfony 3's environment dynamic variable support. https://github.com/mautic/mautic/blob/3.x/UPGRADE-3.0.md#removing-the-container-as-a-configuration-dependency

Mautic 3 loads the configuration options into the environment with a `MAUTIC_` prefix. M3 was written to use Symfony's environment variable processors to type cast values based on the default configured in each bundle's config file. In this case, `trusted_proxies` is an array and the variable written to the environment is `MAUTIC_TRUSTED_PROXIES`. Symfony uses a json processor to encode/decode arrays to and from the environment. 

https://symfony.com/blog/new-in-symfony-3-2-runtime-environment-variables
https://symfony.com/blog/new-in-symfony-3-4-advanced-environment-variables
https://symfony.com/doc/current/configuration/env_var_processors.html

https://github.com/mautic/docker-mautic has the option to pass in `MAUTIC_TRUSTED_PROXIES` as a string. But this conflicts with Mautic 3/Symfony 3 because it expects it to be processed as an array. 
https://github.com/mautic/mautic/blob/3.x/app/bundles/CoreBundle/Config/config.php#L1088
https://github.com/mautic/mautic/blob/3.x/app/config/parameters.php#L40
https://github.com/mautic/mautic/blob/3.x/app/bundles/CoreBundle/Loader/EnvVars/ConfigEnvVars.php#L29

Something you could try to make the docker repo compatible with M3 is to use json encoded string version of an array as the value for MAUTIC_TRUSTED_PROXIES. `["0.0.0.0\\/0"]`

**Comment by luizeof** [comment]
thanks @alanhartless.

in addition to trusted proxies, are there any other variables that must be passed through the Docker ENV and that will no longer be in `local.php?

**Comment by luizeof** [comment]
@alanhartless tested. We need to remove the `trusted_proxies` from local.php.

After, we need to add the settings you recommend: MAUTIC_TRUSTED_HOSTS = ["0.0.0.0\\/0"]

This works fine!

**Comment by luizeof** [comment]
@alanhartless even passing ["0.0.0.0\\/0"], does not work.

I tested in several formats and I was not successful.

**Comment by luizeof** [comment]
@RCheesley @alanhartless 

after numerous tests, the solution was:

- remove trusted_proxies from `local.php`
- remove ENV `MAUTIC_TRUSTED_PROXIES` from Docker

apply this pull: #7931

Mautic 3 running fine on popular open source reverse proxies like `nginx-proxy` and `traefik`.

**Comment by RCheesley** [comment]
Closing as this was resolved

**Comment by riisi** [comment]
For what it's worth, I found a format that works without error is `MAUTIC_TRUSTED_PROXIES ='["192.168.0.1\\/20"]'`. 

I wasn't able to confirm that the setting was taking effect however, as I don't think values set via env vars display in the settings UI, and I resolved the related problem I was having via other means, so didn't go any further.

**Comment by linuxd3v** [comment]
@riisi when using official docker image - it doesnt seem like MAUTIC_TRUSTED_PROXIES is even picked up:  

https://github.com/mautic/docker-mautic/blob/mautic5/common/entrypoint_mautic_web.sh
