### ISSUE TITLE
[MAIL ERROR] Unable to open file for reading [{tracking_pixel}]

### ISSUE THREAD

**Issue by fianbiasa** [mautic/mautic#8908]
it happend in Mautic 2.16.0

`[2020-06-15 15:46:40] mautic.ERROR: [MAIL ERROR] Unable to open file for reading [{tracking_pixel}] (send); rihlah******per@gmail.com {"exception":"[object] (Swift_IoException(code: 0): Unable to open file for reading [{tracking_pixel}] at /home/rihlahtu/email.ri******ahwisata.co.id/vendor/swiftmailer/swiftmailer/lib/classes/Swift/ByteStream/FileByteStream.php:144)"} []`

_Originally posted by @fianbiasa in https://github.com/mautic/mautic/issues/7265#issuecomment-643997704_

**Comment by RCheesley** [comment]
Hi there,

Please try with the latest version (2.16.2) as there were some fixes for encoded images.

**Comment by fianbiasa** [comment]
> Hi there,
> 
> Please try with the latest version (2.16.2) as there were some fixes for encoded images.

thank's for reply...
**done** with disabled **base64 image** in email setting.

**Comment by RCheesley** [comment]
Did this fix the issue or not? It was not clear from your message.

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by fianbiasa** [comment]
> Did this fix the issue or not? It was not clear from your message.

yes... **problem solved** with disabled **base64 image** in my case

**Comment by fianbiasa** [comment]
> Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
> Thanks!

im not tested mautic 3.

**Comment by DeanWookey** [comment]
I get this issue on Mautic 3.0.2. It does go away if you disable base64 image encoding, but when you re-enable it, it comes back.

I believe it's due to this commit: https://github.com/mautic/mautic/commit/c151d3aae197120707ca757688924ae5bc6bcf2d

in conjunction with the call to setBody in EmailSendEvent. It seems like setBody is called twice. The second time it tries to replace the {tracking_pixel} token that the first call to setBody put there. I'm guessing it's also related to this commit: https://github.com/mautic/mautic/commit/3d866b6f21de9f5f1e83995d6e9a85ef0b5586f1

It seems the original intention was to ignore embedding and tracking in that call to setBody.

Using both commits, I changed the code in MailHelper to:

```php
    public function setBody($content, $contentType = 'text/html', $charset = null, $ignoreTrackingPixel = false, $ignoreEmbedImageConversion = false)
    {
        if (!$ignoreEmbedImageConversion && $this->factory->getParameter('mailer_convert_embed_images')) {
            $content = $this->convertEmbedImages($content);
        }
```

and in EmailSendEvent.php to:

```php
    public function setContent($content)
    {
        if (null !== $this->helper) {
            $this->helper->setBody($content, 'text/html', null, true, true);
        } else {
            $this->content = $content;
        }
    }
```

which seems to have fixed it for me.

**Comment by dhmusman** [comment]
Hi @DeanWookey 

Thanks for the solution it work for me and save our time.

**Comment by LevryKurniawan** [comment]
It happened again in Mautic **3.1.0**

**Comment by LevryKurniawan** [comment]
It looks like this issue still continues up to Mautic 3.1.0.

**Comment by scaraliu** [comment]
on Mautic v3.1.2 still not working.

**Comment by MauriceW2** [comment]
This is why I am so sick and tired of Mautc.

- They fix 1 thing
- They ONLY test this one thing, without testing EVERYTHING
- And so without knowing, they might break other things

As long as there is no professional way of approching this procedure, Mautic will be toy forever that is highly unreliable and not suitable for serious applications.

That's why bug keeps existing in many, many, many versions.

**Comment by RCheesley** [comment]
@MauriceW2 we are actively working on improving our test coverage and implementing automated E2E testing, but it is a huge task when we currently have around [38% coverage](https://codecov.io/gh/mautic/mautic) and no E2E testing (I am working on an [open WIP PR ](https://github.com/mautic/mautic/pull/9338)for that with the team from Acquia).

Much of the code needs to be re-written file by file to make it even possible to write automated tests so this is no easy task. We did a huge amount with Mautic 3, and have much tighter controls in place now.

We are also desperately short of testers. I can count on one hand the number of people who are regularly helping us to manually test pull requests - which is a huge load to put on a small number of people. This means that inevitably we are not covering every single possible task and feature every single time.

So, here's how you can be a part of the solution:

1. Join us on **Friday or Saturday THIS WEEK!**  We have our contribution weekend, open to all, where we are finalising the 3.3 release. We have around 95 pull requests that are [tagged for this release](https://github.com/mautic/mautic/pulls?q=is%3Aopen+is%3Apr+milestone%3A3.3.0) and waiting for people to test them. All you need to do is be able to use Mautic. We have mautibox.com which allows you to test a PR without even spinning up your own instance. Head to #t-product on Slack to join us (https://mautic.org/slack to get an invite).

2. Test the Release Candidates! Every single release we make available a Release Candidate for folk to test and report any bugs that they might find, which we fix in the week between that release and the General Availability release. This has been the case since the 3.0 release.

3. If you are a developer, or you have developers in your team, consider picking up any of the pull requests in our backlog that are tagged with the label [needs-automated-tests](https://github.com/mautic/mautic/pulls?q=is%3Aopen+is%3Apr+label%3Aneeds-automated-tests). These are ready to go, but require automated tests before they can be merged. This is a hard-block to merging PR's [since 3.0](https://www.mautic.org/blog/press/mautic-community-introduces-multiple-major-improvements) (as our commitment to making Mautic less buggy, and directly addressing the points you raise).  Likewise, if you just feel like adding tests around a particular part of Mautic, you can submit a PR that simply adds those tests. We would LOVE to see that kind of PR.

3. Join the triage team. We need people who will help us work through the issue queue, work through the PR backlog, and reproduce issues, make sure that descriptions and PR test instructions are clear. Keep folk in the loop with what's happening. 1-2 hours per week maximum.

4. If you cannot contribute your time, and/or you do not have developer resources, consider financially supporting the project by: 
  - Sponsoring us on [Github](https://github.com/sponsors/mautic)
  - Backing us on [Open Collective](https://opencollective.com/mautic)  
  - Sponsoring the upcoming [Mautic Conference Global](https://mauticon.mautic.org) - details coming soon

5. If you can't contribute time, developer resources, or financially, then help us to attract people who can. We really need to raise our contributor base, so if there is anybody you know or come across who would be interested in helping us make Mautic better, in any way (marketers, writers, editors, project managers, documentation writers, event organisers .... the list is endless and there is something for everybody!) then please, send them our way.

The **only** way we are going to improve the situation is by people committing to helping us make positive change. It's a big ship that we are steering here, and it's taking time for us to turn around and increase our code coverage, implement better QA processes, and generally develop that "professional way of approaching this procedure". We can **only** do that if people are willing to get their hands dirty and make that change happen.

**Comment by MauriceW2** [comment]
Hello Ruth, thank you for explaining this. It was an awesome response. I 'll see what  can do!

**Comment by GeorgBNM** [comment]
Seems, with 4.4.7 the issue is back again. Hope for a fast fix.

`[2023-03-11 12:10:36] mautic.ERROR: [MAIL ERROR] Unable to open file for reading [image_URL] Log data: ++ Starting Swift_Transport_EsmtpTransport << 220 mail.xxx.de ESMTP Postfix  >> EHLO marketing.xxx.de  << 250-mail.xxx.de 250-PIPELINING 250-SIZE 31457280 250-ETRN 250-AUTH PLAIN LOGIN 250-AUTH=PLAIN LOGIN 250-ENHANCEDSTATUSCODES 250-8BITMIME 250-DSN 250 SMTPUTF8  >> AUTH PLAIN R2VvcmdAYmF1cm5ld21lZGlhLmMyLmV1AEdlb3JnQGJhdXJuZXdtZWRpYS5jMi5ldQBnTzlDaTlvdlYkYms=  << 235 2.7.0 Authentication successful  ++ Swift_Transport_EsmtpTransport started >> MAIL FROM:  >> RCPT TO:  >> DATA  << 250 2.1.0 Ok  << 250 2.1.5 Ok  << 354 End data with .  (send); email@email.com {"exception":"[object] (Swift_IoException(code: 0): Unable to open file for reading [image_URL] at /var/www/html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/ByteStream/FileByteStream.php:131)"} {"hostname":"bc75d01506f4","pid":10456}`

Best,
Georg
