### ISSUE TITLE
Add lead owner field in the update lead campaign action

### ISSUE THREAD

**Issue by tomferreira** [mautic/mautic#897]
Add lead owner field in update lead action.

**Comment by Robmobius** [comment]
+1

**Comment by npracht** [comment]
Hello,

Just to complete because it is not the only place where it is missing.
_____

## Problematic

The availability to edit lead owner of a lead is quite limited:

* Manual edit / creation of a lead
* List import
* Maybe API ? (To be checked)
* Suggestion

## Add places to edit lead owner of a lead:

* Campaign action « edit lead field » in the dropdown list of selectable fields.
* Point trigger events
* Form action tab
* API (if not already possible)

**Comment by kvalade** [comment]
This is a critical capability for our campaigns. 

For example, a specific offer should be routed to a specific salesperson. Or, we have an offer to capture new leads setup with an auto-responder email, and we want to use {signature} in the email, but have the email send with a specific lead owner dedicated to that offer, as opposed to the more generic default signature. Would be good to set a lead owner upon form submit, or add a hidden field to the form where we can set a default lead owner value.

**Comment by jordan8037310** [comment]
+1 for this per @kvalade. We route our offers to appropriate sales people. Hopefully others find this valuable and can help contribute. We might pick it up if we can get a customer to sponsor.

**Comment by luizeof** [comment]
@kuzmany @escopecz with #3980 it's time for this feature too?

**Comment by luizeof** [comment]
@virlatinus @kuzmany can you help with this feature?

Thanks!

**Comment by YannickBiet** [comment]
+1, this feature is a must have, our customers asked how they could automatically assign the owner based on the country... and it seems they can't... until we enable to update the owner field from a campaign.

**Comment by escopecz** [comment]
Closing in favour of https://github.com/mautic/mautic/issues/4774 which is planned for a future version
