### ISSUE TITLE
Send example/test email

### ISSUE THREAD

**Issue by janus-reith** [mautic/mautic#9036]
So far I was unable to find out how to to send a test for an email campaign.
The emails section of the developer documentation doesn't mention this either: https://developer.mautic.org/#emails

<img width="152" alt="Bildschirmfoto 2020-07-19 um 18 31 35" src="https://user-images.githubusercontent.com/1831220/87879940-17633b00-c9ee-11ea-8d92-5414872ebfac.png">

Is this implemented in the REST API?

**Comment by RCheesley** [comment]
Hi @janus-reith, please post your issue over at https://forum.mautic.org/c/development as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems or have questions :)

**Comment by janus-reith** [comment]
@RCheesley I disagree and consider this a correct fit for an issue.
I'd expect to go to the forums when I actually encounter specific issues related to my configuration and/or seek help with that, which is not the case here.
Although I agree that I could rephrase my post to not include a question to be on the safe side.

I expect one of the two options to be the case:
1. Sending a test for an email is present, but not documented -> An issue that this needs documentation seems reasonable.
2. Sending a test for an email is really not exposed over the REST API, which seems like more like an issue that it's missing than an explicit design decision or something that should be explicitly requested as a new feature, given how feature-complete some other parts of the API are.

I'd kindly ask you to reopen this, except for if you totally have a different opinion on this and see this fit into to general scope of what people refer to as feature request.

**Comment by benfavre** [comment]
The fuck is wrong with people, why was this closed ?

**Comment by benfavre** [comment]
why was this closed ?

**Comment by greichel-evrima** [comment]
For anyone landing here from search: until now this wasn't available in the REST API — only the **Send example** button in the email builder UI could send a test/proof copy.

I've opened a PR that adds it: mautic/mautic#16308. It introduces a new endpoint:

`POST /api/emails/{id}/example/send`

It's the API equivalent of the UI action and reuses the same core service (`EmailModel::sendSampleEmailToUser`), so the behavior matches:

- Sends a proof copy to one or more arbitrary addresses (`recipients`)
- **No stats recorded** and the tracking pixel is stripped
- **Works on unpublished/draft emails**
- Fills tokens with fake contact data by default, or a real contact's data via `contactId`
- `[TEST]` subject prefix (optional via `noSubjectPrefix`), and the stored email is never modified

Developer docs PR: mautic/developer-documentation-new#540.

Since this issue is closed, maybe worth reopening to track until the PR merges — the PR is set to `Fixes #9036`, so it'll close again automatically on merge.
