### ISSUE TITLE
Allow "input placeholder" in a textarea form field

### ISSUE THREAD

**Issue by troelsfeodor** [mautic/mautic#907]
I'm using the Input placeholder field in my form fields instead of the label which I've turned off - to get a nice looking form.
However, the textarea field does not offer that option, but only allows me to use a "default value" which is not ideal.

**Comment by escopecz** [comment]
There is lots of HTML attributes which can be added to the field configuration and also, anyone can create custom attributes. That's why instead of this extensive configuration there is generic option to add any HTML attribute to the field HTML tag.
![mautic-form-placeholder](https://cloud.githubusercontent.com/assets/1235442/9958516/12a3ee38-5e0b-11e5-8cdc-4db3abecf9d7.png)

**Comment by mathysp** [comment]
For consistency reasons it would still be better if the "input placeholder" was available as a setting. It works like this for all other fields, so there is no good reason to exclude textareas just because "There is lots of HTML attributes which can be added to the field configuration". 

Either you make the same setting available to all types, or you don't show it for any of the fields.

Remember that Mautic is usually managed by people with limited html knowledge. This adds yet another barrier that makes things harder for them to manage.
