### ISSUE TITLE
Forms do not submit

### ISSUE THREAD

**Issue by rileyseaburg** [mautic/mautic#9084]
## Bug Description
Mautic forms are not submitting to the API.

After creation of the a form when submitting the page reloads but not api calls are made.
Not sure what the issue is as there are no errors in the logs or in the inspector.

| Q   | A
| --- | ---
| Mautic version | 3.0.2
| PHP version | 7.3.20
| Browser | Chrome

### Steps to reproduce
1.  Install Mautic
2.  Create A Form 
3. Post form on landing page
4. Submit form
5. Page reloads no API calls made.
 
### Log errors
None

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
@mabumusa1 would you mind taking a look at this one please?

**Comment by mabumusa1** [comment]
@RileySeaburg Thanks for reporting this. I think you mean webhooks instead of APIs because forms would not issue API calls after submitting, they will produce a webhook. which should be configured like this 

![image](https://user-images.githubusercontent.com/12627658/90953783-2880eb00-e477-11ea-8028-469187771b61.png)

I tested webhooks and everything is working as expected, may you please rewrite the steps in details to test it on my end

**Comment by rileyseaburg** [comment]
The documentation doesn't make this clear. 

The typical action is for a form to just submit to a specified url which is either through webhook or API.

Please update the documentation to make clear to novice users that in order for a form to be submitted outside of a Muatic hosted landing page that a corresponding webhook must also be created.
