### ISSUE TITLE
failed to send error message - on top

### ISSUE THREAD

**Issue by frankofno** [mautic/mautic#9221]
[//]: # ( Invisible comment: 

## Bug Description
Adding a contact manually with a wrong (not existing email).
After that go to the contact, choose send email from template (choose a long message).
Since the send button is all the way down at the bottom, you will not see the failed to send error message on top.

| Q   | A
| --- | ---
mautic 3.1.0
php 7.3.22
firefox| 

### Steps to reproduce
Adding a contact manually with a wrong (not existing email).
After that go to the contact, choose send email from template (choose a long message).
Since the send button is all the way down at the bottom, you will not see the "failed to send error message" on top.
You have to scroll up by accident to find out, that the email address does not exist and therefor the email can not be sent.

Screenshot: the send button at the end of the message:
![Screenshot 2020-09-20 at 16 37 59](https://user-images.githubusercontent.com/35775329/93717394-cef30580-fb75-11ea-8fa7-f6567144ecbc.png)

Screenshot: error message at top of the message in case the email does not exist:
![Screenshot 2020-09-20 at 16 38 13](https://user-images.githubusercontent.com/35775329/93717406-ea5e1080-fb75-11ea-973e-a6bf34229491.png)

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
@frankofno do you suggest that the error message should instead be rendered at the bottom of the page beside the send button, rather than at the top of the page? Just so I can understand what it is you're reporting and how it might be resolved.

If so, would you like to take a go at making a pull request to implement this?

**Comment by frankofno** [comment]
Yes, actually I would move the whole part up. 
So the template dropdown field,  the cancel button and send button are always above the message field/box.
First pull request, not sure what to do, I will find out I guess :)

**Comment by RCheesley** [comment]
OK let's get some thoughts from @mautic/core-team about this proposal before we start poking about in the code. 

From the user perspective I get where you're coming from, but equally once you've created the email and you're at the bottom of the page, you don't want to have to go all the way to the top in order to hit save - that would be super confusing and somewhat frustrating. So I think that moving the save button and template select to the top might be counter-intuitive.

I can, however, see how moving the error message down to the bottom (or having it appear as an alert/notification instead) could be useful - as you say, when you hit save you're going to be at the very bottom of the page so it doesn't make sense to have the error out of view.

**Comment by escopecz** [comment]
The modal buttons are down in all modal windows throughout the UI. Let's be consistent and have them always at the same space.

**Comment by RCheesley** [comment]
@escopecz how about the error message? I have experienced the issue that @frankofno mentions myself several times in Mautic where the error is appearing a long way from the submit button.

**Comment by frankofno** [comment]
How about a scrollable content / body field? So all buttons and fields are visible.

I guess there are different scenarios in here:

- Writing a new long email so a send button down - great
- Choosing a template email - i don't actually need to be at the bottom - send button top -great
- Either way, many times I set the subject at last. So after composing I have to go up, to type in the subject.
- Before hitting send I actually like to check the address | subject, so a send button near and on top would be convinient.

The way I came across this issue is quit rare and happens at the beginning when testing I guess. In most cases you don't actually want to type or send individual emails.
The fact that I hit the cancel button several times and closed the whole thing, because the send button was not doing a thing shows this can become a dead end.

**Comment by RCheesley** [comment]
I think from my perspective I would prefer that we keep this simple, and have the error message show beside the send/cancel button rather than right at the top of the popup.  @frankofno would you be up for looking into making a PR for this change?
