### ISSUE TITLE
Feature Request - Throttle Logic for Forms/Campaigns

### ISSUE THREAD

**Issue by TornMarketing** [mautic/mautic#9249]
**Feature Request - Throttle Logic for Forms/Campaigns**

We are ultimately using the forms to send autoresponders to the prospects and send lead alerts to relevant stakeholders.
We would want to throttle this so that if someone submits 10 times in 5 minutes, the actions only result in 1 email. 
But if they submit again an hour later, it has cleared any potential system noise and would allow the action to be processed.

Need a means of throttling logic where duplicate submissions with the same email comes through within a specified timeframe. 
ie where a form maybe integrated on a product page, and a prospect submits enquiries on multiple forms with different context, or a slow form submitting for whatever reason results in the frontend user submitting multiple times.

We would be looking for a means of throttling a form and/or campaign actions based on a specified logic
ie throttle submission where a duplicate emails are the same for the next x minutes/hours.

Or same as above but with an additional condition, throttle where same email and is not {custom_field} = {custom_field}
Thus allowing different variations of a form to be submitted for different context by the same user.

**Comment by RCheesley** [comment]
Hi @TornMarketing thanks for sharing your ideas for how to improve Mautic!

In the Mautic community we use Github issues for reporting bugs 🐛 only - not for suggesting feature requests. The reason for this is that we have a large audience who are not developers and do not venture into Github, and we want those folk to be able to engage in discussions about features that might be considered for Mautic.  We also want to keep our issue queue clean so that developers can quickly find bugs to work on.

Please post your feature request at https://forum.mautic.org/c/ideas. This is where we discuss new features and ideas, until they have code associated with them. Please use the post template when you share your idea there.  When you have someone interested in working on an idea, they can create a pull request and start to work on that in Github as a WIP pull request - if they pop the link in the forum thread it will create a reciprocal link between the discussion in the forum and the Github PR.

Thanks again for your interest in helping to improve Mautic!
