### ISSUE TITLE
Allow using the same point action multiple times per lead for multiple emails, page hit URLs, etc

### ISSUE THREAD

**Issue by Jakub087** [mautic/mautic#929]
Hi, 

I did set up points per action  - opening email = + 2 points.
But points are added to lead just for first time. It does not matter if lead opens 1 or 10 emails --> lead still get same points for opening just first email.

How do I set it up that points are added every time lead opens sent email?

Thanks, Jacob

**Comment by ptcc** [comment]
i see the same, for email opens and for page visits too...

**Comment by alanhartless** [comment]
Point actions are tracked and applied per lead once.  To get around this, you'll need an action per email or per unique URL.

I'll mark this as a feature request though to consider tracking and allowing a single point action for multiple emails, page hits, etc per lead.

**Comment by LAN-Laurene** [comment]
Hello,

We have encountered the same problem.

We put some "logs" in order to understand better and have been able to make some fixes (see the pull request).

We now have this error:
`[2016-04-13 13:30:33] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\DBALException: "An exception occurred while executing 'INSERT INTO point_lead_action_log (date_fired, point_id, lead_id, ip_id) VALUES (?, ?, ?, ?)' with params ["2016-04-13 13:30:33", 2, 274, 1]:  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '2-274' for key 'PRIMARY'" at D:\git\Automation_dev\vendor\doctrine\dbal\lib\Doctrine\DBAL\DBALException.php line 91 {"exception":"[object] (Doctrine\\DBAL\\DBALException(code: 0): An exception occurred while executing 'INSERT INTO point_lead_action_log (date_fired, point_id, lead_id, ip_id) VALUES (?, ?, ?, ?)' with params [\"2016-04-13 13:30:33\", 2, 274, 1]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '2-274' for key 'PRIMARY' at D:\\git\\Automation_dev\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\DBALException.php:91, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '2-274' for key 'PRIMARY' at D:\\git\\Automation_dev\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Statement.php:165)"} []`

For now, we are not going further on that subject.

Here are the "Manage Actions" that I would use in order to test this : 
![capture7](https://cloud.githubusercontent.com/assets/17120397/14497383/1936b69c-0197-11e6-8c2a-37a78468e087.PNG)
![capture6](https://cloud.githubusercontent.com/assets/17120397/14497391/21027960-0197-11e6-8006-f3dd10b71411.PNG)

**Comment by jjroelofs** [comment]
I would also like to be able to score leads based on how many pages they visited on the site and then it would make more sense to count visits on example.com/* rather than making an event for ever page and page-revisit, which would be impossible on any sizeable website. +1

**Comment by cspenn** [comment]
I'll +1 this as well. Other marketing automation systems offer the ability to constantly increment a score with similar activities like reading the weekly newsletter.

**Comment by rcarloscalderon** [comment]
+1

**Comment by bloodlynx** [comment]
+1 Would be nice if could be time related, so every time a lead views a page for let's say 30 seconds the leads get's another point.

**Comment by vdittgen** [comment]
+1

**Comment by hansakoch** [comment]
+1

**Comment by mellsaid** [comment]
+1

**Comment by zenzozen** [comment]
+1. Manually adding Point Action for every email sent or url visited doesnt seem an automated approach. Thanks!

**Comment by freqout** [comment]
Has there been any motion on this? I need to both have every hit be scored and also be able to wildcard content within a section of a site (i.e. http://site.com/section/*) and score all content there based on per-content-type defaults.

**Comment by visual4** [comment]
+1 from me... We'd need this for a page that is showing dynamic content from a database, not the single pageview matters, but the total.

**Comment by jaisonveneri** [comment]
+1

**Comment by bigdatabreen** [comment]
+1

**Comment by ramezrafla** [comment]
+1
If you have a large email list, you can't keep clicking each contact to see their activity. We can have a switch 'One time' in the action, this feature is a must for proper tracking of activity, as right now we are truly blind on actual engagments.

**Comment by YannickBiet** [comment]
+1

Thanks to @escopecz to maintain the bug tracker, sometimes hard to find the original bug / FR reports when they are aged of almost two years now !

**Comment by rorymadden** [comment]
+1 This would be very useful.

**Comment by dannyfranca** [comment]
+1

**Comment by cspenn** [comment]
Any progress on this?

**Comment by migrivas** [comment]
+1

**Comment by cpot** [comment]
+10

Very very important for scoring. A suspect that looks at 10 pages if far more important than one looking to only one

**Comment by toddviau** [comment]
+1

**Comment by katzueno** [comment]
+1

**Comment by kolinz** [comment]
+1

**Comment by aleksanterip** [comment]
+1

**Comment by Woeler** [comment]
Is there any news on a feature like this? Giving points based on multiple visits to a page is really an essential feature. Even if it requires a big code change, is this planned for a next major version? Yes, no? If so, can I help?

**Comment by dbhurley** [comment]
In order to improve engagement and increase visibility to this feature request we are closing this issue on GitHub and recommending all Feature Requests (without code attachment) be placed in the [Ideas forum](https://www.mautic.org/forums/forum/ideas) on our community site. 

We recommend you post your ideas to Mautic's forum so others can comment on them and help turn your ideas into a proof of concept and eventually an exciting new feature in Mautic. 

_More information about this move can be found in our [blog announcement](https://www.mautic.org/community-blog/moving-feature-requests/)._
