### ISSUE TITLE
[UI] Tracking URLs are extremely large/long in lead screen

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#93]
In the lead screen, the tracking URLs are exceptionally long which breaks the UI considerably, and makes it difficult to see activity easily.

http://nimb.ws/j7Ti4m

**Comment by escopecz** [comment]
If you'll use [Joomla plugin](https://github.com/mautic/mautic-joomla) or [WP plugin](https://github.com/mautic/mautic-wordpress) with the next release of Mautic, you'll be able to see Page names instead of that long URL.

The tracking image technique has its limits. It is possible to bypass these limits with additional information passed inside the URL query of the tracking image. Latest versions of those 2 plugins add missing information to the tracking image URL and Mautic then use it.

**Comment by alanhartless** [comment]
Closing this as it was resolved in the latest version of Mautic and Joomla plugin.  If you find otherwise, we'll reopen.

Thanks!
Alan

**Comment by RCheesley** [comment]
I've updated the plugin on the site, and updated Mautic, and I'm still seeing big long URLs.

**Comment by alanhartless** [comment]
No, the PRs aren't against this issue. @escopecz Any thoughts?

**Comment by escopecz** [comment]
Ruth is using hosted version I think. I didn't commit the fix there because of the merge confusion. I'll fix it right away.

**Comment by RCheesley** [comment]
Yes, we are using the hosted version for this account.

Ruth
On 2 Mar 2015 07:57, "John Linhart" <notifications@github.com> wrote:

> Ruth is using hosted version I think. I didn't commit the fix there
> because of the merge confusion. I'll fix it right away.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/mautic/mautic/issues/93#issuecomment-76671070>.
>

-- 
Be like me, be Carbon free - don't print this and save a tree
IMPORTANT: The contents of this email and any attachments are confidential. 
They are intended for the named recipient(s) only. If you have received 
this email by mistake, please notify the sender immediately and do not 
disclose the contents to anyone or make copies thereof.
