### ISSUE TITLE
Non administrator role can not override locked segment

### ISSUE THREAD

**Issue by nrfocus** [mautic/mautic#9324]
Detail your bug report:

| Q  | A
| ---| ---
| Confirm it is a Bug report |
| Mautic version | 3.1.1
| PHP version | 7.3.22

[//]: # (Feature request? ---> Go to forum please ---> https://forum.mautic.org/c/ideas)
[//]: # (Enhancement? ---> Go to forum please ---> https://forum.mautic.org/c/ideas)
[//]: # (Need support, have questions? ---> Go to forum please ---> https://forum.mautic.org/c/support)

## Description:
Non administrator role can not override locked segment
related issue :  https://github.com/mautic/mautic/issues/8870

### Steps to reproduce:
1. I created a Role let’s call it “R1” with the following “Contact permissions”
Contacts - User has access to : Full
Segments - User has access to: Full
Import - User has access to: View

2. When user “U1” having role “R1” edit a segment “S1”, user “U2” having role “R1” can not override the locked segment S1.
Only a user having “Administrator” role can override the locked segment “S1”.
 
### Log errors: 

no errors

**Comment by RCheesley** [comment]
Thanks for submitting this @nrfocus - I'm not sure that this is actually a bug.

If I managed a Mautic instance, I would not want regular users to be able to clear the locks on anything while they are being edited, because this could lead to someone inadvertently cancelling another user's changes while they were making them.

What is the use case where you would want or need a non-administrative user to be able to carry out this function?

Usually I would expect in this situation, for the non-admin users to have to make a request to an admin to clear the lock.  Interested to understand why that isn't an option in your situation!

**Comment by vyahhi** [comment]
@RCheesley looks like it was implemented in https://github.com/mautic/mautic/pull/2291, so this issue may be a bug indeed.
