### ISSUE TITLE
Issue updating enum fields from Pipedrive

### ISSUE THREAD

**Issue by janwinkler** [mautic/mautic#9384]
https://github.com/mautic/mautic/blob/32401017622b13c7bb80331e6e821667c74d8aa6/plugins/MauticCrmBundle/Integration/Pipedrive/AbstractPipedrive.php#L57-L67

Seems incorrect. Type "enum" returns a single string. Use instead:

     if(in_array($field['field_type'], ['enum']) && in_array($field['key'], $keys))
     {
      $pipedriveContactFieldOption = $data[$field['key']];
      $pipedriveAllFieldOptions = array_combine(array_values(array_column($field['options'], 'id')), array_column($field['options'], 'label'));
      if(isset($pipedriveAllFieldOptions[$pipedriveContactFieldOption]))
      {
       $data[$field['key']] = $pipedriveAllFieldOptions[$pipedriveContactFieldOption];
      }
     }
     else if(in_array($field['field_type'], ['set']) && in_array($field['key'], $keys))
     {
... old code ...
    }

**Comment by RCheesley** [comment]
@janwinkler thanks for the bug report, although it's not entirely clear for a user who isn't familiar with Pipedrive what the issue is. If you'd like to submit a PR to address this please do, there's guidance on how to do this at https://contribute.mautic.org/contributing-to-mautic/developer/code/pull-requests.

We do have some [open PR's relating to Pipedrive](https://github.com/mautic/mautic/pulls?q=is%3Apr+is%3Aopen+pipedrive) so you may want to review them first to check if any address this issue.
