### ISSUE TITLE
Redirect loop

### ISSUE THREAD

**Issue by bvanrhijn** [mautic/mautic#9395]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Good fun, I've been running into redirect loops on 3.1.2 after clearing the cache. I get 19 redirect loops in a row. 20 if I start with an http link. Is this a Symfony bug? Error.log and Mautics logs are empty for the day.

| Q   | A
| --- | ---
| Mautic version | 3.1.2
| PHP version | 7.3.24
| Browser | Chrome & Firefox latest

### Steps to reproduce
1. Install Fresh Mautic 3.1.2 
2. Wait 2 days for it to become a bag of bugs that you need to clear cache for.
3. Clear the cache and surprise your site is now broken. You need to restore from a backup to get it working until you clear cache again. 
 
### Log errors
No log entries in error.log (apache) or mautic's log even after several goes at this. 

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by bvanrhijn** [comment]
I found the reason why this is happening. I've got Mautic behind Haproxy.

Found this link in an obscure Mautic doc. https://symfony.com/doc/current/deployment/proxies.html
But no real suggestion where to implement this in Mautic. Assuming this goes in index.php in the document root?

**Comment by RCheesley** [comment]
@bvanrhijn glad to hear you got this sorted. In terms of working behind a proxy the documentation you linked to is from Symfony rather than Mautic, but there are various guides to setting it up, take a look at this one from Autoize for example: https://autoize.com/logging-client-ip-addresses-behind-a-proxy-with-docker/.

We do have an open PR suggesting improving support for proxies but it needs work before we can merge it.  We'd also love to have some documentation in our Knowledgebase https://kb.mautic.org if you'd like to help by contributing anything.
