### ISSUE TITLE
Foreign keys are not created  on plugin install

### ISSUE THREAD

**Issue by kuzmany** [mautic/mautic#9502]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
On plugin install foreign keys are not created, even If we expect it.
I understand during the install plugin we work  just with plugin db schema, and link to others tables are skipped. 

I am able to create this foreign keys after plugin install schema in each plugin, but I am looking for smoother solution, If exists.

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 
| Browser | 

### Steps to reproduce
1. Install plugin https://github.com/kuzmany/mautic-plugin-test-bundle 
2. Expect two columns id and lead_id with foreign key to leads table
![image](https://user-images.githubusercontent.com/462477/102323943-71f2ca00-3f81-11eb-905f-1724853a9239.png)
3. Not foregin key created
4. Call `php bin/console doctrine:schema:update --dump-sql`
5. See there is foreign key update for plugintest table
6. 
![image](https://user-images.githubusercontent.com/462477/102326174-5a691080-3f84-11eb-89c4-d55df4bb5355.png)

 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by alanhartless** [comment]
I’d recommend to use the IntegrationBundle’s migration system instead of relying on Doctrine to generate. 
https://github.com/mautic/plugin-helloworld/blob/mautic-3/HelloWorldBundle.php#L7
https://github.com/mautic/plugin-helloworld/tree/mautic-3/Migrations

My guess is that Doctrine doesn’t recognize the relationship from the core side based on the plugin's entity metadata. Or maybe the relationship is mis-configured. In either case, the PluginBundle's migration depends on Doctrine generating a schema diff.

**Comment by alanhartless** [comment]
Sorry, I went from the slack message and didn't fully read the description above. 🤦 Regardless if Doctrine generates the schema diff, I'd still recommend using the IntegrationBundle's migration system.

**Comment by kuzmany** [comment]
Ok, thanks.
