### ISSUE TITLE
package-versions does not exist and could not be created.

### ISSUE THREAD

**Issue by EnziinSystem** [mautic/mautic#9533]
My environment:
```
php -v
PHP 7.4.13 (cli) (built: Nov 28 2020 06:24:59) ( NTS )
```
I download the zip file and composer install
```
wget https://github.com/mautic/mautic/archive/features.zip
unzip features.zip
mv mautic-features mautic
cd mautic/
composer install
```
It very simple, but I get an error.
```
In Filesystem.php line 186:
                                                                                                    
  xxx/mautic/vendor/ocramius/package-versions does not exist and could not be created.  
```

**Comment by saitanay** [comment]
Can you confirm the version of composer you are using. I believe this is being caused by using composer v2. 

Quoting @RCheesley from https://github.com/mautic/mautic/issues/9478 
`Hi there, we do not currently support composer v2, we hope to introduce that in Mautic 4.0 (we have to bump some dependencies which will cause a BC break, so we can't bring it in before then).`
