### ISSUE TITLE
Utm added to url with query string should use "&" instead of ?

### ISSUE THREAD

**Issue by valmedia** [mautic/mautic#9536]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version |  3.2.1
| PHP version |  7.3
| Browser | 

### Steps to reproduce
1.  Just use an URL with query strings in email content
2. 
 
### Log errors

[//]: # ( Invisible comment:

Having a minor issue where the URL we are using has query string already and utm parameters were added with ? instead of &.

**Comment by npracht** [comment]
Hi @valmedia !
Thanks for your message. I'm very sorry but I'm not sure to understand. Could you please document more in detail and use example to explain your issue ?

Thanks

**Comment by valmedia** [comment]
So I have an URL like https://xxxx.com/cart/?mauwoo_utype=guest&mauwoo_uid=testtest@test.com added to email content and I also have UTM parameters added to the "Google Analytics UTM tags" section of the edit section. So when the email is sent out, the utm parameters would be added to this URL with "?" instead of "&". So the URL ends up being "https://xxxx.com/cart/?mauwoo_utype=guest&mauwoo_uid=testtest@test.com?utm_source=123&utm_medium=email" instead of "https://xxxx.com/cart/?mauwoo_utype=guest&mauwoo_uid=testtest@test.com&utm_source=123&utm_medium=email".

Thanks

**Comment by saitanay** [comment]
Tested on 3.2.1

Added link on email
`https://xxxx.com/cart/?mauwoo_utype=guest&mauwoo_uid=testtest@test.com`

Email GTM config
<img width="402" alt="image" src="https://user-images.githubusercontent.com/3456349/103170969-6c915b80-486e-11eb-9d51-62a9c04e9387.png">

Link received in email (sent via Amazon SES):
`https://xxxx.com/cart/?mauwoo_utype=guest&mauwoo_uid=testtest%40test.com&utm_source=googlesource123&utm_medium=googlemedium123&utm_campaign=googlecampaignname123&utm_content=googlecampaigncontent123`

Apart from URL encoding, which is expected, the additional UTM tags added are all added via "&" and there was no additional "?" added to the link received in email. 

Markup from the email received. (Checked via "View Original" option on gmail)
`                                                            <div data-slot=
=3D"text" style=3D"font-family:'Open Sans', Helvetica, Arial, sans-serif;fo=
nt-size:14px;line-height:1.6;text-align:left;color:#414141;"><h1>Hello Worl=
d!</h1>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid of=
ficia consequatur placeat reprehenderit excepturi, tempore, id quos quaerat=
 ab fuga.<br /><br />Lorem ipsum dolor sit amet, consectetur adipisicing el=
it. Inventore, voluptate.<br /><br /><a href=3D"http://localhost/r/2e3b8eff=
38b0b4b1cb9324aa0?ct=3DYTo1OntzOjY6InNvdXJjZSI7YToyOntpOjA7czo1OiJlbWFpbCI7=
aToxO2k6MTt9czo1OiJlbWFpbCI7aToxO3M6NDoic3RhdCI7czoyMjoiNWZlODdlYzM3Y2UyMDQ=
1NzY1NDQzNSI7czo0OiJsZWFkIjtzOjE6IjEiO3M6NzoiY2hhbm5lbCI7YToxOntzOjU6ImVtYW=
lsIjtpOjE7fX0%3D&utm_source=3Dgooglesource123&utm_medium=3Dgooglemedium123&=
utm_campaign=3Dgooglecampaignname123&utm_content=3Dgooglecampaigncontent123=
">https://xxxx.com/cart/?mauwoo_utype=3Dguest&mauwoo_uid=3Dtesttest@test.co=
m</a>=C2=A0<br /><br />Lorem ipsum dolor sit amet, consectetur adipisicing =
elit. Dignissimos alias rerum nemo ducimus modi perspiciatis.</div>
`

Although there is a remote possibility that since i received the URL in gmail, which is actually tracked by google by replacing with a redirection from a google domain, it could be the case that google is fixing the URL by replacing the second ? with a &, before redirecting to https://xxxx.com/cart/?mauwoo_utype=guest&mauwoo_uid=testtest%40test.com&utm_source=googlesource123&utm_medium=googlemedium123&utm_campaign=googlecampaignname123&utm_content=googlecampaigncontent123  . Unlikely, but unable to confirm

**Comment by valmedia** [comment]
> Tested on 3.2.1
> 
> Added link on email
> `https://xxxx.com/cart/?mauwoo_utype=guest&mauwoo_uid=testtest@test.com`
> 
> Email GTM config
> <img alt="image" width="402" src="https://user-images.githubusercontent.com/3456349/103170969-6c915b80-486e-11eb-9d51-62a9c04e9387.png">
> 
> Link received in email (sent via Amazon SES):
> `https://xxxx.com/cart/?mauwoo_utype=guest&mauwoo_uid=testtest%40test.com&utm_source=googlesource123&utm_medium=googlemedium123&utm_campaign=googlecampaignname123&utm_content=googlecampaigncontent123`
> 
> Apart from URL encoding, which is expected, the additional UTM tags added are all added via "&" and there was no additional "?" added to the link received in email.
> 
> Markup from the email received. (Checked via "View Original" option on gmail)
> ` <div data-slot= =3D"text" style=3D"font-family:'Open Sans', Helvetica, Arial, sans-serif;fo= nt-size:14px;line-height:1.6;text-align:left;color:#414141;"><h1>Hello Worl= d!</h1>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid of= ficia consequatur placeat reprehenderit excepturi, tempore, id quos quaerat= ab fuga.<br /><br />Lorem ipsum dolor sit amet, consectetur adipisicing el= it. Inventore, voluptate.<br /><br /><a href=3D"http://localhost/r/2e3b8eff= 38b0b4b1cb9324aa0?ct=3DYTo1OntzOjY6InNvdXJjZSI7YToyOntpOjA7czo1OiJlbWFpbCI7= aToxO2k6MTt9czo1OiJlbWFpbCI7aToxO3M6NDoic3RhdCI7czoyMjoiNWZlODdlYzM3Y2UyMDQ= 1NzY1NDQzNSI7czo0OiJsZWFkIjtzOjE6IjEiO3M6NzoiY2hhbm5lbCI7YToxOntzOjU6ImVtYW= lsIjtpOjE7fX0%3D&utm_source=3Dgooglesource123&utm_medium=3Dgooglemedium123&= utm_campaign=3Dgooglecampaignname123&utm_content=3Dgooglecampaigncontent123= ">https://xxxx.com/cart/?mauwoo_utype=3Dguest&mauwoo_uid=3Dtesttest@test.co= m</a>=C2=A0<br /><br />Lorem ipsum dolor sit amet, consectetur adipisicing = elit. Dignissimos alias rerum nemo ducimus modi perspiciatis.</div>`
> 
> Although there is a remote possibility that since i received the URL in gmail, which is actually tracked by google by replacing with a redirection from a google domain, it could be the case that google is fixing the URL by replacing the second ? with a &, before redirecting to https://xxxx.com/cart/?mauwoo_utype=guest&mauwoo_uid=testtest%40test.com&utm_source=googlesource123&utm_medium=googlemedium123&utm_campaign=googlecampaignname123&utm_content=googlecampaigncontent123 . Unlikely, but unable to confirm

I figured it out now. We used {contactfield=mwb_abncart_url} as URL and it seems to replace the placeholder after Mautic added UTM parameters so Mautic didn't detect the "?".

-Tony
