### ISSUE TITLE
Landing page doesn't autofill form with querystring parameters

### ISSUE THREAD

**Issue by smcpeck** [mautic/mautic#9545]
## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 3.2.2
| PHP version | 7.2.34

### Steps to reproduce
1. Create form with fields email_address, first_name, last_name

![image](https://user-images.githubusercontent.com/8724583/103330808-b1f98880-4a28-11eb-9615-336c58303586.png)

2. Create landing page with form embedded

3. Create e-mail with link to landing page
`{pagelink=2}?email_address={contactfield=email}&first_name={contactfield=firstname}&last_name={contactfield=lastname}`

    3a. Attempts to use the URL Encode filter (i.e. `{contactfield=email|true}`) seems to break things as the pipe character is encoded by the page builder.

![image](https://user-images.githubusercontent.com/8724583/103330908-292f1c80-4a29-11eb-88fc-52bf6188ac34.png)

4. Send e-mail, click link.

5. Form does not autofill with query string parameters.

    5a. Assuming maybe URL Encoding with the e-mail address (due to the `@` character) may be an issue, removing that and just going with `?first_name=Shaun&last_name=McPeck` still fails to populate (and hide) the fields for which values were provided.
 
I know the page/email builder is being revamped for a future release, so I know there's not a lot of work being done on that existing code base, but a quick hack that might fix this would be great!  (Also, maybe I'm just missing something and/or doing something wrong so there's a better "do it the right way" fix. 🤣)

Any guidance would be a great help. Cheers!

An old thread that I found didn't seem to have anything helpful for me: https://forum.mautic.org/t/how-to-pass-url-parameters-to-a-form/15315/13

**Comment by saitanay** [comment]
**Triage/Analysis**

Firstly, this is not related to pages or emails, as the functionality to populate the form by adding params to  the URL seems to be broken. ie, ?email_address=saitanay@example.com is not working, let alone passing token like ?email_address={contactfield=email} 

The reporter also suggests the same
`just going with ?first_name=Shaun&last_name=McPeck still fails to populate (and hide) the fields for which values were provided.`

The source of this issue seems to be the regex written in `app/bundles/FormBundle/Helper/FormFieldHelper.php`

`if (preg_match('/<input(.*?)id="mauticform_input_'.$formName.'_'.$alias.'"(.*?)value="(.*?)"(.*?)\/>/i', $formHtml, $match)) {`

This tries to match the HTML which is
`<input id="mauticform_input_mauticissues9545_first_name" name="mauticform[first_name]" value="" class="mauticform-input" type="text" />\n`

This seems to have worked in the past, although some regression seems to have caused changes over time to the form HTML markup that has caused the regex to break. 
The current regex works only if
* id is the first param in the input tag
* **value** attribute in the html of the input element comes right after the **id** attribute
* The input tag has a "/" before the closing ">"

This is failing now because the form markup generated inserts a name attribute between the id and value attributes of the input field markup. Further the "/" before the closing ">" is gone now. 

This will likely affect other types of fields than just text as well. 

Fixing the regex accordingly only for Text field. Might require further testing and fix for other types of fields like Checkbox etc

PR: https://github.com/mautic/mautic/pull/9550

**Comment by smcpeck** [comment]
Thanks for your detective work on this @saitanay! I can confirm that the RegEx change **does** fix the autofill issue that I was experiencing. It even works for e-mail addresses, so that was a red herring -- the `@` is not an issue in the querystring and things don't need to be URL encoded.

This feels like a pretty important part of Mautic's overall usefulness, so I'd also hope that we could see some units tests to help ensure that this sort of thing doesn't pop up again.

Another side effect that is still lingering: The `Show when Value Exists = No` flag doesn't seem to be getting consumed properly. So this part still needs some investigation.

As @saitanay already mentioned, this is only fixing text fields... so other field types likely need a RegEx tweak as well.

I'm happy to help with testing (and even some code), but my RegEx is weak and I need a little Mautic developer on boarding to understand the structure of the code base and get a dev environment setup.  Let me know if I can help with anything.

**Comment by saitanay** [comment]
Thanks for confirming that the fix works @smcpeck . 

I am currently checking on some PHPUnit tests that are failing for the PR I raised. (https://github.com/mautic/mautic/pull/9550)

Once I understand the failing tests, and fix (either the test or the code), I intend to look into the other field types as well. 

> Show when Value Exists = No

Will need to check this further. I am not sure what that means. 

>  I'd also hope that we could see some units tests to help ensure that this sort of thing doesn't pop up again.

Rightly said

**Comment by smcpeck** [comment]
🍻  Cheers to you, @saitanay.

To be clear, I'm looking at how the following `Behavior` flag is consumed on a `Field` for the `Form`:
![image](https://user-images.githubusercontent.com/8724583/103421099-474b6880-4b60-11eb-8f72-6a190a366e51.png)

...and maybe that's a whole different issue. I don't want to load up too many bugs in one issue/PR. So I'm happy opening another issue for that item if it makes the most sense. But it definitely seems related.


I don't expect that my hack is the "right place" to handle the `Show when Value Exists` functionality, but I have  hack in place on my landing page that gets the job done with a little jQuery.
```
var fields = ['first_name', 'last_name', 'email_address'];
$("input:not([value=''])").filter(
   function() {
      $inp = $(this)[0];
      return fields.filter(
         function(el) {
            return $inp.name.includes(el);
         }
      ).length != 0;
   }
).closest("div").hide(); 
```

**Comment by saitanay** [comment]
Thanks, that clarifies. Yeah, adding that as a separate bug helps. 

Meanwhile, for the other field types - an earlier PR that I raised (and closed) addresses all field types. I closed it and trimmed down the changes to just the text field type until I figured out the issues with PHPUnit tests issue with the text field type. 

Meanwhile, if you need the fix for other field types for reference to try out, they are on this closed PR - https://github.com/mautic/mautic/pull/9549/files
