### ISSUE TITLE
add proxy support for the http/https updates

### ISSUE THREAD

**Issue by protondev9** [mautic/mautic#9579]
## Bug Description
Currently Mautic does not allow the updates via a proxy server: there seem to be no setting to confugure proxy support in Mautic configuration files and Mautic does not respect HTTP_PROXY or HTTPS_PROXY environment variable for CLI operations.

### Log errors
Without setting HTTPS_PROXY, running `mautic:update:find` returns `An error occurred while checking for updates. Please try again later.`. The following line is added to the logs:
```
mautic.ERROR: An error occurred while attempting to fetch updates: Failed to connect to 104.236.73.40: Network is unreachable [] []
```

With HTTPS_PROXY set, the behaviour is different:
```
PHP Notice:  Trying to get property 'latest_version' of non-object in /var/www/html/mautic/app/bundles/CoreBundle/Helper/UpdateHelper.php on line 207

Notice: Trying to get property 'latest_version' of non-object in /var/www/html/mautic/app/bundles/CoreBundle/Helper/UpdateHelper.php on line 207
PHP Notice:  Trying to get property 'version' of non-object in /var/www/html/mautic/app/bundles/CoreBundle/Helper/UpdateHelper.php on line 215

Notice: Trying to get property 'version' of non-object in /var/www/html/mautic/app/bundles/CoreBundle/Helper/UpdateHelper.php on line 215
Great! You are running the current version of Mautic.
```
That is because the line 175 in /var/www/html/mautic/app/bundles/CoreBundle/Helper/UpdateHelper.php
```
$data   = $this->connector->post($this->coreParametersHelper->getParameter('system_update_url'), $appData, [], 10);
```
returns an empty message back, despite code 200.

Nothing is added to the log file in this case.

Mautic 2.16.2
PHP 7.2

**Comment by RCheesley** [comment]
Hi there, 

Thanks for taking the time to report this issue, unfortunately you are using a very outdated version of Mautic so you will not benefit from the features and bug fixes that we are introducing.

This version has not been actively supported since June and security support ended in December 2020 ([see supported versions](https://github.com/mautic/mautic#supported-versions)). You should update to Mautic 3 at your earliest convenience and test to see if this issue persists as we would not fix it for 2.16.2.

For info, [this PR](https://github.com/mautic/mautic/pull/9499) was merged in 3.2.2 addresses issues relating to using a reverse proxy with https.

**Comment by protondev9** [comment]
Can you clarify what does this issue have to do with reverse proxying? :confused:

**Comment by RCheesley** [comment]
> Can you clarify what does this issue have to do with reverse proxying? 😕

I was sharing as an example of an issue that was recently resolved in 3.x relating to issues with using proxies - we are actively working on issues like the one you raised but you will not get any fixes on your current version and we will not be looking into issues that are raised for that version either.
