### ISSUE TITLE
installation error: Could not scan for classes inside oneup/uploader-bundle/Tests/App/AppKernel.php 

### ISSUE THREAD

**Issue by directpromo** [mautic/mautic#9810]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
When installing after the "composer install" step, I get an error
`[RuntimeException]                                                                                                                                                                         
 Could not scan for classes inside "/home/.../public_html/vendor/oneup/uploader-bundle/Tests/App/AppKernel.php" which does not appear to be a file nor a folder`

| Q   | A
| --- | ---
| Mautic version | 3.3.1
| PHP version | 7.3

### Steps to reproduce
1. download release https://github.com/mautic/mautic/releases/download/3.3.1/3.3.1.zip
2. copy composer.json from https://github.com/mautic/mautic ( This file is not available in the release :( )
3. Run the following command `composer install`
 
### Log errors in linux terminal 
`[RuntimeException]                                                                                                                                                                         
 Could not scan for classes inside "/home/.../public_html/vendor/oneup/uploader-bundle/Tests/App/AppKernel.php" which does not appear to be a file nor a folder`

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Are you using Composer 1 or 2?

If you want to use Composer please ensure that you are using Composer 1, not 2 - the latter will not be supported until Mautic 4 as there are breaking changes needed to implement it.

We will look into why the file is not in the build any more - I suspect it may be due to Github Actions doing our release process nowadays and maybe it is ignoring the file!

**Comment by npracht** [comment]
Close for lack of feedback. I'll re-open if we have a feedback.

**Comment by jos0405** [comment]
Hello,
I ran into this problem as well.
It happens, because your oneup/uploader-bundle will be installed in the wrong version.
Error:
Installation request for oneup/uploader-bundle 3.1.0 -> satisfiable by oneup/uploader-bundle[3.1.0].

When looking at the package, you'll realize this version is not working on Symfony3:
[](https://packagist.org/packages/oneup/uploader-bundle)
"Version 3.0.0 supports now Symfony 5 (kudos to @steveWinter, @gubler, @patrickbussmann, @ErnadoO and @enumag, see #373! Symfony 3.x support was dropped."

So you'll need to install a prev version:

`composer require oneup/uploader-bundle:2.0.0`

That will fix your problem.
Good luck :)

I think we can close this ticket as solved.
