### ISSUE TITLE
Duplicate Email Addresses - across multiple lead lists

### ISSUE THREAD

**Issue by davkap92** [mautic/mautic#993]
Hi, not that this is necessarily a bug, but I just wondered if there was a way I could prevent duplicate email addresses across lists, so i know in one import the duplicates are merged, but if I go to add a lead later in a new list with the same email address it seems to allow it.

Thanks!

**Comment by alanhartless** [comment]
Emails should be used as unique identifiers and thus should not create duplicate leads on an import as long as the email field is matched up.  If you're finding that leads are getting duplicated, can you verify that the email field listed in Leads -> Manage Fields has a key in the far right column? If it does not, edit the field and ensure Is Unique Identifier is selected as yes.

If it is set as yes, are there any differences at all with the email addresses (case or otherwise)? Maybe we're not doing a proper match.

**Comment by alanhartless** [comment]
Just following up to see if this is still an issue or if it was resolved?

**Comment by hostz-frank** [comment]
I'm interested in this as well. Unique email addresses would be like handling them as ID's. 

There is a German autoresponder provider who has a "special" solution that is very simple and seems very effective at the end: instead of making lists important and thinking of them as objects or real "containers", they keep mail addresses only once in their system. They take the lists idea and degrade lists to **tags** so that you simply **add a list tag** to an email address as you would do by tracking pixels if so. visits a page. So a list membership is simply seen as beeing tagged with a label of *list_name*. This way every email occurs definitely once in the whole system and this is from a db perspective a very clean way to avoid double and tripple occurencies of emails which turns often into a problem if so. unsubscribes and continues to get emails from "other" lists.

So yes, I'm a very new Mautic user and would love to hear how this is solved or handled.

**Comment by nazab** [comment]
I can confirme that Mautic is not deduplicating leads based on email even if the email is identical.
I have the litlle key symbole on the "manage field" screen and I still get duplicate email.

**Comment by github-grabaz** [comment]
Why was this closed?  It still seems to be an issue such that I am reviewing all past such issues looking for what was fixed and how.  But in this instance it was just closed without any explanation.

**Comment by Uebix** [comment]
In 2.11.0 the issue exists. I try to import multiple CSV files and leads are duplicated...
