### ISSUE TITLE
point added to lead, even though email send failed on gmail

### ISSUE THREAD

**Issue by rmalla** [mautic/mautic#9953]
## Bug Description
we're using gmail to send smtp emails, I believe it has a limit of 250 emails per day. now. when that limit expires, but cron schedules continue to execute (we had an error on the cron scheduling), the campaign continues to the next step (in our case add  one point), even though the email was not sent and we get a not sent error on the log. 

if the email was not send, the point should not be added. this creates havoc on our system. 

| Q   | A
| --- | ---
| Mautic version: 3.3 | 
| PHP version:  7.4.3 | 
| Browser: Fiefox| 

### Steps to reproduce
1. 
2. 
 
### Log errors
[2021-04-28 15:19:04] mautic.NOTICE: Swift_TransportException: Expected response code 354 but got code "550", with message "550 5.4.5 Daily user sending quota exceeded.

**Comment by npracht** [comment]
Hi @rmalla !
Thanks for your message.
Nevertheless, I have to disagree. The campaign is working properly and the workflow moves fwd. Your issue is an integration / third party issue and should not impact the application behaviour.

Join forums and slack if you want to discuss this and find solution with community members.

**Comment by rmalla** [comment]
thanks will do.
