### ISSUE TITLE
Remove Mautic code mode in Grapesjs mode and use only Grapesjs functionality

### ISSUE THREAD

**Issue by adiux** [mautic/mautic#9988]
Grapesjs already allows to import and edit code

Therefore, the existing code mode functionality is redundant and can be removed.

See demo for details:
https://grapesjs.com/demo-newsletter-editor.html

Note: the code edit button/popup is only available on Mautic
![image](https://user-images.githubusercontent.com/13075514/117527359-b8e26a00-afcb-11eb-95e2-eea49d587eb9.png)

Related to:
https://github.com/mautic/plugin-grapesjs-builder/issues/44

**Comment by adiux** [comment]
The grapesjs code editing functionality for editing code is too limited for our needs: It does not allow to edit the <head>

Therefore, we need the custom ability to edit the code inside the builder. 

However, we can still remove the code mode that is available from outside the grapesjs builder. The one that is available on the theme level.

![image](https://user-images.githubusercontent.com/13075514/124959479-8b418d80-e01b-11eb-9d00-d4dbc529b633.png)

**Comment by RCheesley** [comment]
Yes, however removing this also means that folks who have used a code mode option to create an email and they use it with dynamic content will no longer be able to use it.

The dynamic content tab appears when you select code mode, and that's where you configure the dynamic content to be used.

How would you plan to address that so that it doesn't break it for existing users, and also enables new users to use dynamic content in their emails?  Will it be available in GrapesJS in code mode somehow?

**Comment by adiux** [comment]
I believe the options inside the grapesjs builder are sufficient. But maybe someone who is using dynamic content and the code mode to a bigger extend should have a look at this.

**Comment by npracht** [comment]
This topic can be related as well. https://github.com/mautic/mautic/issues/10572
